### ISSUE TITLE
docker-for-win: container with root user is not terminated

### ISSUE THREAD

**Issue by mviereck** [mviereck/x11docker#106]
Coming from #103 

@1138-4EB wrote:
`./x11docker --user=0 -- -p 5555:8080 -- ghdl/ext:ide -p 8080` does work. `./x11docker --user=RETAIN -- -p 5555:8080 -- ghdl/ext:ide -p 8080` too.

But, with both of them, when I Ctrl+C to terminate, the log seems correct, the X server is closed, but the container is not. 

I need to `docker rm -f x11docker_X100_....`

**Comment by mviereck** [comment]
@1138-4EB I've made a fix that should resolve this. Please try out.

**Comment by 1138-4EB** [comment]
It is fixed now. Thanks!
