### ISSUE TITLE
docker-for-win: firewall settings / no X window appears

### ISSUE THREAD

**Issue by eine** [mviereck/x11docker#108]
Coming from https://github.com/mviereck/x11docker/issues/87#issuecomment-457307011

I tried the following:

- Allow VcXsrv windows xserver in Private and Public networks.
- Start vcxsrv with xlaunch: Multiple windows, Display number 0, Start no client, Clipboard, Disable access control.
- `winpty docker run -it -e DISPLAY=10.0.75.1:0.0 alpine_term xterm` works.
- Stop vcxsrv.
- Allow VcXsrv in Private networks only.
- Start vxcsrv again with xlaunch.
- `winpty docker run -it -e DISPLAY=10.0.75.1:0.0 alpine_term xterm` does not work.

However, `x11docker` does not work with any of them.

Last, I disabled the firewall everywhere (Domain network, Private network and Public network). Now `x11docker` works.

So, it is strange that this problem did not happen earlier. Although it might sound strange, I think that this might have something to do with changing from wireless to ethernet recently. I did change nothing more these last days.

Will have to investige further.

**Comment by mviereck** [comment]
Thank you for reporting and investigation!
I have added a note about this in README.md and a message in x11docker.
I will keep this ticket open for those who might stumble over it, too.

**Comment by mviereck** [comment]
Also in wiki, closing.
https://github.com/mviereck/x11docker/wiki/x11docker-on-MS-Windows
