### ISSUE TITLE
Quoted image command arguments are not parsed accordingly

### ISSUE THREAD

**Issue by 1138-4EB** [mviereck/x11docker#112]
I am trying to execute `winpty docker run --rm -it x11docker/xfce bash -c "ls && pwd"` with x11docker.

- `./x11docker -i -t x11docker/xfce bash`: works, but it not what I want.
- `./x11docker -i -t x11docker/xfce ls`: does not show the output of `ls`.
- `./x11docker -i -t x11docker/xfce ls && pwd`: the output from x11docker is shown and then `pwd` is executed in the host. The output of `ls` is not shown.
- `./x11docker -i -t x11docker/xfce bash -c "ls && pwd"`: `-c` is considered to be the option `--clipboard` of x11docker, so a warning is shown:

``` bash
...
x11docker WARNING: Option --clipboard is not supported for --tty.
  Fallback: Disabling option --clipboard.

x11docker note: Did not find container init system 'tini'.
  This is a bug in your distributions docker package.
  Normally, docker provides init system tini as '/usr/bin/docker-init'.

  x11docker uses tini for clean process handling and fast container shutdown.
  To provide tini yourself, please download tini-static:
    https://github.com/krallin/tini/releases/download/v0.18.0/tini-static
  Store it in one of:
    /home/eine/.local/share/x11docker/
    /usr/local/share/x11docker/

/fakehome/eine
/usr/bin/ls: /usr/bin/ls: cannot execute binary file
```

- `./x11docker -i -t x11docker/xfce "ls && bash"`: as used in #110, `ls` is not executed at first, but a bash is provided. After exiting, `ls` is executed, which shows nothing.

``` bash
...
x11docker note: Did not find container init system 'tini'.
  This is a bug in your distributions docker package.
  Normally, docker provides init system tini as '/usr/bin/docker-init'.

  x11docker uses tini for clean process handling and fast container shutdown.
  To provide tini yourself, please download tini-static:
    https://github.com/krallin/tini/releases/download/v0.18.0/tini-static
  Store it in one of:
    /home/eine/.local/share/x11docker/
    /usr/local/share/x11docker/

eine@2aa7533005d5:~$ exit
exit

```

> NOTE: with `./x11docker -i -t x11docker/xfce "ls -la && bash"` the output is:
>
>``` bash
>eine@0bc040f292cf:~$ exit
>exit
>total 24
>drwxr-xr-x 2 eine None 4096 Jan 29 22:42 .
>drwxrwxrwx 3 root root 4096 Jan 29 22:42 ..
>-rw------- 1 eine None    5 Jan 29 22:42 .bash_history
>-rw-r--r-- 1 eine None  220 Jan 29 22:42 .bash_logout
>-rw-r--r-- 1 eine None 3526 Jan 29 22:42 .bashrc
>-rw-r--r-- 1 eine None  807 Jan 29 22:42 .profile
>```

> NOTE: `./x11docker -i -t x11docker/xfce "pwd && bash"` shows the output of `pwd`.

However, in neither case is a command prompt provided after. The container exists instead. This is different from the results reported in #110.

- `./x11docker -i -t x11docker/xfce bash "ls && bash"`: as in the previous case, `ls` is not executed at first, but a bash is provided. After exiting, `ls` is executed, but it fails now.

``` bash
...
x11docker WARNING: Option --clipboard is not supported for --tty.
  Fallback: Disabling option --clipboard.

x11docker note: Did not find container init system 'tini'.
  This is a bug in your distributions docker package.
  Normally, docker provides init system tini as '/usr/bin/docker-init'.

  x11docker uses tini for clean process handling and fast container shutdown.
  To provide tini yourself, please download tini-static:
    https://github.com/krallin/tini/releases/download/v0.18.0/tini-static
  Store it in one of:
    /home/eine/.local/share/x11docker/
    /usr/local/share/x11docker/

eine@e489ccf9645b:~$ exit
exit
/usr/bin/ls: /usr/bin/ls: cannot execute binary file
```

- `./x11docker -i -t x11docker/xfce bash "ls && pwd && bash"`: same as the previous case.

- `./x11docker -i -t x11docker/xfce bash "ls; pwd; bash"`: same as the previous case.

- `./x11docker -i -t x11docker/xfce bash -c "ls && bash"`: same as the case without `-c`, but with the note about `--clipboard`.

**Comment by 1138-4EB** [comment]
I pulled the latest master and I tried:

``` bash
# ./x11docker -ti -- x11docker/fvwm sh -c "ls -la ; pwd ; sh"
...
Image 'sh' not found locally.
Do you want to pull it from docker hub? [Y|n]
(Will wait up to 60s for a response, otherwise assuming no)y
/c/Users/eine/x11docker/cache/sh-42d07a/dockerrc: line 123: notify-send: command not found
Using default tag: latest
x11docker note: Pulling image sh from docker hub

Error response from daemon: pull access denied for sh, repository does not exist or may require 'docker login'

x11docker ERROR: Did not find image sh.
  Please build image first or pull it from docker hub with:

      docker pull sh

  or run x11docker with option --pull=yes

  Type 'x11docker --help' for usage information
  Debug options: '--verbose' (full log) or '--debug' (log excerpt).
  Logfile will be: /c/Users/eine/x11docker/cache/x11docker.log
  Please report issues at https://github.com/mviereck/x11docker

./x11docker: line 448: /c/Users/eine/x11docker/cache/sh-42d07a/message.log: No such file or directory
./x11docker: line 448: /c/Users/eine/x11docker/cache/sh-42d07a/message.log: No such file or directory
./x11docker: line 448: /c/Users/eine/x11docker/cache/sh-42d07a/message.log: No such file or directory
./x11docker: line 448: /c/Users/eine/x11docker/cache/sh-42d07a/message.log: No such file or directory
```

> But this has to wait until I push the next x11docker release that does the copy on itself.

I'll try with other images meanwhile.

> Meanwhile you can test e.g.
>
> ``` bash
>  x11docker -ti -- x11docker/fvwm sh -c "ls -la ; pwd ; sh"
> ```

I tried, but it fails as shown above. I think that this is related to the fix, rather than to the image.

> The correct syntax uses `--` to divide x11docker options from image command options:

I always forget about it when I don't put docker run options. Thanks for the remainder.

**Comment by mviereck** [comment]
> I tried, but it fails as shown above. I think that this is related to the fix, rather than to the image. The same happens with x11docker -i -t -- x11docker/xfce bash -c "ls && bash".

Stupid me, I should have tested without `DOCKER_RUN_OPTIONS`, too.  Is fixed now.

**Comment by 1138-4EB** [comment]
It works great now! I believe we can close this too.
