### ISSUE TITLE
[play-with-docker] Tests and enhancements

### ISSUE THREAD

**Issue by 1138-4EB** [mviereck/x11docker#114]
Since x11docker allows to run *sandboxed* demos using a browser to render the GUI apps (see #110), I tried it in [play-with-docker](http://play-with-docker.com) ([play-with-docker/play-with-docker](https://github.com/play-with-docker/play-with-docker)):

> Play with Docker (PWD) is a project hacked by Marcos Liljedhal and Jonathan Leibiusky and sponsored by Docker Inc.
> 
> PWD is a Docker playground which allows users to run Docker commands in a matter of seconds. It gives the experience of having a free Alpine Linux Virtual Machine in browser, where you can build and run Docker containers and even create clusters in Docker Swarm Mode. Under the hood Docker-in-Docker (DinD) is used to give the effect of multiple VMs/PCs. In addition to the playground, PWD also includes a training site composed of a large set of Docker labs and quizzes from beginner to advanced level available at training.play-with-docker.com.

The shell is not `bash`, so some errors are shown:

``` bash
$ ./x11docker -it -- ghdl/ext:vunit-gtkwave bash
./x11docker: line 6190: mcookie: command not found
pstree: unrecognized option: s
BusyBox v1.28.4 (2018-07-17 15:21:40 UTC) multi-call binary.

Usage: pstree [-p] [PID|USER]

Display process tree, optionally start from USER or PID

        -p      Show pids
tty: ignoring all arguments
/dev/pts/1
x11docker note: Your terminal seems to be not POSIX compliant.
  Command 'logname' does not return a value.
  Consider to use another terminal emulator.
  Fallback: Will try to check $SUDO_USER and $PKEXEC_UID.

x11docker note: Will use $(id -un) = root as host user.

x11docker WARNING: Running as user root.
  Maybe $(logname) did not provide an unprivileged user.
  Please use option --hostuser=USER to specify an unprivileged user.
  Otherwise, new X server runs as root, and container user will be root.

Image 'ghdl/ext:vunit-gtkwave' not found locally.
Do you want to pull it from docker hub? [Y|n]
(Will wait up to 60s for a response, otherwise assuming no)y
x11docker note: Pulling image ghdl/ext:vunit-gtkwave from docker hub


vunit-gtkwave: Pulling from ghdl/ext
21fb37f5cb03: Pull complete
8ec54003ede9: Pull complete
74b25a0e5a32: Pull complete
fde4f3354579: Pull complete
757ea9e282d8: Pull complete
10bfa80f3ef9: Pull complete
Digest: sha256:7ac253bc902300d51eafd291c930d08e2964f9f5cf0129f4c273a6c758281264
Status: Downloaded newer image for ghdl/ext:vunit-gtkwave

ps: unrecognized option: p
                          BusyBox v1.28.4 (2018-07-17 15:21:40 UTC) multi-call binary.

                                                                                      Usage: ps [-o COL1,COL2=HEADER]

                                                                                                                     Show list of processes

                                                                                                                                                -o COL1,COL2=HEADESelect columns for display
                         root@56618133342d:~#
root@56618133342d:~#
```

However, the container is properly started.

Then, I tried:

``` bash
./x11docker -it -- -p=8080:8085 -e BROADWAY_DISPLAY=:5 -e GDK_BACKEND=broadway -- ghdl/ext:vunit-gtkwave bash
```

In the prompt inside the container:

``` bash
root@d157f9b9e531:~# broadwayd :5 &
[1] 85
root@d157f9b9e531:~# Listening on /tmp/XDG_RUNTIME_DIR/broadway6.socket
root@d157f9b9e531:~# gtkwave

GTKWave Analyzer v3.3.99 (w)1999-2019 BSI

GTKWAVE | Use the -h, --help command line flags to display help.
GTKWAVE | Touch screen detected, enabling gestures.
```

A button with name `8080` is created. This means that the service is running in the container, and it is being properly served. Unfortunately, when accessing it, nothing is shown, just an empty white page. This is different from error 404, so I opened the console and I found:

```
Firefox can't establish a connection to the server at ws://ip172-18-0-41-bh8h15spkul0008n14f0-8080.direct.labs.play-with-docker.com/socket.
```

It seems that something between my machine and the container is blocking the websocket.

---

The issue with the websocket is specific to the deployment at `play-with-docker.com`. Nevertheless, since the environment can be deployed in ones own infrastructure (see https://github.com/play-with-docker/play-with-docker/wiki/Deploying-PWD-in-your-own-infrastructure) it is commonly used for workshops/trainings. Therefore, I think that it might be worth fixing the issues with the shell, because that would allow to use x11docker in those workshops.

The image that is used in play-with-docker by default is [franela/dind](https://hub.docker.com/r/franela/dind/) (sources https://github.com/play-with-docker/play-with-docker/tree/master/dockerfiles/dind and https://microbadger.com/images/franela/dind).

**Comment by mviereck** [comment]
I did some fixes, currently I don't get errors in play-with-docker.

Note that someone managed to escape from play-with-docker containers a few month ago: https://www.cyberark.com/threat-research-blog/how-i-hacked-play-with-docker-and-remotely-ran-code-on-the-host/

**Comment by 1138-4EB** [comment]
I checked `curl -fsSL https://raw.githubusercontent.com/mviereck/x11docker/master/x11docker | bash -s -- --update-master`. No error is produced!

Since the websocket error is not related to x11docker, I think we can close this.

> In fact it is a bash shell although the image is based on alpine. The issues were related to limited options of busybox commands.

Then, there might be further issues in a plain alpine image. We'll see when someone tries to execute x11docker on alpine.
