### ISSUE TITLE
docker-for-win: use --mmap between portable xpra client for win and xpra server in container

### ISSUE THREAD

**Issue by 1138-4EB** [mviereck/x11docker#118]
Coming from #110 and #117.

x11docker does not support `--xpra` on Windows ATM. However, successful results running `xpra` in a docker container have been reported in #117. In [#110](https://github.com/mviereck/x11docker/issues/110#issuecomment-459602622), a maintainer/developer of `xpra`, suggested to use option `--mmap` to improve the performance.

---

> @totaam wrote:
> In particular, if you care about performance, try to enable mmap. You may have to fiddle with the mmap file path.

> @totaam wrote:
> I have zero experience trying to get mmap to work from a windows client to a container.
> Try to enable `-d mmap` debug output. See also the `mmap=ABSOLUTEFILENAME` man page entry.

> @totaam wrote:
> Here I assume that windows and the container both have access to a filesystem that supports shared memory where you can create the mmap backing file. But that may not be the case... I don't know.

> @totaam wrote:
> According to the xpra code, the mswindows code path should honour whatever mmap filename you tell it to use. (so I must have tested that at some point)

> @mviereck wrote:
> `xpra server` runs in a container in a Linux VM. `xpra client` runs on Windows.
> It is possible to share the same file located on the Windows ntfs file system with x11docker option `--sharedir` or `docker run` option `--volume`.
> But I doubt that this allows to share memory. Though, it is worth a try.

> @totaam wrote:
> You're right. I was thinking of WSL, and shared-memory doesn't even work there yet:
> [Add support for semaphores and shared memory](https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/13412589-add-support-for-semaphores-and-shared-memory)

---

Let's continue here...

**Comment by mviereck** [comment]
> x11docker does not support --xpra on Windows ATM.

This would only be possible with xpra server on Windows.

> mmap file

As being said it is quite likely to fail across VM <-> Windows.
You can test it. Add `--sharedir /tmp/mmap --debug` to x11docker command. Check the pathes for mmap file in created docker command. Provide them with `--mmap=path` to xpra server and xpra client accordingly.

**Comment by mviereck** [comment]
> I don't understand. --sharedir /tmp/mmap is the same as -v /tmp/mmap:/tmp/mmap, isn't it? 

The path is different. On Windows side it is something like `/c/msys2/tmp/mmap` (I would have to check in VM for exact path). In container it will be `/tmp/mmap`

> Therefore, it will bind a path inside the VM, which I don't know if I can access.

The left path in generated `--volume` option is the windows path you should provide to xpra windows client.
The right path in generated `--volume` option is the path within the container you should provide to xpra server in container.

> x11docker WARNING: File or folder not found:
  /tmp/mmap

My fault; the file does not exist on container startup as xpra has to create it. So no `--volume` option is added in generated docker command. Try with `--sharedir /tmp` instead and provide the pathes to xpra with `[...]/tmp/mmap`.

**Comment by mviereck** [comment]
Feel free to re-open if this is of interest again.
