### ISSUE TITLE
DRM Permissions

### ISSUE THREAD

**Issue by hackel** [mviereck/x11docker#12]
The recent change that made /dev/dri readonly borked up hardware acceleration for me.  It was never able to open the device and so reverted to hardware rendering.

I just changed this line (2080) back and it fixed it:
`[ "$Gpu" = "yes" ] && Dockercommand="$Dockercommand --device=/dev/dri"`

**Comment by mviereck** [comment]
Thanks for your feedback!
Curious, hardware acceleration works fine here with read-only flag. 
Does it work if you set rw flag? That should be enough, avoiding the default (and imho unnecessary) mknod flag.
```
 [ "$Gpu" = "yes" ] && Dockercommand="$Dockercommand --device=/dev/dri:rw"
```

**Comment by hackel** [comment]
Yes, with rw it worked fine.  Here's the error I'm seeing:
```
libGL error: failed to open drm device: Operation not permitted
libGL error: failed to load driver: i965
fixme:d3d:wined3d_guess_card No card selector available for card vendor 0000 (using GL_RENDERER "Gallium 0.4 on llvmpipe (LLVM 3.9, 256 bits)").
```

**Comment by mviereck** [comment]
I've set rw flag for /dev/dri in V3.5.4. Thanks!
