### ISSUE TITLE
Try to run magicmirror

### ISSUE THREAD

**Issue by lpt2007** [mviereck/x11docker#124]
Hi,

Same as kodi I try to run magicmirror on x11docker.
https://magicmirror.builders/

The steps:
I used raspbian-lite from this link:
https://www.raspberrypi.org/downloads/raspbian/

I enabled ssh with:
```
sudo apt-get update
sudo systemctl enable ssh
sudo reboot
```
I update host system:
`sudo apt-get upgrade -y`

I installed docker:
```
curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
sudo usermod -aG docker pi
```

I Installed x11docker:
```
sudo apt-get install -y xdg-utils
wget https://raw.githubusercontent.com/mviereck/x11docker/master/x11docker -O /tmp/x11docker
sudo bash /tmp/x11docker --update
rm /tmp/x11docker
```
I create folders:
```
mkdir /home/pi/docker
mkdir /home/pi/docker/magicmirror
```

create and edit Dockerfile:
`nano /home/pi/docker/magicmirror/Dockerfile`

add this:
```
FROM raspbian/stretch
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y curl
RUN bash -c "$(curl -sL https://raw.githubusercontent.com/MichMich/MagicMirror/$
WORKDIR "/home/pi/MagicMirror"
CMD npm start
```
build docker container:
`sudo docker build -t magicmirror /home/pi/docker/magicmirror`

then I run:
`x11docker magicmirror`

error:

```
xdpyinfo:  unable to open display ":0".
xwininfo: error: unable to open display ":0"
```

```
npm ERR! path /home/pi/MagicMirror/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /fakehome/pi/.npm/_logs/2019-02-04T20_05_24_214Z-debug.log
```

**Comment by mviereck** [comment]
Are you still able to run your kodi image?
Try to add `--no-auth`. If that works, there is some authentication issue.

**Comment by lpt2007** [comment]
What x11docker this error mean?
`Did not find a possibility to provide a display`

**Comment by mviereck** [comment]
>  `x11docker ERROR: Did not find a possibility to provide a display`

This means x11docker neither runs on X nor found an X server. Is Xorg installed?

**Comment by lpt2007** [comment]
> > `x11docker ERROR: Did not find a possibility to provide a display`
> 
> This means x11docker neither runs on X nor found an X server. Is Xorg installed?

On host system or container?

**Comment by mviereck** [comment]
> In host system or container?

On host. x11docker provides X from host to containers.

**Comment by lpt2007** [comment]
> On host. x11docker provides X from host to containers.
Ok, thanks.

Can you help me about magic mirror app?
https://magicmirror.builders/

My docker file:
```
FROM raspbian/stretch:latest
RUN apt-get update
RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_11.x  | bash -
RUN apt-get -y install nodejs
RUN apt-get -y install git
RUN cd ~/
RUN git clone https://github.com/MichMich/MagicMirror
RUN cd MagicMirror
RUN npm install -g express
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -q -y xinit
RUN apt-get install -y xorg
RUN apt-get install -y matchbox
RUN apt-get install -y unclutter
RUN  cd ~/
RUN  cd MagicMirror
CMD npm start
```
command to buil container:
`sudo docker build -t magicmirror /home/pi/docker/magicmirror`

then I run:
`x11docker magicmirror`

I get error:
```
npm ERR! path /fakehome/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/fakehome/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /fakehome/pi/.npm/_logs/2019-02-09T18_20_39_844Z-debug.log
```

**Comment by mviereck** [comment]
> RUN  cd MagicMirror

That does not work. You cannot switch directories with the RUN command in a Dockerfile. The next RUN will be in `/` again. 
You can set a working directory with `WORKDIR`.

> RUN  cd ~/

That does not make sense either. During build the commands are executed as root. `~` will be `/root`. 
x11docker creates an unprivileged container user with its own home directory different from `/root`.

> RUN git clone https://github.com/MichMich/MagicMirror
RUN cd MagicMirror
RUN npm install -g express

The `npm` command won't be executet in `MagicMirror`.

I can't help to set up a correct installation, please look at the magicmirror documentation instead. It seems they provide a ready-to-use docker image. Also they provide instructions for installation with prepared installer scripts instead of fiddeling with the repo itself.

**Comment by lpt2007** [comment]
> It seems they provide a ready-to-use docker image.
Can I use docker ready image? How?

**Comment by mviereck** [comment]
> Can I use docker ready image? How?

Looking at the example given on their github page:
```
docker run  -d \
	--publish 80:8080 \
	--restart always \
	--volume ~/magic_mirror/config:/opt/magic_mirror/config \
	--volume ~/magic_mirror/modules:/opt/magic_mirror/modules \
	--name magic_mirror \
	bastilimbach/docker-magicmirror
```
Pull the image with `docker pull bastilimbach/docker-magicmirror`
Run x11docker with `x11docker -- --publish 80:8080 -- bastilimbach/docker-magicmirror`

Does magicmirror have a GUI at all? If not, you can just use their provided docker command or add x11docker option `--tty` to run without X.

**Comment by lpt2007** [comment]
> Does magicmirror have a GUI at all? If not, you can just use their provided docker command or add x11docker option `--tty` to run without X.

Yes it has a GUI.

**Comment by lpt2007** [comment]
> Pull the image with `docker pull bastilimbach/docker-magicmirror`
> Run x11docker with `x11docker -- --publish 80:8080 -- bastilimbach/docker-magicmirror`

error: can't open display. Probably because magicmirror container starts in severonly mode?

**Comment by lpt2007** [comment]
I try to run with `--tty`:
`x11docker -- --tty --publish 80:8080 -- bastilimbach/docker-magicmirror`

error:
```
x11docker ERROR: Got error message from docker daemon:
Error response from daemon: No such container: x11docker_X0_cc28c0_bastilimbach-docker-magicmirror

  Type 'x11docker --help' for usage information
  Debug options: '--verbose' (full log) or '--debug' (log excerpt).
  Logfile will be: /home/pi/.cache/x11docker/x11docker.log
  Please report issues at https://github.com/mviereck/x11docker

Error: Can't open display: :0
Error: Can't open display: :0
```

**Comment by mviereck** [comment]
`--tty` was meant run run without X and it should be placed before `--`. If you want X, don't use `--tty`.

> Error: Can't open display: :0

As said above:
>  Try to add `--no-auth`. If that works, there is some authentication issue.

**Comment by lpt2007** [comment]
I try to run with `--no-auth`
`x11docker --no-auth --  --publish 80:8080 -- bastilimbach/docker-magicmirror`

error:
`Error response from daemon: No such container: x11docker_X0_cc28c0_bastilimbach-docker-magicmirror`

**Comment by mviereck** [comment]
No other messages? Please show the full output.

**Comment by lpt2007** [comment]
Maybe tag is not correct:
https://hub.docker.com/r/bastilimbach/docker-magicmirror/tags

**Comment by mviereck** [comment]
> Maybe tag is not correct:

Than try with tag `raspberry`.
Pull the image with `docker pull bastilimbach/docker-magicmirror:raspberry`
Run x11docker with `x11docker -- --publish 80:8080 -- bastilimbach/docker-magicmirror:raspberry`

**Comment by lpt2007** [comment]
I find this Dockerfile:
https://github.com/bastilimbach/docker-MagicMirror/tree/master/raspberry

```
FROM hypriot/rpi-node:latest

ENV NODE_ENV production

WORKDIR /opt/magic_mirror

RUN git clone --depth 1 -b master https://github.com/MichMich/MagicMirror.git .

RUN cp -R modules /opt/default_modules
RUN cp -R config /opt/default_config
RUN npm install --unsafe-perm --silent

COPY docker-entrypoint.sh /opt
RUN apt-get update \
  && apt-get -qy install dos2unix \
  && dos2unix /opt/docker-entrypoint.sh \
  && chmod +x /opt/docker-entrypoint.sh

EXPOSE 8080
CMD ["node serveronly"]
ENTRYPOINT ["/opt/docker-entrypoint.sh"]
```
and file docker-entrypoint.sh
https://github.com/bastilimbach/docker-MagicMirror/blob/master/docker-entrypoint.sh

Problem is magicmirror starts in server only mode:
`CMD ["node serveronly"]`

**Comment by mviereck** [comment]
> Problem is magicmirror starts in server only mode:

You can set another image command after the image name:
`x11docker -- --publish 80:8080 -- bastilimbach/docker-magicmirror:raspberry node`

**Comment by lpt2007** [comment]
> You can set another image command after the image name:
> `x11docker -- --publish 80:8080 -- bastilimbach/docker-magicmirror:raspberry node`

I think magicmirror gui start command is:
`npm start` or from ssh: `DISPLAY=:0 nohup npm start &`

docs about manual instalation and start
https://github.com/MichMich/MagicMirror#manual-installation

**Comment by lpt2007** [comment]
I changed:
`CMD ["node serveronly"]`
to this:
`CMD ["npm start"]`
in Dockerfile

and run with this x11docker command:
`x11docker magicmirror`

I get this:
```
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.3

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, prune, publish, rb,
    rebuild, repo, restart, root, run, run-script, s, se,
    search, set, shrinkwrap, star, stars, start, stop, t, team,
    test, tst, un, uninstall, unpublish, unstar, up, update, v,
    version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /fakehome/pi/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.0.3 /usr/local/lib/node_modules/npm
```

**Comment by mviereck** [comment]
>  `CMD ["npm start"]`

Use :
 `CMD ["npm","start"]`
or:
 `CMD npm start`

**Comment by lpt2007** [comment]
Use :
`CMD ["npm","start"]`
or:
`CMD npm start`

Same message as with `CMD ["npm start"]`

**Comment by mviereck** [comment]
Try
 `x11docker -- --publish 80:8080 -- bastilimbach/docker-magicmirror:raspberry npm start`

**Comment by lpt2007** [comment]
I try with original:
`CMD ["node serveronly"]`

and 

`x11docker -- --publish 80:8080 -- bastilimbach/docker-magicmirror:raspberry npm start`

Still same message.

**Comment by mviereck** [comment]
I had a look at the `ENTRYPOINT` script: https://github.com/bastilimbach/docker-MagicMirror/blob/master/docker-entrypoint.sh

It has a bug in the last line. Instead of `$1` it should be `$@` or `exec $@`.
As a workaround, try:
 `x11docker -- --publish 80:8080 -- bastilimbach/docker-magicmirror:raspberry "npm start"`

**Comment by lpt2007** [comment]
It has a bug in the last line. Instead of `$1` it should be `$@` or `exec $@`
Thats it. I add `$@` this.

Now I have error:
```
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.3
npm info lifecycle magicmirror@2.6.0~prestart: magicmirror@2.6.0
npm info lifecycle magicmirror@2.6.0~start: magicmirror@2.6.0

> magicmirror@2.6.0 start /opt/magic_mirror
> sh run-start.sh

fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/opt/magic_mirror/node_modules/electron/index.js'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/magic_mirror/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:569:30)
npm info lifecycle magicmirror@2.6.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror@2.6.0 start: `sh run-start.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the magicmirror@2.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /fakehome/pi/.npm/_logs/2019-02-09T22_49_14_260Z-debug.log
```

**Comment by mviereck** [comment]
Maybe the image is not designed to run with an unprivileged user.
Try with `--user=root`.

**Comment by lpt2007** [comment]
I also try with original:
`CMD ["node serveronly"]`

message:
```
Starting MagicMirror: v2.6.0
Loading config ...
WARNING! Could not find config file. Please create one. Starting with default configuration.
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: helloworld.
All module helpers loaded.
Starting server on port 8080 ...
Server started ...
Connecting socket for: updatenotification
Sockets connected & modules started ...

Ready to go! Please point your browser to: http://localhost:8080
```

I have nothing on http://IP:8080???

**Comment by mviereck** [comment]
If it shows no error in browser but an empty white page, than the connection has succeeded. Ask the magicmirror developer or look at its documentation why you don't see content.

**Comment by lpt2007** [comment]
With --user=root

I get error:
```
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.3
npm info lifecycle magicmirror@2.6.0~prestart: magicmirror@2.6.0
npm info lifecycle magicmirror@2.6.0~start: magicmirror@2.6.0

> magicmirror@2.6.0 start /opt/magic_mirror
> sh run-start.sh

/opt/magic_mirror/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
npm info lifecycle magicmirror@2.6.0~start: Failed to exec start script
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! magicmirror@2.6.0 start: `sh run-start.sh`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the magicmirror@2.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /fakehome/root/.npm/_logs/2019-02-09T22_56_33_432Z-debug.log
```

**Comment by mviereck** [comment]
> /opt/magic_mirror/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory

It seems the image misses a libgtk3 package. Please look which one it might be or ask the magicmirror developer.

**Comment by lpt2007** [comment]
I think there missing X11 packages in container?
`xinit`, `xorg`, `matchbox`

There is link with howto install magicmirror gui on raspberry:
http://emmanuelcontreras.com/how-to/how-to-create-a-magic-mirror-2-with-pi-zero-w/

Howto I add them to Dockerfile correctly?

**Comment by lpt2007** [comment]
I added those files in Dockerfile:
```
RUN apt-get -y install libgtk-3-0
RUN apt-get -y install libx11-xcb-dev
RUN apt-get -y install libxtst6
RUN apt-get -y install libxss1
RUN apt-get -y install libgconf-2-4
RUN apt-get -y install libnss3
RUN apt-get -y install libasound2
```
Now I have error:
```
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.3
npm info lifecycle magicmirror@2.6.0~prestart: magicmirror@2.6.0
npm info lifecycle magicmirror@2.6.0~start: magicmirror@2.6.0

> magicmirror@2.6.0 start /opt/magic_mirror
> sh run-start.sh

npm info lifecycle magicmirror@2.6.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror@2.6.0 start: `sh run-start.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the magicmirror@2.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /fakehome/root/.npm/_logs/2019-02-10T00_24_58_360Z-debug.log
```

**Comment by mviereck** [comment]
> npm info lifecycle magicmirror@2.6.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE

This looks quite specific to magicmirror. Ask the developer what it means.

**Comment by lpt2007** [comment]
> > npm info lifecycle magicmirror@2.6.0~start: Failed to exec start script
> > npm ERR! code ELIFECYCLE
> 
> This looks quite specific to magicmirror. Ask the developer what it means.

I figured out the error occured when I try to run mm from ssh if I run directly on rpi consol it works?
Partial success:)

But I need to find solution to run mm from ssh:

I try like this:
ssh to my rpi and run commands:
```
export DISPLAY=:0
x11docker --user=root magicmirror
```
Error:
```
npm info lifecycle magicmirror@2.6.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
```

**Comment by mviereck** [comment]
Why do you set `export DISPLAY=:0`? If you run `ssh -X`, it should be set already. If not, check `XAUTHORITY`, too.

**Comment by lpt2007** [comment]
If I don't run `export DISPLAY=:0` before I run `x11docker --user=root magicmirror` I get error:
```
x11docker ERROR: You are running x11docker over SSH without providing a display.
  Please run with 'ssh -X' or 'ssh -Y'.
  (If you insist, you can run with option '--xorg', but won't see the result.)

  Type 'x11docker --help' for usage information
  Debug options: '--verbose' (full log) or '--debug' (log excerpt).
  Logfile will be: /home/pi/.cache/x11docker/x11docker.log
  Please report issues at https://github.com/mviereck/x11docker
```

**Comment by lpt2007** [comment]
If I run with x11docker --user=root --xorg magicmirror' I get error:
```
x11docker ERROR: Error during startup of X server --xorg.
  Last lines of xinit log:

/usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server



  Type 'x11docker --help' for usage information
  Debug options: '--verbose' (full log) or '--debug' (log excerpt).
  Logfile will be: /home/pi/.cache/x11docker/x11docker.log
  Please report issues at https://github.com/mviereck/x11docker

Error: Can't open display: :100

```

**Comment by mviereck** [comment]
`ssh -X` should set `DISPLAY` and `XAUTHORITY`. Check them both and provide them to x11docker.

**Comment by lpt2007** [comment]
`ssh -X` should set `DISPLAY` and `XAUTHORITY`. Check them both and provide them to x11docker.
I never use `ssh -X` and `XAUTHORITY`. Please explain how?

**Comment by mviereck** [comment]
> I never use ssh -X

I thought you would. It allows to show GUI applications locally whilst there are running on a remote server.

You want to access the pi with ssh, but run and show the GUI application on the pi without seeing the GUI? The X server runs on the pi? 
Than check `XAUTHORITY` on your pi and provide both `DISPLAY` and `XAUTHORITY` to x11docker.

**Comment by lpt2007** [comment]
> Than check `XAUTHORITY` on your pi and provide both `DISPLAY` and `XAUTHORITY` to x11docker.

How can I check `DISPLAY` and `XAUTHORITY` on my pi?

**Comment by mviereck** [comment]
> How can I check `DISPLAY` and `XAUTHORITY` on my pi?

Start your pi with its X server.
`echo $DISPLAY`
`echo $XAUTHORITY`

**Comment by lpt2007** [comment]
I try to start xserver on my pi with command:
`startx`

I get black screen.

When I run `echo $DISPLAY` or echo `$XAUTHORITY` I get nothing.

with `xauth list` command I get this:
```
raspberrypi/unix:0  MIT-MAGIC-COOKIE-1  0b8d582f6cdf6c3cffd6527411ff119f
raspberrypi:0  MIT-MAGIC-COOKIE-1  0b8d582f6cdf6c3cffd6527411ff119f
```

**Comment by lpt2007** [comment]
If I don't run `statx` first on my pi (I get black screen with cursor on it) I get nothing if I run `xauth list` command over ssh? Something missing on my host?

**Comment by lpt2007** [comment]
I have changed raspian lite for raspbian desktop image on host.

```
echo $DISPLAY
:0.0
echo $XAUTHORITY
/home/pi/.Xauthority
```

> rovide both `DISPLAY` and `XAUTHORITY` to x11docker.

Can you show me how?

**Comment by mviereck** [comment]
> >    provide both DISPLAY and XAUTHORITY to x11docker.

> Can you show me how?

```
export DISPLAY=:0
export XAUTHORITY=/home/pi/.Xauthority
x11docker [...]
```

**Comment by lpt2007** [comment]
> export DISPLAY=:0
> export XAUTHORITY=/home/pi/.Xauthority
> x11docker [...]

Now is working, with one problem. 

If I start raspbian on host only in console mode, magic mirror won't start. If I start raspbian on host with desktop magic mirror works ok. Why?

**Comment by 1138-4EB** [comment]
> If I start raspbian on host only in console mode, magic mirror won't start. If I start raspbian on host with desktop magic mirror works ok. Why?

x11docker uses an X server running on the host. If you don't have any, because you are in console mode, it cannot share it with the container. However, when you start in desktop mode, there is an X server running, so it can be shared.

You can probably use `--xvfb` to make magic mirror work in console mode. However, how are you going to see the content?

**Comment by lpt2007** [comment]
> x11docker uses an X server running on the host. If you don't have any, because you are in console mode, it cannot share it with the container. However, when you start in desktop mode, there is an X server running, so it can be shared.

Why KODI works like that?

**Comment by 1138-4EB** [comment]
You can try comparing or providing the logs to know which option is being used and why it is failing.

**Comment by mviereck** [comment]
> x11docker uses an X server running on the host. If you don't have any, because you are in console mode, it cannot share it with the container.

x11docker can start Xorg on itself if it runs on console. (Option `--xorg`).
However, if it works with kodi but not with magicmirror, than I have no idea why magicmirror fails.
As  @1138-4EB says, you can provide `x11docker.log` on www.pastebin.com. Maybe magicmirror gives a hint in its error messages.

**Comment by 1138-4EB** [comment]
> x11docker can start Xorg on itself if it runs on console. (Option `--xorg`).

Indeed. However, there is a 'Lite' version of raspbian, which I don't know if includes xorg dependencies (see https://www.raspberrypi.org/downloads/raspbian/). Since he/she provides so little info about the context, who knows whether this is the image being used in 'console mode'.

**Comment by lpt2007** [comment]
> x11docker can start Xorg on itself if it runs on console. (Option `--xorg`).
> However, if it works with kodi but not with magicmirror, than I have no idea why magicmirror fails.
> As @1138-4EB says, you can provide `x11docker.log` on [www.pastebin.com](http://www.pastebin.com). Maybe magicmirror gives a hint in its error messages.

Error log if I run: `x11docker --user=root --xorg magicmirror`
https://pastebin.com/mu0he2w3

Error log if I run: `x11docker --user=root magicmirror`
https://pastebin.com/K5bpsn5f

**Comment by lpt2007** [comment]
> Indeed. However, there is a 'Lite' version of raspbian, which I don't know if includes xorg dependencies (see https://www.raspberrypi.org/downloads/raspbian/). Since he/she provides so little info about the context, who knows whether this is the image being used in 'console mode'.

I am using raspbian + desktop image.

**Comment by 1138-4EB** [comment]
In:

> Error log if I run: `x11docker --user=root magicmirror`
> [pastebin.com/K5bpsn5f](https://pastebin.com/K5bpsn5f)

you can find:

``` bash
npm info lifecycle magicmirror@2.6.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror@2.6.0 start: `sh run-start.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the magicmirror@2.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-14T09_42_30_396Z-debug.log
```

So [`npm ERR! code ELIFECYCLE`](http://lmgtfy.com/?q=npm+ERR!+code+ELIFECYCLE).

**Comment by mviereck** [comment]
> x11docker --user=root --xorg magicmirror

It seems you ran x11docker in an X session.
You got this warning and an explanation how to fix it:
```
x11docker WARNING: Your configuration seems not to allow to start
  a second core Xorg server from within X. Option --xorg will probably fail.
  (Per default, only root or console users are allowed to run an Xorg server).
 
  Possible solutions:
  1.) Install one of nested X servers 'Xephyr', 'Xnest' or 'nxagent'.
      For --gpu support: install 'weston' and 'Xwayland'.
  2.) Switch to console tty1...tty6 with <CTRL><ALT><F1>...<F6>
      and start x11docker there.
  3.) Run x11docker as root.
  4.) Edit file '/etc/X11/Xwrapper.config' and replace line:
          allowed_users=console
      with lines
          allowed_users=anybody
          needs_root_rights=yes
      If the file does not exist already, you can create it.
      On Ubuntu 16.04 and debian 9 you need package xserver-xorg-legacy.
```

------------------------
> x11docker --user=root magicmirror

> So [`npm ERR! code ELIFECYCLE`](http://lmgtfy.com/?q=npm+ERR!+code+ELIFECYCLE).

We already had this error message above. I am citing myself:

>>    npm info lifecycle magicmirror@2.6.0~start: Failed to exec start script
>>    npm ERR! code ELIFECYCLE

> This looks quite specific to magicmirror. Ask the developer what it means.

I also found:
> xhost:  unable to open display ":0"

Probably you set `DISPLAY`, but did not set `XAUTHORITY`. We already talked about that above.

@lpt2007 Please carefully read the terminal messages and the answers you already got. I am glad to help, but please be aware that it costs my free time and it is a bit frustrating if you don't do this basic work yourself.

**Comment by lpt2007** [comment]
> I also found:
> 
> > xhost:  unable to open display ":0"
> 
> Probably you set `DISPLAY`, but did not set `XAUTHORITY`. We already talked about that above.

Before I run: `x11docker --user=root magicmirror`
I always run this:
```
export DISPLAY=:0
export XAUTHORITY=/home/pi/.Xauthority
```
I get errors `xhost: unable to open display ":0"` and `npm ERR! code ELIFECYCLE` only if I start raspbian on host in console mode. If X is running on host mm starts ok, no errors. I already explained here:

>  > export DISPLAY=:0
> > export XAUTHORITY=/home/pi/.Xauthority
> > x11docker [...]
> 
> Now is working, with one problem.
> 
> If I start raspbian on host only in console mode, magic mirror won't start. If I start raspbian on host with desktop magic mirror works ok. Why?

**Comment by mviereck** [comment]
> I get errors xhost: unable to open display ":0" and npm ERR! code ELIFECYCLE only if I start raspbian on host in console mode.

If you run on console, than you have no X server running. Than you must not set `DISPLAY` and `XAUTHORITY` because they suggest an X server would run.

**Comment by lpt2007** [comment]
Success:) I added `sudo` and `privileged` to command and mm starts ok.
`sudo x11docker --user=root --xorg -- --privileged -- magicmirror`

thx for time and patience :)

**Comment by mviereck** [comment]
:)
