### ISSUE TITLE
start two applications from separate container on same x server

### ISSUE THREAD

**Issue by lpt2007** [mviereck/x11docker#128]
It is possbible to start two applications from separate container on same x server?

**Comment by 1138-4EB** [comment]
Yes. You can have a look at https://github.com/mviereck/x11docker/wiki/Custom-access-to-new-X-server

**Comment by lpt2007** [comment]
I have two web browsers and I can start:
chrome:
`sudo x11docker --pulseaudio --gpu --xorg -- --privileged -- chrome`
luakit:
`sudo x11docker --xorg luakit`

Can you  show me on this example how to start both? Can I choose position both app windows? Can I choose which web page will be opened in each browser?

**Comment by mviereck** [comment]
> It is possbible to start two applications from separate container on same x server?

Re-using X servers started by x11docker is a bit of advanced usage and needs some deeper understanding in the concept of X servers and environment variables. If you understand the basics of X, you'll be able to apply the wiki.
For now you are probably better served if you run a regular desktop and use x11docker on the desktop if you want to share the same X with multiple containers.

> Can I choose position both app windows? 

Have a look at `xdotool`.

> Can I choose which web page will be opened in each browser?

`x11docker --no-entrypoint jess/firefox -- firefox www.markscheid.com`
