### ISSUE TITLE
Will this work on a raspberry pi?

### ISSUE THREAD

**Issue by uniquegodwin** [mviereck/x11docker#13]
Will this app work on a raspberry pi? How do I install it ? Do you have any installation instructions?

Thanks

**Comment by mviereck** [comment]
I think that should be possible, though I have no raspberry pi to test it. 
x11docker is developed on debian, and there is debian based raspbian. If you can install docker on raspbian and an X server, and you have a display, it should be possible. x11docker needs at least docker and X to work, bash will already be part of raspbian, I assume. 
What do you want to accomplish? 
I have no special installation instructions. Assuming raspbian will be very similar to debian, I would try:
Install raspbian
Install docker and X
check if your display works
copy x11docker to /usr/local/bin and make it executeable with `chmod +x`

**Comment by 1138-4EB** [comment]
See #100.
