### ISSUE TITLE
is it possible to use border-bottom or border-top in --border=color,width?

### ISSUE THREAD

**Issue by Fabiofont** [mviereck/x11docker#132]
Hello, thank you for developing x11docker

I tested --border=red, 1 and works on xpra however bothering it to be applied has all the corners.

It would be possible to use an border-top or border-bottom (this one would look good on --xorg)

thanks

**Comment by mviereck** [comment]
Sorry, that is not possible yet. x11docker uses `xpra` option `--border`. From `man xpra`:

> --border=BORDER
              Specifies  the  color and size of the border to draw inside every xpra window.  This can be used to easily distinguish xpra windows running on remote hosts from local windows.  The BORDER can  be specified using standard color names (ie: red, or orange) or using the web hexadecimal syntax (ie: #F00 or #FF8C00). The special color name "auto" will derive the  color  from  the  server   target address (the connection string) so that connecting to the same target should always give the same color.  You may also specify the size of the border in pixels, ie: --border=yellow,10.

There is no specification for one side only. However, you could ask the developer at www.xpra.org if he likes to extend the option to specify one border only.

> this one would look good on --xorg

For other X servers there is no `--border` implementation in x11docker. I am not aware of a tool that x11docker could use for this job.
