### ISSUE TITLE
The `find` program is sometimes unavailable

### ISSUE THREAD

**Issue by gidfiddle** [mviereck/x11docker#135]
Some of the shell scripts x11docker writes and executes within the container invoke the `find` program.  Inconveniently, some basic images, such as Fedora:29, don't contain the `find` program.

Perhaps these scripts can be revised to avoid the need for `find`.

**Comment by mviereck** [comment]
Thank you! The next release will replace `find` with `ls`.

I am disappointed about fedora that it forces me to use `ls`. It is a bad practice to parse the output of `ls` and `find` should be used instead. Even the minimalist `busybox` has a `find` command, but fedora does not. sigh. It is hard to find GNU/Linux commands that work on every linux system.
