### ISSUE TITLE
Add TOC to the readme

### ISSUE THREAD

**Issue by 1138-4EB** [mviereck/x11docker#139]
It is possible to add a table of contents to the readme (manually). See for example https://github.com/spf13/cobra/blob/master/README.md. I think it can be useful for users visiting GitHub. However, I don't know how would the output be in other markdown viewers. You might want to be strict.

BTW, regarding this addition:

> Most times it makes sense to store the --verbose output (or ~/.cache/x11docker/x11docker.log) at pastebin.com.

It is possible to attach logs to the comments in the issues. Why do you prefer pastebin?

**Comment by mviereck** [comment]
I have added a table of contents. I often thought of that, now it is finally done. Thanks for the suggestion.

> It is possible to attach logs to the comments in the issues. Why do you prefer pastebin?

I can read the logs online. Attachments must be downloaded and be opened afterwards. And quickly I get a bunch of `x11docker.log(1..n)` in my download folder. Also I don't need to explain how to attach the log.

**Comment by 1138-4EB** [comment]
Thanks!
