### ISSUE TITLE
Imageuser command seems to be incorrect

### ISSUE THREAD

**Issue by inchuev** [mviereck/x11docker#140]
Hello @mviereck,

First of all, thank you for the software you created, it's really convenient.

I tried to customize some stuff and encountered an error during the execution:

```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/util/json: dial unix /var/run/docker.sock: connect: permission denied
```

It seems the error was caused by the following [line](https://github.com/mviereck/x11docker/blob/8f1cc6e4d56db754fe508661acdb643e4fe9ad65/x11docker#L4016), because it uses a hardcoded path instead of a variable.

The proposed change from my side would be:

```
-  echo "Imageuser=\$(docker inspect --format '{{.Config.User}}' $Imagename | rmcr)"
+  echo "Imageuser=\$($Dockerexe inspect --format '{{.Config.User}}' $Imagename | rmcr)"
```

After I changed that, the error message is gone and my experiment worked as expected.

If that's okay with you and you agree that it should be a variable, would you mind if I send a pull request?

**Comment by mviereck** [comment]
> It seems the error was caused by the following line, because it uses a hardcoded path instead of a variable.

Indeed, thank you for reporting and even finding the bug!

> If that's okay with you and you agree that it should be a variable, would you mind if I send a pull request?

It is quite appreciated.
However, I can fix and upload it myself, you would not need to do the work with a pull request. Feel free to make a PR or to let me do it.
