### ISSUE TITLE
Build of Elementary OS

### ISSUE THREAD

**Issue by hoshsadiq** [mviereck/x11docker#147]
Hello, could we get a desktop build of [Elementary OS](https://en.wikipedia.org/wiki/Elementary_OS)?

**Comment by mviereck** [comment]
Sorry, this won't work.

The pantheon desktop (and budgie desktop, too) is based on Gnome 3. 
Gnome 3 has some serious issues and segfaults if running in a container.
Only Cinnamon as a quite early Gnome 3 fork works flawlessly.

I hardly tried Gnome 3, budgie and pantheon about a year ago, but with no success.
A few weeks ago I tried Gnome 3 again, it is still segfaulting. Maybe I'll try next year again.

**Comment by hoshsadiq** [comment]
That's a shame. No problem! Thanks for trying.

**Comment by mviereck** [comment]
It might be possible now to run pantheon desktop in a Docker container.
So far, Gnome 3 and Budgie succeeded. Compare #16
