### ISSUE TITLE
does not run on Mac OS

### ISSUE THREAD

**Issue by philippefuentes** [mviereck/x11docker#15]
When I run it, I got:
```
x11docker ERROR Could not find user 'eussam' in /etc/passwd.
```

**Comment by mviereck** [comment]
Hello,

I doubt if x11docker will run on MacOS at all. Apple does not provide virtual machines for developing, so I can not test anything, and I won't buy me a Mac for this. (With a test environment, I'm sure I would get it to work).

From your error message, I assume MacOS does not provide the command `getent`.
You can try to disable line 1210 to bypass the check:
```
#  getent passwd $Hostuser >/dev/null 2>&1 || error "Could not find user '$Hostuser' in /etc/passwd."
```
Most probably, some other errors will occur afterwards.

**Comment by philippefuentes** [comment]
hi,
I see , thank you, didn't realise it was only meant to work on linux system.
indeed I don't have getent on Mac, and more errors occur afterwards

**Comment by mviereck** [comment]
If you want to fork x11docker to develop a version for Mac, I would help you where I can.

**Comment by philippefuentes** [comment]
I'm sorry, I wish I had time and knowledge for this :)

**Comment by mviereck** [comment]
ok :)
