### ISSUE TITLE
Possible replacement for kaptain

### ISSUE THREAD

**Issue by JED1SEN7INEL** [mviereck/x11docker#150]
First off, thank you for x11docker!

I saw you were looking for someone to port kaptain to QT5 and while trying to research that for you, I came across the following and wondered if it might satisfy your use case and act as a replacement to kaptain (or perhaps inspire a solution):

https://github.com/chriskiehl/Gooey

I have no affiliation with Gooey or it's author, but I hope it can be of help to you.

Thanks again for your work on x11docker!

**Comment by mviereck** [comment]
Thank you for this hint! It looks interesting.

Currently I'll stay with `kaptain` because it still works and `gooey` would need similar manual steps for installation or image use. But if some day `kaptain` is not feasible anymore and I need an alternative, I'll come back to this and check it out.
