### ISSUE TITLE
windows 10 WSL installation error

### ISSUE THREAD

**Issue by bfmcneill** [mviereck/x11docker#153]
![Capture](https://user-images.githubusercontent.com/16538715/57103684-bc0f3500-6ce3-11e9-8a13-27f4db344e32.JPG)

**Comment by mviereck** [comment]
Thank you for reporting this!
Can you please show me the output of `echo $PATH` in WSL?

It seems that the path to the Windows applications is missing somehow.
It should contain something like `/mnt/c/Windows/System32`.

Does the file `C:\Windows\System32/ipconfig.exe` exist? 
And as well `C:\Windows\System32/powershell.exe`?

**Comment by mviereck** [comment]
Just a thought: Maybe sudo is configured to set up its own `PATH` environment and misses the Windows pathes.
The installation may succeed with sudo option `-E` to preserve the user environment variables.

Can you please try:
```
curl -fsSL https://raw.githubusercontent.com/mviereck/x11docker/master/x11docker | sudo -E bash -s -- --update
```

**Comment by mviereck** [comment]
I've checked in a Windows VM and found, that `sudo` deletes Windows pathes from `PATH`. Option `-E` does not help.
The master branch includes a fix. Can you please try out:

```
curl -fsSL https://raw.githubusercontent.com/mviereck/x11docker/master/x11docker | sudo bash -s -- --update-master
```
(This command uses `--update-master` instead of `--update`).

**Comment by mviereck** [comment]
@bfmcneill Would you be so nice to check out the fix?
