### ISSUE TITLE
Integration of the sources of docker images in a single repository

### ISSUE THREAD

**Issue by 1138-4EB** [mviereck/x11docker#156]
Currently, a separate repository is used for each docker image. I think that it would be sensible to integrate all of them in a single repo. This would make it easier to potentially use multi-stage dockerfiles to make similarities between images explicit, and to reduce build time.

Note that I don't mean to merge all of them in this repo, but to create a new one instead. It is possible to preserve the histories of all the repos.

**Comment by mviereck** [comment]
That is worth a thought. 
However, I am not sure about one point: Currently the Dockerfile repositories are linked to docker hub for automated builds. Each time I update the github repo, the according docker image is rebuild automatically. I don't know yet if this is possible with a single collected repo, too.

**Comment by 1138-4EB** [comment]
There are several approaches:

- Docker Hub allows to use regular expressions to define multiple builds with custom file names: https://docs.docker.com/docker-hub/builds/#regexes-and-automated-builds. You could use a branch/tag for each image.
- You can use some external service, such as Travis CI or Circle CI. Images can be built sequentially (potentially sharing common cached layers) or in parallel jobs.
- Recently announced GitHub [registry](https://github.com/features/package-registry) and [actions](https://github.com/features/actions), or equivalent features on GitLab or Bitbucket.

My experiencie with regular expressions on Docker Hub is not good. Hence, I'd suggest to use a CI service that offers some more flexibility. I have experience with Travis CI, so I can help you setting it up. Certainly, you only need a docker user and password. Then, you write a bash script that executes `docker build`, `docker login`, `docker push` and `docker logout`. You can decide to build and push all the images every time `master` is updated, or implement some logic for a more granular approach.

If this project is going to stay on GitHub, I think that the best approach is to sign up for the beta of registry/actions or to wait until the features are public. Otherwise, if you are going to move it to GitLab, I think that this can be implemented through pipelines: https://docs.gitlab.com/ee/ci/pipelines.html.

**Comment by mviereck** [comment]
Thank you for the information!

Currently it is too much effort for me to do the changes and to check out the possibilities.
And I would not gather much; it works as it is, and I don't have plans to publish more Dockerfiles.

Maybe I'll look at this one time again in the future. For now I decide to leave it as it is.

**Comment by 1138-4EB** [comment]
> Edit: I just want to note that the autobuild feature of Docker Hub is important. I don't like solutions that upload a local built.

Yes, all the proposed alternative preserve this feature: the build process is automatic and 'public'.
 
> Maybe I'll look at this one time again in the future. For now I decide to leave it as it is.

Let me know if you need any help in the future.
