### ISSUE TITLE
docker-for-win: support PowerShell

### ISSUE THREAD

**Issue by 1138-4EB** [mviereck/x11docker#157]
Ref #148.

> @phil294:
> Concerning my idea of a docker-x11docker-image: Yes, I know, it would not help much: a simple batch script could achieve the same thing. However, there is no such batch script right now and I did not know there were any plans on doing so.

Since x11docker is itself a single bash script, adapting it to a batch script would imply rewriting almost the full project. Furthermore, x11docker relies on several tools that are normally found on Linux/Bash contexts, so I don't think it is a matter of syntax only.

> @phil294:
> With no batch script available and x11docker containerized, Windows users could be spared to install msys2 or cygwin. Feel free to ignore this paragraph, I should have opened a seperate issue.

This is a specific requirement, and we might be able to work around it. It is currently possible to execute `bash` from PowerShell, and it seems that the integration will improve in upcoming versions: https://www.youtube.com/watch?v=lwhMThePdIo.

So, it might be possible to use x11docker from PowerShell with VcXsrv, without requiring neither cygwin nor msys2. Cygwin would still be required in order to use `--xwin`.

I just tried the following:

``` powershell
PS C:\Users\username> bash
username@host:/mnt/c/Users/username$ export PATH=$PATH:/mnt/c/Program\ Files/Docker/Docker/resources/bin/
username@host:/mnt/c/Users/username$ cd /mnt/c/Program\ Files/Docker/Docker/resources/bin/
username@host:/mnt/c/Program\ Files/Docker/Docker/resources/bin/$ ln -s docker.exe docker
username@host:/mnt/c/Program\ Files/Docker/Docker/resources/bin/$ cd /mnt/c/Users/username
username@host:/mnt/c/Users/username$ curl -fsSL https://raw.githubusercontent.com/mviereck/x11docker/master/x11docker | bash -s -- --clipboard --gpu x11docker/check
mkdir: cannot create directory ‘/c’: Permission denied

x11docker ERROR: Could not create cache folder
  /c/Users/eine/x11docker/cache

  Type 'x11docker --help' for usage information
  Debug options: '--verbose' (full log) or '--debug' (log excerpt).
  Logfile will be:
  Please report issues at https://github.com/mviereck/x11docker
```

**Comment by mviereck** [comment]
I did a test in Powershell, too. It works here.
However, a different cache folder is created, the right one is `/mnt/c/Users/...`. I am not sure why `/mnt` is missing in your case.

x11docker itself checks `uname -r`. If it contains `Microsoft`, it configures itself for WSL.
```
PS C:\Users\User\Downloads> bash -c 'uname -r'
4.4.0-17134-Microsoft
```
Can you check `bash -c 'uname -r'` in Powershell, please?

**Comment by 1138-4EB** [comment]
> Can you check `bash -c 'uname -r'` in Powershell, please?

With 'Windows PowerShell' or 'Windows PowerShell ISE':

```
PS C:\Users\username> bash -c 'uname -r'
4.4.0-17134-Microsoft
```

With 'Windows PowerShell (x86)' or 'Windows PowerShell ISE (x86)':

```
PS C:\Users\username> bash -c 'uname -r'
3.0.6-338.x86_64
```

With 'Debian GNU/Linux':

```
username@DESKTOP-E1ER43H:~$ uname -r
4.4.0-17134-Microsoft
```

**Comment by mviereck** [comment]
Thanks. 
So x11docker's check fails in 'Windows PowerShell ISE (x86)'. Maybe it should check `PATH` instead (or afterwards) for something like `/Windows/System32`.

I would expect that x11docker will already work on your system in 'Windows PowerShell' or 'Windows PowerShell ISE'. I did my own test run in just 'Powershell'.

**Comment by 1138-4EB** [comment]
The error reported in the first comment corresponds to 'Windows PowerShell'. I get the same result with either of them.

**Comment by mviereck** [comment]
There will be several changes for x11docker on MS Windows (#160).
I'll look at this ticket again after the changes are done.

**Comment by mviereck** [comment]
I've installed a new Windows developer VM (WinDev1905Eval) and run x11docker with `runx` (#165) in PowerShell:
```
bash /usr/bin/runx -- /usr/bin/x11docker -e xterm
```
It succeeds, I still cannot reproduce the issue.

**Comment by 1138-4EB** [comment]
``` bash
PS C:\> bash
eine@DESKTOP-E1ER43H:/mnt/c$ /mnt/d/data-dev/github/runx/runx -- /mnt/d/data-dev/github/x11docker/x11docker -e xterm
runx note: MSYS2 does not provide xauth to create a cookie.
  Fallback: Enabling discouraged option --no-auth.

runx ERROR: No X server found for MSYS2.
  Please install X server VcXsrv:
      https://sourceforge.net/projects/vcxsrv
```

Anyway, I'll focus on #165.

**Comment by mviereck** [comment]
The issue here might be related to the failing WSL runs in #165.
WSL is somehow not detected properly.
Do you have `cygcheck.exe` available in WSL? That would confuse x11docker.

I've changed the order of the Cygwin/MSYS2/WSL check, maybe that fixes this issue as well as the WSL failures in #165.

Previously WSL was checked first, now at last. The new check:
```
  # Check for MS Windows subsystem
  command -v cygcheck.exe >/dev/null && {
    cygcheck.exe -V | rmcr | grep -q "(cygwin)"   && Winsubsystem="CYGWIN"
    cygcheck.exe -V | rmcr | grep -q "(msys)"     && Winsubsystem="MSYS2"
  }
  uname -r | grep -q "Microsoft"                  && Winsubsystem="WSL"
```

**Comment by 1138-4EB** [comment]
> Do you have `cygcheck.exe` available in WSL? That would confuse x11docker.

Yes, it is available in WSL:

``` bash
~$ cyg
cygcheck.exe               cygpath.exe                cygwin-console-helper.exe
~$ which cygcheck.exe
/mnt/c/msys64/usr/bin/cygcheck.exe
```

> I've changed the order of the Cygwin/MSYS2/WSL check, maybe that fixes this issue as well as the WSL failures in #165.

It works now. Both when launching WSL or when running bash from PowerShell. Some probably fixable messages are shown:

``` bash
# runx -- x11docker -e xterm
...
mkdir: cannot create directory ‘/run/user/1000’: Permission denied
chown: cannot access '/run/user/1000': No such file or directory
chmod: cannot access '/run/user/1000': No such file or directory
...
```

**Comment by mviereck** [comment]
> It works now. Both when launching WSL or when running bash from PowerShell. 

Great!

> Some probably fixable messages are shown:

I'll look into this. Do you get an output in WSL or PowerShell for: 
```
echo $XDG_RUNTIME_DIR
```
?

**Comment by 1138-4EB** [comment]
> I'll look into this. Do you get an output in WSL or PowerShell for:
> 
> ```
> echo $XDG_RUNTIME_DIR
> ```
> 
> ?

No. It's empty/unset. No matter if I check it in WSL, Cygwin or MSYS.

**Comment by mviereck** [comment]
The `mkdir ...` errors are fixed. Thanks for your tests!
