### ISSUE TITLE
Keep screen/hdmi active

### ISSUE THREAD

**Issue by gsantner** [mviereck/x11docker#163]
Hi there!

I', currently using x11docker with the [kodi](https://github.com/ehough/docker-kodi) image.
When I turn off the monitor/TV and turn it on again, it always tells me "no signal" etc.

The issue doesn't happen when I use other devices (and turn on/off), so I wanted to ask if somebody here got an idea how to keep the signal active and show the application again when turning on the TV. I saw multiple (unrelated) comments in kodi docker thread so I guess you (dev) know that one too and have maybe an idea how to fix this.

BTW, I'm not having any DE or DM on host, just console and x11docker window above. Tried `--wm=none` and xfce configuration, both same result. Also unplugging and replugging the cable doesn't show anything.

**Comment by gsantner** [comment]
If somebody else runs into this, ` --vt 1` parameter will do the job.

**Comment by mviereck** [comment]
I don't know what technically happened in your case. Great that you found a solution!
Thank you for reporting the issue and a solution.
