### ISSUE TITLE
Error "su: cannot set groups: Operation not permitted" with --sudouser

### ISSUE THREAD

**Issue by rsuhendro** [mviereck/x11docker#169]
I run this, the host is Ubuntu 18.04 LTS:
`x11docker --desktop --home --sudouser  -c x11docker/xfce`

From a terminal inside the container, I invoke su command but got this error:
```
hendro@43f4368fe622:~$ su
Password: 
su: cannot set groups: Operation not permitted
hendro@43f4368fe622:~$ ls -l /bin/su
-rwsr-xr-x 1 root root 63568 Jan 10 15:30 /bin/su
hendro@43f4368fe622:~$ cat /etc/sudoers
# /etc/sudoers created by x11docker
root ALL=(ALL) ALL
hendro ALL=(ALL) ALL
```
Need another hint, I'm really excited with X11docker... Thanks

**Comment by mviereck** [comment]
This is odd. The same command works well here (host: Debian).
The host should not make a difference.

Can you please show me the output of `--debug`?
```
x11docker --debug --desktop --home --sudouser -c x11docker/xfce
```

You can also try to add option `--cap-default`. That will most likely work. However, you should not need it.

**Comment by rsuhendro** [comment]
Please find the output:
[output message](https://pastebin.com/t541xa8G)  and [log](https://pastebin.com/YHEJwPDy) 

--cap-default doesn't make any difference..same error.

**Comment by mviereck** [comment]
Maybe there is an issue in `/etc/group`.
Can you please show me (from container):
```
cat /etc/group
cat /etc/passwd
cat /etc/shadow
```

**Comment by rsuhendro** [comment]
[This is the output.](https://pastebin.com/f7a4sVhG)

Btw the error for sudo is different:
```
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set
      or an NFS file system without root privileges?
```

**Comment by rsuhendro** [comment]
My temporary solution for invoking authorized command  is using separately:
`docker container exec -it --user root <container name/id)  /bin/bash`
Of course it doesn't require --sudouser at the first place.

**Comment by mviereck** [comment]
Thanks for the `cat` output. Everything looks well. I still have no idea why it does not work for you.

Could you try `su hendro` in your workaround solution? And if it suceeds, a `su` to root afterwards?

Another workaround would be to run x11docker with `--user=root`.

Maybe I have to set up an Ubuntu VM for test runs.

**Comment by rsuhendro** [comment]
Not sure what you meant with try su hendro then su to root. Am I already in root in workaround solution?
Yes x11docker with --user=root works but my intention is using normal user only certain commands such as apt-get I need to bump up the authority using su or sudo. 
Me too trying to set up Debian VM, will let you know later..

**Comment by rsuhendro** [comment]
I've created both Ubuntu 18.04 and Debian 9 VM and the problem do not occur on both VMs. Seems the issue is in my desktop Ubuntu 18.04 not on your x11docker. You can close it. I think I still  need to compare the msg log of both Ubuntu 18.04s.

**Comment by mviereck** [comment]
> I've created both Ubuntu 18.04 and Debian 9 VM and the problem do not occur on both VMs. 

Thank you for the test!

> Not sure what you meant with try su hendro then su to root. Am I already in root in workaround solution?

I though of this:
```
$ docker container exec -it --user root <container name/id> /bin/bash
root@abc123# su hendro
hendro@abc123# su
root@abc123#
```
This way you could check if user switching works in the `docker exec` environment.

**Comment by rsuhendro** [comment]
> I thought of this:
> 
> ```
> $ docker container exec -it --user root <container name/id> /bin/bash
> root@abc123# su hendro
> hendro@abc123# su
> root@abc123#
> ```
> 
> This way you could check if user switching works in the `docker exec` environment.

Oh OK but same error:
```
root@8d83fe45e87c:/tmp# su hendro
su: cannot set groups: Operation not permitted
```

**Comment by mviereck** [comment]
Maybe there is a wrong security configuration of docker. Please try:
```
 x11docker --desktop --home --sudouser -c --cap-default -- --security-opt seccomp=unconfined -- x11docker/xfce
```
If that fails, too, please try:
```
 x11docker --desktop --home --sudouser -c --cap-default -- --security-opt seccomp=unconfined --cap-add=ALL -- x11docker/xfce
```

**Comment by rsuhendro** [comment]
Thanks for the hints. I'll get back with the result later...

**Comment by rsuhendro** [comment]
> Maybe there is a wrong security configuration of docker. Please try:
> 
> ```
>  x11docker --desktop --home --sudouser -c --cap-default -- --security-opt seccomp=unconfined -- x11docker/xfce
> ```
> 
> If that fails, too, please try:
> 
> ```
>  x11docker --desktop --home --sudouser -c --cap-default -- --security-opt seccomp=unconfined --cap-add=ALL -- x11docker/xfce
> ```

Both failed with the same old error 



> Please build this image and run some user switching tests:
```
$ docker run --rm -ti --user=testuser mytest bash
testuser@0d0a79325d73:/$ id
uid=1000(testuser) gid=1000(testuser) groups=1000(testuser),27(sudo)
testuser@0d0a79325d73:/$ sudo ls
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
testuser@0d0a79325d73:/$ su
Password: 
unix_chkpwd[9]: check pass; user unknown
unix_chkpwd[9]: password check failed for user (root)
su: Authentication failure
testuser@0d0a79325d73:/$ su
Password: 
unix_chkpwd[11]: check pass; user unknown
unix_chkpwd[11]: password check failed for user (root)
su: Authentication failure
testuser@0d0a79325d73:/$ 

```
doesn't accept 'x11docker' as valid password ?

BTW, following are the message when building the image:
```
$ docker build   -t mytest  .
Sending build context to Docker daemon  2.048kB
Step 1/6 : FROM debian:buster
buster: Pulling from library/debian
478cd0aa93c0: Pull complete 
Digest: sha256:543a3f93a1f53d2d292ec067fa13528d5f3843ae4c4ffe6ef6993ca70b6ac2fa
Status: Downloaded newer image for debian:buster
 ---> 098963abf3c3
Step 2/6 : RUN apt-get update
 ---> Running in afa329a7b68e
Get:2 http://cdn-fastly.deb.debian.org/debian buster InRelease [163 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [46.8 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7902 kB]
Get:1 http://security-cdn.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:5 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [1132 B]
Fetched 8152 kB in 20s (410 kB/s)
Reading package lists...
Removing intermediate container afa329a7b68e
 ---> c58aa441128d
Step 3/6 : RUN apt-get install -y sudo
 ---> Running in 2640d37c5af3
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  lsb-base
The following NEW packages will be installed:
  lsb-base sudo
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 1273 kB of archives.
After this operation, 3936 kB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian buster/main amd64 lsb-base all 10.2019051400 [28.4 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster/main amd64 sudo amd64 1.8.27-1 [1245 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1273 kB in 2s (645 kB/s)
Selecting previously unselected package lsb-base.
(Reading database ... 6674 files and directories currently installed.)
Preparing to unpack .../lsb-base_10.2019051400_all.deb ...
Unpacking lsb-base (10.2019051400) ...
Selecting previously unselected package sudo.
Preparing to unpack .../sudo_1.8.27-1_amd64.deb ...
Unpacking sudo (1.8.27-1) ...
Setting up lsb-base (10.2019051400) ...
Setting up sudo (1.8.27-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Removing intermediate container 2640d37c5af3
 ---> 25d1cacde065
Step 4/6 : RUN useradd testuser --password sac19FwGGTx/A
 ---> Running in 225b17b4a3c3
Removing intermediate container 225b17b4a3c3
 ---> 9bbda90bbf13
Step 5/6 : RUN adduser testuser sudo
 ---> Running in f13b73d4fec1
Adding user `testuser' to group `sudo' ...
Adding user testuser to group sudo
Done.
Removing intermediate container f13b73d4fec1
 ---> 2a8b6171d657
Step 6/6 : RUN echo root:x11docker | chpasswd
 ---> Running in 7e2c2f2c4b80
Removing intermediate container 7e2c2f2c4b80
 ---> 8983935054af
Successfully built 8983935054af
Successfully tagged mytest:latest
```

**Comment by mviereck** [comment]
It's really odd.
Your test with the `mytest` image shows that the problem is not specific to x11docker.
The same image works quite well here. Password `x11docker` is correct.

Let's focus on this error message:
```
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```
Where/how do you store your Docker images? Is there anything special about this?

**Comment by rsuhendro** [comment]
> Where/how do you store your Docker images? Is there anything special about this?

Just perfect, that's great pointer. Yes, I've moved out the docker data folder from default /var/lib/docker to other folder due to partition space constraint. 
I use the --data-root option in docker's ExecStart, see this [stackoverflow link](https://stackoverflow.com/questions/32070113/how-do-i-change-the-default-docker-container-location/50726177#comment72568827_32072042url).

If I return it back to default folder, this problem is gone ;-)
Sure this is not x11docker issue.

I'll pursue --data-root separately.. Thank you very very much.

**Comment by mviereck** [comment]
So we tracked it down, great!
You can check the ouput of `mount` for the partition with your Docker images. Probably it is mounted with `nosuid`.

**Comment by rsuhendro** [comment]
Yes, you are right, it is mounted with nosuid. thanks again
