### ISSUE TITLE
NVIDIA Driver Not Installing

### ISSUE THREAD

**Issue by sjordahl** [mviereck/x11docker#171]
Wanting x11docker to install the NVIDIA driver in a container, but something (possibly the error) getting in the way.  Using `x11docker --hostdisplay --gpu &lt;image&gt;` DOES work, but the attached config doesn't do the install.
[x11docker.log](https://github.com/mviereck/x11docker/files/3327069/x11docker.log)

**Comment by mviereck** [comment]
Hi Steve, nice to hear from you!

I recently fixed some issues around NVIDIA in master version. Could you please update with `x11docker --update-master` and try again? If the master version works, I'll publish a new release soon.

**Comment by sjordahl** [comment]
Thanks for the quick response.  The master DID install the driver properly.  I like the quick and easy ones!

Thank you!

**Comment by sjordahl** [comment]
Here's the log: [x11docker.log](https://github.com/mviereck/x11docker/files/3327174/x11docker.log)

**Comment by mviereck** [comment]
I probably found the reason. Your command:
```
'/usr/bin/x11docker' '-D' '--hostdisplay' '--gpu' '--env' 'VRDE=off' '--env' 'VBPORT=33389' '--cap-default' '--hostnet' '--' '-v' '/home/jordahl/workspace/vms/windows/Windows:/vm' '--device' '/dev/vboxdrv' '--cap-drop=ALL' '--' 'steve/virtualbox:6.0.8'
```
The command contains `--cap-default -- --cap-drop=ALL` to fit your VirtualBox setup.
However, `--cap-drop=ALL` causes the NVIDIA installer to fail.
Please try without `--cap-drop=ALL`.

Background: The NVIDIA installer needs several capabilities and must not run with `--security-opt=no-new-privileges`.
In this special case your VirtualBox setup would even run without `--cap-default` because x11docker adds some privileges to allow the NVIDIA installer.

**Comment by sjordahl** [comment]
Great call!  The driver did install, and worked as expected.  Thanks for the assist!  Now to figure out why vbox 3D acceleration is making some of my window panes black...

As always, your help is very much appreciated!

**Comment by mviereck** [comment]
:-) You're welcome!

> Now to figure out why vbox 3D acceleration is making some of my window panes black...

That is probably a VirtualBox and/or NVIDIA issue. However, if you assume it is related to x11docker, please tell me. 
I never had a satisfying VirtualBox GPU setup even with other graphics cards. I did not try for a long time, though.

**Comment by sjordahl** [comment]
Agreed, this is not an x11docker issue.  I think it might be a NVIDIA/WDDM issue.

**Comment by mviereck** [comment]
Some years ago I had an experimental setup with Linux host and Linux VM:
The applications in the VM has been connected to the X server from host and used the host GPU flawlessly.
I am not sure how I accomplished that; probably I set up an X server with `-listen tcp` and set `DISPLAY` in the VM with `IP:DISPLAYNUMBER`.
