### ISSUE TITLE
Startup of docker failed. Unknown runtime specified nvidia

### ISSUE THREAD

**Issue by AnkS4** [mviereck/x11docker#172]
docker: Error response from daemon: Unknown runtime specified nvidia.

Error log: https://gist.github.com/AnkS4/a60311075d0417a56ef503db9a7e608b

**Comment by mviereck** [comment]
Hello AnkS4,

is your system correctly configured for [NVIDIA/nvidia-runtime](https://github.com/NVIDIA/nvidia-docker)? This error message indicates that it is not:
> docker: Error response from daemon: Unknown runtime specified nvidia.

Also note that `--runtime=nvidia` only makes sense for images based on images provided by NVIDIA. Is this the case for your image `osrf/ros:kinetic-desktop-full`?

Compare: https://github.com/mviereck/x11docker/wiki/NVIDIA-driver-support-for-docker-container#nvidianvidia-docker-images

**Comment by AnkS4** [comment]
`osrf/ros:kinetic-desktop-full` is not image provided by NVIDIA.

`$ x11docker --gpu --runtime=nvidia -- nvidia/cuda nvidia-smi` too returning ERROR.

x11docker ERROR: Got error message from docker daemon:
docker: Error response from daemon: OCI runtime create failed

[ErrorLog](https://gist.github.com/AnkS4/fd7b3e9bc448994f0b9aae03066ad70d)

**Comment by mviereck** [comment]
I am still wondering if your docker installation is configured well for nvidia runtime.
Can you show me the output of:
```
docker info | grep Runtime
```
It should contain the string `nvidia`.

To check the runtime configuration, try docker directly instead of x11docker:
```
docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
```

**Comment by AnkS4** [comment]
I've bumblee driver, so I need to run it with `primusrun`:

```
$ primusrun docker info | grep Runtime
Runtimes: nvidia runc
Default Runtime: runc
```

```
$ primusrun docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 --pid=11636 /var/lib/docker/aufs/mnt/0802c315b56e37bbd0c7cdd81253a7dd8a97951f48d8e888f6e905028fcbd9f0]\\\\nnvidia-container-cli: initialization error: cuda error: unknown error\\\\n\\\"\"": unknown.
```

**Comment by mviereck** [comment]
At this point I don't know how to debug further. 
It is not an x11docker issue but somehow related to the NVIDIA setup.

I recommend to report this at https://github.com/NVIDIA/nvidia-docker, they probably know what to do. Provide them these info of yours:
```
$ primusrun docker info | grep Runtime
Runtimes: nvidia runc
Default Runtime: runc

$ primusrun docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411 --pid=11636 /var/lib/docker/aufs/mnt/0802c315b56e37bbd0c7cdd81253a7dd8a97951f48d8e888f6e905028fcbd9f0]\\\\nnvidia-container-cli: initialization error: cuda error: unknown error\\\\n\\\"\"": unknown.
```

-----------------
You could still try to run x11docker without `--runtime=nvidia` and instead provide an NVIDIA installer file to x11docker. Compare [Automated install of NVIDIA driver during container startup](https://github.com/mviereck/x11docker/wiki/NVIDIA-driver-support-for-docker-container#automated-install-of-nvidia-driver-during-container-startup)

**Comment by mviereck** [comment]
I am closing here for now. 

Feel free to ask again if something comes up or if you want to try out the other possibilities to use NVIDIA driver.
