### ISSUE TITLE
how to gui for unity3d in docker?

### ISSUE THREAD

**Issue by twyeld** [mviereck/x11docker#186]
Thanks to you and others' excellent work, I have got very close to having a GUI launch from inside a docker container but something is missing.

So far I have followed lots of tutorials and examples (gableroux, jessfraz, mviereck and so on) - and I can get many GUIs working from a docker install - but not a standalone unity3d game level

here is what I have done so far:

1) start xhost
xhost +local:root;
2) create a display to use
Xvfb :2 -screen 0 1024x768x16
3) check that the display is running
ps aux | grep X
4) run my docker session
docker run -it --rm -e DISPLAY=:2 \
-v /tmp/.X11-unix:/tmp/.X11-unix <docker_imageID> /bin/bash
5) from inside docker:
root@<containerID>:/app# ./<my_game>.x86_64 

from the traceback you can see it is running but no screen pops up?:
Set current directory to /app
Found path: /app/<my_game>.x86_64
Mono path[0] = '/app/<my_game>_Data/Managed'
Mono config path = '/app/<my_game>_Data/MonoBleedingEdge/etc'
Preloaded 'libgrpc_csharp_ext.x64.so'
Unable to preload the following plugins:
	ScreenSelector.so
PlayerPrefs - Creating folder: /root/.config/unity3d/Unity Technologies
PlayerPrefs - Creating folder: /root/.config/unity3d/Unity Technologies/Unity Environment
Logging to /root/.config/unity3d/Unity Technologies/Unity Environment/Player.log

any ideas where I am going wrong?

**Comment by mviereck** [comment]
There seems to be some confusion:
> start xhost
xhost +local:root;

This affects your current X `$DISPLAY`, probably `:0`. But later your run another X server with display number `:2`.
Btw., I would prefer the syntax `xhost +SI:localuser:root`, if needed at all. For this setup you don't need it.

> create a display to use
Xvfb :2 -screen 0 1024x768x16

You run an additonal X server Xvfb. Xvfb is invisible; vfb means `virtual frame buffer`.
Try instead: `Xephyr :2 -ac -extension MIT-SHM`. Xephyr is a visible nested X server.

Compare: https://github.com/mviereck/x11docker/wiki/Short-setups-to-provide-X-display-to-container#providing-nested-x-server-xephyr

**Comment by twyeld** [comment]
wow - thanks for the speedy response - I'll try that now...

**Comment by twyeld** [comment]
ok - I tried the following:
Displaynumber=1
Xephyr :$Displaynumber -extension MIT-SHM -extension XTEST &

I get the following error:
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 

I tried sudo stop lightdm but doesn't seem to stop the x-server?

when I use:
Xephyr -ac -screen 1280x1024 -br -reset -terminate 2> /dev/null :1 &

and run the docker script - it runs but still no popup screen...

docker run --rm \
-e DISPLAY=:$Displaynumber \
-v /tmp/.X11-unix/X$Displaynumber:/tmp/.X11-unix/X$Displaynumber:rw \
--user $(id -u):$(id -g) \
--cap-drop=ALL \
--security-opt=no-new-privileges \
<image_name> ./<my_game>.x86_64

**Comment by mviereck** [comment]
> (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)

This error indicates that you already have an X server with display number 1.
Have a look at `/tmp/.X11-unix/`. Probably there is already a socket `X1`. Try a free display number.

**Comment by twyeld** [comment]
ok I changed display to 2 - I get a popup window now - great! - but when I run the docker script still no game graphics in window

I use ps aux | grep X to check what display is free
root      1231  0.0  0.1 182976 47948 tty1     Sl+  22:28   0:01 /usr/lib/xorg/Xorg vt1 -displayfd 3 -auth /run/user/123/gdm/Xauthority -background none -noreset -keeptty -verbose 3
root      1767  1.7  0.2 194252 53748 tty3     Sl+  22:28   0:25 /usr/lib/xorg/Xorg vt3 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3
twyeld    3776  0.0  0.2 1102724 49360 ?       Sl   22:43   0:00 docker run --rm -e DISPLAY=:1 -v /tmp/.X11-unix/X1:/tmp/.X11-unix/X1:rw --user 1000:1000 --cap-drop=ALL --security-opt=no-new-privileges mytest3 ./ban2heliIndAgents.x86_64
twyeld    4092  0.0  0.0  17484   904 pts/1    S+   22:53   0:00 grep --color=auto X

**Comment by mviereck** [comment]
Xephyr does not appear in your ps output. Is it really running?
The docker run command shows `DISPLAY=:1`, but you said you switched to display number 2.
Please check again.

**Comment by twyeld** [comment]
sorry for confusion - that display listing was taken before I loaded your script.

this is what I get after loading your script:
root      1246  0.6  0.1 182988 47808 tty1     Sl+  10:49   0:01 /usr/lib/xorg/Xorg vt1 -displayfd 3 -auth /run/user/123/gdm/Xauthority -background none -noreset -keeptty -verbose 3
root      1923  2.8  0.2 191212 52216 tty3     Sl+  10:50   0:04 /usr/lib/xorg/Xorg vt3 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3
twyeld    3103  0.0  0.1 709080 37892 pts/0    Sl   10:52   0:00 Xephyr :2 -extension MIT-SHM -extension XTEST
twyeld    3170  0.6  0.2 1175944 49324 pts/0   Sl+  10:52   0:00 docker run --rm -e DISPLAY=:2 -v /tmp/.X11-unix/X2:/tmp/.X11-unix/X2:rw --user 1000:1000 --cap-drop=ALL --security-opt=no-new-privileges mytest3 ./ban2heliIndAgents.x86_64
twyeld    3388  0.0  0.0  17484   912 pts/1    S+   10:53   0:00 grep --color=auto X

It is definitely running Xephyr :2 

and I get a popup window but still no graphics from the standalone Unity3D game app...

**Comment by mviereck** [comment]
So far the setup should work. Now let's look at the application itself. What output does it give?
Do you have another X application in the image to test? You could install e.g. `xterm` in the image and try that instead of unity3d.

**Comment by twyeld** [comment]
Thanks mviereck  - I have tried several ways but can't even get a xterm working.

Here is the new dockerfile (whcih includes xterm and my standalone unity3d game):
```FROM ubuntu:18.04
RUN apt-get update && apt-get install -y xterm
RUN useradd -ms /bin/bash xterm
USER xterm
WORKDIR /home/xterm
COPY standalone /home/app/```

And here is how I build:
```docker build -t xterm .```

and attempt to run - not assigning a display:
```docker run -it --rm -e DISPLAY=${DISPLAY} \
-v /tmp/.X11-unix:/tmp/.X11-unix xterm xterm```

and error:
```No protocol specified
xterm: Xt error: Can't open display: :1```

and attempt to run - assigning display 2:
docker run -it --rm -e DISPLAY=:2 \
```-v /tmp/.X11-unix:/tmp/.X11-unix xterm xterm```

and error:
```xterm: Xt error: Can't open display: :2```

**Comment by twyeld** [comment]
here I am sending you the unity3d standalone app I am trying to launch from
inside a docker container... maybe it helps?

it certainly works in the native linux env
 standalone.zip
<https://drive.google.com/file/d/1R-j6F9cYZXcQATilYUabkTdfbIjiBjFT/view?usp=drive_web>

**Comment by mviereck** [comment]
Try:
```
Xephyr :2 -ac -extension MIT_SHM
```
```
docker run --rm -e DISPLAY=:2 -v /tmp/.X11-unix:/tmp/.X11-unix xterm xterm
```

**Comment by twyeld** [comment]
ok - that got me an xterm in xephyr on :2 (after changing MIT_SHM to MIT-SHM)

**Comment by mviereck** [comment]
Good!
Now try to run your unity3d application in that xterm window.

**Comment by twyeld** [comment]
how to check what directory am in ?
xterm doesn't take dir or ls

**Comment by mviereck** [comment]
Yo are probably in an empty directory if you don't get an output.
Try `pwd`.

**Comment by twyeld** [comment]
it returns: /home/xterm

**Comment by twyeld** [comment]
ok so I cd ../ etc up to app and then launched the game!!! yay!

pretty chugsville though!

clearly only using cpu for rendering - is there anyway to get it to use my nvidia 1050 card?

**Comment by mviereck** [comment]
GPU usage does not work with Xephyr. 
Using NVIDIA GPU with containers is more complicated than other GPUs.
Compare:
https://github.com/mviereck/x11docker/wiki/Hardware-acceleration
I suggest to use x11docker for NVIDIA setups: https://github.com/mviereck/x11docker/wiki/NVIDIA-driver-support-for-docker-container

**Comment by twyeld** [comment]
I managed to launch your x11docker session using xterm embedded in xephyr - but i don't think this is what you meant... I could get gpu_glxgears to run at ~2500fps - cool!

not sure how to access x11docker other than through xterm and xephyr...?

is there a more direct method?

**Comment by twyeld** [comment]
I tried
```xhost local:root```
then:
```docker run --rm -e DISPLAY=:2 x11docker```
but get error:
```kaptain: cannot connect to X server :2```
I even tried:
```docker run --rm -e DISPLAY=:2 -v /usr/bin/x11docker:/tmp/x11docker x11docker xterm```
but same error...

**Comment by mviereck** [comment]
You need to be more clear, in your reports as well as in your attempts to get to run something.

> docker run --rm -e DISPLAY=:2 x11docker
but get error:
kaptain: cannot connect to X server :2

That is impossible. `x11docker` does not use `kaptain`. You probably tried to run `x11docker-gui`.
Also, `x11docker` is not a docker image but a bash script.

Please read the [documentation](https://github.com/mviereck/x11docker/blob/master/README.md) on how to use x11docker:
```
To run a Docker container on a new X server:
  x11docker IMAGE
  x11docker [OPTIONS] IMAGE [COMMAND]
  x11docker [OPTIONS] -- IMAGE [COMMAND [ARG1 ARG2 ...]]
  x11docker [OPTIONS] -- DOCKER_RUN_OPTIONS -- IMAGE [COMMAND [ARG1 ARG2 ...]]
To run a host application on a new X server:
  x11docker [OPTIONS] --exe COMMAND
  x11docker [OPTIONS] --exe -- COMMAND [ARG1 ARG2 ...]
To run only an empty new X server:
  x11docker [OPTIONS] --xonly
```
Try:
```
x11docker --xephyr xterm xterm
```

**Comment by twyeld** [comment]
ok - I think the confusion comes from me creating docker images with the names x11docker and xterm2 respectively... I should have used different naming...

```x11docker --xephyr xterm xterm```
gives me a xephyr shell with xterm inside from which i can launch a unity3d game app - but xephyr only supports CPU rendering

can I use something like xorg with --gpu or even --hostdisplay ?

**Comment by mviereck** [comment]
> can I use something like xorg with --gpu or even --hostdisplay ?

Yes. Be aware that `--gpu` with NVIDIA needs some special setup, compare: https://github.com/mviereck/x11docker/wiki/NVIDIA-driver-support-for-docker-container
The wiki article describes three possible setups.

Probably the best choice for you is to create a custom driver base image: 
https://github.com/mviereck/x11docker/wiki/NVIDIA-driver-support-for-docker-container#nvidia-driver-base-image

Use this driver base image to create a new image containing `xterm` and your unity3d game.

**Comment by twyeld** [comment]
I am still a bit confused. Yes, I need to move on to configuring for the nVidia driver but, surely I can get a simple session working using --hostdisplay before that?
Here is s screen grab of the errors I am getting - not sure where I am going wrong...

![Screenshot](https://user-images.githubusercontent.com/29798223/65320430-2a965600-dbe5-11e9-8a61-9d274eb083dc.png)

**Comment by mviereck** [comment]
Please do no provide screenshots but copy the terminal messages und provide them in codeblocks

x11docker shows two warnings that applications may fail with `--hostdisplay`.
At first it recommends `--clipboard`, at second it warns about NVIDIA.
Please read the messages and try with `--hostdisplay --clipboard`.

**Comment by twyeld** [comment]
ok - this time I get the following error:
```libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request: GLXBadContent```
etc...

**Comment by mviereck** [comment]
This error is probably due to the NVIDIA driver.
As the warning says, `--hostdisplay` can fail with NVIDIA.

At this point, you can either use another X server option like `--xpra`, `--xephyr` or `--nxagent`, or you set up an NVIDIA driver image and run with `--hostdisplay --gpu`.

**Comment by twyeld** [comment]
I have successfully installed your "x11docker/nvidia-base" image - how to run it and point it at my basic container with my game app in it?

**Comment by mviereck** [comment]
Build a new image instead of using the old one. Example:
```
FROM x11docker/nvidia-base
RUN apt-get update && apt-get install -y xterm
COPY standalone /home/app/
CMD xterm
```

**Comment by twyeld** [comment]
OMG! you are a legend! It works!

so sweet to see it working at last - after weeks of bashing away...
thank you so much...

**Comment by mviereck** [comment]
Great! :-)
You're welcome.

**Comment by twyeld** [comment]
I now have a new issue for x11docker/nvidia-base

After starting the docker image and executing the <my_game>.x86_64 from a live container, I need to be able to communicate with the running game from another docker container.

How this works: I have 2 containers - container A runs a python script for ML that communicates on port 5005. Container B has the game exec which needs to communicate with the ML python script in container B on port 5005.

My problem is that the normal port expose function doesn't seem to work for the  x11docker/nvidia-base image.

I have tried several alternatives, including:
`#dockerfile`
`FROM x11docker/nvidia-base`
`RUN apt-get update && apt-get install -y xterm`
`COPY bin /home/app/`
`WORKDIR /home/app`
`EXPOSE 5005`
`CMD xterm`

`$ x11docker --hostdisplay --gpu --env PORT=localhost5005:5005 <my_image> xterm`

I know it "should" work because when I run the game exec on the local machine outside docker and I run the ML python script inside the container they communicate fine.

any ideas?

**Comment by mviereck** [comment]
> normal port expose function doesn't seem to work

You need docker option `-p` for both containers. This should work:
```
x11docker --hostdisplay --gpu --env PORT=localhost5005:5005 -- -p 5005:5005 -- <my_image> xterm
```
Alternatively a setup with docker option `--network` should be possible, providing the same network namespace to both containers.

> I now have a new issue for x11docker/nvidia-base

In general, please open new tickets for new issues.
