### ISSUE TITLE
x11docker-gui /usr/bin/catatonit: invalid option -- 's'

### ISSUE THREAD

**Issue by philuser** [mviereck/x11docker#189]
Hello,
when I run `x11docker-gui`, I systematically get the error:
```bash
$ x11docker-gui
...
/usr/bin/catatonit: invalid option -- 's'
usage: catatonit [-ghLV] [--] <progname> [<arguments>...]
```
My file  [x11docker.log](https://gist.github.com/philuser/1204371a79b46341c2fb1679d538f00b)
catatonit according to what I saw is a particularity of opensuse https://github.com/openSUSE/catatonit.
In the `x11docker.log`. 
```bash
378  |69	Tini='/usr/bin/catatonit'
392  |83	storeinfo test tini && Tini="$(storeinfo dump tini) -s --" || Tini=''
```
but the `catatonit` process does not have the `-s` switch

How can I fix this? 

Thank you.

**Comment by mviereck** [comment]
Thank you for the report and already pointing on the relevant code parts!
I wasn't aware of `catatonit` on openSUSE, good to know.

I've fixed the bug, x11docker does not use the switch `-s` anymore. Instead it sets environment variabe `TINI_SUBREAPER=1`.
`catatonit` will run as a subreaper automatically and does not need a switch.

Please update x11docker. Aternatively you could just set `Tini=''` in the code, it is not really important at this point, it just serves to have a clean process tree.

**Comment by philuser** [comment]
Great. Great. 

What a surprising reactivity, bravo.

I'll test it at the end of the day, I'll make a comeback.

And thanks again for the work.
