### ISSUE TITLE
Resizeable Xephyr

### ISSUE THREAD

**Issue by azazar** [mviereck/x11docker#192]
Noticed the message on x11-docker start.

```
x11docker note: Xephyr is a quite stable nested X server.
  Less stable, but resizeable is nxagent with option --nxagent.
```

Xephyr is resizeable too. It has command line option for that: `-resizeable          Make Xephyr windows resizeable`

**Comment by mviereck** [comment]
Yes, thank you for pointing on this.

I once tried `Xephyr -resizeable` and found that it occasionally crashes. Xephyr is not stable anymore with option `-resizeable`. So I decided not to use or provide this option.

**Comment by mviereck** [comment]
In a recent commit I've added `-resizeable` to Xephyr.
I ran several tests and could not reproduce the crashes that I've encountered years ago. Maybe something has been fixed.
I still encounter segfaults if I rotate the display with e.g. `xrandr --rotate`.
