### ISSUE TITLE
Need some advice

### ISSUE THREAD

**Issue by r3d9u11** [mviereck/x11docker#195]
Hello. 

I have some questions about working with x11docker's images and containers:
1. Where I can watch downloaded containers through x11docker? Is there something like a `docker ps -a` ?
2. Is it possible to run image which was downloded by docker?
3. Is it possible to create custom image for x11docker? What may need for this (it should be able to run OpenGL/Vulkan application)?
_(I can't find answers to those questions on the wiki)_

Thanks!

**Comment by mviereck** [comment]
Just some term clarification:
 - You do not download a container. Instead you are dowloading an image. In terms of Docker you are _pulling_ an image. 
 - With `docker run IMAGENAME` you are starting a container from an image.

> Where I can watch downloaded containers through x11docker? Is there something like a docker ps -a ?

x11docker uses Docker and its commands `docker pull`  and `docker run`. x11docker images are not different from Docker images, it is entirely the same.
 - You can see local images with `docker images`
- You can see current active containers with `docker ps`
- x11docker always starts a fresh container from an image and discards it afterwards. It does not use the possibility to reuse an old container.

> Is it possible to run image which was downloded by docker?

Yes.

> Is it possible to create custom image for x11docker? 

Yes. You can look at my repositories for some examples. Short example for a Dockerfile:
```
FROM debian:buster
RUN apt-get update
RUN apt-get install -y xterm
```
Build:
```
docker build -t myxtermimage PATH/TO/DOCKERFILE
```
Run:
```
x11docker myxtermimage
```
You can look in image list:
```
docker images | grep xterm
```
You can look at containers while xterm is running:
```
docker ps 
```

> What may need for this (it should be able to run OpenGL/Vulkan application)?

Probably it is enough to install the open source MESA drivers in image / in the Dockerfile and to run x11docker with option `--gpu`. Compare [Dependencies in image](https://github.com/mviereck/x11docker/wiki/dependencies#dependencies-in-image) for option `--gpu`.
```
RUN apt-get install -y mesa-utils mesa-utils-extra
```

**Comment by r3d9u11** [comment]
@mviereck 
>You do not download a container. Instead you are dowloading an image. In terms of Docker you are pulling an image.
Yes, sorry, my mistake.

Many thanks for help and detailed answer!
