### ISSUE TITLE
--gpu doesn't install drivers automatically anymore

### ISSUE THREAD

**Issue by 01e9** [mviereck/x11docker#198]
1. The [x11docker script](https://github.com/01e9/snake-game-opengl/blob/9f572ac52481375f680966c26ca1498d61f13428/docker/ide.sh#L18-L26)
2. The driver is [prepared in the right directory](https://user-images.githubusercontent.com/28860670/69495963-83c88180-0ed5-11ea-8279-949b047004ab.png)
3. [Output](https://pastebin.com/raw/hgVRUbZW) doesn't contain "installing driver..." and container starts fast.

**Comment by mviereck** [comment]
Thank you for the report!

I did a test run with the current master version, it works well so far.
Can you please show me the output with option `--debug`?

Maybe this check fails, could you please try it out?
```
head -n1 2>/dev/null </proc/driver/nvidia/version | awk '{ print $8 }'
```
It should print `390.116` on your system.

**Comment by 01e9** [comment]
With `--debug` https://pastebin.com/raw/6BhncsRy
Driver version and installer are detected properly but installation is not starting.

**Comment by mviereck** [comment]
Ok, it is fixed now.
It only happened along with `--cap-default`, so i missed it first. It was only one `:` missing in the code. :)
Please update to current master. I'll publish a new release soon.

**Comment by 01e9** [comment]
Fixed. Thanks!

**Comment by mviereck** [comment]
I did a change in latest commit that affects the NVIDIA driver installation, too.

x11docker's root setup in container now runs with `--privileged` flag. This gives all privileges that are needed to install the driver. The final container command on the other hand does not need or get any privileges anymore.

Could you please run two tests for me?
This should just work and show the NVIDIA card name:
```
x11docker --gpu x11docker/check glxinfo | grep renderer
```
This one might fail:
```
x11docker --gpu --init=systemd --newprivileges=no x11docker/check glxinfo | grep renderer
```
I need to check if `--newprivileges=no` makes a difference here. 
With `--init=systemd` x11docker takes another code path that does not give `--privileged` to `containerrootrc`. 

Background:
Earlier the NVIDIA driver did not need `--newprivileges=yes`. Later the driver installation failed and needed `--newprivileges=yes` (automatically enabled). 
Now it works in my tests with `--newprivileges=no` again. 

It is confusing and I assume that there has been a docker bug for some time.
With my current Docker version 19.03.5 the installation succeeds with `--newprivileges=no`.

**Comment by 01e9** [comment]
- https://pastebin.com/raw/T386QDBb
- https://pastebin.com/raw/788mgdhJ

```
$ uname -a
Linux d 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux



$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic



$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by mviereck** [comment]
Thank you!
So it seems the driver installation succeeds again without `--newprivileges=yes`. Maybe I can disable that in the code again.
It has been an issue in #162. I'll ask there for a check, too.
