### ISSUE TITLE
How to share CEC device for kodi

### ISSUE THREAD

**Issue by mviereck** [mviereck/x11docker#203]
Coming from #191 :

Ticket to discuss how to share a CEC device.

@marcosvrs:
I found package [cec-utils](https://packages.debian.org/buster/cec-utils) proving `cec-client`.

Could run run `cec-client --list-devices` on host?
It may show device files that must be shared with the container.
It may also help to install `cec-utils` in image to check things out.

**Comment by marcosvrs** [comment]
https://askubuntu.com/questions/935445/how-to-get-hdmi-cec-working-on-a-7th-gen-intel-nuc

At least for my device, looks like it's not a software problem :(

**Comment by mviereck** [comment]
> At least for my device, looks like it's not a software problem :(

So it does not work at all, including the host? Ok, then I'll close the ticket for now.
