### ISSUE TITLE
Found unknown container runtime: oci

### ISSUE THREAD

**Issue by seandilda** [mviereck/x11docker#205]
While trying x11docker on Fedora 30, I received the warning:

x11docker WARNING: Found unknown container runtime: oci 
  Please report at:  https://github.com/mviereck/x11docker

**Comment by mviereck** [comment]
Thank you for the report!

Currently I am a bit confused about it.
OCI ist the name of the runtime specification standard: https://github.com/opencontainers
The default runtime code provided there is `runc`.

I did not find any documentation about a runtime directly called `oci`. All search results refer to the OCI standard, not to a code called `oci`.

For now I'll assume that runtime `oci` does the same as runtime `runc`.
I've added it in x11docker to the list of known runtimes.

Some runtimes need some special setup to be done by x11docker. So, if you encounter odd behaviour or failures, it would be nice if you report them, too.
