### ISSUE TITLE
After Installing and running thunderbird in X11docker in Ubuntu,while restarting getting stuck on Login screen.

### ISSUE THREAD

**Issue by koustubhnaik** [mviereck/x11docker#207]
After succesfully installing and running several instances of thunderbird in X11docker installing all its dependencies and running in x servers.But ,after restarting the laptop it gets stuck on login screen,Keyboard and mouse donot work at all.
I dont understand why?then i have to boot it live in kali linux and download data and reinstall Ubuntu Mate 18.04.3 !! it has been hectic!! but i think solution has to do with display server interference and im working it out.Any help would be welcome.
Thanks.

**Comment by mviereck** [comment]
> after restarting the laptop it gets stuck on login screen,Keyboard and mouse donot work at all.

This should not happen by just using or installing x11docker. At least I can't imagine why.

> i think solution has to do with display server interference

The only case I could think of is that you have installed package `xorg` and Ubuntu did some startup configuration changes. Though, should not happen nonetheless.

> installing all its dependencies 

Which dependencies did you install? I ask because most of them are optional.

Sorry that I can't help more yet; I don't have a good idea how installing x11docker+some dependencies could change your system startup.

**Comment by koustubhnaik** [comment]
> Which dependencies did you install? I ask because most of them are optional.
> xpra-core,xfvb,xorg.
> Sorry that I can't help more yet; I don't have a good idea how installing x11docker+some dependencies could change your system startup.
> 
> Edit: One idea: Do you have an NVIDIA card? Maybe installing `xorg` somehow changed some driver settings.

No it doesn't have an Nvidia card but the display server after running  this command _ps -e | grep  tty7_ its displaying tty7     00:00:27 Xorg
ref:[https://unix.stackexchange.com/questions/236498/how-to-get-information-about-which-display-server-is-running/283936]

**Comment by mviereck** [comment]
With Ubuntu Mate 18.04.3 you should already have `xorg` on your system, so an `apt install xorg` would do nothing.
Installing `xpra` and `xvfb` should not do any harm.

Sorry, I really have no idea what might have damaged your system startup. Maybe you also did an `apt upgrade` and something entirely different has changed your system?

**Comment by mviereck** [comment]
One idea:
By default docker stores the images on the root partition. 

If the root partition is rather small and divided from the `/home` partition, the size of the docker images and ontainers can eat up all space on the root partition and the system becomes unbootable or just behave very strange. Maybe this happened to you.

For this reason I have a separate partition for docker images.

**Comment by koustubhnaik** [comment]
Thanks for your reply,
Working on it will let you know when I resolve it.

Regards,
Koustubh Naik.

**Comment by koustubhnaik** [comment]
Hey,
Could you also just refer me the stable version of Ubuntu where I can run
x11docker seamlessly and also without any problems you've been a great
help.
Thank you man really appreciate it.

**Comment by koustubhnaik** [comment]
After working on a couple of things i think this issue is similar to the one mentioned in the link below.
[https://bugs.launchpad.net/ubuntu/+source/gdm3/+bug/1786883]

**Comment by mviereck** [comment]
The ticket speaks of issues with gdm3 and Wayland.
If you are using Mate, you would not need either of them.
You can exchange gdm3 with another display manager, e.g. lightdm. lightdm uses Xorg only.

**Comment by koustubhnaik** [comment]
Resolved!!!

>  Maybe you also did an apt upgrade and something entirely different has changed your system?
Actually the upgrade was making some changes and so there was a error.
Sorry.
Thank you .

**Comment by mviereck** [comment]
> Resolved!!!

Great!
I am relieved that it was not an x11docker bug. ;-)
