### ISSUE TITLE
--keymap=clone is ignored

### ISSUE THREAD

**Issue by seandilda** [mviereck/x11docker#210]
I'm trying out the new --keymap=clone and it doesn't seem to be doing anything.

After digging in, I think the problem might be in https://github.com/mviereck/x11docker/commit/af7140bfe0c1a445172b0e645d71f9ffbb91d2fe  

It appears to be unsetting the Xkblayout variable if its set to clone unless $Xserver is set to "nxagent".   I think the check should be looking for "--nxagent" instead of "nxagent"

Thanks for carrying on with the keymap=clone stuff without me.  I was offline for the holidays, which is why I never responded.

**Comment by mviereck** [comment]
>  I think the check should be looking for "--nxagent" instead of "nxagent"

You are right, thanks for looking at it! Is fixed now.

**Comment by seandilda** [comment]
I just updated to master and it works great.  Thanks!
