### ISSUE TITLE
Is there something analogous to this, but for Windows containers?

### ISSUE THREAD

**Issue by philippemnoel** [mviereck/x11docker#212]
All in the title, this repo is amazing and I was wondering if there is similar work done on running GUI applications in Windows containers that can be remoted into through VNC since image windows:1809 and up can run GUI apps?

**Comment by mviereck** [comment]
Sorry, I am not aware of such a tool.
It might be technically possible, though, but is out of my scope.

As a workaround it would be possible to run Windows applications with wine in a Linux container. Some applications work well with wine, others don't.
https://github.com/mviereck/dockerfile-x11docker-lxde
https://hub.docker.com/r/x11docker/lxde-wine
