### ISSUE TITLE
Seamless mode for --xwayland?

### ISSUE THREAD

**Issue by seandilda** [mviereck/x11docker#213]
I noticed on https://github.com/mviereck/x11docker/wiki/X-server-and-Wayland-Options that --xwayland does not support seamless mode.  Would it be possible to support this?

From a high level, I notice that my normal wayland login launches Xwayland in a way that X11 apps have a seamless mode.  I'd really love it if I can get some similar working with x11docker.

Thanks for all your hard work on this project!

**Comment by mviereck** [comment]
> xwayland does not support seamless mode. Would it be possible to support this?

I'd like that very much, too.
It should be technically possible. The current Wayland compositors like Weston or Gnome 3 use a seamless Xwayland. Only x11docker uses the desktop mode / root window mode of Xwayland.
But Xwayland is poorly documented and I could not figure out how to set up the seamless mode.

The Xwayland options to set this up are:
```
-rootless              run rootless, requires wm support
-wm fd                 create X client for wm on given fd
-listen fd             add give fd as a listen socket
```

I have no idea how to set up option `-wm fd`. It seems to need some sort of file descriptor providing a connection to the Wayland compositor.
Also, the Wayland compositor would need to support more than one Xwayland session. Likely no one does.
Help from someone experienced with Wayland+Xwayland seamless mode would be highly appreciated.
