### ISSUE TITLE
RFE: Allow predefined option sets

### ISSUE THREAD

**Issue by mviereck** [mviereck/x11docker#218]
Coming from #217 

@eine wrote:
> Actually, I think this would be a nice CLI feature for x11docker:
```sh
x11docker --preset interactive_as_root IMAGE

x11docker --preset as_root IMAGE xterm

x11docker --preset interactive_as_root_port5000 IMAGE

x11docker --preset interactive_as_root -p 5000 IMAGE
```

**Comment by mviereck** [comment]
As a quick shot I've added an experimental option `--preset`. 

It expects a file name as an argument. The file should exist either in `$HOME/.config/preset` or in the current directory.
The file must contain one line only with the options you'd like to have.
Example:
```
$ cat  $HOME/.config/x11docker/preset/multimedia
--gpu --pulseaudio --webcam
```
Run e.g. `x11docker --preset multimedia x11docker/check`

**Comment by mviereck** [comment]
I've made some fixes for `--`.
A preset file like this should work:
```
-i --user 0 -- -p 5000 --
```

**Comment by eine** [comment]
> I am not entirely sure about the best location for storage of the preset files. The options are parsed before the host user is checked. `$HOME` might not be right.

Two thoughts:

- Requiring an absolute path, just as docker's volumes. `--preset $(pwd)/filename` or `--preset $HOME/.config/x11dockerpresets` is not so long compared to writing all the args.
- Allowing multiple lines per file, so that a single file is enough for most use cases.

Hence, the syntax would be `x11docker --preset /abs/path/to/file LINENUM`.

**Comment by mviereck** [comment]
I've included `--preset` as a regular option.
From `x11docker --help`:
```
     --preset FILE     Read a set of predefined options from file FILE.
                       FILE is searched in directory /etc/x11docker/preset,
                       in directory ~/.config/x11docker/preset or absolute.
                       Multiple lines in FILE are allowed. 
```
Thanks for your suggestions. 
I've decided to keep the setup with one file for each preset. That allows meaningful file names.
Using the predefined folders is possible as well as an absolute path.

Multiple lines are allowed in the preset files. Newlines are just replaced with whitespaces.
That allows a readable preset file with one option per line.
