### ISSUE TITLE
Latest firefox-esr not working at all under x11docker 6.5

### ISSUE THREAD

**Issue by jmokuzai** [mviereck/x11docker#220]
First of all, I believe firefox is doing something irregular here, because everything else seems to work. And one of firefox's command line options is --display=DISPLAY so that it is obviously designed to mess with X remoting in its own ways.

I tried all options, --gpu, --xpra, --nxagent (I have all of the auxiliary tools installed), with or without giving the container the device mount of /dev/dri, set or not set the DISPLAY parameter of firefox, and I have built essentially the same image out of both Debian and Alpine, I get nothing no matter what, not even a error message when I run it from a terminal window. 

I am out of options, according to my research, the firefox command line option --no-remote and --no-xshm is supposed to make a difference, didn't work for me, but hopefully can help you debug this. Last but not least, if I throw tightvnc inside the container and put a viewer on it, firefox works just fine, so it really comes down to firefox not liking X remoting.

**Comment by mviereck** [comment]
How did you start firefox?
In `README.md` I give this example:
```
x11docker --share $HOME/Downloads -- --tmpfs /dev/shm -- jess/firefox
```
`jess/firefox` is not ESR but the latest beta version.
Note the part `-- --tmpfs /dev/shm --` that avoids tab crashing.

> one of firefox's command line options is --display=DISPLAY so that it is obviously designed to mess with X remoting in its own ways.

This won't hurt if you don't use it.

>  the firefox command line option --no-remote and --no-xshm is supposed to make a difference,

`--no-remote` only disallows multiple firefox instances to communicate with each other. That would not hurt a container setup.
`--no-xshm` is interesting. It does not appear if I run `firefox --help`. Where did you find it?

> I have built essentially the same image out of both Debian and Alpine, I get nothing no matter what, not even a error message when I run it from a terminal window.

Can you show me your Dockerfile?

**Comment by jmokuzai** [comment]
I figured out why ... long story short .... you overrode the /etc/sudoers file within the container without me asking for it, how do I turn that feature off please?

**Comment by mviereck** [comment]
> you overrode the /etc/sudoers file within the container without me asking for it, how do I turn that feature off please?

You can set option `--user=RETAIN` to keep the container user settings (including `/etc/sudoers`). By default, x11docker sets up an unprivileged container user.

**Comment by mviereck** [comment]
Could you show me the Dockerfile, please? I'd like to know what user setup in image can cause a failure with x11docker.
