### ISSUE TITLE
Running X11 server inside a container

### ISSUE THREAD

**Issue by hoshsadiq** [mviereck/x11docker#221]
I'm curious if it is possible at all to run x11 server and client inside a container. Reason for this is that I'd like to run a pi with nothing but docker and let docker continually pull an updated fully configured image. I know I can (obviously) run server on the pi, but I'm trying to have to avoid as any moving pieces within the pi, and so all the configuration required would be inside the container. Is this possible at all? I've done a lot of searching but have come out blank.

**Comment by mviereck** [comment]
Do you want the X server to access the hardware?

If you want to use a real Monitor at your pi, you would need Xorg with hardware access. That is possible with a highly privileged container, but I discourage it. If Xorg runs in a container, it might make wrong assumptions on the connected hardware and might damage it.

An invisible X server without hardware access like Xvfb would be no problem. You could remotely access it with xpra, or even run xpra+Xvfb in a container.

A third possibility is Xwayland in container and Wayland compositor Weston on host. See https://github.com/mviereck/dockerfile-x11docker-xwayland

**Comment by hoshsadiq** [comment]
I think really you answered my question. Was hoping that it would be possible without increased privileges, so I'll try and use the ways you suggested. Thanks for your help!
