### ISSUE TITLE
Printing Issue

### ISSUE THREAD

**Issue by sjordahl** [mviereck/x11docker#222]
At present I'm using the --printer option to allow the container to print through the host.  Printing works fine when I start the container, but after some amount of time it stops working.  In digging into it I'm finding that the cups.sock socket appears to be changed by the host, thereby invalidating it in the container.

Before going further I wanted to validate that I wasn't reinventing the wheel.  My first thought is to pass the cups directory through rather than the file, which should allow the container to access the new socket, assuming it is, in fact, being changed.

**Comment by mviereck** [comment]
Thank you for the report and your investigation!

I wonder why the cups socket might change. Maybe the cups server is restarted for some reason? I see no good reason for cups to recreate the socket under normal circumstances.

I followed your suggestion, x11docker now shares entire `/run/cups`.

>  assuming it is, in fact, being changed.

Maybe you could validate this? `ls -l /run/cups/cups.sock` should show the time you've booted the system. If not, the socket has been changed meanwhile.

-------------
For the full picture yet: Another possibility is a TCP connection with `--printer=tcp`. But it needs some host configuration:
```
    note "Option --printer: Network setup for CUPS detected.
  Server address: $Cupsserver
  You may need to allow container access in /etc/cups/cupsd.conf, e.g.:

Port 631
<Location />
  # Allow remote access...
  Order allow,deny
  Allow 172.17.0.*
  Allow 127.0.0.1
</Location>"
```

**Comment by sjordahl** [comment]
Thank you for the follow-up.  Per your suggestion I took a look at the timestamp of the socket.  In my case, the container showed "Feb  9 11:21" and the host shows "Feb 15 05:08", so the service definitely restarted.  This particular system is an Ubuntu MATE instance, so Gnome 2-based which might have a legacy aspect (restarting cups) as I don't recall having this issue on my previous non-MATE install. 

I'll try the change you've committed as soon as I have time.

**Comment by sjordahl** [comment]
I've updated my x11docker to master and upon starting my container my printing is working fine.  As time progresses I'll let you know if it starts failing again.

**Comment by mviereck** [comment]
Great!
I'll close for now, I assume the issue won't appear anymore.
