### ISSUE TITLE
Is it possible on Ubuntu Server 18.04?

### ISSUE THREAD

**Issue by kawaaii** [mviereck/x11docker#223]
Dear developer(s)

I discovered x11docker today and I have been struggling with it for some hours now.
I'm trying to run `erichough/kodi` with it on Ubuntu Server, but I get this feeling that thats not working
or that I'm doing something completely wrong, since the x11 server seems to startup `xorg` but keeps crashing after some time and never showed anything beside a gray screen and my cursor.

Some additional information that I hope it might help:
- I tried installing `x11docker/openbox` and `x11docker/fvwm` and tried running those also same results, gray screen and only a cursor.
- I tried this on a fresh ubuntu server install in a VM on a different machine, same results.
- tried using Wayland instead of Xorg, same result only a blue screen.

**Comment by mviereck** [comment]
Hello,

it seems the container has a startup failure, and x11docker terminates the X server.
Can you please show me `~/.cache/x11docker/x11docker.log`? You can store it at www.pastebin.com.
Likely there is an error message near the end of the log.

**Comment by kawaaii** [comment]
Dear Mviereck.

This is a log from my virtual machine with while trying to run `x11docker erichough/kodi` without any arguments.

https://paste.ubuntu.com/p/bdyd4kwzHn/

**Comment by mviereck** [comment]
I am not entirely sure what is going wrong.
The container starts up, but seems to terminate immediately.
There is one message that does not make sense:
```
docker: Error response from daemon: error while creating mount source path '/usr/bin/docker-init': mkdir /usr/bin/docker-init: read-only file system.
```
Do you have `/usr/bin/docker-init` on your system?
Please try x11docker with option `--init=none` if that makes a difference.

**Comment by kawaaii** [comment]
Dear

Yes I do have `/usr/bin/docker-init` (https://lolisafe.kawaaii.moe/NtZAGxuv.png)
Also trying with the argument `--init=none` results the same (https://paste.ubuntu.com/p/dY8Yk7KVRk/)
Again these are the results from the virtual machine, without any other arguments beside the one you asked me to use!

**Comment by mviereck** [comment]
>  May the installation of Docker during the installation of Ubuntu Server be a problem?

that could be the reason: there has been a similar issue: https://github.com/mviereck/x11docker/issues/191
Ubuntu installed docker with snappy, not with apt. 
snappy installations run in containers, and docker in snappy behaves different.
x11docker should detect docker in snappy, but that is barely tested.

Can you show me `which docker`?
Could you try: 
```
x11docker --newprivileges --xoverip --xorg x11docker/fvwm xterm
```

**Comment by kawaaii** [comment]
Dear.

After creating another VM without ticking the Docker during installation and removing the packages `docker, docker.io, docker-engine, containered and runc` following by installing Docker with `sudo apt install docker docker.io` seems to solved the issue.

I will boot up the faulty VM in a second and do what you asked me to do!
This is the log from the working setup using `x11docker erichough/kodi` (https://paste.ubuntu.com/p/X7JkwmMk5G/)

**Comment by mviereck** [comment]
Great that you found one working setup!

Looking at the log of the faulty VM, there seems to be a snap installation of doker. I found lines containing `snap`:
``` 
                "WorkDir": "/var/snap/docker/common/var-lib-docker/overlay2/d059b72ba4b7337fa25e6688c865f30b70fa776224fdeb7844188e0615d35364/work" 
```
Do you have both `/snap/bin/docker` and `/usr/bin/docker`?
What does this show?
```
ls -l /usr/bin/docker
ls -l /usr/bin/docker-init
ls -l /snap/bin/docker
realpath /usr/bin/docker
```
In worst case Ubuntu did a mixture mess of apt and snappy.

Please try:
```
x11docker --init=none --newprivileges --xoverip --xorg x11docker/fvwm xterm
```

**Comment by kawaaii** [comment]
Dear.

Sorry for the slow reply, I was busy setting everything up since all works fine now! <3
I will try out what you asked tomorrow when I'm a bit more awake again!

**Comment by kawaaii** [comment]
Dear.

This is the outcome of the four command https://lolisafe.kawaaii.moe/UWapjRyr.png
And after running the `x11docker` command it seems to work on the faulty VM

**Comment by mviereck** [comment]
>  And after running the x11docker command it seems to work on the faulty VM

Good!

> This is the outcome of the four command

The output is confusing. It does not give a clear hint if docker runs in snap or native on the host. I am setting up a similar VM yet to reproduce the setup.

**Comment by kawaaii** [comment]
> The output is confusing. It does not give a clear hint if docker runs in snap or native on the host. I am setting up a similar VM yet to reproduce the setup.

I used VirtualBox with `Ubuntu Server 18.04 LTS`
And while doing the installation I ticked on `SSH` and `Docker`
Then I installed x11docker using the easy install method with cURL and installed Docker.io

**Comment by mviereck** [comment]
Thanks for clarification!

So you have two docker installations, one with snap (during system installation) and later an additional one with apt.
This is sort of a mess. But even then I would expect that Ubuntu starts one of them, either the snap installation or the docker installation. The first one in `PATH` should win. They should not interfere, but somehow they do.

So I'll try with only the snap installation first. If that works, I'll add the apt installation of `docker.io` and should get the faulty mess, too.

**Comment by kawaaii** [comment]
> So you have two docker installations, one with snap (during system installation) and later an additional one with apt.

Oof, I did not know that Docker and Docker.io both gave just Docker.. _feels dumb now_
I assumed Docker.io were additions to Docker such as the Docker group.

**Comment by mviereck** [comment]
> Oof, I did not know that Docker and Docker.io both gave just Docker.. feels dumb now
I assumed Docker.io were additions to Docker such as the Docker group.

:D 
During the system installation it is not that obvious that there is a different sort of package installation. The installer could as well provide apt packages.
Overall I prefer docker installed with apt. The snap installation has some limitations.

I did some fixes in x11docker. Now it works with the snappy installation as well as with the additionally apt installation.

Thank you for the report and the tests!
