### ISSUE TITLE
running same image multiple times [Xwayland/Gnome issue?]

### ISSUE THREAD

**Issue by mortezaPRK** [mviereck/x11docker#226]
Hi. I have a problem launching multiple instance of an image.
when I run first image, and then running the second one, x11docker  re opens first one.

this is my commands:
```shell
alias ff_work='x11docker --name firefoxwork -q --hostdisplay --clipboard --home=$HOME/x11docker/firefox_work --share $HOME/Downloads -- -- jess/firefox:latest'
alias ff_app='x11docker --name firefoxapp -q --hostdisplay --clipboard --home=$HOME/x11docker/firefox_app --share $HOME/Downloads -- -- jess/firefox:latest'
```

so, when I run `ff_work` and then `ff_app` I will get two firefox which are same
whats the problem here?

**Comment by mviereck** [comment]
This is specific to firefox. On startup it tries to find already running instances and opens a new window in an already running firefox.

In your commands you use option `--hostdisplay` that degrades container isolation. Using the X11 protocol the second firefox detects the first one and sends it a signal to open a new window.

You have two possibilities:
 - Either use another x11docker X server option, e.g. `--nxagent` to have an isolated X server.
 - Or use firefox option `--new-instance`.

**Comment by mortezaPRK** [comment]
thanks. I'm using `--new-instance` for now since using `--nxagent` will mess up my system. can't open any application with gnome and I have to restart my system. this is the log with `journalctl`:

```
Feb 20 17:50:28 prk dbus-daemon[2078]: [session uid=1000 pid=2078] Activating service name='org.gnome.ControlCenter.SearchProvider' requested by ':1.17' (uid=1000 pid=2161 comm="/usr/bin/gnome-shell ")
Feb 20 17:50:28 prk dbus-daemon[2078]: [session uid=1000 pid=2078] Activating service name='org.gnome.Calculator.SearchProvider' requested by ':1.17' (uid=1000 pid=2161 comm="/usr/bin/gnome-shell ")
Feb 20 17:50:28 prk dbus-daemon[2078]: [session uid=1000 pid=2078] Successfully activated service 'org.gnome.Calculator.SearchProvider'
Feb 20 17:50:28 prk dbus-daemon[2078]: [session uid=1000 pid=2078] Successfully activated service 'org.gnome.ControlCenter.SearchProvider'
Feb 20 17:50:28 prk gnome-control-c[12634]: cannot open display: :104
Feb 20 17:50:28 prk gnome-shell[2161]: Received error from DBus search provider gnome-control-center.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Feb 20 17:50:28 prk dbus-daemon[2078]: [session uid=1000 pid=2078] Activating service name='org.gnome.Nautilus' requested by ':1.17' (uid=1000 pid=2161 comm="/usr/bin/gnome-shell ")
Feb 20 17:50:28 prk dbus-daemon[2078]: [session uid=1000 pid=2078] Successfully activated service 'org.gnome.Nautilus'
Feb 20 17:50:28 prk nautilus[12656]: cannot open display: :104
```

**Comment by mviereck** [comment]
> I'm using --new-instance for now since using --nxagent will mess up my system. can't open any application with gnome and I have to restart my system. 

That is very odd. nxagent just runs as a client application, and only child processes of x11docker should use the new display.
Why would gnome-control-center or nautilus try to run on nxagent / display :104? I can only assume that they do some detection of running X servers and automatically choose the wrong one.

Can you tell me something about your system? Which OS, which Gnome version, which nxagent version?

Could you please try another X server option, e.g. `--xephyr`, if it has the same symptoms?

**Comment by mortezaPRK** [comment]
I didn't install `nxagent` in my new system. maybe this is the problem!
some info about my system:
```shell
:~$ gnome-shell --version
GNOME Shell 3.30.2
:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by mviereck** [comment]
> I didn't install nxagent in my new system. maybe this is the problem!

Maybe somehow related; x11docker uses fallbacks if a chosen option is not possible. I just imagine that you run Gnome-Wayland and x11docker used Xwayland as a fallback, and that somehow caused confusion for Gnome applications.

Could you provide me the logfile `~/.cache/x11docker/x11docker.log` at www.pastebin.com? Maybe I find some hints.
