### ISSUE TITLE
Is it save to run x11docker as root(sudo) ?

### ISSUE THREAD

**Issue by elovin** [mviereck/x11docker#228]
On gentoo I had problems when running the xserver without root, I can start x11docker but only from another tty and when switching between them my default xserver crashed (kde plasma).

Running x11docker with sudo e.g. as root works however just fine, now Im wondering
if its a good idea to run x11docker with sudo ?

**Comment by mviereck** [comment]
x11docker is designed to be safe if running it as root.
In fact, I consider it to be more safe than adding an unprivileged user to group `docker`.

Internally, x11docker  runs a lot of commands as unprivileged user with function `unpriv()`. It gets the unprivileged user from command `logname`.

>  when switching between them my default xserver crashed (kde plasma).

I've seen this crashes on Debian, too. x11docker shows a warning and recommends to switch to an unused tty before switching to X. Good to know it happens on other systems, too. Likely it is an Xorg bug. (Race condition in releasing/grabbing hardware access).

> Running x11docker with sudo e.g. as root works however just fine

The Xorg bug does not happen if you run as root? That would be interesting news!

**Comment by elovin** [comment]
> The Xorg bug does not happen if you run as root?
No sorry thats not what I meant, I can run x11docker as an unprivileged user only from another unused tty. When Im trying to run it from a terminal from my plasma session (on tty 1) I cant run it without using sudo.
