### ISSUE TITLE
how to run multiple identical html xpra sessions?

### ISSUE THREAD

**Issue by twyeld** [mviereck/x11docker#231]
How to run multiple identical html=on xpra sessions on different machines porting the same image/container - ie multiple users with single image - currently can only run one html browser session at a time...

**Comment by mviereck** [comment]
Please clarify if you want to share the same container or the same image.
If you want to share the same container, i.e. running one instance only, but access the same instance from different machines, xpra has an option `--sharing`. From `man xpra`:
```
--sharing=yes|no|auto
              Sharing allows more than one client to connect to the same session.  This must be enabled on both the server and all  co-operating  clients  to  function.
              When  used  server-side, the default value auto allows the clients to decide if they are willing to share the session.  When used client-side, the default
              value auto evaluates to no.  To allow sharing to work with unix domain sockets (either using local connections or via ssh), you should create at least one
              socket  in  a  group  accessible directory. On Posix with a default configuration, being a member of the xpra group should be enough to create a socket in
              /run/xpra. You must also ensure that the permissions of this socket file allow group access, see socket-permissions.
```

If you want to run multiple containers, but only can access one of them (the first one?), we need to somehow specify the desired xpra server you want to attach to, maybe with different port numbers or X display numbers.

**Comment by twyeld** [comment]
apologies for confusion - yes, sharing a single container instance by multiple users.

I also got a bit confused with the shadow flag - thinking that would allow sharing...

will try the --sharing=yes flag

**Comment by mviereck** [comment]
> oh yay! that worked!

Great!

**Comment by innerop** [comment]
Hi @mviereck 

New to Xrpa/X11Docker. 

Does this mean the users can share the same keyboard and mouse? How does that work? What about webcams? Does each user get an instance of the app or they all share the same instance? I think separate instances, right?

**Comment by twyeld** [comment]
It's been a long time since I explored this, but yes, each screen port is interactive - so, I suppose you can share mouse and keyboard input - would cause some conflicts though?
