### ISSUE TITLE
--share flag documentation

### ISSUE THREAD

**Issue by Blunderchips** [mviereck/x11docker#233]
I am having trouble using the `--share`. Is there any other documentation/examples other than the README.

For context, I would like to generate a PDF within the container and have it outputted to the host.

**Comment by mviereck** [comment]
Other documentation (but not more) is in `x11docker --help`:
```
Shared folders:
 -m, --home [=DIR]     Share a host folder as home folder in container to store
                       persistent data. Uses ~/.local/share/x11docker/IMAGENAME.
                       Optionally specify another host folder DIR.
                       ( ~/.local/share/x11docker has a softlink to ~/x11docker.
                        Use --homebasedir to change the base storage folder.)
     --share PATH      Share host file or folder PATH. Read-only with PATH:ro
                       Device files in /dev can be shared, too.
```
You can create a folder on host, e.g. `mkdir /tmp/myshare`. Run x11docker with `--share /tmp/myshare`. If you store a file in this folder, it is accessible from host and from container. If you generate a pdf in container and store it in this folder, you can access it from host.

**Comment by eine** [comment]
@Blunderchips, alternatively, you can use regular docker arguments, along with x11docker. For example: `x11docker --runx --no-auth -- -v $(pwd):/src -- x11docker/xfce xfce4-terminal`.
