### ISSUE TITLE
x11docker hello-world fails with: OCI runtime create failed ... "exec: \"env\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by GorillaCoder** [mviereck/x11docker#235]
Thanks much for any help you can give!

_docker hello-world_ works fine.

x11docker version is 6.6.0. Having just installed it, I believe it's the most recent stable release.
command: _x11docker --verbose --debug hello-world_
I've followed the troubleshooting steps.

The issue seems to be that the directory ~/.cache/x11docker/hello-world-ID exists for a bit, and then doesn't:

x11docker.log attached.

> ...
> ==> /home/giuliano/.cache/x11docker/hello-world-70793703444/message.log <==
> DEBUGNOTE[23:06:35,912]: xinitrc: Created cookie: conservatory/unix:1  MIT-MAGIC-COOKIE-1  8b57213328bf31ca229d406dbf4128f6
> #ffff#636f6e7365727661746f7279#:1  MIT-MAGIC-COOKIE-1  8b57213328bf31ca229d406dbf4128f6
> 
> ==> /home/giuliano/.cache/x11docker/hello-world-70793703444/xinit.log <==
> xinitrc: xinitrc is ready
> 
> ...
> 
> DEBUGNOTE[23:06:36,147]: storeinfo(): xinitrc=ready
> DEBUGNOTE[23:06:36,287]: waitforlogentry(): dockerrc: Found log entry "xinitrc is ready" in xinit.log.
> 
> ==> /home/giuliano/.cache/x11docker/hello-world-70793703444/share/container.log <==
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"env\": executable file not found in $PATH": unknown.
> 
> ==> /home/giuliano/.cache/x11docker/hello-world-70793703444/message.log <==
> DEBUGNOTE[23:06:36,791]: storeinfo(): containerid=2859c2ea9235efcbb30b919458f0bacdabb3b1e14fd01c5541b7b0ada01a4fa1
> 
> ==> /home/giuliano/.cache/x11docker/hello-world-70793703444/share/container.log <==
> Error: No such container: x11docker_X1_hello-world_70793703444
> 

[x11docker.log](https://github.com/mviereck/x11docker/files/4362505/x11docker.log)

**Comment by GorillaCoder** [comment]
Okay, weird:
- x11docker/check works when run the first time.
- x11docker (via docker I suppose) had to download it, and then x11docker/check ran fine.
- Ran it a second time, and got the OCI error.
- Removed containers and images using  _docker system prune -a_ and verified no containers running using _docker ps_.
- Ran x11docker/check and it worked. Exited, ran it again, it worked. Tried a few more times and it continued to work.
- So I tried _x11docker hello-world_, docker had to download the image, and it failed as above.

**Comment by GorillaCoder** [comment]
The below all download the appropriate image and work fine. But hello-world downloads image, and fails.
- _x11docker patricknw/xaos_
- _x11docker --gpu x11docker/xfce glxgears_
- _x11docker --pulseaudio --share=$HOME/Videos jess/vlc_

**Comment by mviereck** [comment]
Thank you for the report!

I can confirm the issue.
Basically the reason is clear: x11docker does some setup in container and uses some common POSIX commands. However, the `hello-world` image is minimalist in a way that it has nearly no commands at all. The command `env` is just the first one that fails fatally.

I am not sure how to fix this, and if I should fix it at all.
Pro fix: support minimalist images, save resources.
Contra: core x11docker features like container user setup fail.

Let me think about this.

**Comment by GorillaCoder** [comment]
Do you need to use _env_? Just about everything I've used it for can be done other ways. In any case, not a big deal really. x11docker/check is probably a better "hello world" anyhow.

**Comment by eine** [comment]
@mviereck, IMHO x11docker should expect the set of common tools/resources that should be available in any container where a GUI app is to be executed. AFAIK, `hello-world` does not fulfill that. This is to say that `hello-world` feels like a synthetic and corner case to test x11docker. There are many other images where static apps are contained in `scratch`, but I believe that none of them is to be used for GUIs. Probably, if any GUI app is installed in a `hello-world` image, `env` will be a dependency.

So, I'm good with supporting minimalist images, but not too minimal.

**Comment by GorillaCoder** [comment]
Thanks much for looking into this.

**Comment by mviereck** [comment]
I had a look which commands are executed by x11docker in container:
`mkdir chmod ln ls cp [ grep cut echo cat sed rm mv id chown rev env sh su read sleep ldd sort uniq tr printf nl basename`.

A few of them could be dropped or allowed to fail, but the majority is important, most of them for container user setup.

I consider to include a dependency check at container startup to error out if an important command is missing.

`env` is special because x11docker uses it to overwrite a possible `ENTRYPOINT` in container with docker option `--entrypoint env`.

**Comment by GorillaCoder** [comment]
Thanks again for looking into it. Maybe just drop hello world from the x11docker gui and the doc? It's presence there was the only reason I tried it.

**Comment by mviereck** [comment]
> Maybe just drop hello world from the x11docker gui and the doc? It's presence there was the only reason I tried it.

?? hello-world is not part of the x11docker documentation. Where did you find this? 

Currently I try an experimental option that causes x11docker to do no setup in container at all. That will disallow some features and some applications won't work anymore, but will allow minimalistic images.

**Comment by GorillaCoder** [comment]
And, I must have been hallucinating ;-> I can find no evidence for it in either the doc, or x11docker-gui. Don't know what inspired me to try hello-world. Probably just a hold over from walking through the docker tutorial, and thinking it was the first baby step? In any case, apologies for not checking before saying that.

**Comment by mviereck** [comment]
I've added an experimental option `--no-setup` that avoids all x11docker setup done in container. This allows to run images with missing core dependencies.
However, this needs further testing and breaks a lot of x11docker features. At least every broken feature needs its own message.

This option is not ready yet. Currently I focus on other projects; not sure when I will work further on `--no-setup`.

**Comment by mviereck** [comment]
Follow-up of experimental option `--no-setup` in #286.
