### ISSUE TITLE
Printing - Revisited

### ISSUE THREAD

**Issue by sjordahl** [mviereck/x11docker#240]
It appears that the changes from [issue 222](https://github.com/mviereck/x11docker/issues/222) have been reverted.  The latest version of x11docker (even master) appears to pass the cups socket rather than the directory. The system I was running in issue 222 was Ubuntu Mate which uses Gnome 2, so I wasn't sure if it was an Ubuntu issue or a legacy Gnome 2 issue.  Now I've got Ubuntu Budgie 18.04.4 running and installed the latest x11docker only to find the printing issue crop up again.  I ditched the --printer option and shared the /run/cups directory and printing appears to be fine again.

To add some color, I run Chrome in a container that is up for days/weeks/months at a time, which is an atypical use case.  When passing the socket I am able to print at the beginning, but at some point later CUPS changes the socket and stops my ability to print from the container.  It could be from a system package update or some other CUPS event -- not sure of root cause.

**Comment by mviereck** [comment]
i did not revert the change. However, there is a check whether the socket is in `/run/cups` before x11docker shares `/run/cups`. (Just fixed an issue there, but if that affected you, printig should have failed at all).

Is your cups socket at a different location? Or in a subfolder?
Please show me `lpstat -H` and the docker command seen with option `--debug`.
`lpstat -H` should show the socket in `/run/cups`.

**Comment by mviereck** [comment]
I did a check with these variations:
```
x11docker --printer x11docker/check
x11docker --printer=tcp x11docker/check
```
Both x11docker/check succeeded.

I stopped cups with `systemctl stop cups`
Both already running x11docker/check showed a failure.

I restarted cups with `systemctl start cups`
Both already running x11docker/check worked again.

**Comment by sjordahl** [comment]
I must have had a version < 6.6.1 installed when I started this process.  I began this thread when I grepped "docker container inspect" for cups and got "/run/cups/cups.sock:/run/cups/cups.sock:rw" as part of the output.  Since then I've updated between master (6.6.2-beta) and release (6.6.1) and as of today both versions output the following on the same grep:
                "/run/cups:/run/cups:rw"
                "Source": "/run/cups",
                "Destination": "/run/cups",
                "CUPS_SERVER=/run/cups/cups.sock",
So it appears I have a non-issue.

To be thorough, here's the output you requested:
$ lpstat -H
/run/cups/cups.sock

When I try to run with --debug I get the following error, which is the same between versions but at a different line in code:
$ x11docker --hostdisplay \
           --gpu \
           --clipboard \
           --pulseaudio \
	   --home \
           --printer \
           --debug \
           -- \
           --security-opt seccomp=$HOME/workspace/docker/chrome/chrome.json \
           --cpuset-cpus 1,2,3,5,6,7 \
           --memory 8g \
           -- \
           steve/chrome:latest $@

6.6.2-beta
/usr/bin/x11docker: line 6946: Runsinspap: unbound variable
DEBUGNOTE[11:37:40,188]: Terminating x11docker.
DEBUGNOTE[11:37:40,191]: time to say goodbye (finish)
DEBUGNOTE[11:37:40,195]: traperror: Command at Line 516 returned with error code 1:
  [ "$Runsinspap" = "yes" ]
  1 - ::finish::main
DEBUGNOTE[11:37:40,199]: storeinfo(): error=64
DEBUGNOTE[11:37:40,204]: time to say goodbye (traperror)
DEBUGNOTE[11:37:40,214]: x11docker exit code: 64

6.6.1
/usr/bin/x11docker: line 6920: Runsinspap: unbound variable
DEBUGNOTE[11:46:12,047]: Terminating x11docker.
DEBUGNOTE[11:46:12,050]: time to say goodbye (finish)
DEBUGNOTE[11:46:12,055]: traperror: Command at Line 516 returned with error code 1:
  [ "$Runsinspap" = "yes" ]
  1 - ::finish::main
DEBUGNOTE[11:46:12,058]: storeinfo(): error=64
DEBUGNOTE[11:46:12,063]: time to say goodbye (traperror)
DEBUGNOTE[11:46:12,073]: x11docker exit code: 64

Thanks for the assist though.  Very much appreciated!  Hope you're staying well in these crazy times.

**Comment by mviereck** [comment]
>  /usr/bin/x11docker: line 6946: Runsinspap: unbound variable

Fixed, thanks!

>  So it appears I have a non-issue.

:-) Nonetheless, this ticket helped to fix two minor bugs before they caused an issue.

> Thanks for the assist though. Very much appreciated! 

You're welcome! Always happy to hear from you.

> Hope you're staying well in these crazy times.

Yes, crazy times. Germany is lucky so far, but USA gets a hard hit. "Bleiben Sie gesund" ("stay healthy"), we say here.
