### ISSUE TITLE
webcam: group "video" is not x11docker default

### ISSUE THREAD

**Issue by mdhooge** [mviereck/x11docker#241]
Hello,

On my up-to-date Archlinux with x11docker 6.6.1, I don't have access to the /dev/video* files in the guests (e.g. it doesn't work with x11docker/check).
As _expected_, the /dev/video* files are owned by group _video_; but my host user doesn't belong to that group. Maybe this is Archlinux specific, but according to the Wiki, this is udev that does the magic!

In the x11docker source, function `setup_webcam` has the following comment:
`Unprivileged users need to be in group video (x11docker default).`
But this is not the case with my configuration…

If I put the following line just below the comment, then everything is fine (check & cheese images tested so far).
`Containerusergroups="$Containerusergroups video"`

I searched through the source, only the `--gpu` option adds this group to the user list.

HTH
M.

**Comment by mviereck** [comment]
Thank you for the report and the detailed investigation!
Is fixed now in master branch with exactly your suggestion.

Once x11docker always added the user to group video, later I decided to do that only if needed (with `--gpu`). But I forgot to adjust `--webcam`, too.
