### ISSUE TITLE
x11docker on Mac Mojave

### ISSUE THREAD

**Issue by ablack-jpl** [mviereck/x11docker#242]
I realize that there isn't a Mac install section, so this probably isn't officially supported. But it would be nice, and given the small dependency list it doesn't seem like a stretch to add it. Initial attempts to just use it out of the box ran into this error:

`x11docker: line 8394: exec: {FDstderr}: not found`

Suggests a change to how FDstderr is assigned is all that it would really take. I'm just not sure on how exec is making that assignment and don't have a replacement suggestion.

**Comment by mviereck** [comment]
There are no plans to add macOS support. Another related ticke t is #239.

The main issue is to keep compatibility across several systems, and commands on macOS differ in several details.
A separate fork that breaks compatibility is likely not too hard. But I would not maintain that myself.


On Linux `exec {FDstderr}>&2` automatically assigns a free file descriptor and stores it in `$FDstderr`. Though, this is just the first error, many others will follow up.

**Comment by ablack-jpl** [comment]
Thanks for the quick reply.

Didn't see that issue in my search, sorry to have opened a new one :-(.
