### ISSUE TITLE
Vulcan support

### ISSUE THREAD

**Issue by JuniorJPDJ** [mviereck/x11docker#246]
Hi,
I set up steam container to play but it complains for lack of vulcan support (not necessary to work, but seen it in log).
Readme also doesn't say anything about it so I guess it's missing.
I'm using [this container](https://gitlab.com/jD91mZM2/docker-steam/), it uses --gpu and --hostdisplay

**Comment by mviereck** [comment]
The image installs the mesa drivers with:
```
RUN apt-get install -y libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libc6:i386
```
It might help to install `mesa-vulkan-drivers`, too.

In my own images I just install `mesa-utils` `mesa-utils-extra` to get all free mesa drivers. Though, I am not sure yet if the vulkan driver package is  in this dependency chain, too.
For some video decoding support it helps to install `libxv1` `va-driver-all`, too.

So I recommend to replace the line above with:
```
RUN apt-get install -y mesa-utils:i386 mesa-utils-extra:i386 libxv1:i386 va-driver-all:i386
```
If the vulkan driver is still missing, add `mesa-vulkan-drivers:i386`.

**Comment by JuniorJPDJ** [comment]
So basicly - x11docker itself has vulcan support?

**Comment by mviereck** [comment]
I am not aware that there would be something special about Vulkan that x11docker would have to support.
With the open MESA drivers in general  (AMD, intel etc.)it is enough to have the drivers on host and in image and to share the files in `/dev/dri`. That's all.

**Comment by mviereck** [comment]
@JuniorJPDJ  Did this work for you? 
Is installing `mesa-utils mesa-utils-extra` enough to get the vulkan driver?

**Comment by JuniorJPDJ** [comment]
I opened issue in upstream container, I'll let you know if it worked.
I don't have time to debug it at my own ;/

**Comment by mviereck** [comment]
Closing for now. Feel free to comment again if something comes up.
