### ISSUE TITLE
Possible to run multiple desktops on different tty?

### ISSUE THREAD

**Issue by Norcoen** [mviereck/x11docker#247]
I am using my private notebook for work and at work I have some customers with rather messy environment setups

So I want to stop polluting my system with all those different software stacks (and most off all, I dont want 30 windows with hundreds of tabs whenever I start my (private) firefox)

My idea is to have multiple instances of Debian 10 running in containers (while the host is also Debian 10, but remaining minimalistic) and being able to switch between them in different tty's with CTRL+ALT+Fn

F7=Debian Host System
F8=Private
F1=Work1
F2=Work2
F3=Work3
...

Those dont need to be running all at the same time, but maybe in special cases all of them will be active while I'm jumping between customer tasks

I have a HP zbook G3 where all external displays are hardwired to the nvidia M2000M, so I use nouveau and reverse PRIME, if that makes any difference for the setup

I hope you can provide me some guidance on how or if this is possible

**Comment by mviereck** [comment]
Yes, in general that is possible.

There are some limitations for desktops in a container. Compare https://github.com/mviereck/x11docker/issues/245 where some of those issues are discussed.
For example, hot plugging USB devices does not work ootb and need some setup on the host. Please have a look at that thread if something affects you.

On important point: For unknown reasons Xorg can crash if you switch tty between two or more Xorg instances. It seems to be a race condition in releasing/controlling devices used by Xorg (likely the video card). 
Workaround: Always switch to a black tty first before switching to an Xorg session.

> I hope you can provide me some guidance on how or if this is possible

Switch to the desired tty and run e.g.
```
x11docker --desktop --gpu --xorg --home=/customerdata/customername -- x11docker/xfce
```
You might find option `--preset` useful to collect some often used options. https://github.com/mviereck/x11docker#option---preset

> I have a HP zbook G3 where all external displays are hardwired to the nvidia M2000M, so I use nouveau and reverse PRIME, if that makes any difference for the setup

I am not sure about a reverse PRIME setup. However, `nouveau` is well supported and likely works ootb with option `--gpu`.

**Comment by Norcoen** [comment]
wow, this is pure gold

> x11docker --desktop --gpu --xorg --home=/customerdata/customername -- x11docker/xfce

thank you for your fast replay, I tested it yesterday and ... it just worked!
I played around with LXC for about a year without any success and now I just find your project covering 99% of what I need... although I need to read up on docker now 

thank you so much again
