### ISSUE TITLE
sway container x server client window

### ISSUE THREAD

**Issue by cherusk** [mviereck/x11docker#252]
Wondering, is there a straightforward way to set the specific of the clienting window to the cotainer bound  x-server. The defaults are not very helpful.

```
               "window_properties": {
                 **"class": "Xephyr",
                 "instance": "Xephyr",
                 "title": "Xephyr on :114.0 (ctrl+shift grabs mouse and keyboard)",**
                 "transient_for": null
               },
```
That's necessary to identify it conveniently in further sway handling.

**Comment by mviereck** [comment]
Currently x11docker does not set any window properties. In fact, it does not even know which window is opened by Xephyr (or another X server) . 

If it especially about Xephyr, you could use x11docker option `--display` to set a custom display number and than look for the window title. Though, this attempt fails with other X servers, and you would have to take care that the display number is not already in use.

Would it help you to know the pid of the X server?

**Comment by cherusk** [comment]
> Currently x11docker does not set any window properties. In fact, it does not even know which window is opened by Xephyr (or another X server) .

Because it cannot or you don't want it to? What about these xinitrc and xpra config generation, wouldn't that be a channel?

> Or the other way around, you can get the display number in use with x11docker option `--showenv`.
 
Hmm.

> Would it help you to know the pid of the X server?
Well, it'd be unique, but still find it hackish.

As there also other sway integration shortcomings via this "x-server window" (no auto-size detection), I might better went the net based clienting way.

**Comment by cherusk** [comment]
**xdotool** seems to be the way if one wanted to do it in hindsight.

**Comment by mviereck** [comment]
> Because it cannot or you don't want it to? 

It was never needed.


> xdotool seems to be the way if one wanted to do it in hindsight.

I had a first look. `xdotool` and `xprop` can be useful here. For example, x11docker can set the pid in `_NET_WM_PID` (some X servers don't) or a meaningful string in property `WM_CLASS`.

However, there is still the problem to reliably find the right window.
x11docker is in the same position as a user here: An application (here Xephyr) opens a window. x11docker has to find out itself what window this might be.
x11docker could check for the window title that likely appears. But that is just some good guess, not a reliable way to go.

> there also other sway integration shortcomings via this "x-server window" (no auto-size detection)

`--nxagent` provides a resizeable window.

**Comment by cherusk** [comment]
> 
> > xdotool seems to be the way if one wanted to do it in hindsight.
> 
> I had a first look. `xdotool` and `xprop` can be useful here. For example, x11docker can set the pid in `_NET_WM_PID` (some X servers don't) or a meaningful string in property `WM_CLASS`.
> 
> However, there is still the problem to reliably find the right window.
> x11docker is in the same position as a user here: An application (here Xephyr) opens a window. x11docker has to find out itself what window this might be.
> x11docker could check for the window title that likely appears. But that is just some good guess, not a reliable way to go.
> 

Anyhow, sensing that must be simpler. If not, it's skewed anyhow and vnc clienting is more elegant, there I can set all specifics.

> > there also other sway integration shortcomings via this "x-server window" (no auto-size detection)
> 
> `--nxagent` provides a resizeable window.

No, failed short equally. Not complaining, only informing you.

Cannot hold you liable for anything further, thanks for your effort @mviereck .
