### ISSUE TITLE
usbip to share USB devices

### ISSUE THREAD

**Issue by mviereck** [mviereck/x11docker#253]
Coming from #251 

@eine wrote:
> > Support for external Hardware (USB Sticks) is difficult. Compare ticket #245.

> As an alternative, USBIP is a kernel module. I have successfully used it on Docker Desktop for Windows, in order to share arbitrary USB devices. Unfortunately, I found no open source client for Windows. See https://github.com/ghdl/docker/tree/master/usbip#readme

**Comment by mviereck** [comment]
A very interting hint, thank you!
Debian provides a package `usbip`, I'll try it out.

**Comment by Intensity** [comment]
@mviereck : It looks like https://www.virtualhere.com/ wraps the functionality of USB forwarding while on Linux still using the standard `usbip` modules. The following may be a helpful reference: https://github.com/hdl/containers/blob/main/usbip/run.sh

**Comment by mviereck** [comment]
Thank you for the hint!
But `virtualhere` seems to be closed source and commercial software, so x11docker won't use it.

**Comment by mviereck** [comment]
I am not sure if I will ever implement this because I did not since, and no urgent need appeared meanwhile.
For now I'll close the ticket, but keep the possibility in mind.
