### ISSUE TITLE
Output logs in docker logs

### ISSUE THREAD

**Issue by hoshsadiq** [mviereck/x11docker#254]
Is there a way to get the `docker logs` command to behave as expected when using `docker logs` with other containers?

Specifically, I'm trying to run [Kodi](https://github.com/ehough/docker-kodi), which currently doesn't output anything to stdout, meaning running `docker logs` will result in no logs. I'm trying to address this by forcing the output of Kodi's real logs into `/dev/stdout` (see below). This causes the logs to come up when running the `x11docker` command, but not when running `docker logs`. In general Docker picks up all output to `stdout` and `stderr` and outputs that when running `docker logs`.

The code snippet is as follows. This is run just before running Kodi in the `entry-point.sh`.

```
tail -F "$HOME/.kodi/temp/kodi.log" &

exec 1<&-
exec 2<&-
exec 1>>/dev/stdout
exec 2>/dev/stdout
```

**Comment by mviereck** [comment]
I can confirm that `docker logs` gives no output. x11docker does a lot of redirection to grab container output, so `docker logs` does not get it.
I'll have a look how to improve this.

**Comment by mviereck** [comment]
I did some changes that allow `docker logs` to show the container output.
The changes need some further tests, e.g. on MS Windows, but basically it should work.
Please try out and report issues if something comes up.
