### ISSUE TITLE
Share IPC namespace of X server and container to allow MIT-SHM

### ISSUE THREAD

**Issue by mviereck** [mviereck/x11docker#257]
Currently x11docker disables X extension `MIT-SHM` that would allow shared memory between X and its clients.
This can cause some performance loss.

Antoine suggested some possible solutions: https://xpra.org/trac/ticket/2647 (Now https://github.com/Xpra-org/xpra/issues/2647)

With the help of `nsenter` it might work to run e.g. `Xvfb` in the same IPC namespace as the container. In that case x11docker could allow `MIT-SHM` and might get a slight performance boost especially with option `--xpra`.

**Comment by matu3ba** [comment]
Does this mean that this option "--hostipc sets docker run option --ipc=host. Allows MIT-SHM / shared memory. Disables IPC namespacing." does not work currently or only not with xpra?

From your experience: Could this be the cause for 3-4% CPU usage on idle, when using xpra on top of x11?

**Comment by mviereck** [comment]
If you set option `--hostipc` then `MIT-SHM` is enabled. However, using `--hostipc` is discouraged because it degrades container isolation.

> From your experience: Could this be the cause for 3-4% CPU usage on idle, when using xpra on top of x11?

I am not sure. You could just try out with and without `--hostipc` and look if it makes a noteable difference.
As long as there is no application or window action and no interaction of you, xpra should be close to idle.

**Comment by mviereck** [comment]
I did a check here, xpra is at about 0,3% CPU usage if idle, next to many other background processes.
This doesn't seem to be unusual.
Which xpra version do you use? Here it is `xpra v4.1-r27063`

**Comment by matu3ba** [comment]
@mviereck xpra v3.0.9-r26127 from Endeavour repo. That might explain alot.

**Comment by mviereck** [comment]
Some first tests with `nsenter` show that it is possible to share the same ipc namespace froma container with Xvfb from host. Unfortunately `nsenter` needs root privileges that might or might not be available.
An alternative would be Xvfb in container and sharing its ipc namespace with the desired container. Either through an image or somehow dynamically created with resources from host.
I am not sure if this is worth the effort. Maybe I should do some performance tests if MIT-SHM makes a significant difference.

**Comment by mviereck** [comment]
Recent beta/master introduces new options to run some X servers in containers of image x11docker/xserver.

This allows to share IPC namespace of X server container with the targeted GUI container.
This in turn allows MIT-SHM.

Current options are `--xpra-c`, `--xpra-c2`, `--xephyr-c`, `--xvfb-c`.

`--xpra-c2` runs xpra server in container, but xpra client on host. The other options run entirely in container.

The setup consists of three parts:
 - Host with Xorg (or Wayland)
 - Container with X server
 - Container with GUI

A possible issue remains: IPC namespace is not shared with host Xorg to preserve container isolation. This might cause MIT-SHM issues of Xephyr or xpra client. Though, in current test runs no graphical glitches nor error messages has been seen.

@totaam  Does the xpra client use MIT-SHM to communicate with the X server it appears on? Can this be influenced with environment variable `XPRA_SHM`?

**Comment by totaam** [comment]
> Does the xpra client use MIT-SHM to communicate with the X server it appears on?

xpra uses GTK to mediate most of the communications with the client's display (ie: X11 server).  
I believe that GTK falls back gracefully and silently when `MIT-SHM` is not available, painting windows will be much slower but it will still work.  

This should not matter when the client uses OpenGL acceleration: https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Client-OpenGL.md since this will use a different mechanism for uploading texture data to the GPU.
But, with the default `opengl=auto` mode, xpra doesn't use OpenGL for all windows (ie: transient windows, etc) so those will remain slow.
You could override some of these checks, ie: `XPRA_NO_OPENGL_WINDOW_TYPES=""` but there are other cases:
https://github.com/Xpra-org/xpra/blob/aa8f907e1486928d285eb1f4f3569e99416d6211/xpra/client/gtk_base/gtk_client_base.py#L1274-L1310

> Can this be influenced with environment variable XPRA_SHM?

No.
That's a server side option.
