### ISSUE TITLE
GPU acceleration over VNC not working

### ISSUE THREAD

**Issue by Kaprog** [mviereck/x11docker#259]
Hi,
I would like to run GPU accelerated docker container over VNC. To do it I use these commands (mainly from x11docker wiki):

`read Xenv < <(x11docker --xvfb --display=31 -cpg --user=RETAIN -- jess/chromium --no-sandbox)`

`env $Xenv x11vnc -noshm -forever -localhost -rfbport 5910`

`novnc --listen 6081 --vnc localhost:5910`

I have to run each commend from another terminal. After running noVNC server and connecting via web browser on host I should see only Chromium window, but I have got exact copy of host screen. I can interact host desktop from web browser and there is no Chromium window:
![screenshot](https://user-images.githubusercontent.com/32985819/84595012-f5f2ba80-ae55-11ea-97d8-1aeadb83d934.png)

Whole situation changes when I remove `--gpu` option from the first commend (so `-cpg` will be `-cp`). Now everything is ok,  I can see only Chromium window in web browser, but I don't have GPU acceleration that I need. I also tried replacing `--xvfb` with `--xdummy` without success.

I am using Ubuntu 20.04. docker 19.03.11 and x11docker 6.6.2.

**Comment by mviereck** [comment]
Please have a look at the x11docker messages and show them here.

Neither `--xvfb` nor `--xdummy` support GPU acceleration.
You should see a message about that and which fallback x11docker uses instead.
Compare https://github.com/mviereck/x11docker/wiki/X-server-and-Wayland-Options#description.

Maybe your `--gpu` setup falls back to `--hostdisplay` and causes the mess in your first screenshot.

Remote setups with `--gpu` are not easy. Compare e.g. https://github.com/mviereck/x11docker/issues/197

**Comment by Kaprog** [comment]
Thank You for quick response. That's output after running first commend (after this log comes chromium's logs and terminal is inactive and that is interesting thing. Without `--gpu` option after chromium's logs I can normally interact with terminal. Looks like x11docker can't switch into daemon mode):
![screenshot](https://user-images.githubusercontent.com/32985819/84596380-c051cf80-ae5d-11ea-980a-fc7b6b8d3980.png)

**Comment by mviereck** [comment]
Please provide terminal output with copy+paste instead of a screenshot, so I can cite from it.

I try to reproduce:
```
read Xenv < <(x11docker --gpu --xvfb --showenv x11docker/check)
```
I get this message like you:
```
x11docker note: Using special setup with Weston, Xwayland and xdotool
  instead of Xdummy or Xvfb to allow GPU access.
```
> After x11docker logs I can see some window's opening and disappearing immediately. I am guessing that it is wayland opening

Yes, that is a weston window immediately hidden with xdotool.

The VNC command fails here:
```
$ env $Xenv x11vnc -noshm -forever -localhost -rfbport 5910
14/06/2020 16:56:59 x11vnc version: 0.9.16 lastmod: 2019-01-05  pid: 21497
14/06/2020 16:56:59 Wayland display server detected.
14/06/2020 16:56:59 Wayland sessions are as of now only supported via -rawfb and the bundled deskshot utility. Exiting.
```
It seems recent VNC versions won't support this setup. 

I've proceeded with the xpra example in the wiki, that works as expected.

> Without --gpu option after chromium's logs I can normally interact with terminal. Looks like x11docker can't switch into daemon mode):

This rather sounds as the Xwayland startup somehow does not finish so x11docker cannot print the `Xenv` / `--showenv` output. Please run with `--debug` to hopefully get a meaningful hint what might be wrong.

**Comment by Kaprog** [comment]
Ok, now I understand. Everything is ok with x11docker. The issue is with VNC:
> The VNC command fails here:

My VNC automatically select `display :0` which explains screenshot in my first comment.
```
14/06/2020 17:17:04 x11vnc version: 0.9.16 lastmod: 2019-01-05  pid: 5301
14/06/2020 17:17:04 Using X display :0
14/06/2020 17:17:04 rootwin: 0x405 reswin: 0x2a00001 dpy: 0xe1292ed0
```
When I add option `-display :31` and `-auth guess` to the x11vnc commend, so it looks like:
`env $Xenv x11vnc -auth guess -display :31 -noshm -forever -localhost -rfbport 5910`

situation immediately changed. Now after navigating to noVNC client in web browser I can see only Chromium window 😄 . But after literally two seconds x11vnc crashed with error: 
```
caught XIO error:
14/06/2020 17:50:31 deleted 39 tile_row polling images.
```

It is quite popular issue so it will need just a little work. 
So it was my mistake to think that x11docker is the reason of this issue. Thanks for your help.
