### ISSUE TITLE
Using Intel Quick Sync

### ISSUE THREAD

**Issue by OscarVanL** [mviereck/x11docker#260]
Hi,

I see there are a lot of issues documenting using Nvidia GPUs, I was wondering if anyone had any experience using Intel Hardware Acceleration in applications, notably Intel Quick Sync?

I want to run some IP Camera Surveillance software in a container, but for this to work well it needs to use Intel Quick Sync for hardware acceleration while also supporting VNC for remote access.

Thanks!

**Comment by OscarVanL** [comment]
Am I right to assume that to achieve what I want I need to use the steps in the [VNC example](https://github.com/mviereck/x11docker/wiki/VNC) but rather than use dummy or Xvfb, use `--xdummy-xwayland` ("Using special setup with Weston, Xwayland and xdotool instead of Xdummy or Xvfb to allow GPU access.")

This acronym soup is starting to make my brain hurt, lol.

**Comment by mviereck** [comment]
> This acronym soup is starting to make my brain hurt, lol.

:-D

> I was wondering if anyone had any experience using Intel Hardware Acceleration in applications, notably Intel Quick Sync?

I don't know about "Intel Quick Sync" itself. But in general Intel GPU's  work well with MESA drivers on host and in image. For video decoding support you also need `libxv1`
and `va-driver-all` in the image. Compare: https://github.com/mviereck/x11docker/wiki/dependencies#dependencies-in-image

**Comment by OscarVanL** [comment]
I see, so in practical terms I have to use Debian and Ubuntu images (which is fine as I had intended to anyway).

Thanks for pointing me in the right direction :)

**Comment by OscarVanL** [comment]
Another (noob) question, when I try and run the VNC example:

`read Xenv < <(x11docker --xdummy --showenv x11docker/lxde)`

I get `-sh: syntax error near unexpected token '<'`

Any idea why my SSH doesn't recognise this symbol?

**Comment by mviereck** [comment]
> I see, so in practical terms I have to use Debian and Ubuntu images (which is fine as I had intended to anyway).

It should work with other systems providing the drivers as well. The dependency tables shows the package names for some systems.

> Another (noob) question, when I try and run the VNC example:

Please open new tickets for new issues.

> I get -sh: syntax error near unexpected token '<'

`read Xenv < <(x11docker ...)` is a `bash` syntax. Likely you tried the command in `sh`. I am not sure yet how to achieve the same in `sh`. Try in `bash` instead.
