### ISSUE TITLE
Setup where user can't see that it is running in container

### ISSUE THREAD

**Issue by Kaprog** [mviereck/x11docker#261]
Hi @mviereck,
I would like to make the best setup using x11docker which will have following features:

- will be isolated (so `-h` is not good idea)
- will have good GPU acceleration performance & low latency (so `--xpra` and everything that is similar like `--xpra-xwayland` are not fitting my needs)
- and the most important: It will be invisible that app is running in container (it should look like normal app launched from host. For example `--xwayland` and  `--xpra-xwayland` are starting compositor so it is not looking like common app. `--xpra-xwayland` has the best effect but it is slow)

I am trying to find such setup for a quiet long time and best option that may work (maybe I am wrong here) is `--xorg`. It has GPU performance as good as host and it's isolated. 

The problem is that I need this container to look, behave and launch as normal app launched from host. Using `--xorg` I am redirected instantly to new TTY and I need to switch TTY using `<CTRL><ALT><F1>....<F12>` to use host or container. 

I would like to see windows from newly created TTY (using `--xorg`) e.g. tty10 on my host's display (tty2) next to normal host's apps. So I need exactly the same effect as `--xpra-xwayland` gives me but with better GPU performance and lower latency.

So I need to merge two TTYs. Is it even possible? If not what is the alternative to have these 3 features in my setup?

Thanks for help

**Comment by mviereck** [comment]
> I would like to see windows from newly created TTY (using --xorg) e.g. tty10 on my host's display (tty2) next to normal host's apps. 

That is a good idea, and I once tried it. Unfortunately, it does not work. Once you switch the tty, applications on the invisible tty using GPU acceleration are frozen. 
The reason behind is that only one Xorg at a time can control and use the GPU.

You can check this if you run an accelerated `glxgears`. It should show about 60 fps. Switch to another Xorg, wait a few seconds, and switch back to glxgears. 
You'll see that it shows very few fps for one second. In fact, this "one" second was much longer, the time glxgears was frozen.

Your setup should be possible with two independent GPUs where one is able to handle a virtual monitor. However, that is quite special.

The best setup x11docker can provide is `--xpra-xwayland`. It has a bit of latency and the shortly seen weston window, so it does not entirely hide that it is a special setup.

Best but yet limited alternative:
If your container applications support Wayland (most of GTK3 and QT5 applications) and your host runs Wayland, you can use option `--hostwayland`. That would be seamless in the best way. It directly uses the host Wayland socket but does not have the security issues of `--hostdisplay`.

**Comment by Kaprog** [comment]
Thank You for your response. I have never thought about Wayland, but maybe it is good idea. I know that app has to have some special compatibility. Is it possible to install some type of compatibility layer to launch let's say "everyday" programs like: GIMP, Spotify, Discord, Firefox etc. using `--hostwayland`?

**Comment by Kaprog** [comment]
> You can check this if you run an accelerated `glxgears`

You are right, that's quite interesting

> Your setup should be possible with two independent GPUs

Sounds like plan :), but unfortunately it is impossible in my setup

>The best setup x11docker can provide is `--xpra-xwayland`

Totally agree. That's the best option for a lot of cases, but this one is quite special

**Comment by mviereck** [comment]
> I know that app has to have some special compatibility. Is it possible to install some type of compatibility layer

At least firefox can run under Wayland. I am not sure about the others.
You don't need or can have a special compatibility layer - either the application works in Wayland, or it does not. You just need a Wayland compositor running on host.
As a rule of thumb, most Gnome, most KDE and some Xfce applications already support Wayland.

>  maybe they have got this compatibility already. How to check it?

If you don't have a Wayland desktop, you can test with x11docker option `--wayland`.
E.g. run `x11docker --wayland x11docker/xfce xfce4-terminal`. x11docker will either use `--hostwayland` if available, otherwise `--weston` to provide a Wayland environment.

**Comment by Kaprog** [comment]
Ok. I will read about it and test some setups tomorrow. I will let You know if I resolve my issue (and maybe ask few questions if You don't mind :) )

Thank You for your very valuable help.

**Comment by mviereck** [comment]
You can test as well your host applications.
Run e.g. `x11docker --wayland --exe xfce4-terminal`. This one works.
I've tried `gimp`, it fails. 
`firefox` fails, too, but I know it is possible to run it under Wayland. Maybe my Debian with firefox-esr is too old.
`krita` fails, `gwenview` works.

**Comment by Kaprog** [comment]
Sorry for long response time. 
After testing and reading about `--hostwayland` I have to say that it is really the best option for apps that support Wayland. It's as fast and normal (I mean invisible for the user) as `-h`, but The Majority of programs that I want to use don't support Wayland unfortunately. 

When reading about Wayland I deeply tested option `--xwayland`. It is fast and X apps are running there correctly. The problem is that it creates blank, gray, fullscreen window which is (i think) compositor. This option would be perfect if this window would be transparent. I read about `weston.ini` file where I can specify `background-color` property, but it is only working with `--weston-xwayland` (which I don't like, because it has latency).

Is it possible to change background color of this compositor to transparent one or maybe even make it possible to click thought it, for example interact with desktop when running e.g. `x11docker -cpg x11docker/check`?

**Comment by mviereck** [comment]
> The problem is that it creates blank, gray, fullscreen window which is (i think) compositor. This option would be perfect if this window would be transparent. 

I totally agree, it would be great. 
The gray fullscreen window is not from the Wayland compositor but it is the root window of Xwayland. The root window of X servers is the background, where e.g. desktop icons are shown. You can change the background e.g. with `xsetroot`.


By default, Wayland compositors run one instance of Xwayland with Xwayland option `-rootless`. X applications appear in Wayland without the X root window.

However, I did not figure out how to set up additional rootless Xwayland instances.
It seems to need option `-wm fd`, too, to communicate with Wayland.  Unfortunately, I found no documentation.

Likely additional rootless Xwayland instances need support by the Compositor; normally it only expects its own one.

From `Xwayland -h`:
```
-rootless              run rootless, requires wm support
-wm fd                 create X client for wm on given fd
-listen fd             add give fd as a listen socket
```
If you can figure out an `Xwayland -rootless` setup, it would be great!

**Comment by Kaprog** [comment]
Ok so we have got common problem :) . I will work on it and keep You informed. I think that I have got few ideas, so there are chance.

One more question about this invisible setup idea. What about kata containers. I know that they give additional isolation. Maybe is it possible to use them with `-h` option to get same isolation like (`-A, -X etc.`) with good GPU acceleration (I remember that there ware some problems with GPU and kata)?

**Comment by mviereck** [comment]
> Ok so we have got common problem :) . I will work on it and keep You informed. I think that I have got few ideas, so there is a chance.

To have a starting point: Run e.g. `weston` and open its terminal:

This works, but has an X root window:
```
Xwayland :10 &
DISPLAY=:10 xterm
```
This works, but xterm is invisible:
```
Xwayland :11 -rootless &
DISPLAY=:11 xterm
```
> What about kata containers. I know that they give additional isolation. Maybe is it possible to use them with -h option to get same isolation like (-A, -X etc.) 

`kata` can provide additional isolation because it does not use the host kernel.
But it does not help with X security issues. All applications that share the same X server can see each other, regardless of where they are running. `--hostdisplay` with kata has the same issues as without kata. 

> I remember that there ware some problems with GPU and kata

I failed to get a working GPU setup with kata. Compare https://github.com/kata-containers/runtime/issues/586
However, with Intel GPUs it might be possible if I give it another try.

**Comment by Kaprog** [comment]
Ok, here is result of my quick research so far:

In fact creating rootless Xwayland seams to be impossible when running other window manager:

> With rootless Xwayland, the Wayland compositor must take the role as the X11 window manager, and one cannot use any other X11 window manager in its place. [source](https://wayland.freedesktop.org/docs/html/ch05.html)

About changing background color of root window to transparent there are few versions of facts: 
There are few [examples](http://www.3kranger.com/HP3000/mpeix/en-hpux/B1171-90076/ch11s02.html) where we can see something like: `xsetroot -solid transparent` and comment `This example turns the root window into a transparent window. `, but when I try to do it on my machine `xsetroot` seys `unknown color "transparent"`.

I looked into the source of `xsetroot` [here](https://github.com/freedesktop/xorg-xsetroot/blob/8c926a2a2d3f1ed06e24259657e27800f2e0ff8c/xsetroot.c#L517) and it seems that `DefaultColormap` may be limited to 24-bit RGB without transparency.

Even [here](https://tronche.com/gui/x/xlib/color/XParseColor.html) in documentation of `XParseColor` we can spot description of one parameter:
> Returns the exact color value for later use and sets the **DoRed** , **DoGreen** , and **DoBlue** flags.

So maybe C library that Xwayland use is globally limited only to 24-bit RGB. 
That's everything that I know so far, but I will be digging for a while. It should be possible in some way.

**Comment by mviereck** [comment]
> With rootless Xwayland, the Wayland compositor must take the role as the X11 window manager, and one cannot use any other X11 window manager in its place. 

Don't confuse X11 and the [X11] window manager.
On normal X we need a window manager like `openbox` to draw window decoration and to move the window around.
With rootless Xwayland the Wayland compositor draws the window decoration and moves the window around. So Wayland acts like a window manager.
Your citation does not say that it would be impossible to run a second rootless Xwayland. It only says we cannot run a window manager like `openbox` in rootless mode.

> but when I try to do it on my machine xsetroot seys unknown color "transparent".

`feh` can set images as desktop background. Maybe setting a transparent image with `feh` would work. However, even if the root window would become transparent, it would be impossible to pass through mouse clicks to Wayland behind the root window.

**Comment by mviereck** [comment]
Your [source](https://wayland.freedesktop.org/docs/html/ch05.html) speaks from the (at least theoretical) possibility of multiple Xwayland servers:

> A Wayland compositor usually spawns only one Xwayland instance. This is because many X11 applications assume they can communicate with other X11 applications through the X server, and this requires a shared X server instance. This also means that Xwayland does not protect nor isolate X11 clients from each other, unless the Wayland compositor specifically chooses to break the X11 client intercommunications by spawning application specific Xwayland instances.

**Comment by mviereck** [comment]
Just found this ticket: https://github.com/swaywm/wlroots/issues/1442

`wlroots` is a Wayland toolkit library that serves as a base at least for Wayland compositors `sway` and `waybox`.
I doubt that [sway](https://github.com/swaywm/sway) will support multiple Xwayland, but it might be worth ta ask at [waybox](https://github.com/wizbright/waybox) . However, waybox is in an early stage and grows rather slow.

**Comment by mviereck** [comment]
Are you still at this? If you find something out about possible multiple Xwayland setups, it would be quite interesting.

**Comment by Kaprog** [comment]
Hi, I have tried and search a lot, but with no results. No idea how to run working and visible -rootless Xwayland. Even I don't know how to make compositor transparent. I have tried `feh` and transparent .png, not working. `xsetroot` is not working too. It's really difficult to make some custom design with Xwayland.

**Comment by mviereck** [comment]
Thank you for the feedback!
So you got at the same point as me. 

> It's really difficult to make some custom design with Xwayland.

I once filed a bug report at swaywm and got the rude answer: "Xwayland is not intended to be run by users", and the ticket was immediately closed. 
Maybe there will be some new development in the next years, but currently there seems to be no solution that improves the current `--xpra-xwayland` setup.

I'll close for now. If you have a new idea or find something out, I'm glad to hear from you. Thanks for your research!

**Comment by Kaprog** [comment]
Hi @mviereck , I cannot stop thinking about this issue, so I came up with some strange workaround how to make setup which is invisible. The idea is to use separated `--xorg` sessions as windows which can be changed like Alt+Tab (so every application is running in separated container). 

Now I can't see other containers' windows, but I can use small script which will be taking screenshots of other containers (script in every container) and will create wallpaper for active xorg session which will emulate common desktop. This script will analize mouse clicks and if I select another window (aka click on some point on wallpaper) it will change tty using `chvt` to another container. 

It is possible, but this setup will need really fast TTY changing to feel naturally. From definition changing TTY should be quite fast (even immediately) using `chvt` or Ctrl+Alt+[F1-F12], unfortunately it is only without proprietary NVIDIA drivers. When I am using nouveau changing TTY is unnoticeable, but when I install NVIDIA's drivers black screen appears for 3-5 seconds during this change. That's really long for everyday use, when you want to change windows (like Alt+Tab).

There is only few posts about this issue, but they have got no answer or the solution is [strange](https://askubuntu.com/questions/1170532/slow-switching-between-users-tty-using-hdmi) and not working in my case. I think that changing GPU mode from graphical to text is taking so much time, but why only with NVIDIA's drivers?

Maybe you were trying to use commends like `x11docker -g --xorg x11docker/check` with proprietary NVIDIA drivers (unfortunately I need them to use CUDA) and then changing TTY, does it take so much time in your case?

**Comment by mviereck** [comment]
> Now I can't see other containers' windows, but I can use small script which will be taking screenshots of other containers (script in every container) and will create wallpaper for active xorg session which will emulate common desktop. This script will analize mouse clicks and if I select another window (aka click on some point on wallpaper) it will change tty using chvt to another container.

That's really strange, but creative, too!
I see one great issue: I often encounter Xorg crashes if I switch immediately between multiple Xorg ttys. I always switch to a text tty first.
Your setup could do that, too; but the black screen would be visible for a short time.

> I think that changing GPU mode from graphical to text is taking so much time, but why only with NVIDIA's drivers?
> Maybe you were trying to use commends like x11docker -g --xorg x11docker/check with proprietary NVIDIA drivers and then changing TTY, does it take so much time in your case?

I don't have an NVIDIA GPU, so I cannot check. No idea why it takes so long.

**Comment by Kaprog** [comment]
I know it's strange but I need this setup for my project, so even stupid idea which will be working is awesome :) Fortunately I have never encounter xorg crashes and I don't need to change TTY to blank one, so one problem less :D

But still Nvidia drivers force GPU to do something that freezes display. Nvidia logs gives one interesting thing: during TTY change some devices like keyboard and monitor are disconnected for a second. 

I will work on it and keep you informed if you're interested. Of course that's not x11docker issue but I thought you should know (you can close this issue if you want of course)

**Comment by mviereck** [comment]
> I will work on it and keep you informed if you're interested. 

Yes, I am very interested, thank you for this!
Indeed I once thought of something similar: x11docker running on several ttys and switching between them with some sort of menu or panel. I did not go further because I thought that goes too far and needs too much additional code and maintanance. Finally I found the GPU accelerated solutions based on weston and Xwayland and did not need Xorg for GPU acceleration anymore.

May I ask why it is that important to hide the container from users?

**Comment by Kaprog** [comment]
Of course. My idea is to make safe, fast and universal operating system. It will base on Clear Linux (from Intel, really fast one). Every application and script will be isolated from system and other apps using your awesome project. Core system will be Linux of course, because it's fast and private (and a lot of other awesome things of course) but I want to run every type of application on this system (.deb, .rpm, .AppImage, .exe and .msi). I will probably use Crossover with docker for that. That's the back-end.

Using electron.js I am going to build front-end of system which will provide easy way to install and run every type of application in modern UI. 

The core idea is to connect speed, privacy and awesome Linux world with Windows' popularity in safe, fast and easy for user way.

That's why I need user to see no visual and performance difference between standard Linux or Windows and my project.

**Comment by mviereck** [comment]
Ups, a great project.
In this picture I'd say a Wayland compositor with multiple Xwayland servers would still be the best way to go.
Maybe it's worth to contact some Wayland developers?
There are already a few active projects, Waybox, Wayfire and KWin come to mind, where I would ask first.
Although X is more in use than Wayland, this will change in future. Your current idea depends on X11 features. Catching and forwarding a mouse click won't work in Wayland environments.

**Comment by Kaprog** [comment]
You're right. And the other thing is that I need NVIDIA proprietary drivers to use CUDA. Weyland doesn't support it so that's why I am looking for really special setup

**Comment by mviereck** [comment]
> I need NVIDIA proprietary drivers to use CUDA. Weyland doesn't support it 

Maybe there has been some progress meanwhile. I am not sure if it is right, but I've heard that Gnome 3 somehow runs Wayland with NVIDIA. But maybe that's wrong.
For a very long time NVIDIA refused to work with the Wayland developers, and now there is a big code gap. Afaik meanwhile NVIDIA is interested in Wayland and might support it.
Things would be much easier if NVIDIA just provides their closed source code to the `nouveau` developers.

**Comment by Kaprog** [comment]
When NVIDIA would share their code I think that one of the biggest Linux users dream will come true. 

Tomorrow I will search for more information about Wayland and NVIDIA. This sounds really interesting. Thank You (again :) ) for your awesome help.

**Comment by Kaprog** [comment]
Hi @mviereck ,
Sorry for long response time.

I think that NVIDIA and Wayland/Xorg is not good idea. I started to search in different direction. I reviewed options that x11docker provide and compare them to my needs. I focused on xephyr, which unfortunately doesn't support GPU acceleration, but during research I saw really interesting [post](https://unix.stackexchange.com/a/346445), which point me to [VirtualGL](https://virtualgl.org/)

> VirtualGL is an open source toolkit that gives any Linux or Unix remote display software the ability to run OpenGL applications with full hardware acceleration. 

With [TurboVNC](https://turbovnc.org/) and it's ability to [hardware 3D acceleration using VirtualGL](https://cdn.rawgit.com/TurboVNC/turbovnc/2.2.5/doc/index.html#hd009) I think It might be the solution to create isolated environment. So each application will create it's own display inside hardware accelerated VNC and run x11docker for additional security. I think it's quite secure, should avoid X11 security leaks, fast, GPU accelerated and nearly invisible setup (each app will have its own vncviewer, which will be looking like normal window).

What do You think about this? I have just made research and run few tests, to check its functionality. I haven't built any setup yet, because I really want to hear your opinion. Thanks in advance.

**Comment by mviereck** [comment]
VirtualGL is really cool and in early days x11docker had an option `--virtualgl` for GPU acceleration in Xephyr.
Unfortunately, it breaks the X isolation. To allow GPU acceleration, VirtualGL connects to the host X server. All applications can connect to host X if they want to.
Maybe the risk is mitigated if each application uses the VNC X server, none connects to host X except by VirtualGL, and no host applications at all run on the host X server.
If an application runs on the host X server, every container could manipulate it, and maybe abuse it to take control over the host. Simplest example, think of a host terminal window, and a container sending some keystrokes with commands.
If you strongly avoid to have any X clients on the accelerated host X, the security risk might be ok. (Even the window manager could run in a container.)

**Comment by Kaprog** [comment]
Thank You for comment. That's sounds interesting. I will build this setup, test its isolation with x11docker/check and some possibly dangerous scripts and let You know.

**Comment by Kaprog** [comment]
VirtualGL seems not to work properly with my setup. I've got NVIDIA GPU, proprietary drivers installed, and I am working on Ubuntu. Running `glxgears` on :0 display without VirtualGL works correctly, shows 60FPS, but after running `vglrun glxgears` on host (:0 display) or in VNC session (:1 display) I have got over 1000FPS, because `glxgears` falls into CPU rendering. The most interesting thing is that when I run `vglrun glxgears -info`, it's not showing `mesa` divers, but NVIDIA GPU with NVIDIA's drivers. So it's detecting GPU, but not using it. That's really strange. 

But that's not x11docker issue of course so You can close this issue anytime. I am just looking for perfect, isolated setup with NVIDIA

**Comment by mviereck** [comment]
Just a thought: You try to hide that something runs in a container.
What about the other way around: Show the user the different containers. Make obvious which applications/windows belong to the same container.
xpra allows to draw a colored border (included in x11docker option `--border`) an allows custom window titles (no x11docker option yet).

> The most interesting thing is that when I run vglrun glxgears -info, it's not showing mesa divers, but NVIDIA GPU with NVIDIA's drivers. So it's detecting GPU, but not using it. That's really strange.

Maybe glxgears uses the GPU, but gets no framerate info from it? It might be worth to check `top` meanwhile.

> But that's not x11docker issue of course so You can close this issue anytime.

Your project and your ideas are interesting, and if you like to discuss several topics, I am happy to give my opinion if it can be useful. 

> I am just looking for perfect, isolated setup with NVIDIA

In general I mistrust closed source NVIDIA drivers. I am pretty sure they have serious security issues.
GPU issues in general, even with open source drivers:
 - Palinopsia leak: https://hsmr.cc/palinopsia/. x11docker/check has a button for it
 - GPU rootkits: https://github.com/x0r1/jellyfish

**Comment by Kaprog** [comment]
> Maybe glxgears uses the GPU, but gets no framerate info from it? It might be worth to check top meanwhile.

I am sure that CPU usage during this test is really high. `glxinfo` gives 100% correct information. I don't know where is the problem, yet.

> In general I mistrust closed source NVIDIA drivers. I am pretty sure they have serious security issues.
GPU issues in general, even with open source drivers:

I know that NVIDIA have issues with security, compatibility and Linux generally. `x11docker` has awesome options to provide really fast and secure GPU accelerated containers, but only with open source drivers for nvidia, which is really fine, but nouveau has poor performance, especially with new nvidia GPUs (Turing). I am not really stick to Nvidia's CUDA, but working with smooth display without flickering is must have in my opinion.

> What about the other way around: Show the user the different containers. Make obvious which applications/windows belong to the same container.
xpra allows to draw a colored border (included in x11docker option --border) an allows custom window titles (no x11docker option yet).

Yeah, that's interesting option (xpra setups are the most useful I think) and I started thinking about AMD's GPU, they seem to be much more compatible with Linux environment (I am not sure). Maybe the best option is to change the GPU, because this project is becoming less and less doable, after discovering next issues with nvidia.

> Your project and your ideas are interesting, and if you like to discuss several topics, I am happy to give my opinion if it can be useful.

Glad to hear that. You're really helping me. I really appreciate that.

**Comment by mobrine-mob** [comment]
Just for those that were looking for a workaround to launch multiple Xwayland instances, your best bet is to use gnome wayland cause it seems to work just fine. Don't waste time looking at some other Wayland compositor

**Comment by mviereck** [comment]
> to launch multiple Xwayland instances, your best bet is to use gnome wayland 

Did you manage to run multiple rootless Xwayland instances?
Running multiple Xwayland instances without `-rootless` works on most Wayland compositors (except sway).
