### ISSUE TITLE
x11docker with Firefox hangs on Linux Mint 20.0

### ISSUE THREAD

**Issue by GregoryVPerry** [mviereck/x11docker#262]
Hello,

Using a fresh install of Linux Mint 20.0 running xfce, and I can't seem to get jess/firefox running. The x11docker framebuffer runs but stays grey, with no Firefox process, and no discernible error on the console to indicate what the issue may be, either with the default config or with openbox pulled using:

```
x11docker --share $HOME/Downloads -- --tmpfs /dev/shm -- jess/firefox
```
Any ideas how I can diagnose this further, perhaps docker debug logging?

**Comment by mviereck** [comment]
Could you please run with `--debug` and show the output at www.pastebin.com? 
```
x11docker --debug -- --tmpfs /dev/shm -- jess/firefox
```
Do other images work as expected?
E.g.:
```
x11docker --desktop x11docker/fvwm
```

**Comment by GregoryVPerry** [comment]
Here's the pastebin output: https://pastebin.com/qEkU2DAM

fvwm seems to run fine using your command.

**Comment by mviereck** [comment]
Everything looks right, firefox seems to be running.
Maybe the issue is in openbox. I sometimes notice that openbox needs one mouse click to show up the windows. Did you try to click into the gray area?
Just to check if it is an openbox/window manager issue: Try without a window manager:
```
x11docker --desktop -- --tmpfs /dev/shm -- jess/firefox
```

**Comment by GregoryVPerry** [comment]
No, still a grey screen even when capturing the keyboard/mouse and releasing. Here's the only message on the output:

(firefox:117): Gtk-WARNING **: 13:19:42.429: Locale not supported by C library.
	Using the fallback 'C' locale.

**Comment by GregoryVPerry** [comment]
Hmm it's not a locale issue either, purged and rebuilt all locales but with no luck. Just a grey screen with no firefox.

**Comment by mviereck** [comment]
Can you try with another window manager? For example, if you have `xfwm4`:
```
x11docker --wm=xfwm4 -- --tmpfs /dev/shm -- jess/firefox
```
Or try with another X server, I recommend `nxagent`:
```
x11docker --nxagent -- --tmpfs /dev/shm -- jess/firefox
```

**Comment by GregoryVPerry** [comment]
Nope to both. xfwm4 is a grey screen, nxagent doesn't even open a window.

**Comment by mviereck** [comment]
I'm a bit out of ideas now.
Likely it is an issue in recent `jess/firefox` builds. I try to pull a fresh image, but my bandwidth is slow, it will take some time.
If you are satisfied with older versions of firefox, you could build an image like:
```
FROM debian:buster
RUN apt-get update
RUN apt-get install -y firefox-esr
CMD firefox
```

**Comment by mviereck** [comment]
I've pulled a fresh `jess/firefox` and can confirm and reproduce your reported bug. Though, still no idea yet. firefox is running, but not opening a window.

**Comment by GregoryVPerry** [comment]
Thanks @mviereck, I appreciate the help.

**Comment by mviereck** [comment]
I am currently building this Dockerfile:
```
FROM debian:buster

RUN apt-get update && \
    apt-get install -y \
      apulse \
      ca-certificates \
      ffmpeg \
      firefox-esr \
      hicolor-icon-theme \
      libasound2 \
      libpulse0 \
      libxv1 \
      mesa-utils \
      mesa-utils-extra \
      va-driver-all 

RUN echo 'pref("browser.tabs.remote.autostart", false);' >> /etc/firefox/syspref.js && \
    echo "#! /bin/sh \n\
if [[ -e /dev/snd ]]; then \n\
  exec apulse firefox-esr "$@" \n\
else \n\
  exec firefox-esr "$@" \n\
fi \n\
" >/usr/local/bin/startfirefox && \
    chmod +x /usr/local/bin/startfirefox

ENTRYPOINT [ "startfirefox" ]
```
If you like to, please try it out, too.
Maybe I should provide an image `x11docker/firefox`. From time to time `jess/firefox` causes issues; it uses beta builds, after all.

**Comment by GregoryVPerry** [comment]
Getting a pull access denied for x11docker/firefox

**Comment by mviereck** [comment]
I don't have published a repository yet, I just consider to provide one based on the Dockerfile above.
You could build an image with the Dockerfile yourself and test it out. 
So far, firefox starts up and shows a window here.

**Comment by mviereck** [comment]
I just did a check,  `jess/firefox` works again. Likely it has been a temporary issue as it can happen with bleeding edge installations.
