### ISSUE TITLE
Way to bypass password for connecting to Display

### ISSUE THREAD

**Issue by chrisl8** [mviereck/x11docker#265]
I use x11docker to run a specific application very often, and every time I run it I get the prompt:
`Please type in your password to run docker on display`

Is there any way to set up my x11docker command line and/or /etc/sudoers file so that this is not required?

I realize it would lessen security on my development environment, but so would creating a shorter password. :)

P.S. I am using both the `--xpra` and  `--hostnet` arguments when I call x11docker.

P.P.S. I am realizing now that maybe I just need to call x11docker with sudo and then it will work?
And then I just need to add x11docker itself to /etc/sudoers to avoid being asked for a password on every run?

I'm not sure why I didn't realize this before now.

**Comment by mviereck** [comment]
Many add their user to group `docker`. That allows to run docker without a password.
However, that opens a security hole. For example, an unprivileged user can share e.g `/etc` or `/usr/bin` with a container and arbitrary change it.
The same is possible with your current solution.

A rather secure solution would be to set up short scripts to run x11docker with desired options and to add these scripts in `/etc/sudoers`.
For example, if you have a script `/usr/local/bin/x11docker-xfce`:
```
#! /bin/bash
x11docker --home --desktop --gpu x11docker/xfce
```
If you add this script to `/etc/sudoers`, no one could share sensible host root folders, but you could run it without a password.

**Comment by chrisl8** [comment]
Thanks, these are all good ideas.

I tried running a script that called x11docker with sudo, but x11docker still asked for my password.
I may have messed something up though. I will try it again as you described.
