### ISSUE TITLE
Fail to use the host ubuntu input method, such as the Chinese input method

### ISSUE THREAD

**Issue by imwcc** [mviereck/x11docker#269]
Fail to use the host ubuntu input method, such as the Chinese input method.
is anyone known how to enable it? 

I use the follow docker image:

``` shell
x11docker  --desktop --dpi 150 --gpu --clipboard --sudouser --lang="zh_CN" --showid --  --  x11docker/lxde-wine
```

**Comment by imwcc** [comment]
Hi @mviereck 

Could you have any comments ?
Thank you very much.

**Comment by mviereck** [comment]
Hi,

Do you get any error messages? Could you show me the terminal output, please?
If there is no obvious error message, please run with `--debug` and show me the output.

**Comment by imwcc** [comment]
Hi @mviereck 
Run with --debug
When I press the "shift" keyboard to switch method, nothing happens output in the terminal.

Here is the a part of terminal logs:

``` shell
xinitrc=ready
containerid=91cce577f0a747b77622d66c9315229af662a3b58ba6c905564d5f60b2083278
pid1pid=5080
containerip=172.18.0.2
containerrootrc=ready
dockerrc=ready
xtermrc=ready
DEBUGNOTE[18:10:09,692]: storepid(): Stored pids:
3208 watchpidlist
3230 watchmessagefifo
4118 containershell
5230 dockerlogs
5596 dockerstopshell
5080 pid1pid
4611 xinit
4612 Xserver
DEBUGNOTE[18:10:09,696]: storeinfo(): x11docker=ready
DEBUGNOTE[18:10:09,836]: waitforlogentry(): containerrc: Found log entry "containerrootrc=ready" in store.info.
DEBUGNOTE[18:10:09,845]: Running containerrc: Unprivileged user commands in container
DEBUGNOTE[18:10:09,880]: containerrc: HOME is not empty. Not copying from /etc/skel
DEBUGNOTE[18:10:09,930]: containerrc: Running container command:  
    /usr/local/bin/start 
  
DEBUGNOTE[18:10:09,969]: waitforlogentry(): tailstderr: Found log entry "x11docker=ready" in store.info.
DEBUGNOTE[18:10:09,969]: waitforlogentry(): tailstdout: Found log entry "x11docker=ready" in store.info.
ln: failed to create symbolic link '/home/arvin/code': File exists
x11docker/lxde: If the panel does not show an approbate menu
  and you encounter high CPU usage (seen with kata-runtime),
  please run with option --init=systemd.

** Message: 18:10:10.174: main.vala:101: Session is LXDE
** Message: 18:10:10.174: main.vala:102: DE is LXDE
** Message: 18:10:10.300: main.vala:133: log directory: /home/arvin/.cache/lxsession/LXDE
** Message: 18:10:10.300: main.vala:134: log path: /home/arvin/.cache/lxsession/LXDE/run.log
```

**Comment by imwcc** [comment]
> Seems sublime do not support ibus input framework.
> It captures all the keyboard input, and do not take input from ibus.
> 
> Please fix this so we can actually use in on Linux.
> Thanks.

Maybe it is a similar issue with it.

**Comment by mviereck** [comment]
Maybe I misunderstood you.
First I thought the `--lang=zh_CN` option would fail. Does this work so far?

>  When I press the "shift" keyboard to switch method, nothing happens output in the terminal.

You mean a special input method giving other chinese chars if pressing shift. I am not familiar with that. 
Likely x11docker has to set up the X server to support this input method.

Can you tell me how you set up and configure this input method on the host system?
This [site](https://wiki.debian.org/InputMethodBuster) describes several methods for keyboard input, is yours `ibus`?

>   Seems sublime do not support ibus input framework.
    It captures all the keyboard input, and do not take input from ibus.
> Maybe it is a similar issue with it.

Likely yes.

**Comment by imwcc** [comment]
Thank you for your support.

I am using the Sogou pinyin.
As I know, the [sougou pinyin](https://pinyin.sogou.com/linux/?r=pinyin) is the most popular input method in China. 
regards to how to enable it, please refer to: https://www.yanlongwang.net/Ubuntu/install-sogou-ubuntu-18/

**Comment by mviereck** [comment]
I had some partial success adding `fcitx-pinyin` in the image:
```
FROM x11docker/lxde-wine
RUN apt-get update
RUN apt-get install -y fcitx-pinyin
```
It might further help to add fonts:
```
RUN apt-get install -y fonts-arphic-uming
```
Could you please build a test image and try out?
So far I had success with russian input method. Steps:
 - Run "Fcitx" in the LXDE menu under "system tools". Nothing visible happens, but the daemon starts.
 - Run "Fcitx configuration" in the LXDE menu under "Preferences". Do some settings.
 - I could enable Russian/Kyrillic keyboard and switch between them with CTRL+SPACE. I failed to enable chinese keyboard.

**Comment by imwcc** [comment]
Got. thank you very much.
I will retry it.

**Comment by mviereck** [comment]
If you succeed, I'd like to hear from you.
Maybe x11docker could support this setup somehow, or at least give some instructions in the wiki.

**Comment by imwcc** [comment]
Ok

I found that the Chinese input is configured through GUI, so far I have not found the way to configure through command.
If successful, I will update the comment. 
Thanks.
