### ISSUE TITLE
--sudouser: sudo without password?

### ISSUE THREAD

**Issue by badele** [mviereck/x11docker#27]
By checking if the option **NOPASSWD:ALL** existing with `--sudouser` option

I could see that this one existed in [2015](https://raw.githubusercontent.com/mviereck/x11docker/e49e109f9e78410d242a0226e58127ec9f9d6181/x11docker) and [document code](https://github.com/mviereck/x11docker/blob/0a4166c020c9700e592c0d7600b4a8b5e9850222/x11docker#L1355)

Why this function is disabled (i think for security reason :) )? Can we add new option (ex: `--nopassword` or `--sudonopass`, etc ..) or must we be dot it in our **Dockerfile** ?

**Comment by mviereck** [comment]
It seemed to me it would be better to run `sudo` with a password. The password is `x11docker` and shown in terminal on x11docker startup.

I would not like to add an option like `--sudonopass`; evil applications can easily detect a passwordless sudo. It is not a great security layer with password `x11docker` as  a special malware written for x11docker would know it. But at least it would have to know it.

`sudo` in x11docker containers is rather useless as all system changes will be discarded when the container stops. Its purpose is  for experimental changes on the fly in a running container before including them in Dockerfile.

Direct changes with `RUN ...` in `/etc/sudoers` in Dockerfile will be overwritten by x11docker, and that is intended. But you can add this in your Dockerfile startscript `/usr/local/start`:
```
echo x11docker | sudo --stdin su -c 'echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers'
```

**Comment by mviereck** [comment]
Argh, wrong "'quotas'". Sorry, will edit my answer

**Comment by mviereck** [comment]
ok, try again with 
```
echo x11docker | sudo --stdin su -c "echo \"$USER ALL=(ALL) NOPASSWD:ALL\"  > /etc/sudoers"
echo x11docker | sudo --stdin su -c "echo \"root ALL=(ALL) ALL\" >> /etc/sudoers"
```

**Comment by badele** [comment]
Thanks, it works like a charm :)
