### ISSUE TITLE
Mistype in line 9 of CHANGELOG.md breaks the installation

### ISSUE THREAD

**Issue by 1ucir** [mviereck/x11docker#272]
`## [Unrelesead]`
while meant to be 
`## [Unreleased]`
Installation process fails on trying to gunzip the "Not found" page fetched from "https://codeload.github.com/mviereck/x11docker/tar.gz/vUnrelesead" URL, built from CHANGELOG.md content and supposed to contain last released version number.

**Comment by mviereck** [comment]
Indeed, what a gross failure chain!
Thank you for the report, CHANGELOG.md is fixed now.
I should have a look how to make the installation process less volatile.

**Comment by 1ucir** [comment]
Yup, the problem's gone.
