### ISSUE TITLE
Support for multi-monitor setup

### ISSUE THREAD

**Issue by rohitsud** [mviereck/x11docker#273]
I am running the script on a desktop with a monitor connected using HDMI. When the display starts up, it defaults to the laptop LCD monitor. There should be a way to customize which display the script loads on.

**Comment by mviereck** [comment]
Which X server option do you use?
If it is a nested X server like with option `--xephyr`, x11docker cannot do much about it.
If it is `--xorg` or `--weston-xwayland` from tty, please show me the output of `xrandr`.

**Comment by mviereck** [comment]
It should work to configure the displays like you would in a regular desktop environment. That can be done with tools in container as well as with tools from host. (Tools from host would need `DISPLAY` and `XAUTHORITY`.)

If you can figure out an `xrandr` command that fits your needs, you can run x11docker e.g. with something like 
```--runfromhost "xrandr --output VGA1 --primary"```

**Comment by mviereck** [comment]
@rohitsud Did this work for you? Can the ticket be closed?

**Comment by rohitsud** [comment]
It almost works; X11docker loads the application on the correct monitor (HDMI). But the resolution it uses is my laptop LCD resolution (2560x1600). Is there a way for it to let it auto-detect the resolution supported by my HDMI monitor?

**Comment by mviereck** [comment]
> But the resolution it uses is my laptop LCD resolution (2560x1600). 

Your xrandr output shows that your HDMI monitor supports at most 1920x1080. How can it show 2560x1600?
Nonetheless, you can add the desired resolution to the xrandr command, e.g.
```
 --runfromhost "xrandr --output HDMI-2 --primary --right-of eDP-1 --mode 1920x1080"
```

**Comment by rohitsud** [comment]
I guess I didn't word the problem properly, sorry about that.

[Here's](https://photos.app.goo.gl/W4xpWxdCW7DXJoR36) a link to photos that show what I am seeing.

The blue photo is of the KODI app that I am trying to launch on my HDMI TV. Note that only the top right of the screen appears.

The other pictures are of my laptop LCD and mirrored HDMI display logged in using a Linux console. Note that the HDMI monitor is trying to use the higher resolution of the laptop LCD and is therefore cropping the bottom few lines in the console  that are visible in the laptop LCD but not in the HDMI.

I am wondering if while launching x11docker, I can override the resolution that is used; the text is tiny in the pictures but I already tried using 1920x1080 as the mode in the xrandr command and it doesn't seem to do anything.

**Comment by mviereck** [comment]
So you get a mirrored output, both monitors show the same content? This should not happen with the `--right-of` option.
To at least avoid the cropped output, set the laptop monitor to the same size as the HDMI output:
```
 --runfromhost "xrandr --output HDMI-2 --primary --right-of eDP-1 --mode 1920x1080 --output eDP-1 1920x1080"
```
Basically the issue is all about to. find a good `xrandr` setup. It might be easier to run a terminal in container.
For example, run `x11docker --xorg x11docker/check xfce4-terminal` and try out some `xrandr` setups in the container terminal until you find one that works for you.
Overall, `xrandr --auto` should already give a basically good setup.
