### ISSUE TITLE
ContainerId

### ISSUE THREAD

**Issue by jmokuzai** [mviereck/x11docker#276]
Hi, 

First of all, good job overall on this useful little tool.

I found somewhere on this wiki about using read containerId < < (x11docker ......) to get the containerId, it did get a seemingly valid containerId, but when I use docker kill containerId to kill it, it doesn't do anything, so I did docker container list --all, guess what, that container Id does not exist, I am not sure how you produced that id in the first place, any pointer would be appreciated.

**Comment by mviereck** [comment]
This works here as expected:
```
lauscher@debianlaptop:~/git/microscopy-tools$ read id < <(x11docker --showid -d wine)
x11docker WARNING: User lauscher is member of group docker.
  That allows unprivileged processes on host to gain root privileges.

x11docker note: Using X server option --xephyr

x11docker note: Xephyr is a quite stable nested X server.
  Less stable, but resizeable is nxagent with option --nxagent.

lauscher@debianlaptop:~/git/microscopy-tools$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
1321ed28d927        wine                "env /usr/local/bin/…"   14 seconds ago      Up 12 seconds                           x11docker_X102_wine_96042916730
a7ddc652183a        x11docker/firefox   "env /usr/local/bin/…"   9 minutes ago       Up 9 minutes                            x11docker_X101_x11docker-firefox_95491104020

lauscher@debianlaptop:~/git/microscopy-tools$ echo $id
1321ed28d92731331841aba355ed1418cd41492dd840a271e149bc29460a7406

lauscher@debianlaptop:~/git/microscopy-tools$ docker kill 1321ed28d92731331841aba355ed1418cd41492dd840a271e149bc29460a7406
1321ed28d92731331841aba355ed1418cd41492dd840a271e149bc29460a7406

lauscher@debianlaptop:~/git/microscopy-tools$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
a7ddc652183a        x11docker/firefox   "env /usr/local/bin/…"   10 minutes ago      Up 10 minutes                           x11docker_X101_x11docker-firefox_95491104020
```
x11docker returns the full id `1321ed28d92731331841aba355ed1418cd41492dd840a271e149bc29460a7406`.
`docker ps` only shows the first 12 digits of the id: `1321ed28d927`.
After `docker kill 1321ed28d92731331841aba355ed1418cd41492dd840a271e149bc29460a7406` the wine container disappears.

Please try to reproduce these steps and show me the terminal output if it still fails for you. Note that the id also disappears if the container terminates otherwise.

**Comment by jmokuzai** [comment]
You are right, the error was in my code .... I had a "&" at the end of x11docker call, it was required for an earlier version of it when I launch something from dmenu, no longer needed. Thanks, this is working as you described, and as I originally expected.
