### ISSUE TITLE
use of x11docker in a swarm

### ISSUE THREAD

**Issue by andrewufrank** [mviereck/x11docker#281]
I would like to use swarm include secrets in the docker, which seem only possible with swarm. can x11docker be used to run a display in a swarm of 1?
I am learning about docker... and love x11docker!

**Comment by mviereck** [comment]
I know close to nothing about docker swarm and docker secrets. I've never used it.
As I don't know how to use docker swarm, I don't know if it can run x11docker.
Sorry, I have no idea because I know nothing about this.

**Comment by eine** [comment]
@mviereck the main concept behind docker swarm is building clusters of machines and deploying containers to any/all of them from a single (manager) entrypoint. It allows replicating containers in several machines, load balancing, etc. See https://docs.docker.com/engine/swarm/key-concepts/. In some sense, it is Docker's own solution to what Kubernetes offered later.
Overall, I believe it is out of scope of x11docker. I understand x11docker as developer centric for single instances. Hence, docker swarm would only be an alternative remote access mechanism to SSH. I don't think it is worth implementing support for that.

**Comment by andrewufrank** [comment]
Thank you for the information. It is helpful for my further approaches. My current goal is a 'single install' solution to manage a number of computers in three locations for daily use (programming, writing papers, email etc) and to avoid that each of the systems is slightly different in its set up (what is installed, what not, which version). This seems feasible with x11docker and I try to understand the limitations. Again, thank you for the help!
