### ISSUE TITLE
How to uninstall completely as never had (for reinstall)

### ISSUE THREAD

**Issue by azrea** [mviereck/x11docker#282]
Due misconfiguration with rootless docker.

**Comment by azrea** [comment]
Is there any windows-desktop images exist that able to run on docker linux? :smile:

**Comment by mviereck** [comment]
> How to uninstall completely as never had (for reinstall) 

You can remove x11docker with `x11docker --remove`. 
It will only leave the softlink `~/x11docker` and its target `~/.local/share/x11docker` where persistant files of option `~/home` are stored.
Additional packages that you have installed yourself (like e.g. Xephyr) are not removed, you would have to care yourself.

> Is there any windows-desktop images exist that able to run on docker linux? 

Afaik those can run on Windows only.

**Comment by azrea** [comment]
:1st_place_medal:

**Comment by mviereck** [comment]
> Is there any windows-desktop images exist that able to run on docker linux?

You might be interested in [x11docker/lxde-wine](https://github.com/mviereck/dockerfile-x11docker-lxde-wine). This is not a Windows container, but allows to run some Windows applications with the help of `wine`.

**Comment by azrea** [comment]
>You might be interested in x11docker/lxde-wine. This is not a Windows container, but allows to run some Windows applications with the help of wine.

@mviereck wine doesn't useful. i'm extremely mad with this software https://www.internetdownloadmanager.com/ for years.
It only available for windows and it's browser integration module super perfect, usually detect video files from nearly all websites with multiple qualities download options https://chrome.google.com/webstore/detail/idm-integration-module/ngpampappnmepgilojfohadhhmbhlaek

Even if we managed to install desktop software with wine somehow but no luck with its integration module. For past versions some're have used flashgot browser extension with IDM but it doesn't good as their own module.

From all available download manager for linux, i see https://ugetdm.com/ as good with features and closer to above IDM with integration module
https://ugetdm.com/downloads/source-code/ - application
https://github.com/ugetdm/uget-integrator - integrator

But they don't receive volunteer contributions and it seems no time for main developer as i noticed on issue comment.

That's the reason i was hardly looking for such option rather than run windows virtual machine always.
