### ISSUE TITLE
Adjust screen size and connectivity issue

### ISSUE THREAD

**Issue by temporallyaccount** [mviereck/x11docker#283]
I have two problems.

1. `x11docker --home xorilog/telegram`
it open too large screen then i tried to add `x11docker --home --size 800x600 xorilog/telegram` but doesn't effect, seems command incorrect.

2. `x11docker -- jess/chromium --no-sandbox`
even above telegram container connect properly but chromium container has network connectivity issue(cannot connect).

![Screenshot from 2020-09-22 19-05-20](https://user-images.githubusercontent.com/64679174/93905381-1e2b6880-fd25-11ea-90ec-b24a9923ebee.png)

**Comment by mviereck** [comment]
Double post #284, closing.
