### ISSUE TITLE
Screen size and connectivity issue

### ISSUE THREAD

**Issue by temporallyaccount** [mviereck/x11docker#284]
I have two problems.

1. `x11docker --home xorilog/telegram`
it open too large screen then i tried to add `x11docker --home --size 800x600 xorilog/telegram` but doesn't effect, seems command incorrect.

2. `x11docker -- jess/chromium --no-sandbox`
even above telegram container connect properly but chromium container has network connectivity issue(cannot connect).

![Screenshot from 2020-09-22 19-05-20](https://user-images.githubusercontent.com/64679174/93905381-1e2b6880-fd25-11ea-90ec-b24a9923ebee.png)

**Comment by mviereck** [comment]
It's not clear to me what your issues are.

> it open too large screen

What do you mean with "too large screen"? A big window? Or did you start from console, and Xorg isn't properly configured?
Please provide me the logfile `~/.cache/x11docker/x11docker.log` after running and terminating `xorilog/telegram`.
Try different X server options to see if it makes a difference.

> chromium container has network connectivity issue

The connection issues shown in the screenshot only show dbus issues and should do no harm. Did you try to open a website?

**Comment by temporallyaccount** [comment]
>What do you mean with "too large screen"? A big window? Or did you start from console, and Xorg isn't properly configured?

It automatically use xephyr, it open big window then i realized what's wrong and started to use nxagent.
then i ran `x11docker --home --nxagent xorilog/telegram`

1. Again i have another problem (had before too). In my telegram account has several languages channels but telegram only display english languages content and rest as rectangle symbols. In this cause i want to fix to display every languages (not just selected languages)
2. I cannot input (type messages) in different language, all input auto type in english characters, which option should i use to solve that problem. --dbus, --dbus-system or --hostdbus? or anything else?
3. I want to login to two telegram accounts, how to keep separate persistent configs? tested command invalid. home/1, home/2
`x11docker --name personal --home/1 --nxagent xorilog/telegram`
`x11docker --name business --home/2 --nxagent xorilog/telegram`

>The connection issues shown in the screenshot only show dbus issues and should do no harm. Did you try to open a website?

Yes. cannot visit to any site but no such problem for telegram.

**Comment by temporallyaccount** [comment]
New question: I started to evaluate this perfect solution x11docker recently and thank you @mviereck 
(this tool very helpful for my many others tasks even i focus and question related telegram and common use causes)

now i want to try something bit advanced (telegram secret chat does not available for desktop clients except unigram)

I prefer run android emulator or simulator in docker, only for telegram app. Actually i'm trying to save host system resources consumption much as possible (lightweight old android version emulator atleast consume 850MB-1GB RAM)

Can you suggest me a good image and instruction about how to run it with x11docker?
(You can add to https://github.com/mviereck/x11docker#examples)

https://github.com/budtmo/docker-android (random sample)

**Comment by mviereck** [comment]
> Again i have another problem (had before too). In my telegram account has several languages channels but telegram only display english languages content and rest as rectangle symbols. In this cause i want to fix to display every languages (not just selected languages)

Likely the image misses a font that can display chars of other languages.
I recommend that you build your own telegram image that contains additional fonts. I am not sure which fonts to recommend. This also depends on the desired languages.

> I cannot input (type messages) in different language, all input auto type in english characters, which option should i use to solve that problem. --dbus, --dbus-system or --hostdbus? or anything else?

You need support of other input methods in the image, e.g. `fcitx-pinyin`.
Compare #269 and chapter "Language locales" in README: https://github.com/mviereck/x11docker#language-locales


A custom telegram Dockerfile could look like:
```
FROM debian:buster
RUN apt-get update
RUN apt-get install -y --no-install-recommends telegram-desktop fcitx-pinyin fonts-noto-core
CMD telegram-desktop
```
You'll need to somehow configure `fcitx`.
I am neither experienced with other fonts nor the input methods, sorry. I hope the hints above can help you.

> I want to login to two telegram accounts, how to keep separate persistent configs? 

You can specify different home folders with a path. Example:
```
x11docker --home=$HOME/x11docker/telegram-1 xorilog/telegram
x11docker --home=$HOME/x11docker/telegram-2 xorilog/telegram
```
Compare `x11docker --help`:
```
 -m, --home [=ARG]     Create a persistant HOME folder for data storage.
                       Default: Uses ~/.local/share/x11docker/IMAGENAME.
                       ARG can be another host folder or a Docker volume.
                       (~/.local/share/x11docker has a softlink to ~/x11docker.)
                       (Use --homebasedir to change this base storage folder.)
```

> Yes. cannot visit to any site but no such problem for telegram.

I am not sure what's wrong with chromium here. Likely it is a chromium issue. Maybe the `--no-sandbox` option does not work correct anymore. Your screenshot shows a sanbox issue.
I cannot check myself here, can't pull the image yet. 

> I prefer run android emulator or simulator in docker, only for telegram app. Actually i'm trying to save host system resources consumption much as possible (lightweight old android version emulator atleast consume 850MB-1GB RAM)
Can you suggest me a good image and instruction about how to run it with x11docker?

There are already too much questions for a single ticket. Please open a new ticket for new questions.

**Comment by temporallyaccount** [comment]
Thank you @mviereck :sunglasses:
