### ISSUE TITLE
Feature request: Run in container instead of creating a new one from image

### ISSUE THREAD

**Issue by gcoimbra** [mviereck/x11docker#288]
Hello.
So I have this enormous container with about 30 GB size. I don't want to instantiate a new one just to run x11docker.
Anyway to run x11docker with it?

**Comment by mviereck** [comment]
x11docker is not designed to start already existing containers. There is a docker issue re-using X unix sockets.

However, you can create a new image from an existing container with `docker commit`: https://docs.docker.com/engine/reference/commandline/commit/
You can run x11docker with this new image. 

I do not recommend this way but rather to set up a Dockerfile containing everything needed. But it is possible to do so, though.

**Comment by mviereck** [comment]
Another idea: Run:
```
x11docker --xoverip --no-auth --xonly --showenv
```
This just runs an X server only. Security risk: cookie authentication is disabled. In worst case others in the network may access it over TCP, too.
This prints variable `DISPLAY`, e.g. `DISPLAY=172.17.0.1:102`.
In your container run your desired application with e.g. `DISPLAY=172.17.0.1:102 xterm`.
