### ISSUE TITLE
Add some unit tests to ensure functionality and prevent regressions

### ISSUE THREAD

**Issue by dragon788** [mviereck/x11docker#29]
BATS or another TAPS compliant framework could integrate nicely with the script and make it easier to diagnose issues on different platforms.

**Comment by dragon788** [comment]
“Testing Your Shell Scripts, with Bats” @pimterry https://medium.com/@pimterry/testing-your-shell-scripts-with-bats-abfca9bdc5b9

**Comment by mviereck** [comment]
I finally decided not to use BATS. 
It seems to be to be too much effort while only covering a rather small part of x11docker functionality. It is not able to do checks within running GUI environments.

I rather rely on bug reports. And many reported bugs point on unforeseen edge cases and/or special setups.

Anyway, thanks for your recommendation!
