### ISSUE TITLE
--share <host_path>:<container_path>[:ro]

### ISSUE THREAD

**Issue by matallui** [mviereck/x11docker#291]
The current `--share` option only allows to share a file/directory at the same location as the host.
In my case, I want to share a host directory/docker volume at a specific place in the container, and can't find a way to do it.

I'm proposing that the `--share` option should work similar to `-v` for docker.
Either that, or maybe there could be another option that would allow to pass extra args to docker directly.

**Comment by eine** [comment]
You can pass extra args directly. See: https://github.com/mviereck/x11docker#terminal-usage

`x11docker [OPTIONS] -- DOCKER_RUN_OPTIONS -- IMAGE [COMMAND [ARG1 ARG2 ...]]`

**Comment by matallui** [comment]
Oh, I must've missed that. Thank you!!
