### ISSUE TITLE
Feature request: adding tab completion to x11docker command line option.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#292]
Hi,

I noticed that there are so many options supported by x11docker, but currently it doesn't support command line option auto-completion by `<tab>` key.

Could you please kindly add this feature?

Regards,
HY

**Comment by mviereck** [comment]
I once had a look how to provide this feature. It looked like a difficult task and I decided not to do it. Maybe I reconsider it.
What already works: You don't need to type the full option. It only needs enough chars to be unique.
For example, `--nx` will be parsed as `--nxagent`, `--cap` as `--cap-default`. This is a feature of `getopt` that is used by x11docker for option parsing.

**Comment by mviereck** [comment]
Another possibility is to use `x11docker-gui`. It allows to choose desired options with some mouse clicks and to copy the generated command to clipboard.

**Comment by hongyi-zhao** [comment]
From a personal preference point of view, I always think that the CLI based method is more efficient than the GUI one. You can see this in the working manners of Emacs and Vim.

**Comment by mviereck** [comment]
Maybe I'll add tab completion one day, but not yet. Closing for now.
