### ISSUE TITLE
Cannot start ssh inside running container

### ISSUE THREAD

**Issue by namnoit** [mviereck/x11docker#295]
I cannot start ssh inside a running x11docker/deepin base (or any other base x11docker image), (openssh-server is already installed):
`error: Bind to port 22 on xxx failed: Permission denied`
and
`Failed to start OpenBSD Secure Shell server`
What's wrong with me? Can I start ssh inside docker?
Thanks.

**Comment by mviereck** [comment]
By default Docker container have less capabilities than regular applications, and x11docker containers even less.
Likely you need capability `CAP_NET_BIND_SERVICE`. Compare `man capabilities`. You can add it as a custom docker run option with `-- --cap-add CAP_NET_BIND_SERVICE --`.

What is your full command to run x11docker and the ssh server?

**Comment by namnoit** [comment]
I start x11docker using
`x11docker --desktop --init=systemd --home --sudouser -- --cap-ad=IPC_LOCK --security-op seccomp=unconfined -- myimage`
And start ssh using
`/etc/init.d/ssh start`

**Comment by mviereck** [comment]
I have success with:
```
 x11docker --desktop --init=systemd --home --sudouser --cap-default -- --cap-add=IPC_LOCK --security-opt seccomp=unconfined -- x11docker/deepin
```
I've installed `openssh-server` and started with:
```
sudo systemctl start ssh
```
Note the additional option `--cap-default` and the usage of the systemd service instead of the sysvinit script.

**Comment by eine** [comment]
> Edit: I am a bit surprised that I did not need `--cap-add=CAP_NET_BIND_SERVICE`.

Maybe it's because the service was started inside the container only and not bind to a port on the host?

**Comment by mviereck** [comment]
> Maybe it's because the service was started inside the container only and not bind to a port on the host?

Maybe. But due to similar capability issues I was not able to update `iptables` in container. I would have expect this to fail.

**Comment by namnoit** [comment]
> I have success with:
> 
> ```
>  x11docker --desktop --init=systemd --home --sudouser --cap-default -- --cap-add=IPC_LOCK --security-opt seccomp=unconfined -- x11docker/deepin
> ```
> 
> I've installed `openssh-server` and started with:
> 
> ```
> sudo systemctl start ssh
> ```
> 
> Note the additional option `--cap-default` and the usage of the systemd service instead of the sysvinit script.
> 
> Edit: I am a bit surprised that I did not need `--cap-add=NET_BIND_SERVICE`.

Thank you, it works for me

**Comment by mviereck** [comment]
I've build a test image with this Dockerfile:
```
FROM x11docker/deepin
RUN apt-get install -y openssh-server
RUN systemctl enable ssh
```
Running it automatically starts the ssh server:
```
x11docker --desktop --init=systemd --cap-default -- --cap-add=IPC_LOCK --security-opt seccomp=unconfined -- testimage
```
