### ISSUE TITLE
Add monitor number flag

### ISSUE THREAD

**Issue by blkmlk** [mviereck/x11docker#296]
Hi,

I think it would be great to be able to specify an output name or a monitor number to run x11docker in fullscreen mode with the monitor's size. I found it really useful for me because I use two monitors. Xephyr has the "output" flag which allows us to pass a specific monitor but I'm not sure about other X servers.

Thanks.

**Comment by mviereck** [comment]
I am not sure how to implement this.
I found that normally the fullscreen window appears on the monitor where the command is executed, e.g. in a terminal emulator. But that likely depends on the window manager (here `xfwm4`).
Also there is no comparable `--output` option for weston or nxagent. And even for Xephyr it might fail in a Wayland/Xwayland environment.

Maybe I could implement an option`--xopt` that allows to add arbitrary options to the X server command.

**Comment by blkmlk** [comment]
Yes, I expected that won't be applicable for other servers but I think it might be really useful for other users who have several monitors

**Comment by mviereck** [comment]
I've added an experimental option `--xopt` in https://github.com/mviereck/x11docker/commit/e205f48997725f60719ab480de4b536cbc24e9bf .

Something like this should work:
```
x11docker --xephyr --xopt="-output VGA-2" --fullscreen [...]
```

However, my own attempts result in a segmentation fault of Xephyr. Did you try out option `-output` with Xephyr?

**Comment by blkmlk** [comment]
It works the same way as before. To make it using -output flag we have to remove -fullscreen flag

**Comment by mviereck** [comment]
I've made  fix in x1docker that does not set a screen size if `--xopt` contains Xephyr option `-output`.
Now I don't get segfaults and can just run:
```
x11docker --xephyr --xopt="-output eDP" [...]
```
(`eDP` is my laptop monitor, replace with your intended monitor).
Can you please try out if it works for you?
