### ISSUE TITLE
Debian 10 (buster) dependencies are incorrect

### ISSUE THREAD

**Issue by SimplicityGuy** [mviereck/x11docker#297]
`xdpyinfo` is listed as a package to be installed, however, this package does not exist:
```
foo@6953a5c825a4:/# apt search xdpyinfo
Sorting... Done
Full Text Search... Done
```

Instead, this utility is part of `x11-utils`. Please refer to: https://packages.debian.org/buster/x11-utils.

**Comment by mviereck** [comment]
Indeed. Is fixed now. Thank you!
