### ISSUE TITLE
How to run that using x11docker?

### ISSUE THREAD

**Issue by itsnotsaved** [mviereck/x11docker#299]
https://github.com/aind-containers/aind
it provide instruction for VNC

**Comment by mviereck** [comment]
I don't know. The setup looks complicated. Please rather ask there how this should be started without VNC if an X server is given.

**Comment by gistsy** [comment]
Above repo about anbox made for docker by volunteer
https://docs.anbox.io/userguide/install.html
https://docs.anbox.io/userguide/install.html#install-the-anbox-snap
https://github.com/anbox/anbox

@mviereck then can you tell how to run original anbox using x11docker

**Comment by mviereck** [comment]
I am not really in investigating this. The setup needs additional kernel modules that I don't want to install on my system.
Please make yourself familiar with x11docker and try out, or just use the ready VNC solution.
