### ISSUE TITLE
How to release the mouse confined in the container window?

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#302]
When I use x11docker/deepin started by x11docker, I suddenly find that the mouse confined in the container window. I don't know why this event has been triggered and how to release it for full screen mobility.

Any hints for this problem?

Regards,
HY

**Comment by mviereck** [comment]
This is a feature of Xephyr, you find a hint in the window title.
Mouse and keyboard are grabbed and released with keys CTRL+SHIFT.
