### ISSUE TITLE
When starting self created deepin-wine image, /etc/profile.d/bash_completion.sh can't be sourced automatically.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#304]
I installed bash-completion package in the self created deepin-wine image, but when I start the image through x11docker, I find that the corresponding script, i.e., */etc/profile.d/bash_completion.sh*, won't be sourced automatically upon the system's startup. As a result, the command tab completion will be unavailable unless I manually source the above script again. See the following for the installed package info:

```
werner@c8db32fab2b1:~/Desktop$ dpkg -l | grep bash-completion
ii  bash-completion                               1:2.1-4.3                         all          programmable completion for the bash shell
```

Any hints for this problem?

Regards,
HY

**Comment by mviereck** [comment]
Maybe you have to enable it in `/etc/bash.bashrc`. 
Compare:
```
$ docker run --rm x11docker/deepin cat /etc/bash.bashrc

[...]
# enable bash completion in interactive shells
#if ! shopt -oq posix; then
#  if [ -f /usr/share/bash-completion/bash_completion ]; then
#    . /usr/share/bash-completion/bash_completion
#  elif [ -f /etc/bash_completion ]; then
#    . /etc/bash_completion
#  fi
#fi
[...]
```

**Comment by hongyi-zhao** [comment]
Do you mean by `--keepcache` and `docker (container) commit` based methods to create a new image which includes this change?

**Comment by mviereck** [comment]
> Do you mean by --keepcache and docker (container) commit based methods to create a new image which includes this change?

I'll never recommend this way.
Instead, I see three possibilities:
 - A customized `bash.bashrc` that is added to the image with build instruction `COPY`.
 - Some parsing done in Dockerfile to remove `#` in the completion part.
 -  Just adding some lines at the end of `bash.bashrc` with `RUN echo [...] >> /etc/bash.bashrc`.

Something like this could work:
```
RUN echo "\n\
# enable bash completion in interactive shells\n\
if ! shopt -oq posix; then\n\
  if [ -f /usr/share/bash-completion/bash_completion ]; then\n\
    . /usr/share/bash-completion/bash_completion\n\
  elif [ -f /etc/bash_completion ]; then\n\
    . /etc/bash_completion\n\
  fi\n\
fi\n\
" >> /etc/bash.bashrc
```

**Comment by hongyi-zhao** [comment]
Thanks for your clarification of your point in more detail.

**Comment by hongyi-zhao** [comment]
I find a very strange thing: I installed [the latest deepin 20](http://cdimage.deepin.com/releases/20/deepin-desktop-community-1002-amd64.iso) system on my hard disk, and find that even the lines corresponding to bash completion in /etc/bash.bashrc is commented out, the tab completion for commands is still enabled.
