### ISSUE TITLE
The problem when transfer file whose name contains Chinese character using File Transfer of wechat started by x11docker.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#305]
When I try to transfer file whose name contains Chinese characters using File Transfer of WeChat started by x11docker, I meet the following error: file cannot be sent as it's in use. Select another file. See the following screenshot for more info:

![image](https://user-images.githubusercontent.com/11155854/99212285-a9951780-2805-11eb-94f9-041ce24af7df.png)

If I click the "OK" button shown in the above screenshot, the file transfer can still proceed. This problem doesn't appear for the case when the  Chinese characters only exists in the path component.

Though I post this problem here, I don't think it's x11docker problem; instead, it should be the problem of wechat itself.

Any hints for this problem?
Regards,
HY

**Comment by mviereck** [comment]
I have no real idea, sounds indeed like a wechat issue.
Maybe it helps to set the system language to chinese with `--lang=zh_CN`.

**Comment by hongyi-zhao** [comment]
Wonderful. I tried with *--lang=zh_CN* and *--lang=zh_CN.UTF-8*, They can all solve the problem. So, I want to know which form should I use.

The locale settings of the host are shown as below: 

```
werner@X10DAi:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by mviereck** [comment]
> Wonderful. I tried with --lang=zh_CN and --lang=zh_CN.UTF-8, They can all solve the problem.

Great! It was a quite vague idea, I did not believe it would really help.

> So, I want to know which form should I use.

x11docker automatically adds the `UTF-8` suffix, so both forms are equivalent.

**Comment by hongyi-zhao** [comment]
Deepin apricot doesn't habe this problem. So, there is no need to set the --lang=zh_CN or --lang=zh_CN.UTF-8 options when staring the containter with x11docker.

**Comment by mviereck** [comment]
Great!
