### ISSUE TITLE
Keyboard irresponsive when running image via x11docker

### ISSUE THREAD

**Issue by nicolasduminil** [mviereck/x11docker#306]
Hello,
I have an image containing Ubuntu, Gnome and Java 8. I want to run Java GUI (Swing) applications in it. I'm using x11docker:

    x11docker --quiet my-image my-java-gui

I got the following warning:

      (java:114): dbind-WARNING **: 16:55:43.120: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-peuXF2t9iQ: Connection refused

The GUI displays correctly, the mouse works as expected, however when I try to type in the text fields (on the host machine, of course) nothing happens.
Trying the same with gedit, like below works as expected:

    x11docker --quiet my-image gedit

It displays the following but it works:

    (org.gnome.gedit:114): dbind-WARNING **: 18:15:49.144: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-peuXF2t9iQ: Connection refused  
    (org.gnome.gedit:114): Gtk-WARNING **: 18:15:51.283: Calling org.freedesktop.portal.Inhibit.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Inhibit” on object at path /org/freedesktop/portal/desktop

What could be the problem here, what did I miss ?
Many thanks in advance.
Kind regards,
Nicolas

**Comment by nicolasduminil** [comment]
Just a short update to say that I noticed that when I type on the keyboard they keys appear in the terminal window of the host where I ran the x11docker command. Launching it in background doesn't change anything.

**Comment by mviereck** [comment]
This sounds odd.
Maybe the java application reads the keyboard in an indirect way.
Try to run with undocumented x11docker option `--xtest`. This enables X extension XTEST that partially affects the keyboard (allows to control it remotely).
