### ISSUE TITLE
x11docker is not working on Raspberry Pi 4

### ISSUE THREAD

**Issue by sotnikov-link** [mviereck/x11docker#308]
Hello. I want to run x11docker on RPi4 4GB. I can run `xeyes`, but command `x11docker --desktop --verbose --size 320x240 x11docker/lxde` is not working: [log file](https://github.com/mviereck/x11docker/files/5612557/x11docker--desktop--verbose.log).

What can I do?

**Comment by mviereck** [comment]
You try to run an amd64 image on an arm architecture host.
Please try arm images instead, or build one yourself. You can take e.g. the Dockerfile of `x11docker/lxde` and build it on the raspberry.
Alternatively (less performant) you can use QEMU. Compare https://github.com/mviereck/x11docker/wiki/Multiarch-setups-with-QEMU

**Comment by sotnikov-link** [comment]
Thank you!

It works: https://youtu.be/sCwNRhYtuSw

**Comment by umarcor** [comment]
FTR, using QEMU for running amd64 on RPi4 might have time/date issues: dbhi/qus#6.
