### ISSUE TITLE
About the list of all packages possiably depenced by x11docker.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#312]
[Here](https://github.com/mviereck/x11docker/wiki/Dependencies#table-of-all-packages) you listed all possibly needed commands and their package names for all possible x11docker options. But I'm still confused by this table given by you. Say, the `mesa-utils` and `mesa-utils-extra` packages listed in the [Dependencies in image](https://github.com/mviereck/x11docker/wiki/Dependencies#dependencies-in-image) are not included here. But by the name, you called it "Table of all packages". Any hints for this question?

Regards,
HY

**Comment by mviereck** [comment]
I assume that every host system will have its graphic drivers set up already. So no need to explain this in x11docker wiki in all possible variations.
