### ISSUE TITLE
ibus layout switching issues with nxagent

### ISSUE THREAD

**Issue by harporoeder** [mviereck/x11docker#315]
Hello.

I use ibus for Chinese input. I can successfully input characters as I expect. Specifically with nxagent though I cannot get the key combinations (such as control + space but it could be anything I have tried others) to switch layouts, I have to click on the dock menu to switch. When I use either xpra or xephry it works fine, and I can use the shortcut to switch layouts.

My test container is a simple derivation of your mate desktop container:

```
FROM x11docker/mate

RUN apt-get install -y ibus ibus-pinyin fonts-noto-cjk

ENV GTK_IM_MODULE="ibus"
ENV QT_IM_MODULE="ibus"
ENV XMODIFIERS="@im=ibus"
```

From there I `x11docker --desktop --nxagent --clipboard --dbus mate`, start `ibus-daemon` and configure the layouts.

I'm not sure where the issue may be. I generally prefer using nxagent but the alternatives are definitely a work around. I am using arch linux with an xorg base. If you happen to know of a way to get this working great! If not oh well.

Thanks for all the work on x11docker I use it daily!

**Comment by mviereck** [comment]
I have a quite similar test setup with `fcitx`. It works well with `--nxagent`. The key shortcut is ctrl+space.
I wonder why you have an issue with `ibus`. Currently I have no idea.

Yet I am building a test image with `ibus` to see if I can reproduce.

**Comment by mviereck** [comment]
I can reproduce the issue with `ibus` and `--nxagent`. Though, I have no idea what is going wrong because the combination of `fcitx` and `ibus` works well and accepts keyboad shortcuts.

Btw., you can run the daemon with x11docker option `--runasuser ibus-daemon -d`. Please update x11docker first, yet I've commited a fix.

**Comment by harporoeder** [comment]
I'll probably end up switching to `fcitx` then I'm not committed to `ibus`. Thanks for the amazing response time and going through the effort of reproducing it. I was hoping it might of been something simple and I don't think I will dig much deeper to try and find the root cause.

**Comment by mviereck** [comment]
> I'll probably end up switching to fcitx then I'm not committed to ibus. 

That is likely the easiest solution. I don't know where the input methods might differ, I have no own experience with it.
