### ISSUE TITLE
loss of mouse and keyboard when x11docker launched from a remote terminal or crontab

### ISSUE THREAD

**Issue by Mike20117** [mviereck/x11docker#316]
If I start x11docker from a terminal on the host system it works fine
  x11docker x11docker/check
I get the check application and I can interact with it via the mouse.

However if I start x11docker from a remote login (e.g. putty from another system) the check application will come up (on the host monitor) but the mouse (on the host) is not recognized.  What is worse is when the container exits it DOES NOT return control of the mouse and keyboard to the host.
  x11docker --hostdisplay x11docker/check

I have to REBOOT the host to get the mouse and keyboard back. 

I have tried stopping and restarting the X server on the host as well as the docker service itself (in case it was hanging on to something).  The X11 login interface come up but it won't recognize the mouse of keyboard.  If I login to the host remotely and look at the X11 log file (when I restart it) it appears to be detecting the mouse and keyboard properly.

The host is Centos 7.5 system.

Can you reproduce this and have any suggestions on how to get the mouse and keyboard to be recognized by the container and on exit back to the host.  A fix (or instructions) on how to get the host to recognize the mouse and keyboard is the most import issue to me but having it work for the apps in the container would be nice.

The reason I am trying to do this (and maybe there is another way to do what I need) is for GUI testing.  I run the tests in a 'clean and known configuration' container and this is working great from a console but I want to run these via a crontab (as well as be able to kick them off remotely via a putty/ssh connection).  Right now this is actually working (as the GUI tests don't need any mouse or keyboard input) but it leaves the host system without its mouse or keyboard so we can't interact with it (and there are other tests that need to be run on the host directly).  Rebooting the system every time we need access to the local mouse and keyboard is not a good solution.

As an aside thank you for putting this out there, it is very useful.

**Comment by mviereck** [comment]
This is quite odd und I still try o understand.

As a first question: Which desktop environment is running on the host? 
If it is Gnome 3, please try with another one, for example Xfce. (I recently got a bug report with odd behaviour on Gnome 3 #313).

**Comment by mviereck** [comment]
> However if I start x11docker from a remote login (e.g. putty from another system) the check application will come up (on the host monitor) but the mouse (on the host) is not recognized. What is worse is when the container exits it DOES NOT return control of the mouse and keyboard to the host.
x11docker --hostdisplay x11docker/check

Do I understand right that neither the host nor the check application can be used with the mouse? Doesn't it move at all or do only clicks not work?
How do you provide variable `DISPLAY` in a remote login? Do you set it manually?

One point is, x11docker itself does not grab mouse or keyboard at all. And option `--hostdisplay` just allows an X application in container to access the host X server.
Just in case, did you try other X server options like `--xephyr`?

Another check: Add option `--clipboard` to `--hostdisplay` to avoid restricted cookies:
```
 x11docker --hostdisplay --clipboard x11docker/check
```

> The X11 login interface come up but it won't recognize the mouse of keyboard.

The login interface is likely a display manager. If it is `gdm` from Gnome, replace it e.g. with `lightdm`,  just in case here is another Gnome issue.

**Comment by Mike20117** [comment]
The host is running Gnome 3.22.2  I will try another desktop

As far as your other questions

The mouse does not move at all nor is any keyboard input accepted in the container (x11docker/check) or in the host once the container exits.

DISPLAY is not set in the terminal, I can try and set it.

I will give --clipboard a try.

I did try a few other containers 
   x11docker --hostdisplay --desktop x11docker/fvwm
   x11docker --hostdisplay --desktop --gpu --init=systemd  x11docker/gnome

Both get mouse control in the container and release it back to the host on exit (this is without setting DISPLAY in the terminal, I still need to try that).  The fvwm one provides me with a desktop, the gnome one just gives me a cursor (which I can move) and an otherwise blank screen.

Unfortunately my test containers behave like x11docker/check and don't release the mouse and keyboard back to the host.  I was hoping to not have to rebuild them but looks like I may need to and get them closer to fvwm (or another container with a window manager in it).

I have not tried having the container run its own X11 server (e.g. --xephyr) as for my purposes, I really need it to be using the host's X11 with graphics hardware acceleration.

**Comment by mviereck** [comment]
> The host is running Gnome 3.22.2 I will try another desktop

This is worth a try. Gnome can cause serious issues.

> I will give --clipboard a try.

Try `x11docker --hostdisplay --clipboard x11docker/check`.

> DISPLAY is not set in the terminal, I can try and set it.

It must have been set already, otherwise x11docker could not run `--hostdisplay`. I am just curious because it is missing in ssh sessions. I am not familiar with putty, maybe there is a difference.

>  x11docker --hostdisplay --desktop x11docker/fvwm

You should not combine `--hostdisplay --desktop`. Option `--hostdisplay` is intended for single applications only.

> I have not tried having the container run its own X11 server (e.g. --xephyr) as for my purposes, I really need it to be using the host's X11 with graphics hardware acceleration.

This check is important to see if this makes a difference in mouse and keyboard behaviour.

**Comment by Mike20117** [comment]
So setting DISPLAY to :0 made a difference
Before without it set I would get the the check application on a gray background and no mouse or keyboard control and I would not get control back on container exit.

Now with it set I get the check application (on the host's desktop) but with no controls (it is just a gray window) but I do have mouse and keyboard control (I can mouse around the host's desktop) and over the container's check application window.  I get errors like:
  X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x142
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 3 (X_ShmPutImage)
  Resource id:  0x280000c

--clipboard did not make a difference

I will try an different desktop once I figure out how to modify my Centos 7.5 install to do so, sticking with Gnome is not a requirement.

**Comment by mviereck** [comment]
> So setting DISPLAY to :0 made a difference

Oh, ok.
Than I assume x11docker did not use option `--hostdisplay` but option `--xorg`. There should have been a message on this in x11docker's terminal output.

> Before without it set I would get the the check application on a gray background and no mouse or keyboard control and I would not get control back on container exit.

So this might be an issue with option `--xorg`.

Can you please show me the x11docker terminal output in your further tests?

> I will try an different desktop once I figure out how to modify my Centos 7.5 install to do so, sticking with Gnome is not a requirement.

If this is just a `DISPLAY` / `--xorg` issue, you might not need to change the desktop.

**Comment by mviereck** [comment]
> Now with it set I get the check application (on the host's desktop) but with no controls (it is just a gray window) but I do have mouse and keyboard control (I can mouse around the host's desktop) and over the container's check application window. 

Good, that's some progress. I am not sure why you get a gray window only.
Please install `Xephyr` and try with `--xephyr`, too.

>  I get errors like: [...]
> --clipboard did not make a difference

I get similar error messages with `--hostdisplay`, but a valid x11docker/check window. 
The error messages disappear with `--hostdisplay --clipboard`.

**Comment by Mike20117** [comment]
I don't have a free system to install Xephyr on at the moment or change graphical desktops but setting DISPLAY in the putty sessions and exporting DISPLAY (not just setting it) in the shell cron executes resolves the keyboard and mouse issue.  Still not sure why the x11docker/check does not populate its window but the programs I need to run (Qt based) do (even without --clipboard) so I am happy.

I'll revisit Xephyr and the desktops when I get the chance. 

I'll close this, thanks for the help.

Not sure it is worth the effort to update the README to point out when using --hostdisplay from a remote terminal make sure DISPLAY is set to a valid entry where the display is running on the host (e.g. ":0").
