### ISSUE TITLE
ERROR:  "/usr/bin/docker-entrypoint.sh": permission denied: unknown.

### ISSUE THREAD

**Issue by apiszcz** [mviereck/x11docker#319]
What am I doing wrong here? 
Tx

```
~/p/docker# docker --version
Docker version 20.10.2, build 2291f61

docker run -d --privileged -p 3389:3389 -p 5900:5900 -p 2222:22 --name chrome sfoxdev/ubuntu-rdp
Status: Downloaded newer image for sfoxdev/ubuntu-rdp:latest
d445562d8b506e5251c7442a3e30c35e4c6c5b1467cc8d85d5d318396003f221
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/usr/bin/docker-entrypoint.sh": permission denied: unknown.
~/p/docker# ls -lh /usr/bin/docker-entrypoint.sh
ls: cannot access '/usr/bin/docker-entrypoint.sh': No such file or directory

```

**Comment by mviereck** [comment]
This is no x11docker issue at all, you even don't use x11docker.

However, it looks like the `/usr/bin/docker-entrypoint.sh` in image does not have the executeable bit that one would set with `chmod +x`.  Please ask the developer of `sfoxdev/ubuntu-rdp` to fix this.

> ~/p/docker# ls -lh /usr/bin/docker-entrypoint.sh
ls: cannot access '/usr/bin/docker-entrypoint.sh': No such file or directory

You would have to check in container, not on host. Try:
```
docker run --rm sfoxdev/ubuntu-rdp ls -lh /usr/bin/docker-entrypoint.sh
```

**Comment by apiszcz** [comment]
(submitted issue). "Please ask the developer of sfoxdev/ubuntu-rdp to fix this., "
