### ISSUE TITLE
Why scripts are not executable after git clone?

### ISSUE THREAD

**Issue by arteniioleg** [mviereck/x11docker#32]
I know git saves the file executable flags (I have some bash scripts in one of my projects)

**Comment by arteniioleg** [comment]
Just do 

```sh
chmod +x x11docker*
git add .
git commit -m 'made scripts executable'
git push
```

**Comment by mviereck** [comment]
Thank you!

You gave me the needed push to finally try out the `git` command.
Until now I've uploaded the files directly on the github page. The executeable bit got lost that way. I thought it would be some sort of security feature of github; but maybe it is just not possible to transfer the bit this way.

I just checked, even the provided zip-Download contains executeables now.
