### ISSUE TITLE
Failed to ssh login in the container.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#321]
I started the [hongyizhao/deepin-wine:apricot](https://hub.docker.com/repository/docker/hongyizhao/deepin-wine) docker image with x11docker with the bridge network mode, and try to login it with ssh. See the following info for the sshd running in the container: 
```
werner@320a7a91cca4:~/Desktop$ ps -ef | grep sshd
root        2455       1  0 20:48 ?        00:00:00 /usr/sbin/sshd -D
```
But I don't know the password and I really don't set any password for the user. I want to know if x11docker sets the password when starting the container.

Regards,
HY

**Comment by mviereck** [comment]
The password is `x11docker`, the same as with option `--sudouser`.

**Comment by hongyi-zhao** [comment]
Thanks a lot. It does the trick. It seems that this is not explicitly stated in the documentation.

**Comment by mviereck** [comment]
> It seems that this is not explicitly stated in the documentation.

I've added a password note now in `--help`:
```
x11docker sets up an unprivileged container user with password 'x11docker'
and restricts container capabilities. Some applications might behave different
than with a regular 'docker run' command due to these security restrictions.
Achieve a less restricted setup with --cap-default, --sudouser or --user=root.
```
