### ISSUE TITLE
Enable/disable MIT-SHM extension of X server.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#326]
See [here](https://github.com/bestwu/docker-wechat/issues/25#issuecomment-785048160) for the suggestion given by `bestwu` to solve the following problem when starting docker container:

`X Error of failed request: BadValue (integer parameter out of range for operation)`

What's the corresponding command option(s) of x11docker to enable/disable MIT-SHM extension of X server? 

Regards,
HY

**Comment by mviereck** [comment]
x11docker automatically cares for MIT-SHM.
MIT-SHM is disabled in all X server options so it causes no issues.

One exception is option `--hostdisplay` that accesses the host X server. 
By default, with `--hostdisplay` untrusted cookies are provided that disable usage of MIT-SHM.
If options `--clipboard` or `--gpu` are enabled along with `--hostdisplay`, trusted cookies are used and x11docker sets `--ipc=host` to allow access to MIT-SHM.

So x11docker provides no option to control MIT-SHM by the user, but takes care for all cases where it could cause troubles.

**Comment by hongyi-zhao** [comment]
Thanks a lot for your explanations. This question seems to involve a lot of similar but different concepts and doesn’t seem to be an easy-to-understand field for me, at least for now.

**Comment by mviereck** [comment]
> This question seems to involve a lot of similar but different concepts and doesn’t seem to be an easy-to-understand field for me, at least for now.

Essentially it boils down to this:
 - MIT-SHM allows X applications to share memory with the X server.
 - Container applications are not allowed to access MIT-SHM. This can cause issues, error messages or garbage in graphics.
 - Docker option `--ipc=host` allows access to MIT-SHM for containers, but severely breaks container isolation.
 - To avoid this x11docker runs X servers without extension MIT-SHM.

**Comment by hongyi-zhao** [comment]
Thanks a lot for breaking down this question with clear logic.
