### ISSUE TITLE
Firefox / Chromium hard crashes in Podman

### ISSUE THREAD

**Issue by pcrockett** [mviereck/x11docker#330]
Hi, I am trying to troubleshoot why Firefox and Chromium are crashing inside my x11docker containers under Podman.

When Firefox crashes, it's such a hard crash that the crash reporter doesn't even come up, and Firefox is unable to restore my tabs when I start it up again. All I have to do is navigate to a web page or two and then everything dies. When running Firefox from command line, I get this output:

```plaintext
ExceptionHandler::GenerateDump cloned child 611
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Bus error (core dumped)
```

My Dockerfile looks like this:

```plaintext
FROM docker.io/x11docker/xfce
RUN \
  apt-get update \
  && apt-get upgrade --yes \
  && apt-get install --yes nano htop gnupg wget curl git firefox-esr
```

_You can replace `firefox-esr` with `chromium` and you'll get similar crashes, albeit less frequently._

The command I use to run the container looks like this:

```bash
x11docker --podman --desktop --cap-default --xorg localhost/web
```

I have tried various combinations including using the Xephyr window server, adding `--gpu`, removing `--desktop` and running `firefox-esr` directly on the `--hostdisplay`, etc. and can't seem to get it to stop crashing.

Interestingly, I tried installing Gnome Web (Evolution) and that browser seems to be pretty stable. It's just the "mainstream" browsers that really enjoy crashing.

My host machine is a laptop running EndeavourOS with i3wm.

What would be the next step to troubleshoot this?

**Comment by mviereck** [comment]
Compare my firefox example in https://github.com/mviereck/x11docker#examples :
```
x11docker --share $HOME/Downloads -- --tmpfs /dev/shm -- jess/firefox
```
firefox needs a lot of RAM in `/dev/shm`, more than provided by docker by default. The default of podman might be too small, too. 
Try to add `-- --tmpfs /dev/shm --`.  (Though, I did not test if this is supported by podman.)

Maybe chromium has the same issue (and same fix). Previously it worked without fixing `/dev/shm`.
Previously chromium failed if started without `--no-sandbox` in a container. I am surprised that it started in your setup.
My example: `x11docker -- jess/chromium --no-sandbox`

**Comment by pcrockett** [comment]
Ah, I missed that example. Yup, that seems to have done the trick, thanks.

I think I was able to omit `--no-sandbox` because I'm also using `--cap-default` in my x11docker command.

By the way, it looks like `--cap-default` is required as well for Firefox (at least on my setup). Without `--cap-default`, Firefox seems to lock up and become unresponsive... kinda. Partially. In a weird way. Hard to explain. So now my full command looks like this and everything seems to be working flawlessly so far:

```bash
x11docker --podman --desktop --cap-default --home --xorg --pulseaudio -- --tmpfs /dev/shm -- localhost/web
```

**Comment by mviereck** [comment]
> Ah, I missed that example. Yup, that seems to have done the trick, thanks.

For chromium, too?

> I think I was able to omit --no-sandbox because I'm also using --cap-default in my x11docker command.

chromium with sandbox needed `--cap-add=SYS_ADMIN`, a quite dangerous root-like capability. 

> By the way, it looks like --cap-default is required as well for Firefox (at least on my setup). 

I'll check that.

**Comment by pcrockett** [comment]
> For chromium, too?

Yes, chromium works.

> chromium with sandbox needed `--cap-add=SYS_ADMIN`, a quite dangerous root-like capability.

Huh. Odd. To test capabilities I ran the "check" container with this command:

```bash
x11docker --podman --desktop --xorg --cap-default --home -- --tmpfs /dev/shm -- docker.io/x11docker/check
```

...and here's the output of the capability check:

```plaintext
All caps                Bounding caps    Default Docker caps    Available caps
----------              ----------       ----------             ----------       
cap_setpcap             +                +                      + 
cap_mknod                                +                      
cap_audit_write                          +                      
cap_chown               +                +                      + 
cap_net_raw                              +                      
cap_dac_override        +                +                      + 
cap_fowner              +                +                      + 
cap_fsetid              +                +                      + 
cap_kill                +                +                      + 
cap_setgid              +                +                      + 
cap_setuid              +                +                      + 
cap_net_bind_service    +                +                      + 
cap_sys_chroot          +                +                      + 
cap_setfcap             +                +                      + 
cap_sys_module                                                  
cap_sys_rawio                                                   
cap_sys_pacct                                                   
cap_sys_admin                                                   
cap_sys_nice                                                    
cap_sys_resource                                                
cap_sys_time                                                    
cap_sys_tty_config                                              
cap_audit_control                                               
cap_mac_override                                                
cap_mac_admin                                                   
cap_net_admin                                                   
cap_syslog                                                      
cap_dac_read_search                                             
cap_linux_immutable                                             
cap_net_broadcast                                               
cap_ipc_lock                                                    
cap_ipc_owner                                                   
cap_sys_ptrace                                                  
cap_sys_boot                                                    
cap_lease                                                       
cap_wake_alarm                                                  
cap_block_suspend                                               
cap_audit_read
```

So `cap_sys_admin` isn't in the list, but would the `cap_setuid` and `cap_setuid` have anything to do with it? I'm no expert with containerization yet, we're kind of pushing the limits of my knowledge here...

For what it's worth, I do get a minor error message about sandboxing in Chromium when running from the terminal, however I get that message regardless of whether I use the `--no-sandbox` parameter.

**Comment by mviereck** [comment]
> So cap_sys_admin isn't in the list, but would the cap_setuid and cap_setgid have anything to do with it? I'm no expert with containerization yet, we're kind of pushing the limits of my knowledge here...

No, that would not be enough for sandboxing in the  chromium way. I forgot the details, but its needs `mount` capabilities only provided by `SYS_ADMIN`.

> For what it's worth, I do get a minor error message about sandboxing in Chromium when running from the terminal, however I get that message regardless of whether I use the --no-sandbox parameter.

Maybe chromium disables the sandbox feature on its own now instead of just crashing. The terminal message might tell that.

For now I won't investigate further why firefox needs `--cap-default` in podman. I'll get a better internet connection within this year that makes building and downloading images for test runs easier than now.

Closing now because the issue itself is solved.
