### ISSUE TITLE
chrome debugging websocket at port 9222

### ISSUE THREAD

**Issue by mviereck** [mviereck/x11docker#332]
@drzraf wrote in #103 :

Trying Chrome + debugging websocket at port 9222:
`$ x11docker --cap-default -g --nxagent --no-entrypoint -- -p 9222:9222 -- zenika/alpine-chrome:with-webgl chromium-browser --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222`

Sadly, ws connection does not work, contrary to the bare run (not using the webgl build image which does not run natively):
`$ docker container run -it -p 9222:9222 --rm --entrypoint ''  zenika/alpine-chrome:86 chromium-browser --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --headless`

From the two `docker inspect` I couldn't spot what's wrong.
- [docker-inspect-native-alpine-chrome-86.txt](https://github.com/mviereck/x11docker/files/6127456/docker-inspect-native-alpine-chrome-86.txt)
- [x11docker-inspect-alpine-chrome-webgl.txt](https://github.com/mviereck/x11docker/files/6127457/x11docker-inspect-alpine-chrome-webgl.txt)

**Comment by mviereck** [comment]
On the first glance I see two differences:
 - Different images `zenika/alpine-chrome:with-webgl` vs ` zenika/alpine-chrome:86`. Try x11docker with `zenika/alpine-chrome:86` if the debuuging websocket works with that image.
 - x11docker sets up an unprivileged user, native docker runs with root. Try with `--user=root`.

**Comment by drzraf** [comment]
`$ x11docker --user=root --cap-default -g --nxagent --no-entrypoint -- -p 9222:9222 -- zenika/alpine-chrome:86 chromium-browser  --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222`

still does not work (`curl http://172.17.0.2:9222/json/version`)

**Comment by mviereck** [comment]
Can you show me the full terminal output of the command?

**Comment by drzraf** [comment]
`x11docker -Dv --user=root --cap-default -g --nxagent --no-entrypoint -- -p 9222:9222 -- zenika/alpine-chrome:86 chromium-browser --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222`
[log.txt](https://github.com/mviereck/x11docker/files/6135274/log.txt)

**Comment by mviereck** [comment]
I found this message:
```

x11docker note: Found 'USER chrome' in image. 
  If you want to run with user chrome instead of host user root, 
  than run with --user=RETAIN.
```
Try with `--user=RETAIN`.

**Comment by mviereck** [comment]
@drzraf 
> Try with --user=RETAIN.

Did this solve the issue?

**Comment by drzraf** [comment]
The issue happened to be https://stackoverflow.com/a/44200427/5441588
In headed mode (as with x11docker), chromium does not respect `--remote-debugging-address=0.0.0.0` but rather always bind to localhost.
Sorry for the noise.

**Comment by mviereck** [comment]
Thank you for the feedback!
Now I know it is a chrome bug, not an x11docker issue.
