### ISSUE TITLE
Question in launching container 

### ISSUE THREAD

**Issue by b573708832** [mviereck/x11docker#333]
Hello!
I have read a paper and try to run multi-robot slam simulation. When i follow the step 2--launch container from https://mistlab.ca/DOOR-SLAM/simulation.html, it seems stuck at mid of somewhere.
![question](https://user-images.githubusercontent.com/80692499/111160040-ac95ee00-85d4-11eb-8caf-04119a8b9cb1.png)
After "x11docker note: Found 'WORKDIR /home/docker/robust_distributed_slam_simulation/argos_simulation' in image.
You can change it with option --workdir=DIR.", the program doesn't seem run anymore or it's stuck. Which step may i had mistakes? And what should i do now? Thanks for your reply!!!!

**Comment by mviereck** [comment]
It seems you have literally used the command as given:
```
sudo x11docker --hostdisplay --hostnet --user=RETAIN -- --privileged -v HOST_FOLDER:/home/docker/robust_distributed_slam_simulation/argos_simulation/log -- lajoiepy/doorslam-argos-simulation:latest
```
But the instruction says:
>Designate a folder ( HOST_FOLDER ) to share files between the host machine and the Docker container. The simulation results and logs will be store in this location.
>Create a folder named datasets inside the HOST_FOLDER.

So create a host folder and replace the word `HOST_FOLDER` accordingly.

Apart from that issue, maybe nothing visible should happen at this step.
In step three you are told to access the container from a different shell with `docker exec`.

**Comment by b573708832** [comment]
Really thanks for your quickly reply!!! Problem solved. Thanks! :)

**Comment by mviereck** [comment]
You're welcome. :-)

**Comment by eine** [comment]
I just want to underline how cool this interaction was. I'm so happy to see that x11docker is being used by third-party application developers/users, then documented and read by other users, who are then coming for help and getting it in less than 24h. Nice work @mviereck!

**Comment by mviereck** [comment]
@eine Thank you! :-)
