### ISSUE TITLE
export in example for Xpra HTML5 Webclient only works in bash

### ISSUE THREAD

**Issue by orangelynx** [mviereck/x11docker#335]
The `export $Xenv` command in the snippet on [this wiki page](https://github.com/mviereck/x11docker/wiki/Container-applications-running-in-Browser-with-HTML5) for HTML5 webclients via xpra only works in `bash`, or at least not in `zsh`, because the chained variables are considered as a single variable. A hint would be appreciated.

**Comment by mviereck** [comment]
Just tried `read Xenv < <(x11docker --xvfb x11docker/lxde pcmanfm)` in zsh. 
Here this command already does not work as expected; the script should continue after reading Xenv with a daemonized x11docker in background. But it does not continue but waits for x11docker to exit.
Same issue with bash version 5.1.4.
It works in bash version 5.0.3.

It seems a completely different attempt is needed. I don't have an immediate idea. I'll look at this.

**Comment by mviereck** [comment]
What zsh version do you have?
Here reading Xenv fails with zsh 5.7.1.and 5.8.

Maybe a different attempt is needed in zsh to get the variables.

**Comment by orangelynx** [comment]
so the solution to the variable problem is that `zsh` does disable splitting by default, which can be enabled with `setopt sh_word_split`. Regarding the first command, for me it runs, but then after it has finished, i still need to to `ctrl+z` to get back to my prompt.

**Comment by mviereck** [comment]
> Regarding the first command, for me it runs, but then after it has finished, i still need to to ctrl+z to get back to my prompt.

Oh, ok. Do you have an idea how this behaviour could be changed? In bash I can just continue once read got some variable content.

> so the solution to the variable problem is that zsh does disable splitting by default, which can be enabled with setopt sh_word_split. 

Another attempt, though not elegant:
```
eval export $Xenv
```

**Comment by orangelynx** [comment]
> Oh, ok. Do you have an idea how this behaviour could be changed? In bash I can just continue once read got some variable content.

Unfortunately not, no. At least nothing that I can guarantee is good / recommended practice.

**Comment by mviereck** [comment]
I have no further idea what to do because I have no experience with zsh. I can only recommend to use bash instead.
Should we close the ticket at this point?

If you get an idea how strg+Z would not be needed, I am glad to hear.

**Comment by orangelynx** [comment]
I'd leave it open, maybe someone comes along who has more experience and can chip in.

another "[recommended practice](https://stackoverflow.com/questions/16365130/what-is-the-difference-between-usr-bin-env-bash-and-usr-bin-bash)" is to use `#! /usr/bin/env bash` for greater

**Comment by mviereck** [comment]
> I'd leave it open, maybe someone comes along who has more experience and can chip in.

I doubt that anyone will chip in here.  I'll close the ticket.

`zsh` is a rather special shell, at least I rarely hear of it. 
It could be discussed at a zsh forum how to read only a part / the first line of stdout of an application (here x11docker).
