### ISSUE TITLE
Change resolution when no connected monitor

### ISSUE THREAD

**Issue by johncadengo** [mviereck/x11docker#336]
I try to provide the `size` argument, but it has no effect.

This is the warning I keep seeing:

```
x11docker note: Could not detect any connected monitor. 
  Running on a server? Will try to set a framebuffer size 
  with xrandr --fb 1024x768 that may serve as a virtual display.
```

Is there any way to change that default value to something else?

**Comment by johncadengo** [comment]
To provide more context, I am trying to run it in a script with the options for GPU. I got this from the other issues (for example: https://github.com/mviereck/x11docker/issues/206):

```
#! /bin/bash
read Xenv < <(x11docker --xorg --gpu --xtest --display=30 --showenv --exe -- SINGULARITY_COMMAND)
env $Xenv xpra start :30 --use-display --start-via-proxy=no --daemon=no
```

**Comment by mviereck** [comment]
I found two related bugs (check of xrandr output (available monitors) and check of --size argument). 
Please update to master version and try again.

**Comment by johncadengo** [comment]
@mviereck I pulled the latest master version, with this command `curl -fsSL https://raw.githubusercontent.com/mviereck/x11docker/master/x11docker | sudo bash -s -- --update` and was able to see this note `x11docker note: Installed x11docker version 6.7.0`. However, even when supplying a size in the script, it doesn't change the size and I still see the warning about xrandr.

`read Xenv < <(x11docker --display=30 --desktop --size 1920x1080 --pulseaudio --gpu --xorg --xtest --showenv x11docker/lxde-wine)`

Is that correct?

My current workaround is that once I am able to get into the container and access terminal, I just type `xrandr --fb 1920x1080` and it will resize the desktop.

**Comment by mviereck** [comment]
Please use `--update-master` instead of `--update`.
You can just run `sudo x11docker --update-master`.

( The long command with `curl` just helps for first installation.)

**Comment by johncadengo** [comment]
@mviereck ok, that worked. Thanks!

New note, which is from the latest version.

```
x11docker note: Could not detect any connected monitor. 
  Running on a server? Will try to set a framebuffer size 
  with xrandr --fb x that may serve as a virtual display.
```

Works.

**Comment by johncadengo** [comment]
@mviereck actually, sorry. What worked was updating to the latest branch. And what works now, that didn't before, is resizing the display from the client end. However, the default size does not go through.

This is what I see in the xpra output on the host:

```
2021-03-29 13:57:46,831  running with pid 1446949 on Linux Ubuntu 20.04 focal
2021-03-29 13:57:46,836  connected to X11 display :30 with 24 bit colors
2021-03-29 13:57:46,837  initial resolution: 640x480
2021-03-29 13:57:46,843   :30.0 (217x163 mm - DPI: 75x75) workarea: 640x454
2021-03-29 13:57:46,843     monitor 2
```

Even though I supplied 1920x1080 as an argument to size to x11docker.

**Comment by mviereck** [comment]
Odd. How did you start xpra?

**Comment by mviereck** [comment]
Yet found another bug.
Please update again.
To check: The message should show the size, too:
```
  with xrandr --fb 1920x1080 that may serve as a virtual display.
```

**Comment by johncadengo** [comment]
Ok, updated,

```
x11docker note: Installed x11docker version 6.8.0-beta-2
```

Now the note says:

```
x11docker note: Could not detect any connected monitor. 
  Running on a server? Will try to set a framebuffer size 
  with xrandr --fb 1920x1080 that may serve as a virtual display.
```

And when I started xpra client up, it loads at the right size by default. Thanks! 💯

**Comment by mviereck** [comment]
Great!
Thank you for reporting and testing.
