### ISSUE TITLE
Ask after a elementary desktop or elementary/files docker :-D

### ISSUE THREAD

**Issue by KDGNOR** [mviereck/x11docker#339]
Can you make a docker? for:
https://github.com/elementary/files
with or without elementary desktop
in your: https://hub.docker.com/u/x11docker 
be very happy if u can make it :-D

Maybe so right to "/" all connected hard disk inside pc and then connected "usb sticks" and "usb hard disks"

**Comment by mviereck** [comment]
Currently I don't have a useable internet connection to build and try new images.
A Dockerfile like this one might work:
```
FROM elementary/docker:stable
RUN apt-get update
RUN apt-get install -y files
CMD files
```
Please try out. The package name might be different, as well the command name.
