### ISSUE TITLE
i3wm inside a container

### ISSUE THREAD

**Issue by skast96** [mviereck/x11docker#343]
Hello, 
I wanted to ask if you could give me a little tutorial how you build these images, is it the same as i would without x11docker or do I have to do some special tweaks to run **x11docker --desktop test/x11i3** for example. Where the starting point of the image is i3wm.

**Comment by mviereck** [comment]
> is it the same as i would without x11docker or do I have to do some special tweaks

There is nothing special in creating Dockerfiles for x11docker.
Example:
```
FROM debian
RUN apt-get update
RUN apt-get install -y i3-wm
CMD i3
```
This should just work with your command example.
