### ISSUE TITLE
Use --xorg without switching display to the new X session

### ISSUE THREAD

**Issue by AllanElleuch** [mviereck/x11docker#344]
Hi,

I would like to know if it is possible to use --xorg without  switching display to the new X session. I use it to run some GPU accelerated application. I often need to open multiple container and the fact that my monitor switch to the new session is an issue.

Do you have any tips how to do it? Should I look inside x11docker or xorg configuration? 

Edit: I am using Ubuntu 20.04 with NVIDIA proprietary driver

Thanks

**Comment by mviereck** [comment]
I don't know how to avoid the vt switch. If you have an idea how to achieve this, I am happy to somehow implement this.

Xorg has an option `-novtswitch`, but that only takes effect on exit of Xorg:
```
-novtswitch            don't automatically switch VT at reset & exit
```
Option `-keeptty` caused broken output here:
```
-keeptty               don't detach controlling tty (for debugging only)
```

Currently x11docker has an undocumented experimental option `--xopt="XORGOPTIONS"` that allows to add custom arguments to the Xorg command. That might help in investigation.
With option `--debug` you can see the generated Xorg command.

>  I use it to run some GPU accelerated application.

Note that normally only the active TTY can use the GPU.

**Comment by AllanElleuch** [comment]
Hi mviereck, thank you for the reply. 

I see if only the active TTY can use the gpu then I will switch to virtuagl + docker. 

During my investigation I went trough this article [NVIDIA Prepares XWayland OpenGL/Vulkan Acceleration Support](https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-GL-VLK-XWayland) I hope that it will really happen

This is all on my side the issue can be closed  :)

**Comment by mviereck** [comment]
> I see if only the active TTY can use the gpu then I will switch to virtuagl + docker.

You might have a look [here](https://github.com/mviereck/x11docker/issues/337#issuecomment-820132499) where multiple accelerated Xorg are set up with NVIDIA. However, I could not reproduce it so far with my intel GPU.

> During my investigation I went trough this article NVIDIA Prepares XWayland OpenGL/Vulkan Acceleration Support I hope that it will really happen

That will make multiple accelerated setups much easier. :-)
