### ISSUE TITLE
The very narrow chat window can't be enlarged by dragging with mouse when using xpra v4.1.2.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#347]
On Ubuntu 20.04, I use the git master version of x11docker to run [my docker image](https://hub.docker.com/r/hongyizhao/deepin-wine) with the `xpra v4.1.2`:

```
$ xpra --version
xpra v4.1.2
```
But I found that the height of the qq's chat window is very narrow, and can't be enlarged by dragging with mouse, as shown below:

![image](https://user-images.githubusercontent.com/11155854/115728636-3c3e7180-a3b7-11eb-92c4-4ee79f9fb564.png)

Any hints for solving this problem?

Regards,
HY

**Comment by totaam** [comment]
I believe that this has been fixed in xpra 4.1.3. Try updating.

**Comment by hongyi-zhao** [comment]
Really. The following steps fixed this problem:
```
$ sudo apt update
$ sudo apt install --reinstall xpra
$ xpra --version
xpra v4.1.3
```
But it seems that the initialization progress of the latest xpra version is very slow.

**Comment by totaam** [comment]
> But it seems that the initialization/starting progress of the latest xpra version is very slow.

The initialization time has not changed since 4.1.2. You should be able to see what stage is taking too long on the splash screen's progress output. Perhaps you have some leftover socket, or a GPU that takes too long to initialize.
On my reference system, this takes 7 seconds on average:
```shell
xpra start --start=xterm --attach=yes
```
In any case, that's unrelated to this ticket, which can be closed.

**Comment by hongyi-zhao** [comment]
> $ xpra start --start=xterm --attach=yes

For my case, it needs around 25 seconds before the xterm apprears.

**Comment by mviereck** [comment]
@totaam Thank you!

**Comment by totaam** [comment]
> For my case, it needs around 25 seconds before the xterm apprears.

Yes, then there's something wrong. 25 seconds is waaaaaaay too long.

**Comment by hongyi-zhao** [comment]
I tried with other X server options, as depicted below:

`--xephyr ` option doesn't have this problem.
`--nxagent` option failed to start qq.
