### ISSUE TITLE
X11docker fails to run with --weston --clipoard --debug flag 

### ISSUE THREAD

**Issue by velcrine** [mviereck/x11docker#352]
Here I have attached the logs.

<details>
<summary>Logs</summary>
<br>

./x11docker -F --weston --clipboard --desktop --debug -- x11docker/lxde
DEBUGNOTE[23:42:42,157]: check_host(): ps can watch root processes: yes
DEBUGNOTE[23:42:42,178]: host user: pkv 1000:1000 /home/pkv
x11docker WARNING: User pkv is member of group docker.
  That allows unprivileged processes on host to gain root privileges.

DEBUGNOTE[23:42:42,295]: storeinfo(): cache=/home/pkv/.cache/x11docker/x11docker-lxde-56762039118
DEBUGNOTE[23:42:42,301]: storeinfo(): stdout=/home/pkv/.cache/x11docker/x11docker-lxde-56762039118/share/stdout
DEBUGNOTE[23:42:42,306]: storeinfo(): stderr=/home/pkv/.cache/x11docker/x11docker-lxde-56762039118/share/stderr
DEBUGNOTE[23:42:42,322]: storeinfo(): x11dockerpid=352709
DEBUGNOTE[23:42:42,361]: 
x11docker version: 6.9.0-beta-1
docker version:    Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
Host system:       "Ubuntu 20.04.2 LTS"
Host architecture: amd64 (x86_64)
Command:           './x11docker' '-F' '--weston' '--clipboard' '--desktop' '--debug' '--' 'x11docker/lxde' 
Parsed options:     -F --weston --clipboard --desktop --debug -- 'x11docker/lxde'
x11docker WARNING: You are running GNOME desktop in outdated version 
  GNOME Shell 3.36.7
  This might cause issues with host applications if using additional X servers.
  It is recommended to use another desktop environment or GNOME >= 3.38.
  Only otherwise discouraged option --hostdisplay might work as expected.

DEBUGNOTE[23:42:42,392]: Dependency check for --weston: 0
DEBUGNOTE[23:42:42,396]: Dependencies of --weston already checked: 0 
DEBUGNOTE[23:42:42,399]: Dependencies of --weston already checked: 0 
DEBUGNOTE[23:42:42,402]: Dependencies of --weston already checked: 0 
DEBUGNOTE[23:42:42,405]: storeinfo(): xserver=--weston
x11docker note: Sharing clipboard with --weston is not supported

x11docker note: xfishtank not found. Can not show a fish tank.
  Please install 'xfishtank' for option --xfishtank to show a fish tank.
  You can look for the package name of this command at: 
 https://github.com/mviereck/x11docker/wiki/dependencies#table-of-all-packages

x11docker note: Option --xfishtank is not supported for --weston.

x11docker note: You are running a pure Wayland environment.
  X applications without Wayland support will fail.

DEBUGNOTE[23:42:42,423]: container user: pkv 1000:1000 /home/pkv
DEBUGNOTE[23:42:42,442]: waitforlogentry(): tailstdout: Waiting for logentry "x11docker=ready" in store.info
DEBUGNOTE[23:42:42,442]: waitforlogentry(): tailstderr: Waiting for logentry "x11docker=ready" in store.info
DEBUGNOTE[23:42:42,456]: storepid(): Stored pid '353229' of 'watchpidlist':  353229 pts/0    00:00:00 bash
DEBUGNOTE[23:42:42,470]: storepid(): Stored pid '353248' of 'watchmessagefifo':  353248 pts/0    00:00:00 bash
DEBUGNOTE[23:42:42,789]: storeinfo(): WAYLAND_DISPLAY=wayland-136
DEBUGNOTE[23:42:42,795]: storeinfo(): XDG_RUNTIME_DIR=/run/user/1000
DEBUGNOTE[23:42:42,801]: storeinfo(): Xenv= WAYLAND_DISPLAY=wayland-136 XDG_SESSION_TYPE=wayland GDK_BACKEND=wayland QT_QPA_PLATFORM=wayland CLUTTER_BACKEND=wayland SDL_VIDEODRIVER=wayland ELM_DISPLAY=wl ELM_ACCEL=opengl ECORE_EVAS_ENGINE=wayland_egl XDG_RUNTIME_DIR=/run/user/1000
x11docker WARNING: Option --no-auth: SECURITY RISK!
  Allowing access to new X server for everyone.

DEBUGNOTE[23:42:42,809]: Compositor command:
  weston \
  --socket=wayland-136 \
  --backend=x11-backend.so \
  --config='/home/pkv/.cache/x11docker/x11docker-lxde-56762039118/weston.ini'
x11docker WARNING: Option --clipboard is not supported for --weston.
  Fallback: Disabling option --clipboard.

DEBUGNOTE[23:42:42,814]: traperror: Command at Line 8917 returned with error code 1:
  return 1
  9060 - ::main::main
DEBUGNOTE[23:42:42,817]: storeinfo(): error=64
DEBUGNOTE[23:42:42,824]: time to say goodbye (traperror)
DEBUGNOTE[23:42:42,884]: storeinfo(): tini=/usr/bin/docker-init
DEBUGNOTE[23:42:42,891]: Users and terminal:
  x11docker was started by:                       pkv
  As host user serves (running X, storing cache): pkv
  Container user will be:                         pkv
  Container user password:                        x11docker
  Getting permission to run docker with:          eval 
  Terminal for password frontend:                 bash -c
  Running in a terminal:                          yes
  Running on console:                             no
  Running over SSH:                               no
  Running sourced:                                no
  bash $-:                                        huBE
DEBUGNOTE[23:42:42,895]: storeinfo(): containername=x11docker_X136_x11docker-lxde_56762039118
DEBUGNOTE[23:42:42,951]: waitforlogentry(): tailstdout: Stopped waiting for x11docker=ready in store.info due to terminating signal.
DEBUGNOTE[23:42:42,951]: waitforlogentry(): tailstderr: Stopped waiting for x11docker=ready in store.info due to terminating signal.
DEBUGNOTE[23:42:43,041]: Docker command:
  docker run --tty --detach \
  --name x11docker_X136_x11docker-lxde_56762039118 \
  --user 1000:1000 \
  --userns host \
  --cap-drop ALL \
  --security-opt no-new-privileges \
  --security-opt label=type:container_runtime_t \
  --volume '/usr/bin/docker-init':'/usr/local/bin/init':ro \
  --tmpfs /run:exec --tmpfs /run/lock \
  --volume '/home/pkv/.cache/x11docker/x11docker-lxde-56762039118/share':'/x11docker':rw \
  --volume '/run/user/1000/wayland-136':'/wayland-136':rw \
  --workdir '/tmp' \
  --entrypoint env \
  --env 'container=docker' \
  --env 'WAYLAND_DISPLAY=wayland-136' \
  --env 'USER=pkv' \
  --env 'ECORE_EVAS_ENGINE=wayland_egl' \
  --env 'ELM_ACCEL=opengl' \
  --env 'ELM_DISPLAY=wl' \
  --env 'SDL_VIDEODRIVER=wayland' \
  --env 'CLUTTER_BACKEND=wayland' \
  --env 'QT_QPA_PLATFORM=wayland' \
  --env 'GDK_BACKEND=wayland' \
  --env 'XDG_SESSION_TYPE=wayland' \
  -- x11docker/lxde /usr/local/bin/init -- /bin/sh - /x11docker/containerrc
DEBUGNOTE[23:42:43,208]: Running xtermrc: Ask for password if needed (no)
DEBUGNOTE[23:42:43,210]: storepid(): Stored pid '353854' of 'containershell':  353854 pts/0    00:00:00 bash
DEBUGNOTE[23:42:43,218]: Running dockerrc: Setup as root or as user docker on host.
DEBUGNOTE[23:42:43,218]: waitforlogentry(): start_xserver(): Waiting for logentry "readyforX=ready" in store.info
DEBUGNOTE[23:42:43,252]: dockerrc: Found default Runtime: runc
DEBUGNOTE[23:42:43,261]: dockerrc: All  Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
DEBUGNOTE[23:42:43,269]: dockerrc: Container Runtime: runc
DEBUGNOTE[23:42:43,278]: storeinfo(): runtime=runc
DEBUGNOTE[23:42:43,317]: storeinfo(): xtermrc=ready
DEBUGNOTE[23:42:43,317]: waitforlogentry(): start_docker(): Waiting for logentry "dockerrc=ready" in store.info
DEBUGNOTE[23:42:43,450]: time to say goodbye (watchpidlist)
DEBUGNOTE[23:42:43,739]: waitforlogentry(): start_xserver(): Stopped waiting for readyforX=ready in store.info due to terminating signal.
DEBUGNOTE[23:42:43,757]: traperror: Command at Line 9046 returned with error code 1:
  return 1
  9060 - ::main::main
DEBUGNOTE[23:42:43,773]: storeinfo(): error=64
DEBUGNOTE[23:42:43,812]: time to say goodbye (traperror)
DEBUGNOTE[23:42:43,827]: time to say goodbye (main)
DEBUGNOTE[23:42:43,836]: waitforlogentry(): start_docker(): Stopped waiting for dockerrc=ready in store.info due to terminating signal.
DEBUGNOTE[23:42:43,846]: Terminating x11docker.
DEBUGNOTE[23:42:43,852]: traperror: Command at Line 6275 returned with error code 1:
  return 1
  8993 - ::start_docker::main::main
DEBUGNOTE[23:42:43,856]: time to say goodbye (finish)
DEBUGNOTE[23:42:43,860]: storeinfo(): error=64
DEBUGNOTE[23:42:43,873]: time to say goodbye (traperror)
DEBUGNOTE[23:42:43,878]: traperror: Command at Line 8993 returned with error code 1:
  return 1
  9060 - ::main::main
DEBUGNOTE[23:42:43,881]: finish(): Checking pid 353854 (containershell):  353854 pts/0    00:00:00 bash
DEBUGNOTE[23:42:43,882]: storeinfo(): error=64
DEBUGNOTE[23:42:43,891]: time to say goodbye (traperror)
DEBUGNOTE[23:42:43,895]: termpid(): Terminating 353854 (containershell):  353854 pts/0    00:00:00 bash
DEBUGNOTE[23:42:43,901]: traperror: Command at Line 947 returned with error code 141:
  cut -c1-12
  431 - ::timestamp::debugnote::setonwatchpidlist::main::main
DEBUGNOTE[23:42:43,904]: storeinfo(): error=64
DEBUGNOTE[23:42:43,913]: time to say goodbye (traperror)
DEBUGNOTE[23:42:43,917]: traperror: Command at Line 431 returned with error code 141:
  cut -c1-12
  721 - ::debugnote::setonwatchpidlist::main::main
DEBUGNOTE[23:42:43,920]: storeinfo(): error=64
DEBUGNOTE[23:42:43,929]: time to say goodbye (traperror)
DEBUGNOTE[23:42:44,048]: finish(): Checking pid 353248 (watchmessagefifo):  353248 pts/0    00:00:00 bash
DEBUGNOTE[23:42:44,071]: finish(): Checking pid 353229 (watchpidlist): (already gone)
DEBUGNOTE[23:42:44,114]: Removing container x11docker_X136_x11docker-lxde_56762039118
    Error: No such container: x11docker_X136_x11docker-lxde_56762039118
DEBUGNOTE[23:42:44,139]: termpid(): Terminating 353248 (watchmessagefifo):  353248 pts/0    00:00:00 bash
DEBUGNOTE[23:42:44,273]: x11docker exit code: 64

</details>

It works when I pass --weston-xwayland, but not with --weston.

**Comment by velcrine** [comment]
Understood ya !

**Comment by mviereck** [comment]
I've uploaded a commit with the fix. Also fixed: The --no-auth warning that does not make sense for Wayland compositors.
