### ISSUE TITLE
[WSL2] x11docker watching unexisting pid1pid (auto close)

### ISSUE THREAD

**Issue by rsrdesarrollo** [mviereck/x11docker#354]
Hi! @mviereck,

First, thanks for such an amazing project. I have been using your tool in Linux without any problem, but right now I'm trying to use it in Windows with Docker WSL2 Backend and VcXsrv with runx. I think I have found a problem in the code and I have it nearly identified, but I need your help to make a valid PR because, to be honest, 9k bash lines are too much for me ;). The command line I'm running

```
x11docker --desktop --size 800x600 --verbose x11docker/xfce
```

### The problem

So, it seems that in watchpidlist you are watching for what you call pid1pid (which I believe is the host PID for guest container PID 1). The thing is that, for some reason, in WSL, the guest process is not present in the host (as you can see in the next image).

![image](https://user-images.githubusercontent.com/5142014/118138688-eb92c500-b406-11eb-8f1f-4cbd36250530.png)

So this makes the tool believe that the container is dead and ends the program.

As you might know, you are starting to watch this PID in: https://github.com/mviereck/x11docker/blob/60ab6d7875ffad490fd79852f9fda88f79a453f2/x11docker#L9022  

So apparently, a possible solution could be use `-mobyvm` flag, and actually this fix the problem, but has other problems related with cleanup after close. 

Actually, changing this line with the same command present in the case where mobyvm is yes `setonwatchpidlist "CONTAINER$Containername" ;;` it seems to work, but probably I'm breaking other things, don't know.

So, what do you think?

**Comment by rsrdesarrollo** [comment]
The fix basically ignores PID for watchpids and only uses docker container. If the container is stopped, the program ends. As I told you, I don't know if this could break other things.

**Comment by mviereck** [comment]
Thank you for the report and the PR! I've left a note in the PR and will merge it after you've adjusted it.

I wonder why the pid check fails in WSL2. However, I don't have a test environment yet to track this down, and take the easy way to accept your fix. It sounds like a new bug in Docker because it worked previously.

> So, it seems that in watchpidlist you are watching for what you call pid1pid (which I believe is the host PID for guest container PID 1)

Yes, entirely correct.

>  it seems to work, but probably I'm breaking other things, don't know.

It doesn't break anything, but costs CPU resource usage (see comment in PR).

**Comment by mviereck** [comment]
A late thought:
Maybe it wasn't the native Linux docker that is executed in your WSL2 setup but your `PATH` points to `docker.exe`/MobyVM first? That would explain the PID1 issue.

Could you please check and show the output of `which docker` in WSL2?

**Comment by rsrdesarrollo** [comment]
Hi, 

The PID thing is because by default, docker creates it's own WSL images to run containers and then (somehow) integrates with other WSLs.

![image](https://user-images.githubusercontent.com/5142014/119330066-1fcb7880-bc86-11eb-86a8-7142ccd3469f.png)

![image](https://user-images.githubusercontent.com/5142014/119330357-691bc800-bc86-11eb-93aa-d9937673edb2.png)

But the actual process is not running on your common WSL (ubuntu in my case) but on the docker-desktop WSL. That's why you can't find the host process.

About `which docker`

![image](https://user-images.githubusercontent.com/5142014/119330732-d596c700-bc86-11eb-886c-eb88a394cd01.png)

Looks normal to me, but docker might be doing some dark magic (probably with docker sock) to connect one WSL to the other.

**Comment by mviereck** [comment]
> But the actual process is not running on your common WSL (ubuntu in my case) but on the docker-desktop WSL. That's why you can't find the host process.
> docker might be doing some dark magic (probably with docker sock) to connect one WSL to the other.

Thank you for the clarification! 
This was different in the early days of WSL2; it allowed a native docker without any modification. 

I think it wasn't a good design decision of Docker devs to change this. Though, my opinion does not count much here.

**Comment by eine** [comment]
FTR, I use Docker on Windows and I don't use the WSL2 integration.
