### ISSUE TITLE
Requirements for rewrite in GO

### ISSUE THREAD

**Issue by velcrine** [mviereck/x11docker#359]
So, as to proceed the rewrite, we need answer to these things,

1. Is there need to be seperate repository, or new code will exist here itself.
2. For easy dockerfile, for all env, I have added the code at https://github.com/velcrine/lightmachine,  lets merge it somewhere.
3. I started with minimal setup first for rewrite, lxde worked fine, but for gnome3 I need some technical help.

**Comment by velcrine** [comment]
cc @eine

**Comment by mviereck** [comment]
> Is there need to be seperate repository, or new code will exist here itself.

It makes sense that you open your own repository.

> For easy dockerfile, for all env, I have added the code at https://github.com/velcrine/lightmachine, lets merge it somewhere.

Generating GUI Dockerfiles is a different task than running GUI containers. I'd say that should be a repository on  its own.

> I started with minimal setup first for rewrite, lxde worked fine, but for gnome3 I need some technical help.

You could open a repository with this rewrite and open tickets there. I'll look at them and answer questions on upcoming setup issues.

-----------------------

After all, I am still not convinced of a complete rewrite that should replace the current bash version of x11docker.
I still don't see an advantage in this task.
Customized short versions for special tasks can make sense, though.

**Comment by velcrine** [comment]
`You could open a repository with this rewrite and open tickets there. I'll look at them and answer questions on upcoming setup issues.`
Thanks for this helping hand.
`Customized short versions for special tasks can make sense, though.`
@mviereck Yeah this is what it is, I will add bit by bit short features. I am more interested in maintaining high-modularity, hence I will not rush for feature completion, but just to the fact that how can I make it more and more simplified for other users to adjust the source code according to their needs. I see no reason for people using VMs, if they have everything in docker.

**Comment by velcrine** [comment]
Hi mviereck, do u have any wiki or some references for runnong gnome3 in docker, i just can't get it done.

**Comment by mviereck** [comment]
Gnome3 in container is a pita.
The image `x11docker/gnome` is marked as experimental due to lot of issues that can come up.

Currently x11docker gets it to run with `--init=systemd`, so you would need to run systemd in container that in turn runs gnome3; a major task. Furthermore it needs a wrapper to start, as is done with `guake` in `x11docker/gnome`.

I do not recommend to run gnome3 in a container.
