### ISSUE TITLE
x11 docker gui kaptain cannot connect to X server

### ISSUE THREAD

**Issue by MandiYang** [mviereck/x11docker#361]
When running x11 docker gui doesn't work, it is because when running x11docker/kaptain throws can't connect to X server, how to fix this problem?

**Comment by MandiYang** [comment]
Solved by updating

**Comment by mviereck** [comment]
Did update to latest release or to current beta?
Can you show me `x11docker --version`?

**Comment by MandiYang** [comment]
Beta

**Comment by MandiYang** [comment]
The latest  version didn't work well

**Comment by mviereck** [comment]
Thank you!
I should publish a new release soon.
