### ISSUE TITLE
Failed to start with nerdctl

### ISSUE THREAD

**Issue by liyimeng** [mviereck/x11docker#362]
I try to test nerdctl backend, using command as below. 

`./x11docker --backend=nerdctl x11docker/xfce xfce4-terminal`

The script just flash and crash out immediately.  below is the log. 

[x11docker.log](https://github.com/mviereck/x11docker/files/6587519/x11docker.log)

What has been going wrong ?

**Comment by mviereck** [comment]
The error message:
```
x11docker ERROR: Startup of nerdctl failed. Did not receive a container ID. 
     
  Last lines of container log: 
time="2021-06-03T05:25:57+08:00" level=fatal msg="needs CNI plugin \"bridge\" to be installed in CNI_PATH (\"/opt/cni/bin\"), see https://github.com/containernetworking/plugins/releases: exec: \"/opt/cni/bin/bridge\": stat /opt/cni/bin/bridge: no such file or directory" 
null 
time="2021-06-03T05:25:58+08:00" level=fatal msg="1 errors: [no such object: x11docker/openbox]" 
time="2021-06-03T05:25:58+08:00" level=fatal msg="needs CNI plugin \"bridge\" to be installed in CNI_PATH (\"/opt/cni/bin\"), see https://github.com/containernetworking/plugins/releases: exec: \"/opt/cni/bin/bridge\": stat /opt/cni/bin/bridge: no such file or directory"
```
The nerdctl installation instructions say:
```
    Minimal (nerdctl-0.8.3-linux-amd64.tar.gz): nerdctl only
    Full (nerdctl-full-0.8.3-linux-amd64.tar.gz): Includes dependencies such as containerd, runc, and CNI
```
I've installed `nerdctl-full` that includes CNI (whatever that is). The error message mentiones that:  `needs CNI plugin`.

Likely you need to install the `nerdctl-full` package.

**Comment by liyimeng** [comment]
hmm, thank @mviereck 
I will give it a try again.

**Comment by mviereck** [comment]
For comparision you could try nerdctl without x11docker:
```
nerdctl run --rm -ti alpine sh
```

**Comment by liyimeng** [comment]
Thanks @mviereck It is my env. problem.

**Comment by liyimeng** [comment]
Hi @mviereck I still need some help :) 

I find I have some issues with my nerdctl setup because I don't have proper IPv6 on my VM. (Not figure out why nerdctl need ipv6). Anyway, I find another way to bring up the container using crictl. 

I firstly follow instructions here  https://github.com/mviereck/x11docker/wiki/Custom-access-to-new-X-server to startup an empty X server and then run x11dokcer/xfce container. It dose show up the beautiful graphics, however I don't  have any mouse or keyboard events. the mouse cursor just frozen in the middle of the screen. 

I test another X11 app from host directly, which dose not run in container at all, the same result. So I guest that I have missed something in starting up X server.  Below is the command I used: 
`
x11docker --xonly --gpu --xorg --showenv
` 

What can be going wrong? 

Thanks a lot in advanced!

**Comment by liyimeng** [comment]
BTW, my VM was alpine linux. When I start empty X server on unbuntu VM, there seem no issue. Can it be alpine missing some lib. It run X app flawless without x11docker though.

**Comment by mviereck** [comment]
> I find I have some issues with my nerdctl setup because I don't have proper IPv6 on my VM. (Not figure out why nerdctl need ipv6).

I am not sure, too, why nerdctl would need ipv6. Maybe a ticket at https://github.com/containerd/nerdctl makes sense.
Two possible workarounds:
  - `--network=none` to disable networking at all, or
  - `--network=host` to use the host network stack. (less secure, disables network namespacing.)

> It dose show up the beautiful graphics, however I don't have any mouse or keyboard events. the mouse cursor just frozen in the middle of the screen.

Xorg should do all needed setup itself for mouse and keyboard, x11docker does no setup here. Could you show me `~/.cache/x11docker/x11docker.log` after a try? Maybe I find a hint in the Xorg output.
If you run in a VM as you mentioned above, maybe the issue is somehow VM related, e.g. a host mouse integration failure.

> BTW, my VM was alpine linux. When I start empty X server on unbuntu VM, there seem no issue. Can it be alpine missing some lib. It run X app flawless without x11docker though.

Currently I have no good idea why there is an alpine specific issue, especially if there is no Xorg issue if running Xorg without x11docker. Maybe the logfile gives me a hint.

**Comment by liyimeng** [comment]
@mviereck Thank you so much for timely reply @mviereck!  I figure it out! It is alpine bug, I guess. After starting up the empty x server, I need to manually issue `udevadm trigger`  Mouse then suddenly move 👯 

Thanks again,  you guy rock!

**Comment by liyimeng** [comment]
I need to give x11docker a star, which I should have done!
