### ISSUE TITLE
x11docker ERROR: waitforlogentry(): dockerrc: Timeout waiting for entry "xinitrc is ready" in xinit.log 

### ISSUE THREAD

**Issue by ItzDerock** [mviereck/x11docker#364]
I'm running the following command:
`x11docker -v -g -- -v "/mnt/d/Code/! Projects/MobileReplays.LOL/Container/Game/Versions/v11.11/en":/Game -v "/mnt/d/Code/\! Projects/MobileReplays.LOL/Container/Test":/Replays -- mobilereplays`

The host machine is running Windows 10 Pro with Docker Desktop in WSL2 mode. The command was executed in Ubuntu 18.04 in WSL2. 

Full logs can be found [here](https://termbin.com/djhq).

**Comment by mviereck** [comment]
I am not exactly sure what is going wrong. Maybe the Windows firewall prevents the X server from starting. Compare https://github.com/mviereck/x11docker/wiki/x11docker-on-MS-Windows#troubleshooting

Does `runx --desktop` show a window?

**Comment by ItzDerock** [comment]
Manually adding VxCsrv and XLaunch to the allowed applications on Windows Firewall fixed it. 
One tiny nit picky bug is that the terminal output for the `-i` option is strangely formatted, making it difficult to read. https://img.derock.dev/xY6PlW.png

**Comment by mviereck** [comment]
> Manually adding VxCsrv and XLaunch to the allowed applications on Windows Firewall fixed it.

Good!

>  One tiny nit picky bug is that the terminal output for the -i option is strangely formatted, making it difficult to read. https://img.derock.dev/xY6PlW.png

Do you get a well formatted output with e.g. `docker run --rm -ti alpine sh`?

**Comment by ItzDerock** [comment]
Running `docker run --rm -ti alpine sh` works fine.
Running `x11docker -vi alpine` shows the incorrect formatting.
Not sure if this is intended behavior, but running without the v flag never attaches me to the shell.

**Comment by ItzDerock** [comment]
Would also like to mention that when not using the `--user=root` flag, the home directory for the user is not owned by the user, which prevents applications like wine from operating. 

`wine: '/home/derock' is not owned by you, refusing to create a configuration directory there`

**Comment by ItzDerock** [comment]
Lastly, not sure if this is an x11docker issue, or a misconfiguration on my end, but with the `--hostipc` flag, MIT-SHM seems to still fail to function. 
`Xlib:  extension "MIT-SHM" missing on display "192.168.1.87:2581"`

**Comment by mviereck** [comment]
A temporary workaround:
`--interactive` together with `--no-setup` works.

**Comment by mviereck** [comment]
`--interactive` is fixed finally. :-)

As often, it was a rather stupid bug ... Some time ago I've changed the container output redirection and forgot to regard `--interactive` where the output must not be redirected.

**Comment by mviereck** [comment]
> Oh and I should probably add that I'm using WSLG which is WSl2 with native gui application support, and doesn't seem like it should be messing with the format.

Out of curiosity:
Could you show me the output in WLSG?
```
echo $DISPLAY
echo $XAUTHORITY
xhost
```

x11docker might run in WSLG with option `--hostdisplay`.

**Comment by ItzDerock** [comment]
https://img.derock.dev/2CSC7h.png

**Comment by mviereck** [comment]
Thank you for the output!
So WSLG disables all X authentication and allows access for everyone. Using `runx` like x11docker does is a better setup in aspects of security.
