### ISSUE TITLE
AppImage and FUSE

### ISSUE THREAD

**Issue by grigio** [mviereck/x11docker#365]
I tried with serveral arguments but I still can't run an AppImage inside a container, ideas?

```
dlopen(): error loading libfuse.so.2
```

**Comment by mviereck** [comment]
I am not familiar with Appimage, but likely it needs more privileges than a container should have.
Compare https://stackoverflow.com/questions/48402218/fuse-inside-docker

Something like this might work:
```
x11docker --cap-default --share /dev/fuse -- --cap-add SYS_ADMIN -- imagename
```
Try to reduce these options to find out which are needed indeed.

**Comment by grigio** [comment]
Thanks for the reply, no same error, I also tried with "privileged"

```
x11docker --cap-default --share $HOME --share /dev/fuse -- --cap-add SYS_ADMIN --privileged -- imagename

```

**Comment by mviereck** [comment]
I discourage `--privileged` because it drops literally all container security. The container essentially has root access to the host system.

I recommend to follow the guidance at https://github.com/mviereck/x11docker#privilege-checks to find out what is really needed.
