### ISSUE TITLE
crictl as backend?

### ISSUE THREAD

**Issue by liyimeng** [mviereck/x11docker#366]
A alternative to nerdctl is crictl,  which seem are more feature completed that nerdctl, see https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/

I am wondering how difficult to add this backend to nerdctl side by side.

**Comment by liyimeng** [comment]
sorry, please ignore my question, they are too much difference.

**Comment by mviereck** [comment]
I had a look at `crictl`, too, but its options shown in `crictl run --help` are much less than x11docker needs.
