### ISSUE TITLE
Readme section formatting

### ISSUE THREAD

**Issue by johncm** [mviereck/x11docker#368]
![image](https://user-images.githubusercontent.com/753991/121793613-6f86cb00-cbc6-11eb-80fc-dc4d960635b8.png)

Maybe it is just me, but I'm not understanding this in the Installation section.
Is this saying what happens when one runs the install? It seems like a it is paragraph that could be formatted as a list, but again, I'm not sure if it is placed properly. Just a suggestion.

**Comment by mviereck** [comment]
Thank you for the suggestion!

> Is this saying what happens when one runs the install?

Yes.

>  It seems like a it is paragraph that could be formatted as a list

I have changed formatting and added a short explanation. I hope it is clearer now.

**Comment by johncm** [comment]
Looks great!
