### ISSUE TITLE
stop container before display server?

### ISSUE THREAD

**Issue by ehough** [mviereck/x11docker#37]
I've encountered an issue regarding `x11docker` and Kodi and I'm hoping you could provide some guidance on how to fix it.

When a termination signal is sent to `x11docker`, like `Ctrl-C` or `kill -SIGTERM`, the container running Kodi usually crashes instantly. Looking through the logs, it seems that this is due to the fact that the X server goes down before the container running Kodi. Apparently Kodi doesn't handle a vanishing X server very well.

If, on the other hand, I use `docker stop` to stop the Kodi container then everything shuts down cleanly. This is a little annoying, though, because I have to look up and/or calculate the name of the container to stop it. It would be a heck of a lot easier to simply send a `SIGTERM` to `x11docker` and be done with it.

Perhaps a solution would be for `x11docker` to stop the container and *then* stop the remaining supporting processes? The teardown process in `x11docker` is a little hard for me to follow, so I'm not sure I can offer up a PR.

Here are some debug logs:

* [using `docker stop`, clean shutdown](https://pastebin.com/raw/zXP1D3xF)
* [using `Ctrl-C`, Kodi crash](https://pastebin.com/raw/Zh9Mu2eU)

The second log is really big, but if you search for `xinit: connection to X server lost` you can see where the crash starts.

Appreciate any guidance you can offer. Thank you.

**Comment by mviereck** [comment]
kodi seems to be really upset if it looses X under his feet. :-D

> Perhaps a solution would be for x11docker to stop the container and then stop the remaining supporting processes?

I've made an update that runs `docker stop` before other processes like xinit are terminated. Indeed it was just one line to execute a bit later. Please try out if it works for you. 

> This is a little annoying, though, because I have to look up and/or calculate the name of the container to stop it.

Since V3.9.8.1 you can get the container ID with `read containerid < <(x11docker [...] )`

**Comment by ehough** [comment]
That fixed it! Thanks for the super fast response. A few notes from testing:

1. Using `kill -SIGTERM` or `kill -SIGHUP` on the top-most `x11docker` process works very well. The container is shut down without error 🎉 

1. Using `Ctrl-C` to kill the process from my terminal results in the crash. Seems like it sends `SIGINT` to all the processes in the hierarchy? Not really sure what's going on under the hood, but I usually won't be using the terminal so it's not really an issue (for me, at least).

1. Using `kill -SIGINT` or `kill -SIGQUIT` had no effect at all.

> Since V3.9.8.1 you can get the container ID with `read containerid < <(x11docker [...] )`

Cool! Thanks for sharing that trick.

> Just two thoughts about your x11docker-kodi command:
>
> `--env LANG=en_US.UTF`
>
> x11docker provides option `--env`, too, you don't need to set it right of `--` as a docker run option.
>
> Especially for language/locale settings there is also option `--lang LOCALE` that sets the desired locale or tries to create it with `locale-gen` if it's missing.
>
> `-v /media/nas/htpc_media:/media:ro`
>
> In general, there is option `--sharedir DIR`; but maybe it is desireable to have read-only access in some cases. I could allow and parse settings like `:ro`. What do you think?

Sounds like I need to RTFM! 😆 These all sound like promising ideas. Let me ponder and test each. I'll report back here with my thoughts. Feel free to close this issue in the meantime, if you like.

**Comment by ehough** [comment]
p.s. [here's a sneak peek](https://github.com/ehough/docker-kodi) of what I'm working on

**Comment by ehough** [comment]
Thanks again for the tips and reminders on the available `x11docker` options.

> x11docker provides option `--env`, too, you don't need to set it right of `--` as a docker run option.

I tested moving `--env` to the left of `--` and indeed it works great. But in my case it just *feels* a little cleaner to keep it "Docker only". In the logs I noticed that my variables were `export`ed in a few places, and the variables are really only needed by my container. There's probably some useful use cases for the "left sided" `--env` that I haven't considered, but for now I'll keep my command as is.

> Especially for language/locale settings there is also option `--lang LOCALE` that sets the desired locale or tries to create it with `locale-gen` if it's missing.

That's quite clever. Haven't had a need for this yet but will keep it in my back pocket. Thanks!

> In general, there is option `--sharedir DIR`; but maybe it is desireable to have read-only access in some cases. I could allow and parse settings like `:ro`. What do you think?

I could go either way with this one, but personally I'd say it's likely more work than it's worth. At the risk of sound like a Docker purist 😄 , again I'd say that the right side of `--` works pretty well for use cases like this. `--sharedir` is very convenient and I think a lot of users will use it as is, so I'm not suggesting that it's redundant. But in my opinion it might be better for `x11docker` to avoid overlapping too much with native `docker run` features.

Closing this issue. I'll keep sending feedback as I come up with it. Thanks again for your great work!

**Comment by ehough** [comment]
> X terminates before this additonal trap is executed. ... It seems I have to dig deeper into this.

According to [this answer](https://stackoverflow.com/a/6110213/229920), `Ctrl-C` sends `SIGINT` to *all* the processes in the foreground process group, including children. Assuming that's true, it could be quite tricky to catch the signal. I would offer up some ideas, but this is getting out of my depth of shell knowledge.

> kodi should not crash that fatally only because X shuts down. It's worth a bug report at kodi developers.

> X will terminate first if the user clicks the close [X] of the X server window. x11docker cannot do anything to catch that. It's really up to kodi to handle that better.

I agree. I'll ask the Kodi folks if they can provide any insight. Or maybe I'll do some testing this weekend.

**Comment by mviereck** [comment]
> According to this answer, Ctrl-C sends SIGINT to all the processes in the foreground process group, including children. Assuming that's true, it could be quite tricky to catch the signal. 

I found an interesting approach to use `setsid` to run a command in its own process group.
I can run `setsid -w xterm`, press `CTRL-C` and voilá, xterm is not terminated.
But it fails with x11dockers `bash -c xinit ...` :-(

**Comment by mviereck** [comment]
Just a note: You can also terminate kodi with examing its pid on host:
```
kill $(pidof -x kodi-standalone)
```
It's a one-side isolation: container applications are isolated from host, but the host still has full access on container applications.
The advantage is to not need a password for `docker stop` if one is not member of group docker.

This should as well go for `nice`, you would not need `SYS_NICE` in container setup.

**Comment by ehough** [comment]
Good points. I wonder how `kodi-standalone` would react to being killed - I'll do some testing and if it terminates everything cleanly then I'll update the docs for my Kodi image.

**Comment by mviereck** [comment]
I did some major changes in background process and shutdown handling the last few weeks. I found that kodi does not crash that spectactulary anymore if I press CTRL+C in terminal.

[I am not sure why](https://oppmax.com/wp-content/uploads/2016/01/google-tag-manager-organizes-tags-and-codes.jpg). It may be due to sending TERM to PID 1 of container. I can do that as unprivileged user (as opposed to `docker stop`). Though, the X server still terminates first.

If you are interested to get the PID of container PID 1, you can use option `--showpid1`, e.g.
```
read pid1 < <(x11docker --showpid1 erichough/kodi)
```
