### ISSUE TITLE
Not working when I build myself. [Dependency issues | snap | Ubuntu server]

### ISSUE THREAD

**Issue by iamneo2416** [mviereck/x11docker#375]
I use **ubuntu20.04LTS server** (console based system) as a host and download **x11docker/mate** image. When I run it by command **"x11docker --desktop x11docker/mate"**  in console, I got following error. I install all suggested package from following error, and re-run many times without luck. Did my process go wrong anywhere or did I miss something? Please help with this. 

X11 connection rejected because of wrong authentication.
Failed to connect to bus: Operation not permitted

x11docker ERROR: Did not find a possibility to provide a display.
  Recommendations:
    To run within an already running X server, install one or all of:
      **Xephyr xpra nxagent**
    To run with GPU acceleration, install:
      **weston and Xwayland**, optionally also: **xpra and xdotool**
    To run from TTY or within Wayland, install:
      **weston and Xwayland**
  You can look for the package name of this command at:
 [https://github.com/mviereck/x11docker/wiki/dependencies#table-of-all-packages](https://github.com/mviereck/x11docker/wiki/dependencies#table-of-all-packages)

  Type 'x11docker --help' for usage information
  Debug options: '--verbose' (full log) or '--debug' (log excerpt).
  Logfile will be: /home/tommy/.cache/x11docker/x11docker.log
  Please report issues at https://github.com/mviereck/x11docker

**Comment by mviereck** [comment]
@iamneo2416  I've transferred the ticket to x11docker.

**Comment by eine** [comment]
> You should try yourself !! Not working ....

@iamneo2416 please be respectful. You are demanding that a single person spends his time and effort for free on solving a problem for you to use a non open-source tool maintained and sold by a company for profit. I beg to strongly disagree with you. @mviereck should not try anything himself. He should not spend a single minute on supporting mobaxterm. He can do it if he feels like and he has fun while doing so. Conversely, you should try any of the following:

- Fix it yourself.
- Demand mobaxterm maintainers/developers that spend time on looking into compatibility issues (as long as you are paying for the product).
- Hire someone else for fixing the problem for you.
- Be very patient and as friendly and helpful as possible with @mviereck, including trying yourself whatever you might have expected him to do.

**Comment by iamneo2416** [comment]
@mviereck  I am sorry. It is still not working .... 

(1) use x11docker --update-master
![image](https://user-images.githubusercontent.com/3412553/127969958-6afa9f9d-1451-41c4-8cf3-1f77290a6339.png)

(2) use x11docker --weston-xwayland x11docker/mate mate-terminal
![image](https://user-images.githubusercontent.com/3412553/127970200-c8aa8ebd-1242-40ba-8c0e-d332c0f20b8b.png)

(3) core dump as follow
[x11docker.log](https://github.com/mviereck/x11docker/files/6921929/x11docker.log)

I am sorry. I need to give up this, since I just want to tried out what he build, but nothing work for me. sorry again ! x11docker has some problem with virtualbox, maybe I don't know how to use it. sorry again. I am not a tech guy, and don't know how to fix it.

I will go for other solution. thanks !

**Comment by iamneo2416** [comment]
I am also doing this try out for fun, since you are not interested in knowing detail of how other met situation and problem. This is also not my responsible to report bug to you. I think you should consider all cases only if you are a developer. If not, then just skip what I am reporting here. thanks for your time anyway.

The other solution seems 100% worked for me on all cases no matter if I use direct console to run or mobaxterm. Again, I am also tried out for fun.

[https://hub.docker.com/r/dorowu/ubuntu-desktop-lxde-vnc/](https://hub.docker.com/r/dorowu/ubuntu-desktop-lxde-vnc/)

**Comment by mviereck** [comment]
Sorry for my late response, curently i am a bit rare online and at x11docker.

@iamneo2416  thank you for the bug report! Sorry for the disturbances.
Basically you and @eine  are both right.
In fact x11docker depends on both my work and on feedback by the users. It is used in a lot of very different environments an I cannot set them up all myself to reproduce issues. Mostly I can fix issues by asking questions and getting feedback.
Sometimes I get bug reports for very special setups but get no response to my questions. I don't fix those issues anymore. The linux world is just too big to reproduce everything. So fixing a bug depends on both the users and the developers.

For this bug I've set up VirtualBox and reactivated and old Ubuntu server 18.04 VM. Currently I get issues in it, too.

Ubuntu server installs applications with snap but tries to hide this. But docker in snap does not work well and has serious limitations. Docker in snap means a container tool within another container tool. This is a bad setup done by Ubuntu.

For now a possible workaround is to use options `--cap-default --xoverip` to circumvent snap limitations.
Example:
```
x11docker --desktop --cap-default --xoverip x11docker/fvwm
```

**Comment by mviereck** [comment]
I have checked this again.
In my Ubuntu server VM Docker in snap is detected and supported if only this is installed.

If Docker is installed in snap and also with apt, there can be interferences and x11docker fails.
x11docker prints a message if it detects `/snap/docker` but also `/usr/bin/docker`.

New option `--snap` allows to manually enable docker-in-snap fallback mode.
