### ISSUE TITLE
Chrome flags support

### ISSUE THREAD

**Issue by agorkiy** [mviereck/x11docker#376]
Couldn't find, does x11docker has support for passing chrome flags? I need to add "--use-fake-ui-for-media-stream" but it seems it doesn't work right now.

**Comment by mviereck** [comment]
Compare the syntax given in `x11docker --help`:
```
To run a container on a new X server:
  x11docker IMAGE
  x11docker [OPTIONS] IMAGE [COMMAND]
  x11docker [OPTIONS] -- IMAGE [COMMAND [ARG1 ARG2 ...]]
  x11docker [OPTIONS] -- RUN_OPTIONS -- IMAGE [COMMAND [ARG1 ARG2 ...]]
```
You need to add ` -- ` before the image name, then you can pass arguments or flags.
Something like: `x11docker -- jess/chrome --use-fake-ui-for-media-stream`

**Comment by agorkiy** [comment]
True, thank you. Another question - will it use system default microfone without any modifications? I'm trying to pass my virtual mic inside, but when I launch it with just `x11docker --pulseaudio -- jess/chromium --no-sandbox  --use-fake-ui-for-media-stream` - it doesn't seem to work. A caveat is that virtual microfone is just a virtual pipe in my case (prw-r--r-- 1 user user 0 сер  3 22:11 /home/user/virtmic), so I'm not sure, can chromium in docker access it at all. I tried to share it with different --share options, but it doesn't seem to work.

**Comment by mviereck** [comment]
Let's discuss this different topic in a new ticket: #377
