### ISSUE TITLE
virtual microphone

### ISSUE THREAD

**Issue by mviereck** [mviereck/x11docker#377]
Another question - will it use system default microfone without any modifications? I'm trying to pass my virtual mic inside, but when I launch it with just `x11docker --pulseaudio -- jess/chromium --no-sandbox  --use-fake-ui-for-media-stream` - it doesn't seem to work. A caveat is that virtual microfone is just a virtual pipe in my case (prw-r--r-- 1 user user 0 сер  3 22:11 /home/user/virtmic), so I'm not sure, can chromium in docker access it at all. I tried to share it with different --share options, but it doesn't seem to work.

_Originally posted by @agorkiy in https://github.com/mviereck/x11docker/issues/376#issuecomment-892120196_

**Comment by mviereck** [comment]
I don't know about virtual microfone pipes. How are they created?

If your host pulseaudio can see and use it, it should work with `--pulseaudio` in container, too, I assume.
Though, I don't know if `jess/chromium` contains pulseaudio libraries for pulseaudio support. 

You could check with `x11docker --pulseaudio x11docker/check pavucontrol` if the microphone appears in tab "Input Devices".

**Comment by agorkiy** [comment]
@mviereck thank you, you can close the issue.
