### ISSUE TITLE
Consider decoupling nx-libs to facilitate flexible connectivity

### ISSUE THREAD

**Issue by Intensity** [mviereck/x11docker#378]
Hi. I've been using `x11docker` for some time now. Thanks for the contribution! For reference, I've been able to confirm success with Alpine Linux as the host, with both Alpine and Debian guests, under rootless `podman`.

I've found great reliability and performance while using `nx-libs` in particular (even without GPU acceleration, I can see full screen videos without any delay or significant CPU usage), and so this leads me to ask to what extent `nx-libs` can run standalone, including for example the case of a network transport layer bridging the client connection and server. For quick testing, `socat` may stand as a useful tool; perhaps a UDP transport would be ideal, but TCP is reasonable too.

While it may appear at first to be beyond the scope of the project, I might suggest it's a close tangent here. Perhaps a user may wish to run the container on a remote system and render the output locally. Plus, if sufficient guidance and automation are provided to spin up an effective channel of X forwarding, this may help with porting the ecosystem to run in different container environments (such as LXC or even OpenVZ), because if the transport fallback is over the network, then a similar method could be used to connect across various container systems and this may work equivalently well over a nearby network and locally (on the same system). I found a preliminary effort to forward X11 using a LXC container environment in a separate Github project; perhaps using `nx-libs` as a commonality can facilitate the port of `x11docker` to that container environment more effectively.

I'm hoping that the idea as presented is intriguing in itself, but at the same time, perhaps there's some basic knowledge discovery that can help others viewing this thread or the Wiki, even if this doesn't become fully implemented or integrated. In current `x11docker` use, with `--nxagent` applied, I can see an `nxagent` process running, and its arguments appear to be like that of a virtual X invocation (like `Xvfb` or `Xnest`). Perhaps running this on a remote endpoint is a simple matter of replicating those arguments and then running a local "client" to connect, as long as the socket is bridged (using `socat`, perhaps to bridge a UNIX socket to TCP/IP). I don't know what the "client" would be, however.

While I know that there is a way to leverage `xpra` and other programs for the network based use case, I'm interested to find out what's possible using `nx-libs` as a foundation, in particular due to the noted stability and performance. The Arctica project may stand as a helpful resource here. If a remote network invocation of `nx-libs` works as well as `x11docker` with `--nxagent`, then I would see this as a step forward, presenting a reasonable alternative to other tooling. At least this would be fully exploring the options. At the moment I'm not clear what the "client invocation" line would be. The noted `nxagent` process may actually be the client. Anyhow if I fully understood the architecture in place, I would already have an answer of how to factor out `nx-libs` use, but I'm unclear about the internals.

Then if the use case mentioned is possible, I'd wonder about other enhancements, like the ability to re-attach to a remote session in the event of temporary downtime, or the potential of recording the stream for convenient playback (much like the commercial variant produces .nxr files). If the primary functionality is already built into `nx-libs` it may just be a matter of invoking it.

**Comment by mviereck** [comment]
Thank you for your interest and suggestions!
Yes, nxagent provides possibilities for remote use that are not implemented or documented here.
Note that a remote usage of xpra is also not part of x11docker code, but possible as outlined in the [wiki](https://github.com/mviereck/x11docker/wiki/Remote-access-with-SSH).

It should be possible to set up nxagent/nxlibs in a very similar way. I just did not explore this.
Basically you would just need to set up a remote connection with nxagent and then run x11docker like:
```
env DISPLAY=$nx_display XAUTHORITY=$nx_xauthority x11docker --hostdisplay [...]
```
If you like to try out a setup like this, I'll happily add this to the wiki.
You could first try to run regular applications with nxlibs first. Once that succeeds, you could run x11docker using the same connection.

I tend to not implement remote connections within x11docker directly. I fear too much special needs that has to be regarded and might explode the already big number of x11docker options. Just to mention a big bunch of different possible ssh setup options that x11docker would have to provide in turn, too. Or look at the many connection options of xpra; I won't add them all to x11docker.
By a manual setup of xpra, ssh or nxlibs the user can choose desired options himself. The wiki just describes working examples as a first guidance. 

> The noted nxagent process may actually be the client.

The nxagent process is the nested X server that should run on the local machine.
As noted above, I don't know how to set up a remote nxlibs connection. I just never tried out.
x11docker option `--nxagent` does not use the remote setup locally (like it does with xpra) but directly accesses the nxagent X server. This use case is not documented or foreseen in the nxlibs documentation. (In fact this direct usage has some pitfalls that are circumvented by x11docker.)

> I'd wonder about other enhancements, like the ability to re-attach to a remote session in the event of temporary downtime

I don't know if nxagent has this feature. xpra does, and that is one of the reasons why I recommend it.

> or the potential of recording the stream for convenient playback (much like the commercial variant produces .nxr files).

In ticket #199 one successfully recorded a remote x11docker session with `ffmpeg`.

> If the primary functionality is already built into nx-libs it may just be a matter of invoking it.

If nxagent provides this easily, I would consider to add this to the `--nxagent` option. Though, I am not sure if this is a reasonable numerous use case.
