### ISSUE TITLE
changelog, tags, and versioning

### ISSUE THREAD

**Issue by ehough** [mviereck/x11docker#38]
I'm curious if you've given any thought to any of the following versioning tools:

* [keeping a separate changelog](https://keepachangelog.com/en/1.0.0/), either in a `CHANGELOG` file or via GitHub's Releases feature (see next bullet point)

* [Tagging releases](https://help.github.com/articles/about-releases/)

* [Semantic versioning](https://semver.org/), though it looks like you may already be adhering to this?

As a user, I expect and find it convenient to see a separate changelog, and I found it a little unusual to see one embedded within the script. Was there any reason you went that route?

**Comment by mviereck** [comment]
Thanks for this inspiration!
Thinking about this, the changelog and versioning can and should be improved. I am not sure which way to choose, I will look closer at the possibilities.

> Semantic versioning, though it looks like you may already be adhering to this?

Mainly I am already doing this, but reading the rules again shows me that I should follow this more precisely in future.

> As a user, I expect and find it convenient to see a separate changelog, and I found it a little unusual to see one embedded within the script. Was there any reason you went that route?

Just an old habit, no special reason. Mostly I am scripting only for myself, and I like to keep it simple. Having the changelog in the script means, I always know where it is and can see the state of the script.

**Comment by mviereck** [comment]
I've outsourced the changelog to a file `CHANGELOG.md`. Looks better now, indeed.

**Comment by ehough** [comment]
Looks great. And much easier to follow. Nice work!
