### ISSUE TITLE
Consider potential value-add of pipewire project

### ISSUE THREAD

**Issue by Intensity** [mviereck/x11docker#380]
Leaving this open-ended for now, since I don't want to add the bias of a predetermined fixed set of use cases when there could be others I'm not aware of.

However it appears to be an interesting project and perhaps it offers unique functionality that can be leveraged or integrated on the host or guest containers.

**Comment by mviereck** [comment]
What could pipewire add to x11docker?
I know it can replace `pulseaudio`, but I don't see a need to do so.
