### ISSUE TITLE
only console users are allowed to run the x server

### ISSUE THREAD

**Issue by felixhume** [mviereck/x11docker#385]
> x11docker --nxagent --desktop --gpu --fullscreen --sudouser --shell="bash" --env="SHELL=/bin/sh" --dbus --hostdbus --sharecgroup --  --  x11docker/kde-plasma

 is the command i used
i got this error:

x11docker ERROR: waitforlogentry(): dockerrc: Found error message in logfile. 
  Last lines of logfile xinit.log: 
 
/usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server

any help? 
thanks

**Comment by mviereck** [comment]
Please have a look at the rest of x11docker output.
`--nxagent` does not support `--gpu`. So x11docker uses `--xorg` as a fallback and should have told you so.

x11docker also prints a message regarding "Only console users are allowed to run the X server" and provides a solution:
```
x11docker WARNING: Your configuration seems not to allow to start
  a second core Xorg server from within X. Option --xorg may fail.
  (Per default, only root or console users are allowed to run an Xorg server).

  Possible solutions:
  1.) Install one of nested X servers 'Xephyr', 'Xnest' or 'nxagent'.
      For --gpu support: install 'weston' and 'Xwayland'.
  2.) Switch to console tty1...tty6 with <CTRL><ALT><F1>...<F6>
      and start x11docker there.
  3.) Run x11docker as root.
  4.) Edit file '/etc/X11/Xwrapper.config' and replace line:
          allowed_users=console
      with lines
          allowed_users=anybody
          needs_root_rights=yes
      If the file does not exist already, you can create it.
      On Debian and Ubuntu you need package xserver-xorg-legacy.
      
   Be aware that switching directly between Xorg servers can crash them.
   Always switch to a black console first before switching to Xorg.
```
If you do not get this message, please tell me.

**Comment by felixhume** [comment]
i thought i had installs weston but hadn't
