### ISSUE TITLE
refactor: split the main script into multiple files, use template files

### ISSUE THREAD

**Issue by milahu** [mviereck/x11docker#388]
> Due to the size of x11docker (9k lines of code) it is a bit difficult to debug and maintain it for others than myself.

is probably the main issue in #353

see my solution to [use bash to generate bash script from template](https://stackoverflow.com/a/69479243/10440128)
these template files (`*.tpl.sh`) are MUCH easier to read and maintain than template-strings

i suggest to move all the branching code (if/else/case) into the template files,
and use only the template variables for branching

currently, im extracting [the code for Xephyr](https://github.com/mviereck/x11docker/wiki/Short-setups-to-provide-X-display-to-container#providing-nested-x-server-xephyr), to create a minimalistic `xephyr-docker`

**Comment by eine** [comment]
> I just don't see a need because x11docker works as it is.

Agree. I do believe that a Python3 module with the X server stuff separated from the container specific layer would be (re)usable by several projects, so it might potentially slightly improve the popularity of x11docker. However, as commented in some other issue, that's a several week effort (if not months). It does only make sense for someone who wants to learn about either bash or Python, as an exercise with a useful outcome.

**Comment by mviereck** [comment]
> see section "Gitpod" in hdl/containers#45. That's what I had in mind.

I am not exactly sure what you want to point me on. If I understand right that section tells of GUIs in containers and cites x11docker. Would there be a need for a pure X server tool?

**Comment by mviereck** [comment]
> I believe it should be possible to use x11docker with authentication features enabled for using an X server or xpra instead of VNC.

I thought that it was this what @umarcor wanted to say there.

**Comment by milahu** [comment]
> let me close this as "too much pain, too little gain"

for what its worth ... here is my attempt at refactoring
if anyone wants to port x11docker to python (or whatever), maybe this is a useful start

i removed the function-redirects for better readability (and cos `tree-sitter-bash` parsed them wrong)

new [x11docker](https://github.com/milahu/x11docker/blob/refactor-split-files-3/x11docker) script

all functions moved to [lib/](https://github.com/milahu/x11docker/tree/refactor-split-files-3/lib) (added some of my temp files by accident, e.g. `*.txt` and `*.2.sh`)

sample use of `fsed1file` (template processor) in [lib/alertbox.sh](https://github.com/milahu/x11docker/commit/ef905386adfee119d4f2c39d927bb5fc58d509ae#diff-76b5a357391276b282a516f54f48ef3c207f46d8192dc58c208d5183d38415f8)

sample result of [extract_script.sh](https://github.com/milahu/x11docker/blob/2ce2db3df32b9a3f72a2328ff37cb75f7cdd6284/extract_script.sh) = call a x11docker-subfunction, write output to file, generate call to `fsed1file`
[lib/create_dockerrc.tpl.sh](https://github.com/milahu/x11docker/blob/2ce2db3df32b9a3f72a2328ff37cb75f7cdd6284/lib/create_dockerrc.tpl.sh)
[lib/create_dockerrc.call-tpl.sh](https://github.com/milahu/x11docker/blob/2ce2db3df32b9a3f72a2328ff37cb75f7cdd6284/lib/create_dockerrc.call-tpl.sh)

the manual work:
set switching vars like 

```bash
Debugmode="yes"
Containersetup="yes"
Containerenvironmentcount=1 # lib/store_runoption.sh
Sharevolumescount=1
Containerenvironment=("TODO__Containerenvironment_idx_0__TODO")
Sharevolumes=("TODO__Sharevolumes_idx_0__TODO")
```

... and move ALL switching code into the `*.tpl.sh` file

alternative approach:
parse the x11docker-subfunction, process the `echo` calls
problem is: i have not-yet found a bugfree parser. closest is https://github.com/tree-sitter/tree-sitter-bash
sample bug in tree-sitter-bash: https://github.com/tree-sitter/tree-sitter-bash/issues/108
bashlex for python has lots of "not implemented" code

**Comment by mviereck** [comment]
Thank you for explaining your thoughts and attempts!

>   i removed the function-redirects for better readability (and cos tree-sitter-bash parsed them wrong)

That's a good suggestion, I've changed x11docker accordingly.

> new x11docker script
> all functions moved to lib/ 

The new x11docker script looks pretty much same here in `kate` with code folding.
I'd say splitting code into multiple files is not a value by itself. It makes sense if the separated files can be used independently on their own. This is the case only for a few helper functions yet.

It would be possible to write more independent/modular functions. Currently many of them rely heavily on global variables, what is not really great. 
In a major rewrite it would be a possible way to write more modular functions that print some actually needed code. For example, a `sound()` function could print (by switch) docker command parts or pulseaudio config files.
In a similar way a `gpu()` function could print code for docker command and code for nvidia driver installation in container.

> sample use of fsed1file (template processor) in lib/alertbox.sh
sample result of extract_script.sh = call a x11docker-subfunction, write output to file, generate call to fsed1file
lib/create_dockerrc.tpl.sh
lib/create_dockerrc.call-tpl.sh

This part I still try to understand. It is nice to have one escape level less than before, but in change another complexity is added.
