### ISSUE TITLE
Is it possible to run a container rather than image?

### ISSUE THREAD

**Issue by djypku** [mviereck/x11docker#395]
Hello, I know that --home and --share are supported, but here is problem that, for example, I run a Xfce docker and then find that apt is not usable at all. At the same time, while I CAN change screen resolution, the change is lost when restarting it.
--home is useless since these changes are not in /home. As for --share, problem is that the mount files and dirs of the host in the same route and so that if I use --share, it will use the files (for example : /etc) of the host which is not my aim.
Maybe x11docker does not provide such a method to mount files from Host is different route. However technologically that is not hard right? Could you tell me where to revise maybe in the source so that I can manage to save changes out of /home?
Thanks

----------------------------------------------------------------------------------------------------------------
After some trying I find it possible to just run a docker-with-gui with 
`startx xterm ; xhost + ; podman start ......`
rather than use
`podman run ......`
Later on is just as x11docker. The difference between two is that the former one run a container yet later one run an image. 
In such way, saving any file at any route is OK in the docker-gui. 
However, using xterm give me THREE problem. First, it will open a window with xterm and cannot be close or else the docker will be close too. Second, it is not good in security. And the most annoying thing is that at that case the apps running is not stable. There are many bugs or even cannot start. 
So I want to know whether possible to run a container rather than image with x11docker.
Thanks

**Comment by fabifrank** [comment]
Have you tried using `DOCKER_RUN_OPTIONS` by setting a volume like `-v ${SOURCE}:${TARGET}`?

**Comment by mviereck** [comment]
>  So I want to know whether possible to run a container rather than image with x11docker.

This is not possible. x11docker is designed to run directly from an image. 
The underlying issue is in docker; if one shares an X unix socket with a container, and it is gone on reboot (as always), the docker daemon creates a root owned folder at the same path. So it is not possible to use the display number again, but it is set as an environment variable in the container.

> As for --share, problem is that the mount files and dirs of the host in the same route and so that if I use --share, it will use the files (for example : /etc) of the host which is not my aim.

You can use option `--volume` as @fabifrank pointed out.

> I run a Xfce docker and then find that apt is not usable at all. 

Use option `--sudouser` to allow the usage of `apt`. Default root password is `x11docker`.
However, for persistance you have to adjust the Dockerfile and build a new image.

> At the same time, while I CAN change screen resolution, the change is lost when restarting it.

You could create an `xrandr` command e.g. with `arandr` and store it in container in `~/.config/autostart`. Or use option `--size`.

**Comment by djypku** [comment]
Well, for me I tried apt but not works even with root, and --size not work too. Thanks for replying me soon. I am then thinking about how to hacking this problem.
BTW:X11docker is much more stable than run a desktop in docker directly, you do really well.

**Comment by mviereck** [comment]
`-size` and `apt` with `--sudouser` work well here (both with `su` and `sudo`), and with both backends `podman` and `docker`.
Can you give me an example how to reproduce your issues?

--------

> For podman, no daemon is here. So maybe it is possible to run GUI from a cantainer?

That might work. It would be a major task to adjust x11docker for this. But you could try with a custom version of the scripts in https://github.com/mviereck/x11docker/wiki/Short-setups-to-provide-X-display-to-container .
Some details of the setup might avoid some issues you've got with your previous custom setup.

**Comment by djypku** [comment]
> `-size` and `apt` with `--sudouser` work well here (both with `su` and `sudo`), and with both backends `podman` and `docker`. Can you give me an example how to reproduce your issues?
> 
> > For podman, no daemon is here. So maybe it is possible to run GUI from a cantainer?
> 
> That might work. It would be a major task to adjust x11docker for this. But you could try with a custom version of the scripts in https://github.com/mviereck/x11docker/wiki/Short-setups-to-provide-X-display-to-container . Some details of the setup might avoid some issues you've got with your previous custom setup.

_____________________________________________________________________
Thank you much. I use x11docker that directly `dnf` from source of Fedora and it is out of date now. I will try new version from github to find out whether these problem remain.
 As for the WIKI, that is awesome, but I have tried similar things with Xorg and too many bugs. Maybe I will try the shell later. BTW: I regret not watching WIKI before.
______________________________________________________________________
I wrote maybe too much words here, hoping you are not tired with me. Actually I am trying to develop something on the ground of X11docker. It may be very hard for me, but I will try.
