### ISSUE TITLE
Language-supporting Fixing for desktop environments of x11docker

### ISSUE THREAD

**Issue by djypku** [mviereck/x11docker#397]
You provide many DEs for x11docker, but they only support English now ( or at most  some other Latin-letter western languages ). I managed to add global ( I hope so ) languages supports.
For example, for xfce, my dockerfile is to add
`    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \ 
      libc-l10n \ 
      locales \ 
      locales-all && \  `
For language support.
And also
`    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \  
      fonts-noto* && \`
For fonts support (otherwise you just see so-called tofu or some numbers in blocks)

For me, I add two above between
`RUN apt-get update && apt-mark hold iptables && \`
And 
`env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \  
      dbus-x11 \  
......`
And others are just the same from x11docker/xfce. Now xfce supports Chinese, Arabic, Thai, Japanese, Greek, Russian, Korean and so on.
For ordinary `podman`, `run` with `-e LANG=$LANG` to use host languages; while for x11docker, I have not understand your codes and parameters much, so you can do some trying.
___________________________________________________________________________
Please , I advise, use this update to most DEs under `x11docker/` as soon as possible. Bear in mind that some DEs may need more libs as said in [Debian Wiki](https://wiki.debian.org/ChangeLanguage) I have tried, however, only find out kde-l10n-xx is abolished. So please test several oriental languages for different DEs. It won't trouble you to try different system languages, you only need to visit website (for example Wikipedia)  to test their languages.
___________________________________________________________________________
Many Asian languages also need a program to input. `ibus` and `fcitx` are two under Linux. Definitely I will add this support, but maybe later, for I am kind of busy in the next week, and I think about making them into container.
Right-to-left support for some Middle-East and South Asia languages is also a problem. Sadly I do not know one of these languages much, so give me more time Please. In German there may be some Arabian people, you may ask one for help.

**Comment by mviereck** [comment]
In general I try to keep the base images as slim as possible. For that reason neither locales nor fcitx are installed. So one can build his custom Dockerfiles based on my examples and add only what he needs.

Installation of package `locales` in debian images adds 20 MB.
Installation of package `locales-all` in debian images adds 232 MB.
Installation of package `fcitx` in debian images adds 674 MB.

If one doesn't need this, it is a waste of resources. As a rule of thumb it is always worth to reduce resource usage.

x11docker provides option `--lang`. If `locales` is installed in image, x11docker generates the desired locale on the fly. So `locales-all` can be avoided. Compare README.md: https://github.com/mviereck/x11docker#language-locales

I once got fcitx running, but it was a bit messy. But basically it is possible.
I have no idea about writing from right to left and what might support/provide this.

**Comment by djypku** [comment]
> In general I try to keep the base images as slim as possible. For that reason neither locales nor fcitx are installed. So one can build his custom Dockerfiles based on my examples and add only what he needs.
> 
> Installation of package `locales` in debian images adds 20 MB. Installation of package `locales-all` in debian images adds 232 MB. Installation of package `fcitx` in debian images adds 674 MB.
> 
> If one doesn't need this, it is a waste of resources. As a rule of thumb it is always worth to reduce resource usage.
> 
> x11docker provides option `--lang`. If `locales` is installed in image, x11docker generates the desired locale on the fly. So `locales-all` can be avoided. Compare README.md: https://github.com/mviereck/x11docker#language-locales
> 
> I once got fcitx running, but it was a bit messy. But basically it is possible. I have no idea about writing from right to left and what might support/provide this.
______________________________________________________________________
Well, then maybe I will try doing this work myself. My aim is to provide a system-level desktop experience as possible. Since we are not doing the same thing, I will do it myself on the ground of your work.
I am surprise that you know 'fcitx'.I fail to install it ( in docker sometimes it is not OK to install as normal , to avoid or add some package is needed ), if you still remember some tips please tell me.
I do not understand why `locales-all` is not necessary, but I will try since you said that. Thanks.
______________________________________________________________________
BTW: I come up with a CRAZY idea, it may be possible to provide a WM by x11docker with the help of xdotool or something else. Just a one-minute thought, please do not take it too serious.

**Comment by mviereck** [comment]
Some quick pointers:
fcitx discussion in:
https://github.com/mviereck/dockerfile-x11docker-deepin/issues/3
https://github.com/mviereck/x11docker/issues/269

The ftcitx daemon can be started with the help of options `--runsasuser` or `--runasroot` if not started already with some init system.
