### ISSUE TITLE
problem about env in x11docker --exe

### ISSUE THREAD

**Issue by djypku** [mviereck/x11docker#398]
If I use `x11docker` to run program in an image, then it is possible to set `env` by `run` parameters of `docker` or `podman`. However, for `--exe` to run a host program, it cannot.
That is trivial. But the point is, when I use `x11docker` to run a host program, it do not inherit the `env` I `export` in the same tty. It seems that it use default `env` which is not my expectation. Then I try write something like ( for example ) `x11docker --exe "export ABC=123;openbox-session"` and also `x11docker --exe "export ABC=123&openbox-session"`.
That will really change `env`, but not the way I expect. Instead of showing `ABC=123`, there show a strange and extremely long result.
I do not know whether it can be called a bug or just a weak point, but it make manually change `x11docker --exe` 's `env` extremely hard if still possible and I think it should be revised.
I advise you to check out why `x11docker --exe "export ABC=123;openbox-session"` do not get correct results to fix this bug. Or you can try to make `x11docker --exe` simply inherit the `env` of  it's "mother" tty. Besides, you may provide your own parametres to change `env`.
I am using the latest x11docker version now, so it is an up-to-date problem.

**Comment by djypku** [comment]
Hopefully I do not annoy you writing here per day.

**Comment by mviereck** [comment]
I cannot reproduce the issue here.
```
$ export a=b
$ x11docker --exe xterm

## in xterm:
$ echo $a
b
```

It might be the same issue as in #399. If you use sudo, try with `sudo -E` to preserve the environment variables.
Aside from that, x11docker provides option `--env` to set environment variables.

> x11docker --exe "export ABC=123&openbox-session"

This can fail because `export` is not a command on itself but a shell builtin.
This one works:
```
x11docker --exe "sh -c 'export ABC=123 ; xterm'"
```
However, rather use option `--env ABC=123`.

**Comment by djypku** [comment]
> I cannot reproduce the issue here.
> 
> ```
> $ export ABC=123
> $ x11docker --exe xterm
> 
> ## in xterm:
> $ echo $ABC
> 123
> ```
> 
> It might be the same issue as in #399. If you use sudo, try with `sudo -E` to preserve the environment variables. Aside from that, x11docker provides option `--env` to set environment variables.
> 
> > x11docker --exe "export ABC=123&openbox-session"
> 
> This can fail because `export` is not a command on itself but a shell builtin. This one works:
> 
> ```
> x11docker --exe "sh -c 'export ABC=123 ; xterm'"
> ```
> 
> However, rather use
> 
> ```
> x11docker --env ABC=123 --exe xterm
> ```

________________________________________________________________
Firstly, adding `-E` just work fine. Thanks!
Second, using `sh -c` or `--env` ( oh I had never known you add this parametre ), it can definitely do the job, but it will meanwhile export some strange ENV too.

**Comment by djypku** [comment]
By the way, could you explain the usage of `-i` and `--enforce-i` ? I do not understand the help file well, and I try but nothing happens.

**Comment by mviereck** [comment]
> Second, using sh -c or --env ( oh I had never known you add this parametre ), it can definitely do the job, but it will meanwhile export some strange ENV too.

What do you mean? What kind of strange ENV do you get?

> By the way, could you explain the usage of -i and --enforce-i ? I do not understand the help file well, and I try but nothing happens.

You'll likely never need `--enforce-i`. It only serves to fix a rare issue on some systems to run `weston` from tty.

`-i` allows an interactive shell. However, you only get an effect with interactive cli applications.
Try e.g. `x11docker -i --desktop x11docker/xfce bash`. You'll get an interactive bash prompt and can run cli applications or start a GUI like `thunar`.

**Comment by djypku** [comment]
`sudo -E x11docker --exe "sh -c 'export ABC=123 ; xterm'"`
And then
`env|grep ABC`
 get
`ABC=123`
`SUDO_COMMAND=/usr/bin/x11docker --exe sh -c 'export ABC=123:xterm'`
`XAUTHORITY=/home/jydeng/.cache/x11docker/sh-x-export-ABC-123-xterm-26942715878/share/Xauthority.clint`
Using `--env` makes similar results.
It seems to be some records of last command. Something kind of strange, but it does not matter whatever.
Thanks.

**Comment by djypku** [comment]
`x11docker -i --desktop x11docker/xfce bash`
What is the difference from
`x11docker --desktop x11docker/xfce xfce4-terminal`
then?
On my computer former one just not work. It starts a Xephyr with nothing in it.

**Comment by mviereck** [comment]
>  On my computer former one just not work. It starts a Xephyr with nothing in it.

Look at the terminal where you've started x11docker. You can type commands there.
