### ISSUE TITLE
--hostdisplay seems broken （Solved by myself）

### ISSUE THREAD

**Issue by djypku** [mviereck/x11docker#399]
I try new version `x11docker`, finding whether I use `--wm` or `--hostdisplay`, there will be a completely new window to shadow old one, and I find `env | grep DISPLAY` also changed, even input `-e DISPLAY=$DISPLAY` do not help.

**Comment by djypku** [comment]
I find out that this problem is because `x11docker` demand a `Xorg` running when using `nxagent`, `xpra` and `xephyr`, but somehow on openSUSE ( My violent behavior has broken the Fedora VM  ) `x11docker` cannot detect running `Xorg` , ( it says "DISPLAY is empty" but actually `env|grep DISPLAY=:0.0` ) ,so it run `Xorg` compulsively and then produce such problem. I will use debug mode to check, but I still suggest you to enable like `--force` option to compulsively run like selected xserver like `--force --nxagent`.

**Comment by djypku** [comment]
`Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
`
`Environment variables DISPLAY and WAYLAND_DISPLAY are empty,
  but it seems x11docker was started within X, not from console.
  Please set DISPLAY and XAUTHORITY.
`
But actually these `env` exist and are not empty.
____________________________________________________________
`If you have started x11docker with su or sudo, su/sudo may be configured to
  unset X environment variables. It may work if you run x11docker with
    sudo -E x11docker [...]
`
I try  `sudo -E` and that is OK, fine. This tip is too infamous and unimpressive...

**Comment by mviereck** [comment]
> but I still suggest you to enable like --force option to compulsively run like selected xserver like --force --nxagent.

You can use option `--fallback=no`.
