### ISSUE TITLE
X or Wayland inside a container?

### ISSUE THREAD

**Issue by ehough** [mviereck/x11docker#40]
This may be a naive or dumb question, but what are your thoughts on running X or Wayland entirely within a container? Assuming this is possible, it seems that you could eliminate virtually all host requirements (aside from Docker itself, of course) for x11docker. Some light Googling on the subject indicates that folks have had some success running X in a (privileged) container.

As a non-expert on X or Wayland, I think it would be incredibly convenient to not have to worry about which packages I need on the host. This could also lead to some really neat [compose](https://docs.docker.com/compose/overview/) files that would fire up GUI apps with essentially no host requirements.

Does that make sense? Thoughts?

**Comment by mviereck** [comment]
> This may be a naive or dumb question, but what are your thoughts on running X or Wayland entirely within a container? 

It is a good question, and I already gave it some tries. :-) Unfortunately with only few success. 

I almost got `Xorg` to run with some rather host specific settings. But I never got a working tty switch with `CTRL+Fn` and was trapped within the containered X.  After some dozens hard shutdowns and reboots I gave up.

I tried to get `weston` running in container, but with no success.

The best success I have with `Xwayland` in container and `weston` on host: [x11docker/xwayland](https://github.com/mviereck/dockerfile-x11docker-xwayland). (But it depends on `--gpu` and thus fails with closed source nvidia drivers).

I would really appreciate a working setup, but currently I am stuck.

**Comment by mviereck** [comment]
Great progress!
I can run `weston` in a docker container!

The setup is with nearly no isolation from host and I have to restrict step by step until I provide the minimal setup needed. Also I have to check for currently hardcoded `seat0`. But nonetheless, it already works:
```
FROM debian:buster
RUN apt-get update
RUN apt-get install -y weston
```
```
#! /bin/bash

tty | grep -q '/dev/tty' || {
  echo "ERROR: Must run from tty/console" >&2
  exit 1
}

docker run --tty --rm --env XDG_RUNTIME_DIR=/tmp \
    --cap-add=ALL --uts=host --net=host --pid=host --ipc=host --privileged \
    --volume=/var/run:/var/run \
    --volume /run/systemd/seats/seat0:/run/systemd/seats/seat0 \
    westonimage \
    agetty --login-options '' --skip-login --login-program /usr/bin/weston $(tty | sed 's/dev\///')
```

**Comment by mviereck** [comment]
Improved restricted version witch check for `seat0`:
```
#! /bin/bash

tty | grep -q '/dev/tty' || {
  echo "ERROR: Must run from tty/console" >&2
  exit 1
}

[ -z "$XDG_SEAT" ] && echo "WARNING: XDG_SEAT is empty" >&2 && seat=seat0 || seat=$XDG_SEAT
[ -e "/run/systemd/seats/$seat" ] && seat="/run/systemd/seats/$seat" || {
  echo "ERROR: $seat not found" >&2
  exit 1
}

docker run --rm --env XDG_RUNTIME_DIR=/tmp \
    --device $(tty) --device /dev/dri --device /dev/input \
    --cap-add SYS_TTY_CONFIG \
    --volume=/run/udev/data:/run/udev/data:ro \
    --volume $seat:$seat:ro \
    westonimage \
    agetty --login-options '' --skip-login --login-program /usr/bin/weston $(tty | sed 's/dev\///')
```
One issue left: `weston` runs as root, need to restrict to an unprivileged user.

**Comment by ehough** [comment]
Just as a data point, I tested this today on my workstation and it didn't work, probably because I was already running KDE at another tty. The screen seemed to freeze; `Ctrl-Alt-F7` didn't let me switch away. I had to SSH in from my laptop and kill the `agetty` process to resume control.

[Screenshot](https://i.imgur.com/8ciphkG.jpg).

As soon as I get a chance I'll test again without any other X servers running.

**Comment by mviereck** [comment]
Thanks for feedback!
Yes, I encountered this, too, forgot to report this here. 
There is an issue with the `--skip-login` option. Sometimes agetty still wants you to type in the username (but no password), but the login prompt is overwritten by weston messages. (Type root + enter, and it goes on). I have an extended test script now that avoids this issue. I will edit my post above.

**Comment by mviereck** [comment]
ok, is fixed now, I've edited the commands above. 
Instead of `--skip-login` the command now runs with `--autologin root`.

**Comment by mviereck** [comment]
The current state of Dockerfile and startscript:
 -  able to run weston either from tty, or in X, or in Wayland
 - weston runs as unprivileged user

Two issues:
 - using setuid with agetty and removing setuid bit later is an ugly workaround
 - with option ` -- --fullscreen` in an X display weston does not use the full screen but only parts of it. The rest shows some GPU garbage.

Dockerfile for `x11docker/weston`:
```
# x11docker/weston

FROM debian:buster
RUN apt-get update
RUN apt-get install -y weston
RUN apt-get install -y psmisc procps

# setuid agetty to allow for unprivileged user. undone in startweston.
RUN chmod +s /sbin/agetty /bin/chmod

# startscript to remove setuid from chmod and agetty before running weston
RUN echo '#! /bin/bash \n\
set -- "$(echo "$@" | cut -d'#' -f1)" \n\
chmod -s /sbin/agetty /bin/chmod \n\
[ -e "/x11docker" ] && { \n\
  [ -n "$DISPLAY$WAYLAND_DISPLAY" ] && exec weston $@ || exec weston-launch -- $@ >>/x11docker/stdout 2>>/x11docker/stderr\n\
} || { \n\
  [ -n "$DISPLAY$WAYLAND_DISPLAY" ] && exec weston $@ || exec weston-launch -- $@ \n\
} \n\
' > /usr/local/bin/startweston ; chmod +x /usr/local/bin/startweston

# startscript to run weston either from tty or within DISPLAY or WAYLAND_DISPLAY
RUN echo '#! /bin/bash \n\
case "$DISPLAY$WAYLAND_DISPLAY" in \n\
  "") \n\
    [ -e /dev/tty$XDG_VTNR ] && [ -n "$XDG_VTNR" ] || { \n\
      echo "ERROR: No display and no tty found. XDG_VTNR is empty." >&2 \n\
      exit 1 \n\
    } \n\
    exec agetty --login-options "$@ #" -a "$(id -un)" --login-program /usr/local/bin/startweston tty$XDG_VTNR \n\
  ;; \n\
  *) \n\
    exec /usr/local/bin/startweston $@ \n\
  ;; \n\
esac \n\
' >/usr/local/bin/start ; chmod +x /usr/local/bin/start

ENTRYPOINT start
``` 
Script to run `x11docker/weston`:
```
#! /bin/bash
# Run x11docker/weston from tty or from within X or Wayland.
#
# Options before -- are provided to x11docker (before its own --)
# Options after  -- are provided to weston

# Split options at --
Options="$@"
Options_x11docker="${Options% -- *}"
echo $@ | grep -q ' -- ' && Options_weston="${Options##* -- }" || Options_weston=""

case "$DISPLAY$WAYLAND_DISPLAY" in
  "") # Setup to run from tty

    tty | grep -q '/dev/tty' || {
      echo "ERROR: Must run from tty/console or within X or Wayland." >&2
      exit 1
    }

    [ -z "$XDG_VTNR" ] && XDG_VTNR=$(tty | cut -c9-)
    [ -z "$XDG_VTNR" ] && {
      echo "ERROR: XDG_VTNR is empty and/or tty has no number."
      exit 1
    }

    [ -z "$XDG_SEAT" ] && echo "WARNING: XDG_SEAT is empty. Check output of loginctl." >&2 && seat=seat0 || seat=$XDG_SEAT
    [ -e "/run/systemd/seats/$seat" ] && seat="/run/systemd/seats/$seat" || {
      echo "ERROR: $seat not found" >&2
      exit 1
    }

    x11docker --gpu --nothing --cap-default \
      --env XDG_VTNR=$XDG_VTNR \
      --group-add weston-launch \
      $Options_x11docker \
      -- \
      --device=$(tty) --device=/dev/input \
      --cap-add=SYS_TTY_CONFIG \
      --volume=/run/udev/data:/run/udev/data:ro \
      --volume=$seat:$seat:ro \
      x11docker/weston $Options_weston
  ;;

  *) # Setup to run within X or Wayland.
    x11docker $Options_x11docker -- x11docker/weston $Options_weston
  ;;
esac
```

**Comment by mviereck** [comment]
tty switching remains to be a major issue. 

I found a partial solution:
 - install `kbd` in image, some console tools.
 - share `/dev/tty0` with container.
- setuid `/bin/chvt`
 - `chvt N` in weston terminal switches to tty N.

BUT: switching to an already running X server causes it to crash. It seems that weston does not deallocate drm/graphics card/GPU. 
So far it is better not to allow tty switching. But it is a showstopper to be trapped in weston. After terminating weston tty switching is ok, even to X.

**Comment by mviereck** [comment]
Finally x11docker allows to run Xorg in a container. 
Since x11docker version 7.1.5-beta-17 this is possible with options `--xc --xorg` if image `x11docker/xserver` is provided.
The most important missing key was to share `/run/udev/data` with the container to allow right hardware detection for Xorg. Other important parts are capability `TTY_SYS_CONFIG` and devices in `/dev/input`.
The setup is still experimental. I hope it will work on other machines and setups as well.

Dependencies on host are reduced now; however, X tools like `xauth` are still used from host.

The setup for `weston` in container outlined above does not work anymore. I did not investigate the reason.
