### ISSUE TITLE
Which audio mode is suggested?

### ISSUE THREAD

**Issue by djypku** [mviereck/x11docker#403]
There are two audio option:`--alsa` and `--pulseaudio`, and actually later one has additional option `tcp` and `socket`.
I have read the wiki where it says that `--alsa` may have problem when more than one program trying to use sound devices. As a result, maybe `--pulseaudio` is better. However, for `tcp` and `socket`, I have no idea about each's weak points.
Since you make `socket` as default, is `--pulseaudio socket` the most recommended way to provide audio support?

**Comment by mviereck** [comment]
In general I suggest the pulseaudio socket mode.
`--alsa` is useful in cases where either host or container do not provide pulseaudio.
The pulseaudio socket mode is likely to be a bit more performant than the tcp mode. The tcp mode is used in few cases only (e.g. with `--runtime=kata-runtime`) where a socket connection is not possible.

**Comment by djypku** [comment]
thanks
