### ISSUE TITLE
Question about to open a host program in docker without xhost +

### ISSUE THREAD

**Issue by djypku** [mviereck/x11docker#405]
1,
preparing `~/test.sh` just like #404 
2,
switch to a black tty
3,
input `sudo -E x11docker --share=home x11docker/xfce`
4,
open a xfce4-terminal in xfce and input 
`echo "export DISPLAY=$DISPLAY ;export $XAUTHORITY=XAUTHORITY; xterm " >~/temcom.txt`
Nothing happens.

5,
input
`xhost +`
`echo "export DISPLAY=$DISPLAY ; xterm " >~/temcom.txt`
It works. A `xterm` is open.

Question:
After weeks of attempt I finally manage to start host gui program in docker desktop. While `xhost +` works, it seems to be not secure. I think about using `XAUTHORITY` but not works. Maybe `xauth` is necessary but I am lost here. Could you give me some points?

**Comment by mviereck** [comment]
It should work without using `xhost`.

You have a typo here: `export $XAUTHORITY=XAUTHORITY`
Instead it should be:  `export XAUTHORITY=$XAUTHORITY`

Maybe that's already the issue?

> After weeks of attempt I finally manage to start host gui program in docker desktop.

Did you try option `--runfromhost` as suggested in another ticket?

**Comment by djypku** [comment]
OMG, what a STUPID mistake I made. However, after correcting it still not works. Problem is that I run a DE from a black tty without `XAUTHORITY` and the `XAUTHORITY`  of `x11docker` DE is `/x11docker/Xauthority.client`, but such file does not exist in host system.
I am trying to due with it.
BTW:`--runfromhost` does not work for me.

**Comment by mviereck** [comment]
> Problem is that I run a DE from a black tty without XAUTHORITY and the XAUTHORITY of x11docker DE is /x11docker/Xauthority.client, but such file does not exist in host system.

Oh, ok, right.
I've just uploaded a commit that might serve you. (Get it with `--update-master` in a few minutes.)
The former option `--showenv` is replaced by `--printenv [=FILE]`.
If you run e.g. `x11docker --printenv=~/cenv --desktop x11docker/xfce`, it will print `DISPLAY` and `XAUTHORITY` into file `~/cenv`.
In your script you can run e.g. `source ~/cenv` to get the variables.

>  BTW:--runfromhost does not work for me.

What is the issue? I can run e.g. `--runfromhost 'xterm &'` and get an xterm from host.

**Comment by djypku** [comment]
Maybe I do not use `--runfromhost` option in right order?
