### ISSUE TITLE
Announcement: No internet access since v7.0.0. Needs -I, --network

### ISSUE THREAD

**Issue by mviereck** [mviereck/x11docker#406]
In v7.0.0 x11docker disables internet access by default to increase container isolation.
Internet access can be enabled with option `-I, --network`.

This also affects rather special options `--pulseaudio=tcp`, `--printer=tcp`, `--xoverip`, `--runtime=kata-runtime`, `--runtime=sysbox-runc`.

It's not a bug, it's a feature. :-)

**Comment by djypku** [comment]
Not a `x11docker` bug though yet I would like to ask here in case you have some idea .I find somehow `--network` not work on my computer, but `--network=host` works. I find that even `sudo docker --network` does not work, which means bridge mode of docker network just break down, which makes `docker` hard to use or even not OK for some images not suitable for `--network=host`.I have no idea about why, it used to be just fine.
Well it does not disturb me not for I am about to switch to other dIstro this year maybe in the next several month, and I guess it well be juslt fine. However, I wonder if you know something may relate to such problem.
BTW, I am thinking about switching to Fedora Silverblue which ban installation to `/usr/bin` and ban most changing directly at root dir but to do any changes at `/var/...` instead. Are there any changes `x11docker` do directly under `/*`? If so. I may need to revise some codes then.

**Comment by mviereck** [comment]
Could you please open a new ticket for your issue? It doesn't seem to be related to my announcement.

**Comment by djypku** [comment]
Not a x11docker bug after all, I withdraw it.
