### ISSUE TITLE
Professional services

### ISSUE THREAD

**Issue by mfloiot** [mviereck/x11docker#416]
Do you know a company providing professional services around x11docker project?

**Comment by mviereck** [comment]
I am not aware of any company that provides support around x11docker.
After all, the code is a bit complex, and one might have a hard time if it comes to bug fixes or a clean integration of new features.

So far, I am the one who knows x11docker the best. :-)
Maybe I could help? What service would you need?

**Comment by mfloiot** [comment]
>Maybe I could help? What service would you need?
Can we have phone call or private email on that?

**Comment by mviereck** [comment]
Of course; I'll write/edit my email adress here in a moment and remove it once you wrote me the first time.

**Comment by mviereck** [comment]
Please have a look at my edited post.

**Comment by mfloiot** [comment]
Thanks, got it!
