### ISSUE TITLE
Commits from fac8367 and onward break Docker volume mounting.

### ISSUE THREAD

**Issue by bernharl** [mviereck/x11docker#419]
When mounting using `sudo x11docker --network=host -i -g --share=ros --env TERM=screen-256color  --hostdisplay --sudouser --verbose <container>` I now get this error message from commit fac8367 and onward:
```
x11docker ERROR: Unknown option ros
  Parsed options:
   --network 'host' -i -g --share 'ros' --env 'TERM=screen-256color' --hostdisplay --sudouser '' --verbose '' -- '<container>'

  Type 'x11docker --help' for usage information
  Debug options: '--verbose' (full log) or '--debug' (log excerpt).
  Logfile will be: 
  Please report issues at https://github.com/mviereck/x11docker
```
Commits before that work as expected and mount the `ros` volume at `/ros`.

**Comment by mviereck** [comment]
Thank you for the report!
I've fixed the issue, the fix is in latest master. I'll publish a new release soon.

**Comment by bernharl** [comment]
Great stuff, now it works!
