### ISSUE TITLE
X server is not being forwarded

### ISSUE THREAD

**Issue by richbai90** [mviereck/x11docker#420]
I just started having this issue, I don't have any idea what might have caused it. When I run my application in X11docker the application is not able to connect to an X server. I have docker/x11 pulled and this was working as recently as yesterday. I'm trying to figure out what might cause this. Here is the output:

```
$ x11docker --user=RETAIN -it -- --volume=(pwd)/src:/home/quartus/src:Z quartus:latest ./start
x11docker WARNING: User rich is member of group docker.
  That allows unprivileged processes on host to gain root privileges.

x11docker note: Option --network=none is set to disable network access.
  If you need network and internet access, set option -I, --network.

x11docker WARNING: Found custom DOCKER_RUN_OPTIONS.
  x11docker will add them to 'docker run' command without
  a serious check for validity or security. Found options:
   --volume=/home/rich/src:/home/quartus/src:Z

quartus: cannot connect to X server 
```

**Comment by richbai90** [comment]
Nevermind the -it disables the x server forwarding. My bad. Closing this issue.

**Comment by mviereck** [comment]
If you use `-i` without `-t` the X server will run.
