### ISSUE TITLE
From the docker container launched by x11docker, use the highest resolution possible to create screenshots including the host screen as part of it.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#422]
I'm running WeChat from [my docker container](https://github.com/hongyi-zhao/dockerfile/blob/master/deepin/wine/Dockerfile), launched by x11docker. When I try to create the screenshot using the capture tool shipped with WeChat, I find the following shortcomings/drawbacks/bottlenecks:

1. The screenshot created has low resolution and is blurry.
2. The screenshot can't include the host screen as part of it.

So, I want to know if I can create screenshots from the docker container launched by X11 docker with the highest resolution possible, including the host screen as part of it?

Regards,
HZ

**Comment by mviereck** [comment]
> The screenshot created has low resolution and is blurry.

This is likely an issue of the screenshot tool.

> The screenshot can't include the host screen as part of it.

It is a feature of x11docker that the X server of the host is not accessible for the container. The only exception is option `--hostdisplay`. That one should give you the full screenshot.

**Comment by hongyi-zhao** [comment]
> It is a security feature of x11docker that the X server of the host is not accessible for the container. The only exception is option `--hostdisplay`. That one should give you the full screenshot.

I enabled this option, but the screenshot tool launched from WeChat still has the same restriction.

**Comment by mviereck** [comment]
Maybe it is designed to capture the wechat window only?
It is unlikely that this is an x11docker issue.
Could you try another screenshot tool for comparision?

**Comment by hongyi-zhao** [comment]
> Maybe it is designed to capture the wechat window only?

The WeChat screenshot tool can capture the entire guest screen.

> Could you try another screenshot tool for comparision?

For the sake of simplicity, can you recommend such a tool?

**Comment by hongyi-zhao** [comment]
> Did you use `--hostdisplay` without another X server option? Please show me your command. You might need to add `--clipboard` or `--gpu` for unrestricted host X access.


```shell
$ x11docker --runasroot 'sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers
        |#$ sudo grep -Ev '\''^[ ]*(#|$)'\'' /etc/sudoers  
        |Defaults	env_reset
        |Defaults	mail_badpass
        |Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
        |root	ALL=(ALL:ALL) ALL
        |%admin ALL=(ALL) ALL
        |%sudo	ALL=(ALL:ALL) ALL
        |$USER ALL=(ALL) NOPASSWD:ALL
	EOF' --hostdisplay --xephyr --network=bridge --pulseaudio --xoverip --home --share=$HOME --sudouser -c --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add=ALL -- hongyizhao/deepin-wine:apricot
```

**Comment by mviereck** [comment]
> --hostdisplay --xephyr 

You have used `--xephyr` after `--hostdisplay`. So `--xephyr` instead of `--hostdisplay` is used.
Tools within Xephyr can only see the content of the Xephyr window.

Remove `--xephyr` and try `--hostdisplay --clipboard`. However, this is only feasible for single applications. If you run the full deepin desktop in container, it will interfere with you host desktop and might give a mess or fail at all.  

If your desire is to capture only the full Xephyr window content and it fails, it is likely an issue of the screenshot tool.

**Comment by hongyi-zhao** [comment]
> Remove `--xephyr` and try `--hostdisplay --clipboard`. However, this is only feasible for single applications. If you run the full deepin desktop in container, it will interfere with your host desktop and might create a mess or fail at all.

I launch the docker container with the following x11docker command, and install `flameshot` in docker container:

```
$ x11docker --runasroot 'sed -r "s/^[[:blank:]]*[|]//" <<-EOF > /etc/sudoers
        |#$ sudo grep -Ev '\''^[ ]*(#|$)'\'' /etc/sudoers  
        |Defaults	env_reset
        |Defaults	mail_badpass
        |Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
        |root	ALL=(ALL:ALL) ALL
        |%admin ALL=(ALL) ALL
        |%sudo	ALL=(ALL:ALL) ALL
        |$USER ALL=(ALL) NOPASSWD:ALL
	EOF' --hostdisplay --clipboard --network=bridge --pulseaudio --xoverip --home --share=$HOME --sudouser -c --desktop --init=systemd -- --device /dev/mem:/dev/mem --cap-add=ALL -- hongyizhao/deepin-wine:apricot
```

However, `flameshot` can still only capture the entire range of the guest screen, as shown below:

![image](https://user-images.githubusercontent.com/11155854/158382290-b8ba6d9f-8162-4f74-baad-1aedbec26c79.png)

> Edit: If you want to capture the host display and the Xephyr window together, than the only way is to use a screenshot tool on the host.

Yes, this is exactly what I want to do. It seems that I didn't describe it clearly at first.
