### ISSUE TITLE
Missing sponsors

### ISSUE THREAD

**Issue by sickcodes** [mviereck/x11docker#425]
Would be cool to be able to sponsor x11docker

**Comment by eine** [comment]
See https://github.com/mviereck/x11docker#support:

> If you like to make a donation: Thank you! :)
> 
> I don't take the money myself, but please spend some to [Galsan Tschinag](http://galsan-tschinag.de/portrait/) in Mongolia ([Wikipedia](https://en.wikipedia.org/wiki/Galsan_Tschinag)). One of his great projects is the afforestation of Mongolia. A donation account in Germany is provided by [Förderverein Mongolei e.V.](http://foerderverein-mongolei.de/spenden/).
> 
> Förderverein Mongolei e.V.
> IBAN DE7261290120 0394 3660 00
> BIC GENODES1NUE
>Volksbank Kirchheim-Nürtingen
> 
> I personally know some of the people behind this. I assure that they are trustworthy and have a great heart and soul and do a good thing.

**Comment by mviereck** [comment]
Thank you!
I've asked github today to add a sponsor account. They'll review it.

Likely that is easier than to spend to the Mongolia project directly. And to admit, I could use a bit of money for myself, too. 
:-)

**Comment by eine** [comment]
@mviereck you do deserve some money for yourself as well! Take some coffee/beer/soda or buy some hardware :wink:

**Comment by mviereck** [comment]
github has approved my account; now I am part of Github Sponsors. :-)
The button at my profile and at some projects (notable x11docker) leads to 
https://github.com/sponsors/mviereck

Thank you for the suggestion!
