### ISSUE TITLE
How to build the simplest docker image that can use gpu&gui

### ISSUE THREAD

**Issue by wnark** [mviereck/x11docker#426]
Hi, I try to use this tutorial to build my own docker image for Ubuntu & desktop
[Docker Tips - Full Ubuntu GUI in a Container Displayed on Windows (XServer)](https://www.youtube.com/watch?v=WutV6n21dys)
I use this dockerfille to build docker images
```
https://agiledevart.github.io/Dockerfile.lubuntu
docker build -t docker-lubuntu .
```
but
When I run with this image
Using the commands that the deepin system can run normally, this desktop cannot be run.

sudo x11docker --desktop --network --init=systemd  --gpu --clipboard --lang=zh_CN --share /videos   x11docker/deepin

changeto

x11docker --desktop --init=systemd docker-lubuntu

It gives an error:

![image](https://user-images.githubusercontent.com/24355466/161195332-dea2ecb2-955e-4755-b669-45b7ef7722be.png)

```
Failed to start dbus.service: Access denied
See system logs and 'systemctl status dbus.service' for details.
Failed to start lightdm.service: Access denied
See system logs and 'systemctl status lightdm.service' for details.
```

P.s.
I didn't use your deepin's dockerfile, because I have been unable to compile a usable docker image through it. When I tried to execute it with the command one by one, I couldn't understand why it did so. (Google didn't find much information)

**Comment by mviereck** [comment]
Hello,

let's have a look at your Dockerfile:
```
FROM ubuntu:latest

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y lubuntu-desktop lightdm

RUN rm /run/reboot-required*
RUN echo "/usr/sbin/lightdm" > /etc/X11/default-display-manager
RUN echo "\
[LightDM]\n\
[Seat:*]\n\
type=xremote\n\
xserver-hostname=host.docker.internal\n\
xserver-display-number=0\n\
autologin-user=root\n\
autologin-user-timeout=0\n\
autologin-session=Lubuntu\n\
" > /etc/lightdm/lightdm.conf.d/lightdm.conf

ENV DISPLAY=host.docker.internal:0.0

CMD service dbus start ; service lightdm start
```

x11docker runs container applications as an unprivileged user. 
`CMD service dbus start ; service lightdm start` would need root privileges. 
That explains the error messages that you got.

Most of the setup done in the Dockerfile is not needed, x11docker will do it for you.
(With `--init=systemd` it starts a dbus system daemon. lightdm is disabled at all, it is not needed.)

This Dockerfile should work:
```
FROM ubuntu:latest
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y lubuntu-desktop
CMD startlxde
```
Your already build image likely will run with both of:
```
x11docker --desktop docker-lubuntu startlxde
```
and
```
x11docker --desktop --init=systemd docker-lubuntu startlxde
```

-----------------------
For GPU support add option `--gpu`. The image needs `mesa-utils` to provide the free MESA graphics drivers.
```
RUN apt-get install -y mesa-utils
```
If you have a proprietary NVIDIA driver, some more setup is needed.

---------------------------------
>  I didn't use your deepin's dockerfile, because I have been unable to compile a usable docker image through it. 

Could you show me the terminal output from `docker build`?

**Comment by wnark** [comment]
Hi, I use this command:
```
FROM ubuntu:latest
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y lubuntu-desktop
CMD startlxde
```
When I use this dockerfile to compile,
![image](https://user-images.githubusercontent.com/24355466/161259550-1a3e6368-0f0e-499a-81ff-9525de35e5d3.png)
After I start using this command
`x11docker --desktop --init=systemd docker-lubuntu`
![image](https://user-images.githubusercontent.com/24355466/161260109-72f672b1-03e8-407d-9a05-fc635cf3bff1.png)
/bin/sh: 1: startlxde:not found
Maybe I have to use systemd command to start this desktop?

**Comment by mviereck** [comment]
>  /bin/sh: 1: startlxde:not found

I assumed that `startlxde` is already available in your installation.
Please try `lxsession` instead.
```
 x11docker --desktop docker-lubuntu lxsession
```
`startlxde` is an alternative and available in package `openbox-lxde-session`.

**Comment by wnark** [comment]
i used lxsession
![image](https://user-images.githubusercontent.com/24355466/161364106-19b9b9fb-397c-4490-a169-72cfd52acf1f.png)
but
![image](https://user-images.githubusercontent.com/24355466/161364116-fbba79f1-41ac-45e5-8a91-b789101be147.png)

when i use 
```
FROM ubuntu:latest
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y openbox-lxde-session
```

and run

`x11docker --desktop docker-lubuntu startlxde`

**Comment by wnark** [comment]
Thank you, I probably understand that docker does not need systemd/systemctl to manage software startup.
Thank you for your help, I will try to make a dockerfile of a complete Ubuntu system by referring to your dockerfile through the existing iso.

**Comment by mviereck** [comment]
Great that it works now!

> Thank you, I probably understand that docker does not need systemd/systemctl to manage software startup.

Some desktop environments need `--init=systemd`, for example deepin, KDE/plasma, Gnome 3 and Cinnamon.

**Comment by wnark** [comment]
emmm, thanks for your answer. I tried not using systemctl but executing the binary separately
I also note here
When I use apt install -y openbox-lxde-session
I can find` /usr/bin/startlxde` in `/usr/bin/`
but I use `apt install -y xubuntu-desktop`
only found
```
root@ubuntu:/# find /usr/bin/ | grep -i xubuntu
/usr/bin/xubuntu-numlockx
```
The number lock key for this desktop.
but i found
`/usr/bin/startxfce4`
and
`/usr/bin/startx`
Therefore I use
```

x11docker --desktop --init=systemd xubuntu startxfce4
```
to start xubuntu 
it work !!
but
```
x11docker --desktop --init=systemd xubuntu startx
```
show
![image](https://user-images.githubusercontent.com/24355466/161385044-d44d893b-a103-4ffa-9997-e2bd0cd0a5b5.png)
but why?

**Comment by mviereck** [comment]
`startx` tries to run an `Xorg` X server on its own. This fails in containers in general. (Sort of possible, but it is a difficult and dangerous setup.)

`startxfce4` is the right choice. It uses the X server provided by x11docker.

**Comment by wnark** [comment]
> `startx` tries to run an `Xorg` X server on its own. This fails in containers in general. (Sort of possible, but it is a difficult and dangerous setup.)
Thank you for your explanation, it has benefited me a lot.
~~I successfully run xubuntu~~

In fact, it is essentially xfce4, lol.
I will continue to explore the essence of dockerfile. I feel that I have touched a little bit of skin at the moment. Regarding complex applications, especially the interaction between docker containers, I still need to continue to learn.
Thank you again.
