### ISSUE TITLE
startx inconsistent behavior

### ISSUE THREAD

**Issue by henriquehbr** [mviereck/x11docker#429]
> **Disclaimer:** this problem is not stricly related to the use of `x11docker` itself, but it's strongly related to some topics that appear on the wiki, including the integration of X11 (with SSH forwarding) and the execution of graphical applications in Docker, once solved, it might be of help to someone else in the future who happens to have the same problem, but if you feel that this issue is off-topic and doesn't belongs here, feel free to close it

I have a SSH server that is responsible for running `dwm` binary through X forwarding, on my client computer, i have a shell script that replaces the `dwm` binary on `/usr/local/bin`, inside that script, i simply make a call to the server requesting it to run the original `dwm`:

```bash
ssh -q -tt user@172.17.0.2 dwm $@
```

With only a single `-t`, i get the following error:

```
Pseudo-terminal will not be allocated because stdin is not a terminal
```

---

On the SSH server side, i'm making use of `ForceCommand` to pass the parameters received through a `container_runner` script, it looks like this:

```bash
#!/bin/sh
/usr/local/bin/$SSH_ORIGINAL_COMMAND
```

The reason for the `ForceCommand` here is to limit the possibility of running anything else other than a set of Docker container initialization scripts (located on `/usr/local/bin`)

Here's an example of one of those scripts, the one below runs the `dwm` Docker image:

```
#!/bin/sh
docker run \
    --pull=never \
    --rm \
    -v container-scripts:/container-scripts \
    -v ssh-keys:/home/dwm/.ssh \
    -v x11-shared:/tmp/.X11-unix \
    -it \
    -e DISPLAY=:1 \
    -e XAUTHORITY=/tmp/.X11-unix/container-cookie \
    dwm \
    $@ 2>/dev/null
```

- `container-scripts` - volume containing a set of scripts that will allow running others sibling containers inside containers
- `ssh-keys` - the SSH keys in order to be able to run containers from inside other containers
- `x11-shared` - X11 shared data (X11 socket and xauth cookie)

---

My `ssh_config` looks like this:

```
StrictHostKeyChecking no
UserKnownHostsFile /dev/null
ForwardX11 yes
ForwardX11Trusted yes
PreferredAuthentications=publickey
```

Things started to get inconsistent after i disabled SSH multiplexing from my `ssh_config`, previously with the settings below, it worked fine all the time (which makes no sense, as far as i know, SSH multiplexing shouldn't interfere in that), settings below:

```
ControlPath /tmp/%r@%h:%p
ControlMaster auto
ControlPersist yes
```

What happens is that whenever i try to run `startx` passing as argument my `dwm` script that makes a request to the SSH server to run the actual `dwm`, i just get a black screen, and nothing happens, it just stays like that, example below:

```bash
startx /usr/local/bin/dwm -- :1
```

But, if i run the same command above, slightly differently, using shell command substitution alongside with the shell noop operator, it works fine (just takes a few more seconds to show `dwm` than usual, probably due to the ugly hack)

```bash
: $(startx /usr/local/bin/dwm -- :1)
```

**Comment by mviereck** [comment]
Thank you for documenting your setup!
Myself I am barely familiar with ssh.

> startx /usr/local/bin/dwm -- :1
> : $(startx /usr/local/bin/dwm -- :1)

Interesting. It might be of interest if `tty` and `echo $(tty) ` might give a different result.

**Comment by henriquehbr** [comment]
Both `tty` and `echo $(tty)` return `/dev/pts/0`

I suspect that it might have something to do with running `startx` in background (or it's client, dwm), but i'm not exactly sure how

When i re-enable SSH multiplexing (basically allow SSH to re-use the same TCP connection for multiple connections) it works without the `:`, but when i close `dwm`, X11 keeps running (i assume that because of the pointer mouse cursor, but i might be wrong)

> Also, i wanted to thank you for your quick response and this outstandingly helpful project of yours, the documentation is so complete, and cover so many relevant things related to the use of Docker and X11 where it's almost impossible to find similar information anywhere else

**Comment by mviereck** [comment]
> I suspect that it might have something to do with running startx in background (or it's client, dwm), but i'm not exactly sure how

In fact I have no idea why the two ways give different results. `$(...)` runs a subshell, not in background. But it should not make a difference.

> but when i close dwm, X11 keeps running (i assume that because of the pointer mouse cursor, but i might be wrong)

I am not sure about `startx` behaviour.
`xinit /usr/local/bin/dwm -- :1` might make a difference. xinit terminates X once the last client exits.

> Also, i wanted to thank you for your quick response and this outstandingly helpful project of yours, the documentation is so complete, and cover so many relevant things related to the use of Docker and X11 where it's almost impossible to find similar information anywhere else

Thank you very much. :-)
It was a lot of work to find all those pieces of information across the net (and to find out some more by just trying out). I wanted to collect and document them so others can use it, too.

**Comment by henriquehbr** [comment]
Using `xinit` instead (with SSH multiplexing) results in `dwm` running, but unable to fully quit the X server once it's closed, keeping only the pointer cursor after `dwm` is already closed

Disabling SSH multiplexing (while keeping the use of `xinit`, but happens with `startx` as well) results in a black screen right after running `xinit`, with no cursor at all

My suspects on SSH multiplexing being the root cause of the problem are mostly due to the fact that a single TCP connection is shared to avoid unnecessary roundtrips, possibly preventing the X server to fully quit because there's still the `ssh` process running in the background, which might be seen as a client that is still running

**Comment by mviereck** [comment]
> Using xinit instead (with SSH multiplexing) results in dwm running

Does it start without the `: $(...)` workaround?

> but unable to fully quit the X server once dwm is closed, keeping only the pointer cursor after dwm is already closed
> possibly preventing the X server to fully quit because there's still the ssh process running in the background, which might be seen as a client that is still running

If `ssh -q -tt user@172.17.0.2 dwm $@` does not terminate along with `dwm` but keeps running, than `xinit` won't terminate but wait for `ssh`.

**Comment by henriquehbr** [comment]
Sorry for the late reply, finally managed to find a solution for that, for some reason, the problem was in the fact that i was:

- Forcing TTY allocation, had to remove `-tt` flag from SSH client
- Requesting Docker to allocate a pseudo-tty and run in interactive mode, had to remove `-it` flags from Docker CLI on the SSH server side

> The points above only applies to graphical applications, like `st` and `firefox`, containers that are interactive, but not graphical (`fish` shell and `neovim`) still needs both flags above, `-tt` on the SSH client and `-t` on Docker CLI

Not sure if that makes sense, as i don't have a very deep knowledge on how TTY allocation would affect that, but that's how i got into solving the problem

**Comment by mviereck** [comment]
Thank you for reporting your solution!
In fact, tty effects are a mystery to me.
