### ISSUE TITLE
What is the purpose of the `FUNDING.yml` file?

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#431]
I noticed the following content in [FUNDING.yml](https://github.com/mviereck/x11docker/blob/master/.github/FUNDING.yml)

```yaml
github: [mviereck]
```
AFAIK, the current free version of dockerhub don't support Automated Builds of images anymore, as shown below:

![image](https://user-images.githubusercontent.com/11155854/161890555-e9b1f3ee-de29-4cb3-9a26-759ee6c16d87.png)

So, I want to know what the purpose of this setting file is.

Regards,
HZ

**Comment by hongyi-zhao** [comment]
> `FUNDING.yml` enables a sponsor button in the top line where stars and forks can be seen, too.

Do you mean the following?

![image](https://user-images.githubusercontent.com/11155854/161927294-46dab6b7-aef4-4a37-9e9b-200de48b436d.png)

**Comment by mviereck** [comment]
Yes.

**Comment by hongyi-zhao** [comment]
BTW, currently, is there a free way to automatically trigger the Docker hub image build process from GitHub commit?

**Comment by mviereck** [comment]
Not that I am aware of.
