### ISSUE TITLE
Let x11docker set the best resolution for the container.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#432]
See the following screenshot, I want to know if x11docker will pick the best resolution of the container automatically:

![image](https://user-images.githubusercontent.com/11155854/161985859-6b5d8aa8-09fe-494d-a4dd-2ab9fcd2427b.png)

Regards,
HZ

**Comment by hongyi-zhao** [comment]
Will this option set a fixed size, as shown below:
```
$ x11docker|grep -- --size
     --size=WxH        Screen size of new X server (e.g. 800x600).
```

**Comment by mviereck** [comment]
Just set one one that fits your needs.
The best size is a question of personal preference.
The Xephyr window will be resizeable, not fixed.

**Comment by tripzero** [comment]
Is it possible to use a resolution larger than the display?  For example, if I want to test a game at 4k but only have a 1080p monitor?

**Comment by mviereck** [comment]
I've answered here: https://github.com/mviereck/x11docker/issues/502
