### ISSUE TITLE
Pinyin input method doesn't work in the latest version of Deepin desktop, started by x11docker.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/x11docker#434]
I start [the docker image](https://github.com/hongyi-zhao/dockerfile/tree/master/deepin/wine) by x11docker, but find that the pinyin input methods can't be used, though they have been activated, anymore. I've tried fcitx-google pinyin and sogou pinyin.

Any hints for this problem?

Regards,
HZ

**Comment by mviereck** [comment]
I could help you better if:
 - you try with my image `x11docker/deepin` instead of yours because I won't build your very large image for testing locally.
 - you describe your setup and what you have tried
 - you document possible error messages
 - you describe how I can reproduce the issue

**Comment by hongyi-zhao** [comment]
I'll try to do it ASAP.

**Comment by mviereck** [comment]
Just an idea:
fcitx uses environment variables.
My test setups with fcitx used fcitx version 4. Some distributions has updated to fcitx5. That might make a difference. Also look at the environment variables that has to be set for fcitx. Maybe they refer to version 4.

**Comment by hongyi-zhao** [comment]
It's set from [Dockerfile](https://github.com/hongyi-zhao/dockerfile/blob/385363f2fb9e70f6006abfbf8eb525b1e3d4f4bb/deepin/wine/Dockerfile#L64
):

`ENV XMODIFIERS=@im=fcitx QT4_IM_MODULE=fcitx QT_IM_MODULE=fcitx GTK_IM_MODULE=fcitx`

How do I change and test it in the container at run time?

**Comment by mviereck** [comment]
> How do I change and test it in the container at run time?

```
     --env VAR=value   Set custom environment variable VAR=value
```

**Comment by hongyi-zhao** [comment]
Do you mean I can test with something similar to the following?

`--env XMODIFIERS="@im=fcitx QT4_IM_MODULE=fcitx5 QT_IM_MODULE=fcitx5 GTK_IM_MODULE=fcitx5"`

**Comment by hongyi-zhao** [comment]
```bash
$ x11docker --env XMODIFIERS=@im=fcitx5 --env QT4_IM_MODULE=fcitx5 --env QT_IM_MODULE=fcitx5 --env GTK_IM_MODULE=fcitx5 --xephyr --desktop --clipboard --init=systemd -- hongyizhao/deepin-wine:apricot
```
