### ISSUE TITLE
Keyboard and mouse not working on Alpine Linux host

### ISSUE THREAD

**Issue by henriquehbr** [mviereck/x11docker#438]
> Disclaimer: this problem is not stricly related to the use of `x11docker` itself, but it's strongly related to most topics that this project covers, being them the use of graphical programs inside Docker containers, once solved, it might be of help to someone else in the future who happens to have the same problem, but if you feel that this issue is off-topic and doesn't belongs here, feel free to close it

This setup might sound a bit confusing, but i'll do my best trying to explain it, my host distro is Arch, on which i'm running an Alpine Linux 3.15.4 VM, which runs Docker, inside that VM, i'm running a container that executes X11 and dwm, i'm able to run the container just fine, it executes without any problems, but once dwm is launched, i'm unable to move both my mouse and my keyboard, they simply don't work, the relevant Dockerfile can be found [here](https://github.com/henriquehbr/docker-experiment/tree/main/containers/preset/x11-workspace)

I've tested this same Dockerfile on a variety of setups (all of them bare-metal, no VM involved), including on:

- my host OS, running on a modern modern laptop (2020) -> worked
- an modern (2018-2020) laptop running the latest version of Fedora -> worked
- an really old laptop (2010-2012) running the latest version of Fedora -> didn't worked

But i couldn't try yet running Alpine Linux on bare-metal (preferably on a modern hardware), my guess is that it has something to do with the device manager, both Arch and Fedora make use of `udev` (which is tightly coupled to `systemd`), but Alpine is an exception to this rule, it uses `mdev` by default (which is bundled with `busybox`)

> I'm not sure if Alpine has SELinux (probably not), but i even tried bypassing it's restrictions as suggested [here](https://github.com/mviereck/x11docker/wiki/SELinux) on the wiki by passing the following option to `docker run`:
> ```
> --security-opt label=type:container_runtime_t
>  ```

**Comment by henriquehbr** [comment]
**Update:** i've just managed to run Alpine Linux 3.15.4 on bare metal and tried running the Dockerfile mentioned above in it, didn't worked as well, so that makes me think even more that the problem probably lies on `mdev`

**Comment by mviereck** [comment]
Thank you for the report! I'll try to reproduce in an alpine VM.

x11docker does no setup for keyboard and mouse, this is entirely done by Xorg.
Do you get a working Xorg (including mouse and keyboard) if you run e.g. `startx`?

**Comment by henriquehbr** [comment]
Installing the exact same packages of the Dockerfile on the Alpine VM, and running `startx` directly from it (instead of running from inside a Docker container) results on the same problem of being unable to move both mouse and keyboard

I'm currently investigating for possible solutions on [this](https://github.com/slashbeast/mdev-like-a-boss) repo, as pointed on it's readme:

> This repo is a stash for notes, scripts and configs for the system running with `mdev` as a `udev` replacement.

**Comment by mviereck** [comment]
This ticket looks related: https://gitlab.alpinelinux.org/alpine/aports/-/issues/5422

It suggests to disable either `dri` or `wfb` in xorg.conf.

**Comment by henriquehbr** [comment]
Unfortunately the solution above didn't worked for me, i've even tried searching for similar problems on Alpine's mailing at sourcehut, but had no luck on finding anything that could be of help

---

But, i've managed to figure it out, on Alpine hosts, in particular, a few extra steps are required to get X11 up and running

> The solution below addresses this issue for both running Xorg directly on a Alpine host, and also running Xorg inside a Docker container on a Alpine host

After closer inspection on the [alpine-conf](https://github.com/alpinelinux/alpine-conf) repo, i've managed to find this [`setup-xorg-base.in`](https://github.com/alpinelinux/alpine-conf/blob/master/setup-xorg-base.in) script, which, as it's own name implies, responsible for setting up the system for running Xorg

On it, there are 2 lines that we should focus on:

```bash
apk add xorg-server xf86-input-libinput eudev mesa "$@"

setup-devd udev
```

This means that those on the first line are the dependencies required for running Xorg, and the second one takes us to another script, more specifically, [`setup-devd.in`](https://github.com/alpinelinux/alpine-conf/blob/master/setup-devd.in), which basically allow us to choose between the following device managers:

- `mdev` - it's the default (comes with busybox)
- `mdevd` - is standalone, compatible with `mdev`, more efficient
- `udev` - is the complex, full-featured one. (from eudev, no `systemd` required)

And as we saw on the script above, the chosen one is `udev` (which unfortunately is not the most minimalistic one, but it's what works, and doesn't pulls `systemd`)

So, we just have to disable `mdev` (it comes enabled by default on Alpine) and enable `udev`, the commands required for this can be easily gathered from `setup-devd.in` script, but i'll leave a cleaner and stripped down version that worked for me here:

```bash
# stop and delete mdev service
rc-service -s mdev stop
rc-update delete mdev sysinit

# installs udev scripts and enable all it's services
apk add udev-init-scripts udev-init-scripts-openrc
rc-update add udev sysinit
rc-update add udev-trigger sysinit
rc-update add udev-settle sysinit
rc-update add udev-postmount default
rc-service udev start
```

Hope it helps someone, thanks for your time and support @mviereck, keep up the great work!

**Comment by mviereck** [comment]
Thank you for posting the details of your solution! I am pretty sure that it will help others, too.
So you were already on the right trace to suspect `mdev`.
