### ISSUE TITLE
How to reverse mouse + keyboard grab?

### ISSUE THREAD

**Issue by Midnighter** [mviereck/x11docker#44]
I tried to run an image with x11docker and a mostly grey window opens. Foolishly I tried out the ctrl + shift for mouse and keyboard grab. How can I undo that in order to close the window?

**Comment by mviereck** [comment]
Thanks for reporting!

Took me some time to find the non-obvious reason: `Xephyr` has a bug that prevents ungrabbing keyboard+mouse if a window title is set with option `-title`. 

I have removed `-title` from Xephyr command, now ungrabbing works again.

Now you can undo the grab pressing ctrl+shift again. Run `x11docker --update-master` to get the latest beta with the bugfix.

**Comment by Midnighter** [comment]
Awesome, thank you for the quick response. It works perfectly for me.
