### ISSUE TITLE
Error 146: bash: line 10386: exec: {FDstderr}: not found [OSX / Mac]

### ISSUE THREAD

**Issue by dsummersl** [mviereck/x11docker#447]
When I try to install on OSX I get this error:

146(146)

```bash
curl -fsSL https://raw.githubusercontent.com/mviereck/x11docker/master/x11docker | sudo bash -s -- --update
bash: line 10386: exec: {FDstderr}: not found
```

**Comment by mviereck** [comment]
x11docker does not support OSX, sorry.
Compare https://github.com/mviereck/x11docker#supported-systems for supported systems.
It is developed for Linux and runs with some restrictions and setup on MS Windows, too.
On OSX you could use it in a Linux VM, but not directly.
