### ISSUE TITLE
Password and shadow

### ISSUE THREAD

**Issue by marco3181** [mviereck/x11docker#449]
The password option is great but seems not to work. It seems there are some changes needed in the x11docker script. And for security reason, I think SHA512 and a random salt in the shadow would be better.
I made changes in my fork and tested on oracle linux with the cinnamon container. I can make a pull request.
Thank you for your great work.

**Comment by mviereck** [comment]
Thank you for the report and the offer of a pull request!
I can confirm that a custom password fails in x11docker/cinnamon at least with the screen locker, yet checked.
A pull request is appreciated!

**Comment by marco3181** [comment]
For the screen locker, I didn't find it yet. I don't know if it is PAM related.

**Comment by mviereck** [comment]
Thank you for the hint with `root:shadow` for `/etc/shadow` . x11docker sets the group accordingly now.
Now cinnamon screenlocker works at least if running along with `--cap-default`.
