### ISSUE TITLE
Using `npm start` in x11docker

### ISSUE THREAD

**Issue by jcalfee** [mviereck/x11docker#45]
`npm start` seems to loose its WORKDIR and think I'm in $HOME.  I see this error:

```bash
x11docker: copy of environment stored in /x11docker/environment
x11docker: running image command: /tini -- npm start

  Last lines of command stderr:
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/fakehome/jcalfee/package.json'
```
It is odd that I can go into the container and run this command without x11docker and it works better:

```bash
root@2f5168a2b14d:/esteem-surfer# npm start

> esteem-surfer@1.0.0 start /esteem-surfer
> node build/start.js
```

Is there a way I can look around?  It would be helpful to run this container in x11docker but instead of using the `npm start` entrypoint I could run `bash` in "-i" interactive mode so I can look around?

For example:
```bash
# Creates error: Error: No such container: x11docker_X404_f8243a_esteem-surfer
x11docker $XDOCK --clipboard --homedir $HOME/.x11docker/esteem-surfer\
      -- "-i --entrypoint bash"\
       esteem-surfer
```
Regardless, is there something about the x11docker environment that I can tweak to get npm start working?

This is the Dockerfile I'm working with:
```Dockerfile
FROM ubuntu:bionic

RUN apt-get update &&\
    apt-get install -y --no-install-recommends\
    ca-certificates git nodejs npm

RUN git clone https://github.com/eSteemApp/esteem-surfer &&\
  cd esteem-surfer &&\
  git checkout tags/1.0.0 &&\
  npm install --no-optional &&\
  npm install -g bower

WORKDIR /esteem-surfer
RUN mv src/config.example.js src/config.js
RUN apt-get install -y libgtk2.0-0 libx11-xcb1 libxtst6 libxss1 libgconf-2-4 libnss3 libasound2

ENTRYPOINT [ "npm", "start" ]
```

**Comment by mviereck** [comment]
> npm start seems to loose its WORKDIR and think I'm in $HOME.

As default x11docker does `cd $HOME`. 
I have made an update that regards `WORKDIR` in image.  Use latest beta version with `x11docker --update-master`. x11docker will no `cd` to `WORKDIR` if specified in image.

> Regardless, is there something about the x11docker environment that I can tweak to get npm start working?

 You can specify working directory with `--workdir /DIR`. x11docker will `cd` to it instead of `HOME`.

> Is there a way I can look around? It would be helpful to run this container in x11docker but instead of using the npm start entrypoint I could run bash in "-i" interactive mode so I can look around?

You can't directly run an interactive shell with x11docker. But you can get the container id to run `docker exec`. 
 
```
read id < <(x11docker --showid imagename sleep infinity)
docker exec -ti $id bash
```

**Comment by jcalfee** [comment]
`--update-master` fixed this issue .. thanks
