### ISSUE TITLE
updates to "HTML5 with xpra" wiki page

### ISSUE THREAD

**Issue by totaam** [mviereck/x11docker#458]
Found on this wiki page:
https://github.com/mviereck/x11docker/wiki/Container-applications-running-in-Browser-with-HTML5

> To provide containerized applications as HTML5 web applications, you need `xpra` and `websockify`.

`xpra` has not required `websockify` for years now.  
I am not aware of any distribution that ships a version of xpra so old that it would need it.

---

We moved the html5 client to github years ago and the old trac server is being archived.
So this page is now showing a dead link:
> Further infos at xpra wiki: HTML5 clients

The html5 client now lives here: https://github.com/Xpra-org/xpra-html5
And the limited html5 client documentation is here: https://github.com/Xpra-org/xpra-html5/blob/master/README.md
The much more thorough xpra documentation is now here: https://github.com/Xpra-org/xpra/tree/master/docs

Thanks!

**Comment by mviereck** [comment]
Thank you!
I have updated the wiki documentation.

>  I am not aware of any distribution that ships a version of xpra so old that it would need it.

At least a few are around, however, I won't regard them.
This page gives an impression: https://repology.org/projects/?search=xpra&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=

Or, as a badge: 
[![Packaging status](https://repology.org/badge/vertical-allrepos/xpra.svg)](https://repology.org/project/xpra/versions)
However, it takes some time until this badge is up to date to a new release on github.
