### ISSUE TITLE
Virtual Keyboard

### ISSUE THREAD

**Issue by itswag7** [mviereck/x11docker#459]
Not sure if this is the right place to ask... Looking to see if others have successfully installed a virtual on-screen keyboard (onboard) for isolated kiosk use cases?

**Comment by mviereck** [comment]
I am not exactly sure what you want to achieve.
What did you tried already, and what did work, and what did not work?

**Comment by itswag7** [comment]
I was able to sort it out with using the --xtest=yes flag on start.  Everything is working now.

**Comment by mviereck** [comment]
Thank you for reporting your solution.
