### ISSUE TITLE
no display timeout / prevent screen from turning black

### ISSUE THREAD

**Issue by rreutebuch** [mviereck/x11docker#46]
Hey
First of all i wanted to say that x11docker is absolutely great!
I am currently using x11docker to start a chromium container from a Debian host system. The Debian i am using is custom built and only has xserver-xorg-video-fbdev and xorg installed. The container i am running is started from terminal only (not booting into any desktop environment) Now i am facing the following issue: the display turns off after 5 or 10 minutes and goes completly black.
What i am currently trying to do is to move the mouse with xdotool every 240 seconds so the screen wont go black but this is not very easy (i managed to get this running with a firefox container but not with the nwjs (chrome) container i am currently using).

Is there any way or possibility to achieve that the display wont ever go black? Maybe there is a configuration for xorg or x11docker.

**Comment by mviereck** [comment]
> First of all i wanted to say that x11docker is absolutely great!

Thank you :-)

> Is there any way or possibility to achieve that the display wont ever go black? Maybe there is a configuration for xorg or x11docker.

It seems Xorg runs some sort of screensaver. I just did a test with `x11docker/lxde`. The screen turns black after some minutes. Though, the display reappeared after a mouse move here. 

It should be possible to disable the Xorg screensaver at all. May an X option will help here:
```
$ X -help 2>&1 | grep saver
-p #                   screen-saver pattern duration (minutes)
-s #                   screen-saver timeout (minutes)
v                      video blanking for screen-saver
-v                     screen-saver without video blanking
```
x11docker already sets related option `-dpms`
```
$ X -help 2>&1 | grep dpms
-dpms                  disables VESA DPMS monitor control
```

You could try to add those options in x11docker script at line 2786, e.g adding `-s 0`:
```
Xserveroptions="-nolisten tcp -dpms -s 0"
```

There exists a screensaver setting elsewhere in the system, I try to remember and look for it. If we find a solution, I'll add it to x11docker.

**Comment by mviereck** [comment]
If adding `-s 0` to X command does not help, try x11docker option:
```
--runfromhost "xset -dpms s off"
```

**Comment by mviereck** [comment]
I've made an update that adds `-s off` to X server command. It seems to work here.
Please run `x11docker --update-master` and try out if the bug is fixed.

**Comment by rreutebuch** [comment]
YOU ARE GREAT!
I did a x11docker --update, and this solved the problem. The screen timeout is gone and i havent seen a black screen in a while :)
Thank You!
