### ISSUE TITLE
Unable to launch x11docker when `--network` is specified

### ISSUE THREAD

**Issue by SimplicityGuy** [mviereck/x11docker#463]
With this commit: https://github.com/mviereck/x11docker/commit/e50feeb4c25a94e37e549dcd0c01b6b8218fa8ac, it is no longer possible to run an image with x11dock when `--network=...` is specified by the user. Please revert or rework this change.

**Comment by SimplicityGuy** [comment]
This was also missed in the release notes, requiring code inspection to find that `--hostname` was now being set.

**Comment by mviereck** [comment]
Thank you for the report!
Sorry that this caused trouble for you. This change was just intended to be a minor convenience to make it easier seeing which container belongs to which open windows. As a quite minor feature I did not mention it in the release notes.
I have removed the `--hostname` code, it should work now again.
May I ask how exactly this caused trouble with `--network`?

**Comment by SimplicityGuy** [comment]
Thanks for the fix! Using `--hostname` and `--network` is incompatible per Docker, when using `--network=container:vpn`. I get this error:
```
conflicting options: hostname and the network mode
```

See the [Docker run reference](https://docs.docker.com/engine/reference/run/#network-settings):
> Network: container
> With the network set to container a container will share the network stack of another container. The other container’s name must be provided in the format of --network container:<name|id>. Note that --add-host --hostname --dns --dns search --dns-option and --mac-address are invalid in container netmode, and --publish --publish-all --expose are also invalid in container netmode.

**Comment by SimplicityGuy** [comment]
So, given that, perhaps the fix here could be to use `--hostname` when `--network` is not a `container`?

**Comment by mviereck** [comment]
> See the [Docker run reference](https://docs.docker.com/engine/reference/run/#network-settings):

Oh, I should have looked there before. I did not imagine that this could have such a major impact.

> So, given that, perhaps the fix here could be to use --hostname when --network is not a container?

That's a good idea! However, I think I won't mess with `--hostname` anymore, since the use case was quite minor.

**Comment by SimplicityGuy** [comment]
No worries, mate. Bugs happen. Appreciate the quick turnaround on this. The docker commands are all over the place. Mutually exclusive flags galore. Wait until you try using `--filter` on docker volumes... oh boy.
