### ISSUE TITLE
[bug] /x11docker/cmdrc: 62: /usr/bin/entrypoint: Permission denied

### ISSUE THREAD

**Issue by CicadaSeventeen** [mviereck/x11docker#465]
When I try to use x11docker on my distro, here shows 
```
/x11docker/cmdrc: 92: /usr/bin/entrypoint: Permission denied

```
But actually I have no `/usr/bin/entrypoint` at all.

Besides, i use `podman` instead of `docker`, and I run 'x11docker --backend==podman --hostdisplay xxxx'

**Comment by mviereck** [comment]
Thank you for the report!

Maybe you have a misconfigured image with a wrong `ENTRYPOINT` rule.
You can check it with 
```
podman inspect -f '{{.Config.Entrypoint}}' <imagename>
```

> But actually I have no /usr/bin/entrypoint at all.

Maybe this file exists in the image. Try:
```
podman run --rm <imagename> cat /usr/bin/entrypoint
podman run --rm <imagename> ls -l /usr/bin/entrypoint
```

Does the error happen with other images, too?
Please try e.g. with slim image `x11docker/fvwm`:
```
podman pull x11docker/fvwm
x11docker --backend=podman --hostdisplay x11docker/fvwm xterm
```

If this fails, too, please provide me the file `~/.cache/x11docker/x11docker.log` that is created when x11docker terminates after the failure.

**Comment by mviereck** [comment]
Could you solve the issue?

**Comment by CicadaSeventeen** [comment]
> Could you solve the issue?

I am busying on something else and my laptop can not work now. so I have to check it several days later.

**Comment by mviereck** [comment]
> I am busying on something else and my laptop can not work now. so I have to check it several days later.

Ok, I'll leave the ticket open.

**Comment by CicadaSeventeen** [comment]
Sorry for late. I said my laptop can not work. It was not a lie but not all truth. Actually I suffer from depression these days so I just disappear for two months. Now I am back since I feel sort of better.
I do not see this problem anymore. I cannot tell it came from bad image or my `podman` had some bugs , because the system I had problem on is now broken.
Thanks anyway. If I meet this problem in future, I will report again.

**Comment by mviereck** [comment]
Thank you for your feedback!
I had some time years ago where I suffered from depression, too. Great that you make your way through it. It's a difficult task, and it needs courage to speak of it to others who mostly don't understand it.
In my case the depression was proceeded by a psychosis. Through years I learn to not drift into the one way or the other, and to watch myself carefully.
