### ISSUE TITLE
Does x11docker depends on xorg?

### ISSUE THREAD

**Issue by CicadaSeventeen** [mviereck/x11docker#471]
`Xorg` is absent when you list your dependencies, so I do not include it into my .deb depends. But it sounds strange that a gui app can run without `Xorg`. This may cause problem if someone install it in the tty-only system.
Please confirm for me.

**Comment by mviereck** [comment]
Some points to consider:
 - Even regular GUI applications like firefox do not depend on Xorg.
 - x11docker provides Xorg and other X servers in image `x11docker/xserver`.
 - Access with `ssh -X` would need no X server at all on the machine where x11docker runs.
 - Xorg can be replaced by Wayland setups.

So I would not declare a dependeny on Xorg.
At most I would set X server `nxagent` to 'recommends'. With rather low dependencies it provides usability on most systems. (It is even useful in `ssh -X` setups.)

**Comment by CicadaSeventeen** [comment]
Thanks
