### ISSUE TITLE
This might be a little odd for you but i am having difficulty understanding how to use x11docker.

### ISSUE THREAD

**Issue by RajaMuneerBaigal** [mviereck/x11docker#472]
I am using an alpine base docker image and have installed sway on it somehow. Though it shows errors but I am able to launch it. I want to know if it is possible to use x11docker with the image I am working on? I want to set up x11docker for vnc access to sway on alpine linux image. Not sure if its possible or not? Any help would be appreciated

**Comment by mviereck** [comment]
In general this should be possible. I once had sway running in an image, too.
How do you run your sway image without x11docker yet?

I am not sure about your VNC question. x11docker itself does not use VNC. However, it is possible to access an x11docker container with VNC.
