### ISSUE TITLE
consider `getent` alternative, doesn't exist on busybox (eg. BalenaOS): Could not find user in /etc/passwd

### ISSUE THREAD

**Issue by jayv** [mviereck/x11docker#477]
It breaks the script early eg: `x11docker ERROR: Could not find user '...' in /etc/passwd.`

**Comment by mviereck** [comment]
Sorry for my late response.
I have replaced `getent` with a custom function using `grep`. That should fix this.
However, it is likely that some other commands might miss in busybox, too. Would you mind to update x11docker to current master version and try out?
