### ISSUE TITLE
Show stdout and stderr of --runasroot

### ISSUE THREAD

**Issue by arteniioleg** [mviereck/x11docker#48]
I made my image production ready, thus with minimal packages. I moved all GUI related packes to x11docker IDE script:

```bash
#!/bin/bash

[ -n "$(which x11docker)" ] \
    || { echo "x11docker is required"; exit 1; }

CMD=${@}
[ -n "${CMD}" ] \
    || { echo "Command is required"; exit 1; }

SCRIPT_DIR=$(dirname $(readlink -f "$0"))
PROJECT_DIR=$(dirname ${SCRIPT_DIR})
IMAGE=defacto_php
NETWORK=defacto_default

[ -n "$(docker images -q --filter=reference="${IMAGE}")" ] \
    || docker build -t ${IMAGE} ${SCRIPT_DIR}

[ -n "$(docker network ls -q --filter name=${NETWORK})" ] \
    || docker-compose -f ${SCRIPT_DIR}/docker-compose.yml up -d

x11docker \
    --hostdisplay \
    --homedir ${HOME} \
    --clipboard \
    --stdout --stderr \
    --cap-default \
    --no-init \
    --workdir ${PROJECT_DIR} \
    --runasroot "apt-get update && apt-get install -y \
        libgtk2.0-0 libcanberra-gtk-module libxext-dev libxrender-dev \
        libxtst-dev libxslt-dev dmz-cursor-theme \
        git wget htop zip unzip nano" \
    -- "--cap-add=SYS_PTRACE --publish=80:8080 --network ${NETWORK}" \
    ${IMAGE} ${CMD}
```

The startup takes a while, so some logs showing what's happening will be useful.

**Comment by mviereck** [comment]
> I made my image production ready

Congratulation :-)

If you run with option `--verbose` you can see the output of `--runasroot`. Though, along with all other noisy verbose output. `--verbose` itself shows all its output on stderr.

Another possibility is to append the output to `/x11docker/stdout` and `/x11docker/stderr`:
```
--runasroot "apt-get update >>/x11docker/stdout 2>>/x11docker/stderr" \
--runasroot "apt-get install -y \
        libgtk2.0-0 libcanberra-gtk-module libxext-dev libxrender-dev \
        libxtst-dev libxslt-dev dmz-cursor-theme \
        git wget htop zip unzip nano \
        >>/x11docker/stdout 2>>/x11docker/stderr" \
```

Some thoughts:
 - Do you think it is wise to do the `apt-get` stuff during x11docker startup? I would say, make the packages part of the image to have a faster startup. 
 - Without `--runasroot apt-get [...]` you are also probably able to drop `--cap-default`, thus improving container security.
 - You should not need `--no-init`. If you have `/tini` in your `ENTRYPOINT`, x11docker will prefer it over possible `tini` or `docker-init` from host.

**Comment by arteniioleg** [comment]
Thanks!
