### ISSUE TITLE
OpenGL in docker (32bit container, 64bit host)

### ISSUE THREAD

**Issue by sebek72** [mviereck/x11docker#481]
Hi. Will x11docker allow to run a 32bit app (centos6 docker image) and have it OpenGL enabled (official Nvidia driver) on a 64bit host?
I know the host and container Nvidia driver versions need to match and this is a problem. 

My hosts are RH8 or CentOS8 (64bit) and my app was compiled to run in a 32bit centos6 container.

The problem is that the newer Cards need to use newer drivers, but Nvidia stopped providing 32bit version long time ago.

Any suggestions how to make this to work? My app relies an a OpenGL support.

Thanks

**Comment by mviereck** [comment]
I highly doubt that this will work, sorry.
Beside the driver version itself there is the difference between 32 and 64 bit. With some setup it is possible to run 32bit containers on a 64bit host: https://github.com/mviereck/x11docker/wiki/Multiarch-setups-with-QEMU
However, this involves a virtual kernel that cannot access the GPU afaik.

If you are fine with software rendered OpenGL, your application likely runs, for example with Xephyr (option `--xephyr`). But using the GPU will likely fail.

**Comment by sebek72** [comment]
Thanks. The 32bit container already runs fine on a 64bit host, the issue is only the OpenGL support within the container and the matching Nvidia driver. I can think of one other option...try to make my 32bit app to run in a 64bit container (in this case centos6).
https://capstonec.com/2019/05/24/32bit-apps-in-a-64bit-docker-container/

**Comment by mviereck** [comment]
Right, I did not thought of multiarch setup. That might work and is worth a try. I am not sure if a 32bit application can make use of the 64 bit driver, but just try out.

**Comment by sebek72** [comment]
Can I somehow force it to use the mesa driver instead of Nvidia for openGL?

**Comment by mviereck** [comment]
You would need the MESA driver/nouveau on host, too. Chances are better that the 32/64bit difference will do no harm. At least you can install both versions of MESA on host and in container. Maybe they can communicate with each other.
Or just use OpenGL software rendering like provided by Xephyr.

**Comment by sebek72** [comment]
Thanks, let's see where this takes me ;)
