### ISSUE TITLE
Wrong deb package for cvt command in the wiki

### ISSUE THREAD

**Issue by Fushko** [mviereck/x11docker#491]
Hi, thanks for your work.

The deb package in the [wiki](https://github.com/mviereck/x11docker/wiki/Dependencies#table-of-all-packages) for cvt is `xserver-xorg-core`, but the correct one is actually `xcvt`.

I already had  `xserver-xorg-core` installed, but the warning about cvt missing was still there.
Running `sudo apt install xcvt` fixed it. Distro is Pop 22.04.

**Comment by mviereck** [comment]
Thank you for the hint!
It seems Debian and Ubuntu have different packages for `xcvt`. I'll add this to the wiki some day.

**Comment by mviereck** [comment]
I've added this as another possible package in the wiki.
