### ISSUE TITLE
jq is generating wrong cmdrc

### ISSUE THREAD

**Issue by Greek64** [mviereck/x11docker#493]
I have a image that is generated with a Dockerfile containing
```
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
CMD ["bash"]
```

When using x11docker (`x11docker -it -- test_image bash`) with normal python (x11docker <= v7.4.2 OR `jq` uninstalled) the generated `cmdrc` contains
```
89  debugnote "cmdrc: Running container command:
90    '/bin/bash' '/entrypoint.sh'   'bash'"
91
92  '/bin/bash' '/entrypoint.sh'   'bash'
93
94  storeinfo cmdexitcode=$?
```
which works as expected.

When using x11docker (`x11docker -it -- test_image bash`) with `jq` (x11docker >= v7.5.0 with `jq` installed) the generated `cmdrc` contains
```
89  debugnote "cmdrc: Running container command:
90    /bin/bash"
91  "/entrypoint.sh  'bash'"
92
93  /bin/bash"
94  "/entrypoint.sh  'bash'
95
96  storeinfo cmdexitcode=$?
```
which fails with 
```
/x11docker/cmdrc: 91: /entrypoint.sh  'bash': not found
/x11docker/cmdrc: 94: /bin/bash
/entrypoint.sh: not found
```

**Comment by mackworthy** [comment]
I think this is related to #485

**Comment by mviereck** [comment]
Thank you for the report!
I'll check this.
