### ISSUE TITLE
parse_inspect(): Error while parsing json for ...

### ISSUE THREAD

**Issue by theottm** [mviereck/x11docker#504]
Hi nice tool you made:) 

I'm trying to use it and eventually package it for guix. I'm trying to get the list of dependencies right.

I get an error that I don't understand
```quote
./x11docker: line 1101: -: command not found
x11docker WARNING: parse_inspect(): Error while parsing json for
  State Pid    (Line 8313)
```
and the same error for `  Architecture     (Line 5613)` `Config Cmd    (Line 5617)` and some others.

Can this be due to some missing dependency? I looks like a bash syntax problem, which would make sense AFAIU.

**Comment by MolassesLover** [comment]
Getting the same error on NixOS, unfortunately.
```
/nix/store/apsn9crvis9crw3gy8k5zr20j2z0zpaj-x11docker-7.6.0/bin/.x11docker-wrapped: line 1099: -: command not found
x11docker WARNING: parse_inspect(): Error while parsing json for
  State Pid    (Line 8311)
```
