### ISSUE TITLE
Question: Using Viewer From Different Host (Client/Viewer)

### ISSUE THREAD

**Issue by alidehghan** [mviereck/x11docker#524]
First of all, I should thank you all people creating such incredible thing.

I looked almost all the web and tried different solutions (spice, xspice, vnc, etc.) to find a solution to isolate browsers within docker, What I want is to run browser (or any gui application) inside docker container, but client view it through remote viewer clients. All samples in your wikis opens client in host, but I want to publish a port and send the stream outside the host (for example internet). Is that possible?

**Comment by mviereck** [comment]
Essentially you already found the answer yourself: run a VNC viewer in the container.
