### ISSUE TITLE
/etc/shadow: Permission denied

### ISSUE THREAD

**Issue by jcalfee** [mviereck/x11docker#53]
```bash
$ x11docker --clipboard --home --sharedir /home/james/Downloads keybase
```

This creates a permission denied error:
```bash
x11docker: Created container.rootsetup.sh:
  61	echo "james:sac19FwGGTx/A:17293:0:99999:7:::" >> /etc/shadow
```

```bash
x11docker ERROR: Container startup seems to have failed! 

  Last lines of container.log:
mkdir: created directory '/tmp/.font-unix'
lrwxrwxrwx 1 root root 5 Jun 30 01:05 /tmp/.X11-unix/X500 -> /X500
sed: can't read /etc/shadow: Permission denied
/x11docker/container.rootsetup.sh: line 57: /etc/shadow: Permission denied
sed: can't read /etc/shadow: Permission denied
/x11docker/container.rootsetup.sh: line 61: /etc/shadow: Permission denied
rm: cannot remove '/etc/sudoers.d': No such file or directory
rm: cannot remove '/etc/sudoers': No such file or directory
rm: cannot remove '/etc/pam.d/sudo': No such file or directory
mkdir: created directory '/tmp/XDG_RUNTIME_DIR'

  Last lines of command stderr:
[FATAL tini (71)] exec -v failed: No such file or directory
  
  Type 'x11docker --help' for usage information
  For debugging, run x11docker in terminal and/or enable option '--verbose'
  or look afterwards at logfile /home/james/.cache/x11docker/x11docker.log
  Please report issues at https://github.com/mviereck/x11docker
```

Environment
```Docker
FROM fedora
RUN yum install -y gtk2 libX11-devel libXtst GConf2 alsa-lib https://prerelease.keybase.io/keybase_amd64.rpm
COPY keybase /
CMD run_keybase
```
```bash
$ docker build -t keybase .
$ x11docker --clipboard --home --sharedir /home/james/Downloads keybase
```

**Comment by mviereck** [comment]
The important message here is `[FATAL tini (71)] exec -v failed: No such file or directory`.
The finally executed command in`CMD run_keybase` is somehow wrong.
Can you show me the content of `run_keybase` and the output of
```
x11docker --debug --clipboard --home --sharedir /home/james/Downloads keybase
```

**Comment by jcalfee** [comment]
Yes but I did that on purpose.. I had to use a wrapper script to get run_keybase to work.  I tough I could simplify it for you because of the error that happened earlier.  Here is the full script, it includes itself in the docker build:

> ./keybase

```bash
set -o errexit

function build() {
  dir=$(dirname "$0")
  base=$(basename "$0")
  docker build -t keybase -f - "$dir" << Dockerfile
FROM fedora
RUN yum install -y gtk2 libX11-devel libXtst GConf2 alsa-lib https://prerelease.keybase.io/keybase_amd64.rpm
COPY keybase /
CMD sh /keybase start
Dockerfile
}

function x11() {
  build
  # SYS_ADMIN added for fuse file mounting (todo --security-opt apparmor:unconfined)
  # todo: --pulseaudio or --alsa
  #-- "--device /dev/fuse --cap-add=SYS_ADMIN"\
  set -o xtrace
  x11docker\
    --hostdisplay --clipboard --home --sharedir $HOME/Downloads --pulseaudio\
    keybase "$@"
}

function start() {
  echo Starting Keybase..
  run_keybase "$@"
  #sleep 5
  #tail -f ~/.cache/keybase/*.log &
  while pgrep Keybase > /dev/null; do sleep 1; done
}

"${@-x11}"
```

When I run this on another computer it works .. Maybe it is coincidence but the /etc/shadow error only appears on the broken setup.  The working computer is docker v17 and the non-working is docker v18.

broken: https://pastebin.com/r7KhzbTy
working: https://pastebin.com/rj974qAm

**Comment by mviereck** [comment]
There may be different behaviour due to different versions of x11docker, the first one shows 4.3.0, the second one 4.3.5. The second log is somehow incomplete, no output of container.log at all, not sure why. 

The error message from your first post does not appear in the first (complete) log: `[FATAL tini (71)] exec -v failed: No such file or directory.`

It shows: `x11docker: Running image command: /x11docker/tini -- sh /keybase start`
It seems to me that function start() is executed, some keybase output appears in the log, but the loop does not continue. Maybe `pgrep Keybase` failes.

--------
> I had to use a wrapper script to get run_keybase to work.

Maybe run_keybase forkes itself into the background like a daemon, and the container stops as it has no foreground process anymore.

-----------
Don't worry about this part, everything works as intended:
```
 Last lines of container.log:
mkdir: created directory '/tmp/.font-unix'
lrwxrwxrwx 1 root root 5 Jun 30 01:05 /tmp/.X11-unix/X500 -> /X500
sed: can't read /etc/shadow: Permission denied
/x11docker/container.rootsetup.sh: line 57: /etc/shadow: Permission denied
sed: can't read /etc/shadow: Permission denied
/x11docker/container.rootsetup.sh: line 61: /etc/shadow: Permission denied
rm: cannot remove '/etc/sudoers.d': No such file or directory
rm: cannot remove '/etc/sudoers': No such file or directory
rm: cannot remove '/etc/pam.d/sudo': No such file or directory
mkdir: created directory '/tmp/XDG_RUNTIME_DIR'
```

**Comment by jcalfee** [comment]
>There may be different behavior due to different versions of x11docker, the first one shows 4.3.0, the second one 4.3.5.

I tested keybase on the working computer under x11docker 4.3.6-beta.  It starts up correctly (is functional, aka works).

>The second log is somehow incomplete, no output of container.log at all, not sure why.

The container does not shut down properly (known bug in my script) .. needs ctrl+c

Keybase is a bit involved, it has some unique features .. I did transfer over the working keybase docker image and the UI still does not appear, also I changed the while loop to `while true > /dev/null; do sleep 1; done` .. [paste](https://pastebin.com/zqYyH7yw). 

I tried a reboot too, not sure what is going on..  Very strange that the working version does not show the ascii squirrel but the broken version does recalling that the keybase the same version / docker image on both machines..

**Comment by jcalfee** [comment]
>Does the image contain any other X application like e.g. xterm or xkbwatch you could try to run?

xterm runs fine


I'm using `docker exec -ti 7387b26352b5 bash` to go into the running x11docker container and looking at that keybase startup script.  It is very involved, I'll come back when I know more and update this ticket.  Ok to close..  Thank you for all your help..

**Comment by jcalfee** [comment]
It was a missing library (gtk3), the install URL for keybase does not have a version .. thanks again
