### ISSUE TITLE
Add option --ssh

### ISSUE THREAD

**Issue by sandrokeil** [mviereck/x11docker#59]
Make it sense to add the option `--ssh` as a shortcut for `--volume=$(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) --env=SSH_AUTH_SOCK=$SSH_AUTH_SOCK`? I'm not sure if it works on every unix system but it works on Ubuntu and Arch Linux by default. I use this for the git container or development IDE PHPStorm.

I can try to bring a PR if you will accept it.

**Comment by mviereck** [comment]
I am less experienced with ssh. What is the purpose of this setup? Does it allow you to use ssh server from host?

Instead of `--ssh` I'd rather call it `--sharessh` for consistence of options that share something from host.

> I can try to bring a PR if you will accept it.

I would appreciate it! (After I've understood the purpose ...)

**Comment by sandrokeil** [comment]
Not the ssh server, it's the ssh agent.

> $SSH_AUTH_SOCK contains the path of the unix file socket that the agent uses for communication with other processes. This is essential for ssh-add.

This is needed if you want to checkout private repositories or your repository via ssh to have write access. You don't have to share the ssh key files within the container.

**Comment by mviereck** [comment]
I am not sure whether this option is rather special or whether several users would appreciate it. But I like to implement it.

If you want to create a PR, digging into the code and to appear in the contributors list, you are welcome. 
If it costs too much time for you, I can implement it myself, it would be fast as I already know where to place the code snippets.
Though, I am always happy if someone has a deeper look at the code.
