### ISSUE TITLE
Is there any x11docker images based on ubuntu?

### ISSUE THREAD

**Issue by wanhongbo** [mviereck/x11docker#64]

**Comment by mviereck** [comment]
There is no ubuntu based image from x11docker. Most x11docker images on docker hub are based on debian.
Though, you can create Ubuntu based images yourself. Example:
```
FROM ubuntu:18.04
RUN apt-get update && apt-get install -y --no-install-recommends xterm
CMD xterm
```
You can also replace `FROM debian:stretch` in x11docker examples with `FROM ubuntu:18.04`. Most debian based images will work on an ubuntu base, too.
