### ISSUE TITLE
sharessh not working anymore

### ISSUE THREAD

**Issue by sandrokeil** [mviereck/x11docker#72]
I've got the error with current master (`--pulseaudio=tcp`). 
```
export: `/run/user/1000/keyring/ssh': not a valid identifier
```
The Docker run command contains `--env /run/user/1000/keyring/ssh`. The `SSH_AUTH_SOCK` name is missing here.

Is it right, that [this was removed](https://github.com/mviereck/x11docker/commit/e50eed004fce1261ba70a250081b717dfc6fb2d5#diff-308fa5eac58a6b2ba23e0fbc6e033041L4568) and [this changed](https://github.com/mviereck/x11docker/commit/e50eed004fce1261ba70a250081b717dfc6fb2d5#diff-308fa5eac58a6b2ba23e0fbc6e033041R1713)?

**Comment by mviereck** [comment]
ups, sorry, the bug is here:
```
Customenvironment="$(escapestring "${SSH_AUTH_SOCK:-}")
$Customenvironment"
```
should be:
```
Customenvironment="SSH_AUTH_SOCK=$(escapestring "${SSH_AUTH_SOCK:-}")
$Customenvironment"
```

I found that I could spare additional variable `$Sharessh` and the check for it while creating docker command with just adding it to the list of environment variables, similar to adding the shared socket to the list of shared files.

Will upload the fix it after some pulseaudio cleanup I am doing yet.

**Comment by sandrokeil** [comment]
If you set in the startscript for docker run the line `set -e` it aborts if an error occurs. This would avoid silent errors. Not sure if it is useful here.

**Comment by mviereck** [comment]
ok, it is fixed now.

> Or simply use the shebang line #! /bin/bash -e.

With option `--debug` x11docker catches errors and undefined variables with:
```
set -Eu -o pipefail
trap 'traperror $? $LINENO $BASH_LINENO "$BASH_COMMAND" $(printf "::%s" ${FUNCNAME[@]})'  ERR
```
