### ISSUE TITLE
Running with --home option, container fails to start when a version tag is specified

### ISSUE THREAD

**Issue by johncm** [mviereck/x11docker#8]
Just an observation, not critical:
Script leaves the ":" in the container name which makes the resulting command fail on -v option.

Looks like you are already converting the "/" to "-" in the container name for the home directory name, maybe the ":" can be converted also.

**Comment by mviereck** [comment]
Thanks! I will fix it soon.

**Comment by mviereck** [comment]
Bugfix in V2.2.0, ":" now gets replaced with "-"
