### ISSUE TITLE
x11docker doesn't work when forwarding X

### ISSUE THREAD

**Issue by Glaeqen** [mviereck/x11docker#81]
Those are the logs, I picked example from wiki. Running x11docker [locally](https://github.com/mviereck/x11docker/files/2492503/no_x_forward_trial.log) works flawlessly but when [ssh with X forwarding](https://github.com/mviereck/x11docker/files/2492504/x_forward_trial.log) it fails.  Links are log files I've captured.

Command used:
```ssh -X localhost -- /home/glaeqen/Documents/x11docker/x11docker --verbose x11docker/lxde lxterminal```

Is my configuration flawed or am I doing something wrong? Thanks for help.

**Comment by mviereck** [comment]
Thanks for your bug report!

I can confirm and reproduce it here. It appears with option `--hostdisplay` that is used if no additional X server is available.

Workaround: If you install an additional X server like `xpra`, `nxagent` or `Xephyr`, your command above will work.

I did some first trials to fix the bug with `--hostdisplay`, but failed so far. I have to investigate that further. I'll report here when it is fixed.

**Comment by Glaeqen** [comment]
>  I have to investigate that further. I'll report here when it is fixed.
I appreciate fast reaction. 
However, it surprises me that such easy to reproduce bug wasn't found earlier. 
I keep thumbs up for resolving this issue. That mad scripting work you made is insane, good job.

**Comment by mviereck** [comment]
The bug is fixed in master branch. It seems that `ssh -X` does not set environment variable `XAUTHORITY` but uses the Xauthority file nonetheless.  Without the cookie in Xauthority the authentication failed.
Please check if it works for you now.

>  However, it surprises me that such easy to reproduce bug wasn't found earlier.

In previous tests this setup worked. I am not sure what may have changed; the bug may be new. 
However, many people don't write bug reports at all; but I need them to fix bugs I don't detect myself. Meanwhile x11docker has so much options that I cannot check all possible setup combinations. So, thanks again for reporting!

> That mad scripting work you made is insane, good job.

thanks :-)

**Comment by mviereck** [comment]
I ran some tests with different `ssh -X` setups and found an odd issue with `Xephyr` (needed in x11docker for desktop option `--xephyr`):

This succeeds: `ssh -X localhost -- Xephyr :15`

But if I try a connection to a remote server different from localhost, Xephyr does not start up:
 `ssh -X remoteserver -- Xephyr :15`

Could you check this, too? Maybe it is a local issue only affecting my system,  or it may be a general issue with Xephyr.

**Comment by Glaeqen** [comment]
> The bug is fixed in master branch. It seems that `ssh -X` does not set environment variable `XAUTHORITY` but uses the Xauthority file nonetheless. Without the cookie in Xauthority the authentication failed.
> Please check if it works for you now.

It works! Great job, thank you.

When it comes to Xephyr, X forwarding from localhost: 
![localhost](https://user-images.githubusercontent.com/20447270/47298350-d91dc980-d617-11e8-8ab4-017f87cb45fe.png)
works as well as from different machine:
![different machine](https://user-images.githubusercontent.com/20447270/47298373-e6d34f00-d617-11e8-9a0a-09ac3853cdc6.png)
I guess it might be environmental issue in your case. Thank you once again.

**Comment by mviereck** [comment]
> It works! Great job, thank you.

Glad to hear that. :-)
I've published a new release v5.3.1 with this bugfix.

 > When it comes to Xephyr, X forwarding from localhost works as well as from different machine

Thank you for testing that! Good to know it is not a general issue. I'll investigate further.
