### ISSUE TITLE
How can I run a Windows exe file?

### ISSUE THREAD

**Issue by MontoyaAndres** [mviereck/x11docker#88]
Hi

I have a file on home/andres/Download/file.exe

I want to run it with x11docker but I dont know how... Someone can help me? Thanks!

**Comment by mviereck** [comment]
I assume `file.exe` is a Windows application. Am I right?

You can use image `x11docker/lxde-wine` to run Windows applications with wine in docker.
You'll also need `Xephyr`.
Run:
`x11docker --desktop --home  x11docker/lxde-wine`
Copy `file.exe` to `/home/andres/x11docker/x11docker-lxde-wine/Desktop`.
It will appear on the lxde-wine Desktop. Try to run it there with wine.

**Comment by MontoyaAndres** [comment]
Thanks!

**Comment by Lecrapouille** [comment]
@mviereck Hi ! I know this ticket is closed I'm trying to launch an windows exe from my Linux home directory. I'm sorry I'm may be a little noob but I did not understand your explanations.

1. I'm able to start `x11docker/lxde-wine`
2. When you said "You'll also need Xephyr" shall I add the `--xephyr` option ? It's fine without for me.
3. When you said "Copy file.exe to /home/andres/x11docker/x11docker-lxde-wine/Desktop" which `x11docker` directory is it ? Is this the one I git pushed ? but 1/ this directory is a temporary (your doc said I can removed it) and 2/ there is no sub-directories `x11docker-lxde-wine/Desktop` inside. So I created them and placed the exe file.
4. I do not see my .exe file in the desktop. I tried with WineFile or File Explorer without success. They only see .desktop files.
4. I have an very old Borland Delphi 5 that I want to install, do you think I can install it ?

**Comment by mviereck** [comment]
> x11docker can run games over wine? If I pass the GTA San Andreas, it'll run?

Just try out. [WineHQ: GTA San Andreas](https://appdb.winehq.org/objectManager.php?sClass=application&iId=2599) says it would run with wine. So it will probably run in `x11docker/lxde-wine`, too.

**Comment by Lecrapouille** [comment]
Ok that worked :) I used --home bu I did not understood that .local/share/x11docker was created

**Comment by mviereck** [comment]
> Ok that worked :)

Good! :)

>  I used --home bu I did not understood that .local/share/x11docker was created

`~/.local/share/x11docker` is not that obvious documented. x11docker should create a softlink to `~/x11docker`. Is that missing on your system? Maybe the softlink creation somehow failed.

**Comment by Lecrapouille** [comment]
Yep this should be documented. I have not the softlink but that's fine since I have the .local directory.

**Comment by mviereck** [comment]
@Lecrapouille Thank you for the feedback!
 `~/.local/share/x11docker` is documented now in `README.md` and in the output of `x11docker --help`.
