### ISSUE TITLE
Invalid argument for -config when using --xpra or --xorg

### ISSUE THREAD

**Issue by mrmakeit** [mviereck/x11docker#9]
Command run: x11docker --xpra --sudo --verbose -- ' ' firefox /usr/bin/firefox 
Docker file: [firefox.txt](https://github.com/mviereck/x11docker/files/945228/firefox.txt)
x11docker log file: [x11docker.txt](https://github.com/mviereck/x11docker/files/945226/x11docker.txt)

I've tried multiple config options, but if I use --xpra or --xorg, I get this error.  Seems Xorg is not happy with -config being an absolute location.

**Comment by mviereck** [comment]
Thanks for your feedback!
Which distribution do you use? Which Xorg version (`Xorg -version`)?
Here, on debian 9, it works fine, although `Xorg -help` tells me only a relative config path would be allowed. (More about allowed pathes on [x.org](https://www.x.org/pub/X11R6.7.0/doc/xorg.conf.5.html ) )
```
-config file           specify a configuration file, relative to the
                       xorg.conf search path, only root can use absolute
-configdir dir         specify a configuration directory, relative to the
                       xorg.conf.d search path, only root can use absolute
```
Does xpra work on its own?
```
xpra start :10
xpra attach :10 &
DISPLAY=:10 xterm
```
And xpra started this way?
```
xpra start :20 --xvfb='Xorg -noreset -nolisten tcp +extension GLX +extension RANDR +extension RENDER -config /etc/xpra/xorg.conf' --no-daemon &
xpra attach :20 &
DISPLAY=:20 xterm
```
I'm not sure how to solve this, as I want to avoid creating files in `/etc/X11`.

**Comment by mviereck** [comment]
Option `--xorg` can not be affected by this, it does not use switch `-config`. Only `--xpra` and `--xdummy` need to specify a config file for X to use Xdummy video driver.
Depending on your setup and system, `--xorg` may only run from console. 
If you have an error with `--xorg`, please show me the logfile for this, too.

**Comment by mrmakeit** [comment]
My current OS is Ubuntu 16.04, which seems to be the problem.  16.04 handles Xorg in a very strange and roundabout way, which forces all Xorg instances to be setuid.  This in-turn precludes the use of either --config or --logfile.
I'm going to close this, as it seems that these issues affect xpra, not x11docker.

**Comment by mrmakeit** [comment]
https://xpra.org/trac/ticket/1220 is the upstream issue.

**Comment by mviereck** [comment]
Thanks!
I made a little workaround: If you install `xvfb`, x11docker will use it instead of Xdummy. That should work on Ubuntu 16.04, too.

For use of option `--xorg` on Ubuntu 16.04, you need package `xserver-xorg-legacy` and edit file `/etc/X11/Xwrapper.conf`.
Replace line:
`allowed_users=console`
with lines
`allowed_users=anybody`
`needs_root_rights=yes`

**Comment by mrmakeit** [comment]
Unfortunately xvfb still triggers the -config issue in 16.04.  Seems `xvfb` still runs `Xorg` at some point with -config.

**Comment by mviereck** [comment]
Do you use the latest version of x11docker? Xvfb is independent from Xorg and is called without any -config option. Can you check your x11docker version (`x11docker --version`). The current one is 3.1.8.
The logfile should show "Xvfb" in "Created X server command".
