### ISSUE TITLE
Permissions problem when executing eclipse on a docker container

### ISSUE THREAD

**Issue by moar82** [mviereck/x11docker#90]
I need to execute Eclipse from a docker container that I was provided.  To do so, I installed x11docker and I managed to redirect display to my fedora 28 host machine. However, when I tried to open the workspace directory located in the docker container I got the following error: [link](https://imgur.com/a/v4pOgE2). 
It seems to me is a problem with permissions, but not sure how to fixed them, any idea?

**Comment by mviereck** [comment]
Some attempts:
 - Eclipse shows several errors that it misses `dbus-launch`. I recommend to install `dbus-launch` in image.
 - Maybe the Dockerfile has a `USER` specification and the setup depends on it. Try to run x11docker with `--user=RETAIN` to run with `USER` defined in image.
- Maybe the Dockerfile has a `WORKDIR` specification. Look for it and set x11docker option `--workdir DIR` (and replace DIR with the working directory of the Dockerfile).
 - x11docker does some security restrictions. You can disable them with `--cap-default`.

If that does not help, please show the the Dockerfile and x11docker output with `--verbose` (or `~/.cache/x11docker/x11docker.log` after terminating x11docker).

**Comment by moar82** [comment]
> Some attempts:
> 
>     * Eclipse shows several errors that it misses `dbus-launch`. I recommend to install `dbus-launch` in image.
> 
>     * Maybe the Dockerfile has a `USER` specification and the setup depends on it. Try to run x11docker with `--user=RETAIN` to run with `USER` defined in image.
> 
>     * x11docker does some security restrictions. You can disable them with `--cap-default`.
> 
> 
> If that does not help, please show the the Dockerfile and x11docker output with `--verbose` (or `~/.cache/x11docker/x11docker.log` after terminating x11docker).
Thanks @mviereck for your quick response.
Unfortunately,  none of these attempts work.  However, I found that whenever I run eclipse with x11docker, it creates a `/fakehome/myuserid/workspace`
and there I can write.  Hence, to solve the issue, I opened a terminal session on the container; granted full permissions to the folder that contains  the workspace that I wanted to open, and run again eclipse using xdocker11, and this time voila,  I have no problems.
