### ISSUE TITLE
Invalid argument: memory flag

### ISSUE THREAD

**Issue by Eusebius1920** [mviereck/x11docker#93]
I just tried to start the project on my local machine (archlinux, kernel: `4.19.8`, docker: `18.09.0-ce, build 4d60db472b`).

Command:
```shell
>> ./x11docker --hostdisplay x11docker/xfce xfce4-terminal
```
I get the following error:
```
==> /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/container.log <==
invalid argument "" for "-m, --memory" flag: invalid size: ''
See 'docker run --help'.
invalid argument "" for "-m, --memory" flag: invalid size: ''
See 'docker run --help'.
```

<details>
<summary>
==> /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/message.log <==
</summary/>
<pre>
==> /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/message.log <==
x11docker[393.15]: Waiting for file creation of /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/xtermready

x11docker[393.15]: Container ID: 

x11docker[393.15]: Found new created file /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/xtermready

x11docker ERROR: Container startup seems to have failed.
  Last lines of log:
invalid argument "" for "-m, --memory" flag: invalid size: ''
See 'docker run --help'.

  Type 'x11docker --help' for usage information
  Debug options: '--verbose' (full log) or '--debug' (log excerpt).
  Logfile will be: /home/USERNAME/.cache/x11docker/x11docker.log
  Please report issues at https://github.com/mviereck/x11docker

x11docker ERROR: Startup of docker failed. Did not receive a container ID.
    
  Last lines of container log:
invalid argument "" for "-m, --memory" flag: invalid size: ''
See 'docker run --help'.

  Type 'x11docker --help' for usage information
  Debug options: '--verbose' (full log) or '--debug' (log excerpt).
  Logfile will be: /home/USERNAME/.cache/x11docker/x11docker.log
  Please report issues at https://github.com/mviereck/x11docker

x11docker[393.21]: Waiting since 0s for /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/container.pid1pid to have content, will wait up to 32000 seconds.

x11docker[393.72]: Waiting since 1s for /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/container.pid1pid to have content, will wait up to 32000 seconds.

x11docker[394.33]: Waiting since 1s for /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/container.pid1pid to have content, will wait up to 32000 seconds.

x11docker[395.03]: Waiting since 2s for /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/container.pid1pid to have content, will wait up to 32000 seconds.

x11docker[395.84]: Waiting since 3s for /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/container.pid1pid to have content, will wait up to 32000 seconds.

x11docker[396.75]: Waiting since 3s for /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/container.pid1pid to have content, will wait up to 32000 seconds.

x11docker[397.76]: Waiting since 4s for /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/container.pid1pid to have content, will wait up to 32000 seconds.

x11docker[398.87]: Waiting since 5s for /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/container.pid1pid to have content, will wait up to 32000 seconds.

x11docker[399.37]: Terminating x11docker.

x11docker[399.37]: time to say goodbye (finish-subshell)

x11docker[399.37]: time to say goodbye (timetosaygoodbyefifo)

x11docker[399.37]: time to say goodbye (main)

x11docker[399.38]: Terminating x11docker.

x11docker[399.42]: Terminating 5344 (containershell) x11docker:  5344 pts/0    00:00:00 bash

x11docker[399.43]: Terminating 5344 (containershell) x11docker:  5344 pts/0    00:00:00 bash

x11docker[399.50]: Terminating 5161 (watchmessagefifo) x11docker:  5161 pts/0    00:00:00 bash

x11docker[399.57]: Terminating 5157 (watchpidlist) x11docker:  5157 pts/0    00:00:00 bash

x11docker[399.67]: time to say goodbye (finish)

x11docker[399.68]: Exitcode 1

x11docker[400.07]: Waiting since 6s for /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/container.pid1pid to have content, will wait up to 32000 seconds.

x11docker[400.08]: Stopped waiting for file content of /home/USERNAME/.cache/x11docker/x11docker-xfce-ef3e4d/container.pid1pid due to terminating signal.
</pre>
</details>

I could not find any information about this error, is this a bug or am I doing something wrong?

**Comment by mviereck** [comment]
Thank you for reporting!

This is indeed a bug, introduced with new option `--limit` that limits resource access to CPU and RAM.
Accidently `--limit` was enabled by default, that is fixed now.

However, you'll still get the bug if you set `--limit`. Can you show me the output of `free -b`, please? It should give available free memory  and works fine here, but somehow fails on your system.

**Comment by Eusebius1920** [comment]
Oh I overlooked that you pushed a new commit. With this one I can start x11docker.

Thank you for this awesome project!

**Comment by mviereck** [comment]
Your hint with `LANG` pointed me in the right direction: x11docker checked with `grep Mem:` for the right line and failed with german `Speicher:`. Is fixed now. Thanks!
